#pragma pack(push, 1)
struct SUDExDataPackage_VelodynePointCloud
{
	unsigned __int32 VelodynePointCloud_MeasPointList_SignalHeader_VeloProcessor_interface_version;
	unsigned __int64 VelodynePointCloud_MeasPointList_SignalHeader_Timestamp_MTS_system;
	unsigned __int64 VelodynePointCloud_MeasPointList_SignalHeader_Timestamp_MTS_UTC;
	unsigned __int64 VelodynePointCloud_MeasPointList_SignalHeader_Revolution_counter;
	unsigned __int8 VelodynePointCloud_MeasPointList_SignalHeader_Signal_validity;
	unsigned __int8 VelodynePointCloud_MeasPointList_MeasPointStatus_GPS_hours_of_current_revolution;
	unsigned __int8 VelodynePointCloud_MeasPointList_MeasPointStatus_GPS_minutes_of_current_revolution;
	unsigned __int8 VelodynePointCloud_MeasPointList_MeasPointStatus_GPS_seconds_of_current_revolution;
	unsigned __int8 VelodynePointCloud_MeasPointList_MeasPointStatus_GPS_day_of_current_revolution;
	unsigned __int8 VelodynePointCloud_MeasPointList_MeasPointStatus_GPS_month_of_current_revolution;
	unsigned __int8 VelodynePointCloud_MeasPointList_MeasPointStatus_GPS_year_of_current_revolution;
	unsigned __int16 VelodynePointCloud_MeasPointList_MeasPointStatus_usReserved;
	unsigned __int64 VelodynePointCloud_MeasPointList_MeasPointStatus_Timestamp_UTC_of_current_rev;
	unsigned __int32 VelodynePointCloud_MeasPointList_MeasPointStatus_Time_GPS_of_curr_rev_HourBased;
	unsigned __int8 VelodynePointCloud_MeasPointList_MeasPointStatus_GPS_connection_established;
	unsigned __int8 VelodynePointCloud_MeasPointList_MeasPointStatus_PPS_connection_established;
	float VelodynePointCloud_MeasPointList_SensorPose_Sensor_position_AUTOSAR_X;
	float VelodynePointCloud_MeasPointList_SensorPose_Sensor_position_AUTOSAR_Y;
	float VelodynePointCloud_MeasPointList_SensorPose_Sensor_position_AUTOSAR_Z;
	float VelodynePointCloud_MeasPointList_SensorPose_Sensor_roll_angle;
	float VelodynePointCloud_MeasPointList_SensorPose_Sensor_pitch_angle;
	float VelodynePointCloud_MeasPointList_SensorPose_Sensor_yaw_angle;
	unsigned __int32 VelodynePointCloud_MeasPointList_NumberOfValidPoints_NumberOfValidPoints;
	__int16 VelodynePointCloud_MeasPointList_MeasPointsX_MeasPointsX[266627];
	__int16 VelodynePointCloud_MeasPointList_MeasPointsY_MeasPointsY[266627];
	__int16 VelodynePointCloud_MeasPointList_MeasPointsZ_MeasPointsZ[266627];
	unsigned __int8 VelodynePointCloud_MeasPointList_MeasPointsIntensity_MeasPointsIntensity[266627];
	unsigned __int8 VelodynePointCloud_MeasPointList_MeasPointsLaserID_MeasPointsLaserID[266627];
	unsigned __int32 VelodynePointCloud_MeasPointList_MeasPointsTimeDelta_MeasPointsTimeDelta[266627];
};
#pragma pack(pop)
