/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \version 6.4.3
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2020 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains an Rte component template / example code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.4.3
 * on Fri Feb 25 14:38:07 CST 2022. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#include <Rte_Sdc.h>
#include "Sdc.h"
#include "SpiSync_Core.h"
#include "Sdc_Fusion.h"
#include "Sdc_Chassis.h"
#include "Sdc_Errh.h"
#include "Sdc_Fusion.h"
#include "Sdc_Perception.h"
#include "Sdc_Radar.h"
#include "Sdc_Vdy.h"
#include "Sdc_Core.h"


/*==================[macros]=================================================*/


/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/
/*==================[.data]==============================*/
#define SDC_START_SEC_VAR_INIT_UNSPECIFIED
#include "Sdc_MemMap.h"



#define SDC_STOP_SEC_VAR_INIT_UNSPECIFIED
#include "Sdc_MemMap.h"

/*==================[.bss]==============================*/
#define SDC_START_SEC_VAR_CLEARED_UNSPECIFIED
#include "Sdc_MemMap.h"

static uint8 Sdc_RunTime_Counter = 0x00;

#define SDC_STOP_SEC_VAR_CLEARED_UNSPECIFIED
#include "Sdc_MemMap.h"

extern void Sdc_SendHandler_MainFunction(void);
/*==================[.text]==============================*/
#define SDC_START_SEC_CODE
#include "Sdc_MemMap.h"

/**
 * \functions Sdc_InitFunction
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments *
 */
FUNC(void, RTE_CODE) Sdc_InitFunction (void)
{
	Sdc_Core_InitFunction();
	Sdc_Chassis_InitFunction();
	Sdc_Fusion_InitFunction();
	Sdc_Perception_InitFunction();
	Sdc_Radar_InitFunction();
	Sdc_Vdy_InitFunction();
	Sdc_SendInterface_InitFunction();
	Sdc_Diag_InitFunction();
}

/**
 * \functions Sdc_DeInitFunction
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments *
 */
FUNC(void, RTE_CODE) Sdc_DeInitFunction (void)
{
	//TODO
}
/**
 * \functions Sdc_MainFunction_5ms
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */

FUNC(void, RTE_CODE) Sdc_MainFunction_5ms (void)
{
	Sdc_Core_MainFunction();
	Sdc_SendHandler_MainFunction();
}
extern void Sdc_SendInterface_MainFunction(void);
/**
 * \functions Sdc_MainFunction_10ms
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */

FUNC(void, RTE_CODE) Sdc_MainFunction_10ms (void)
{
	Sdc_Chassis_MainFunction();
	Sdc_Errh_MainFunction();
	Sdc_Diag_MainFunction();
	Sdc_SendInterface_MainFunction();

}

/**
 * \functions Sdc_MainFunction_20ms
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */

FUNC(void, RTE_CODE) Sdc_MainFunction_20ms (void)
{
	Sdc_RunTime_Counter++;
	Sdc_Vdy_MainFunction();
	Sdc_Radar_MainFunction();
	Sdc_Perception_MainFunction();
	Sdc_Fusion_MainFunction();
	if(Sdc_RunTime_Counter > 50)
	{
		Sdc_RunTime_Counter = 0;
		Sdc_Diag_TxVersionData();
	}
}
#define SDC_STOP_SEC_CODE
#include "Sdc_MemMap.h"



