/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \version 6.4.3
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2020 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains an Rte component template / example code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.4.3
 * on Mon Jan 10 17:32:21 CST 2022. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#include <Rte_LcfAdapter.h>
#include "LcfAdapter.h"
#if	(DBG_LCFADAPTER_ALGO_ENABLE == STD_ON)
#include "lcf_cfg.h"
#include "lcf_veh_ext.h"
#include "lcf_sen_ext.h"
#endif
#include "CSC_Platform_Common.h"
#include "Ioc_gen.h"
#include "LCFVEH_type.h"
#include "LCFSEN_type.h"
#include "lcf_sen_iface.h"
#include "IFX_Os.h"

/*****************************************************************************
  Meas Freeze Virtual Addr Define
*****************************************************************************/
#define LCF_MEAS_ADDR_BASECTRL_VI 		(0xA00A1000u)//
#define LCF_MEAS_ADDR_ABDOUTPUT_VI	 	(0xA00AA000u)
#define LCF_MEAS_ADDR_TUNPARDMC			(0xA00A3000u)//
#define LCF_MEAS_ADDR_TUNPARKMC			(0xA00A4000u)//
#define LCF_MEAS_ADDR_LCFINPUT_VI	 	(0xA00A5000u)//
#define LCF_MEAS_ADDR_GENERICINPUT		(0xA00A6000u)//
#define LCF_MEAS_ADDR_LCFSODATA_VI 		(0xA00A7000u)
#define LCF_MEAS_ADDR_LCFVIFS_VI 		(0xA00A8000u)
#define LCF_MEAS_ADDR_NVMLCF_VI			(0xA00A9000u)//
#define LCF_MEAS_ADDR_VDYOFFSET 		(0xA00B0000u)//
#define LCF_MEAS_ADDR_VEHDYN_VI 		(0xA00B1000u)//
#define LCF_MEAS_ADDR_VEHPAR_VI 		(0xA00B2000u)//
#define LCF_MEAS_ADDR_VEHSIG_VI 		(0xA00B3000u)//
#define LCF_MEAS_ADDR_ALGOCOMP_V 		(0xA00B4000u)//
#define LCF_MEAS_ADDR_LCFLADMC 			(0xA00B5000u)//
#define LCF_MEAS_ADDR_LCFVODATA_VO 		(0xA00B6000u)//
#define LCF_MEAS_ADDR_LCFSIFV_VO 		(0xA00B7000u)
#define LCF_MEAS_ADDR_NVMLCF_VO			(0xA00B8000u)//
#define LCF_MEAS_ADDR_LCFVRC_VO         (0xA00BD000u)
#define LCF_MEAS_ADDR_LCFVRI_VO         (0xA00BE000u)
#define LCF_MEAS_ADDR_BASECTRL_SI 		(0xA00B9000u)//
#define LCF_MEAS_ADDR_ABDOUTPUT_SI 		(0xA00BA000u)//
#define LCF_MEAS_ADDR_CAMOBJLIST		(0xA00C1000u)//
#define LCF_MEAS_ADDR_PROVIDOUTPUT 		(0xA00C2000u)//
#define LCF_MEAS_ADDR_TUNPARLDP 		(0xA00C3000u)//
#define LCF_MEAS_ADDR_TUNPARLKA 		(0xA00C4000u)//
#define LCF_MEAS_ADDR_GENOBJLIST 		(0xA00CA000u)//
#define LCF_MEAS_ADDR_RADAROBJLIST 		(0xA00C6000u)//
#define LCF_MEAS_ADDR_LCFINPUT_SI 		(0xA00C7000u)//
#define LCF_MEAS_ADDR_LADMCIUCTOSOC 	(0xA00C8000u)//
#define LCF_MEAS_ADDR_LCFSIFV_SI 		(0xA00C9000u)//
#define LCF_MEAS_ADDR_LCFVODATA_SI 		(0xA00D0000u)//
#define LCF_MEAS_ADDR_LSDENVIRONMENT 	(0xA00D1000u)//
#define LCF_MEAS_ADDR_VEHDYN_SI 		(0xA00D2000u)//
#define LCF_MEAS_ADDR_VEHPAR_SI 		(0xA00D3000u)//
#define LCF_MEAS_ADDR_VEHSIG_SI 		(0xA00D4000u)//
#define LCF_MEAS_ADDR_ALGOCOMP_S 		(0xA00D5000u)//
#define LCF_MEAS_ADDR_LCFSODATA_SO 		(0xA00D6000u)//
#define LCF_MEAS_ADDR_LCFVIFS_SO 		(0xA00D7000u)//
#define LCF_MEAS_ADDR_LCFSRC_SO         (0xA00DB000u)//
#define LCF_MEAS_ADDR_LCFSRI_SO         (0xA00DC000u)//

/*****************************************************************************
  PDO
*****************************************************************************/
#ifdef __PDO__
/****** Lcf Veh In ******/
/*! @VADDR: LCF_MEAS_ADDR_BASECTRL_VI 		@CYCLEID: CycleId_23 */
typedef BaseCtrlData_t BaseCtrlData_LcfVeh_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_ABDOUTPUT_VI 		@CYCLEID: CycleId_23 */
typedef AbdOutputData_t AbdOutputData_LcfVeh_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_TUNPARDMC 		@CYCLEID: CycleId_23 */
typedef CPAR_LCF_TunParamsDMC_t CPAR_LCF_TunParamsDMC_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_TUNPARKMC 		@CYCLEID: CycleId_23 */
typedef CPAR_LCF_TunParamsKMC_t CPAR_LCF_TunParamsKMC_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LCFINPUT_VI 		@CYCLEID: CycleId_23 */
typedef LCF_GenericInputs_t LCF_GenericInputs_LcfVeh_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_GENERICINPUT 		@CYCLEID: CycleId_23 */
typedef LCF_LaDmcIucToSoc_t LCF_LaDmcIucToSoc_LcfVeh_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LCFSODATA_VI 		@CYCLEID: CycleId_23 */
typedef LCF_SenGenericOutputs_t LCF_SenGenericOutputs_LcfVeh_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LCFVIFS_VI 		@CYCLEID: CycleId_23 */
typedef LCF_SenToVeh_t LCF_SenToVeh_LcfVeh_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_NVMLCF_VI 		@CYCLEID: CycleId_23 */
typedef NVM_LcfLearningData_t NVM_LcfLearningData_LcfVehIn_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_VDYOFFSET 		@CYCLEID: CycleId_23 */
typedef VDYOffsets_t VDYOffsets_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_VEHDYN_VI 		@CYCLEID: CycleId_23 */
typedef VehDyn_t VehDyn_LcfVeh_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_VEHPAR_VI 		@CYCLEID: CycleId_23 */
typedef VehPar_t VehPar_LcfVeh_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_VEHSIG_VI 		@CYCLEID: CycleId_23 */
typedef VehSig_t VehSig_LcfVeh_MTS_T;

/****** Lcf Veh Out ******/
/*! @VADDR: LCF_MEAS_ADDR_ALGOCOMP_V 		@CYCLEID: CycleId_23 */
typedef AlgoCompState_t AlgoCompState_LcfVeh_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LCFLADMC 			@CYCLEID: CycleId_23 */
typedef LCF_LaDmcSocToIuc_t LCF_LaDmcSocToIuc_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LCFVODATA_VO 		@CYCLEID: CycleId_23 */
typedef LCF_VehGenericOutputs_t LCF_VehGenericOutputs_LcfVeh_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LCFSIFV_VO 		@CYCLEID: CycleId_23 */
typedef LCF_VehToSen_t LCF_VehToSen_LcfVeh_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_NVMLCF_VO 		@CYCLEID: CycleId_23 */
typedef NVM_LcfLearningData_t NVM_LcfLearningData_LcfVehOut_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LCFVRC_VO 		@CYCLEID: CycleId_23 */
typedef s_Time_RunCycleMeas_t LCF_LcfVehExec_Cycle_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LCFVRI_VO			@CYCLEID: CycleId_23 */
typedef s_Time_RunIntervalMeas_t LCF_LcfVehExec_RunInterval_MTS_T;

/****** Lcf Sen In ******/
/*! @VADDR: LCF_MEAS_ADDR_BASECTRL_SI 		@CYCLEID: CycleId_90 */
typedef BaseCtrlData_t BaseCtrlData_LcfSen_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_ABDOUTPUT_SI		@CYCLEID: CycleId_90 */
typedef AbdOutputData_t AbdOutputData_LcfSen_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_CAMOBJLIST 		@CYCLEID: CycleId_90 */
typedef EM_t_CamObjectList EM_t_CamObjectList_MTS;
/*! @VADDR: LCF_MEAS_ADDR_PROVIDOUTPUT 		@CYCLEID: CycleId_90 */
typedef CB_t_ProvidedOutputs_t CB_t_ProvidedOutputs_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_TUNPARLDP 		@CYCLEID: CycleId_90 */
typedef CPAR_LCF_TunParamsLDP_t CPAR_LCF_TunParamsLDP_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_TUNPARLKA 		@CYCLEID: CycleId_90 */
typedef CPAR_LCF_TunParamsLKA_t CPAR_LCF_TunParamsLKA_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_GENOBJLIST 		@CYCLEID: CycleId_90 */
typedef EM_t_GenObjectList EM_t_GenObjectList_Lcf_MTS;
/*! @VADDR: LCF_MEAS_ADDR_RADAROBJLIST 		@CYCLEID: CycleId_90 */
typedef HLA_RadarObjectList_t HLA_RadarObjectList_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LCFINPUT_SI 		@CYCLEID: CycleId_90 */
typedef LCF_GenericInputs_t LCF_GenericInputs_LcfSen_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LADMCIUCTOSOC 	@CYCLEID: CycleId_90 */
typedef LCF_LaDmcIucToSoc_t LCF_LaDmcIucToSoc_LcfSen_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LCFSIFV_SI 		@CYCLEID: CycleId_90 */
typedef LCF_VehToSen_t LCF_VehToSen_LcfSen_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LCFVODATA_SI 		@CYCLEID: CycleId_90 */
typedef LCF_VehGenericOutputs_t LCF_VehGenericOutputs_LcfSen_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LSDENVIRONMENT 	@CYCLEID: CycleId_90 */
typedef LSD_EnvironmentData_t LSD_EnvironmentData_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_VEHDYN_SI 		@CYCLEID: CycleId_90 */
typedef VehDyn_t VehDyn_LcfSen_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_VEHPAR_SI 		@CYCLEID: CycleId_90 */
typedef VehPar_t VehPar_LcfSen_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_VEHSIG_SI 		@CYCLEID: CycleId_90 */
typedef VehSig_t VehSig_LcfSen_MTS_T;

/****** Lcf Sen Out ******/
/*! @VADDR: LCF_MEAS_ADDR_ALGOCOMP_S 		@CYCLEID: CycleId_90 */
typedef AlgoCompState_t AlgoCompState_LcfSen_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LCFSODATA_SO 		@CYCLEID: CycleId_90 */
typedef LCF_SenGenericOutputs_t LCF_SenGenericOutputs_LcfSen_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LCFVIFS_SO 		@CYCLEID: CycleId_90 */
typedef LCF_SenToVeh_t LCF_SenToVeh_LcfSen_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LCFSRC_SO			@CYCLEID: CycleId_90 */
typedef s_Time_RunCycleMeas_t LCF_LcfSenExec_Cycle_MTS_T;
/*! @VADDR: LCF_MEAS_ADDR_LCFSRI_SO			@CYCLEID: CycleId_90 */
typedef s_Time_RunIntervalMeas_t LCF_LcfSenExec_RunInterval_MTS_T;


#endif
/*****************************************************************************
  TYPEDEFS
*****************************************************************************/
/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/
#if (DBG_LCFADAPTER_DEBUG_ENABLE == STD_ON)
s_Time_RunCycleMeas_t Debug_LcfAdapter_LcfSenExec_Cycle;
s_Time_RunIntervalMeas_t Debug_LcfAdapter_LcfSenExec_RunInterval;
s_Time_RunCycleMeas_t Debug_LcfAdapter_LcfVehExec_Cycle;
s_Time_RunIntervalMeas_t Debug_LcfAdapter_LcfVehExec_RunInterval;
#endif
uint32 Debug_LcfAdapter_LcfSenExec_Counter = 0;
uint32 Debug_LcfAdapter_LcfVehExec_Counter = 0;

#if	(DBG_LCFADAPTER_ALGO_ENABLE == STD_ON)

reqLcfSenPrtList_t LcfAdapter_reqLcfSenPrtData;//Input list of LcfSen
proLcfSenPrtList_t LcfAdapter_proLcfSenPrtData;//Output list of LcfSen
reqLcfVehPrtList_t LcfAdapter_reqLcfVehPrtData;//Input list of LcfVeh
proLcfVehPrtList_t LcfAdapter_proLcfVehPrtData;//Output list of LcfVeh
AS_t_ServiceFuncts LcfAdapter_LcfServiceFunctionsTable;//Service function list of LcfSen and LcfVeh

/*TODO : Data element shall mapping the LcfAdapter_reqLcfSenPrtData or LcfAdapter_proLcfSenPrtData or LcfAdapter_reqLcfVehPrtData or LcfAdapter_proLcfVehPrtData*/
BaseCtrlData_t         	LcfAdapter_BaseCtrlData_SenIn;//In,from Fcu,OK
BaseCtrlData_t         	LcfAdapter_BaseCtrlData_VehIn;//In,from Fcu,OK

AbdOutputData_t        	LcfAdapter_AbdOutputData_SenIn;//In,from Sdc,OK
AbdOutputData_t        	LcfAdapter_AbdOutputData_VehIn;//In,from Sdc,OK

EM_t_CamObjectList     	LcfAdapter_CamObjectList;//In,unused,OK,Del by Mingfen
CB_t_ProvidedOutputs_t 	LcfAdapter_CbOutputs;//In,unused,OK,Del by Mingfen
CPAR_LCF_TunParamsLDP_t LcfAdapter_CParLdp;//In,unused,OK,Del by Mingfen
CPAR_LCF_TunParamsLKA_t LcfAdapter_CParLka;//In,unused,OK,Del by Mingfen
EM_t_GenObjectList     	LcfAdapter_GenObjectList;//In,from Sdc,OK,TBD
HLA_RadarObjectList_t  	LcfAdapter_HlaRadarObjectList;//In,unused,OK,Del by Mingfen

LCF_GenericInputs_t    	LcfAdapter_LcfInputData_SenIn;//In,from Fcu,OK
LCF_GenericInputs_t    	LcfAdapter_LcfInputData_VehIn;//In,from Fcu,OK

LCF_LaDmcIucToSoc_t    	LcfAdapter_LcfLaDmcIucToSoc_SenIn;//In,unused,OK,Del by Mingfen
LCF_LaDmcIucToSoc_t    	LcfAdapter_LcfLaDmcIucToSoc_VehIn;//In,unused,OK,Del by Mingfen

LCF_VehToSen_t         	LcfAdapter_LcfSenInputFromVehData_VehOut;// out
LCF_VehToSen_t         	LcfAdapter_LcfSenInputFromVehData_SenIn;// In
LCF_VehGenericOutputs_t LcfAdapter_LcfVehOutputData_VehOut;// out
LCF_VehGenericOutputs_t LcfAdapter_LcfVehOutputData_SenIn; // in
LSD_EnvironmentData_t  	LcfAdapter_LsdEnvironmentData;//In,unused,OK,Del by Mingfen

VehDyn_t               	LcfAdapter_VehDyn_SenIn;//In,from Vdy
VehPar_t               	LcfAdapter_VehPar_SenIn;//In,from Fcu
VehSig_t               	LcfAdapter_VehSig_SenIn;//In,from Fcu

VehDyn_t               	LcfAdapter_VehDyn_VehIn;//In,from Vdy
VehPar_t               	LcfAdapter_VehPar_VehIn;//In,from Fcu
VehSig_t               	LcfAdapter_VehSig_VehIn;//In,from Fcu

AlgoCompState_t         LcfAdapter_AlgoCompState_Sen;//Out,OK
LCF_SenGenericOutputs_t LcfAdapter_LcfSenOutputData_SenOut;// out
LCF_SenGenericOutputs_t LcfAdapter_LcfSenOutputData_VehIn; // in
LCF_SenToVeh_t          LcfAdapter_LcfVehInputFromSenData_SenOut;// out
LCF_SenToVeh_t          LcfAdapter_LcfVehInputFromSenData_VehIn; // in

CPAR_LCF_TunParamsDMC_t LcfAdapter_CParDmc;//In,unused,OK,Del by Mingfen
CPAR_LCF_TunParamsKMC_t LcfAdapter_CParKmc;//In,unused,OK,Del by Mingfen
NVM_LcfLearningData_t   LcfAdapter_NvmLcfData;//In/out,Shall definition the default value or unused??,Del by Mingfen
VDYOffsets_t            LcfAdapter_VdyOffsets;//In,from Vdy
AlgoCompState_t         LcfAdapter_AlgoCompState_Veh;//Out,OK
LCF_LaDmcSocToIuc_t     LcfAdapter_LcfLaDmcSocToIuc;//Out,unused,OK

#endif


/*==================[internal function declarations]========================*/
#if	(DBG_LCFADAPTER_ALGO_ENABLE == STD_ON)
static AS_t_MeasReturn LcfAdapter_Cot_MeasHdlr(const AS_t_MeasInfo * const meas_info, const void * data, AS_t_MeasCallback callback);
static sint32 LcfAdapter_Cot_RTAAlgoServiceAddEvent(const AS_t_RtaEventType RtaEvtType, const uint8 u_IdGlobal, const uint8 u_IdLocal, const uint8 u_OptData);
static AS_t_Dem_ReturnType LcfAdapter_Cot_Dem_SetEventStatus(const AS_t_Dem_EventIDType u_Dem_EventIdRaw, const AS_t_Dem_EventStatusType u_Dem_EventStatus);
static FUNC(void, RTE_CODE) LcfAdapter_MeasFreezeData(void);
static void LcfAdapter_Mtsi(uint32 VirtAdd, uint8 funcid, pvoid data_p, uint32 length);
void LcfAdapter_MTSI_FreezeData_Proxy_23_In(void);
void LcfAdapter_MTSI_FreezeData_Proxy_23_Out(void);
void LcfAdapter_MTSI_FreezeData_Proxy_90_In(void);
void LcfAdapter_MTSI_FreezeData_Proxy_90_Out(void);
void LCF_filledfixParm(void);
#endif



/*==================[external function definitions]=========================*/
/**
 * \functions LcfAdapter_InitFunction
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */
FUNC(void, RTE_CODE) LcfAdapter_InitFunction (void)
{
#if	(DBG_LCFADAPTER_ALGO_ENABLE == STD_ON)
	/*TODO : Clean the local variable*/
	memset(&LcfAdapter_reqLcfSenPrtData, 0x00, sizeof(reqLcfSenPrtList_t));//Input list of LcfSen
	memset(&LcfAdapter_proLcfSenPrtData, 0x00, sizeof(proLcfSenPrtList_t));//Output list of LcfSen
	memset(&LcfAdapter_reqLcfVehPrtData, 0x00, sizeof(reqLcfVehPrtList_t));//Input list of LcfVeh
	memset(&LcfAdapter_proLcfVehPrtData, 0x00, sizeof(proLcfVehPrtList_t));//Output list of LcfVeh
	memset(&LcfAdapter_LcfServiceFunctionsTable, 0x00, sizeof(AS_t_ServiceFuncts));//Service function list of LcfSen and LcfVeh

	memset(&LcfAdapter_BaseCtrlData_SenIn, 0x00, sizeof(BaseCtrlData_t));//In
	memset(&LcfAdapter_BaseCtrlData_VehIn, 0x00, sizeof(BaseCtrlData_t));//In
	memset(&LcfAdapter_AbdOutputData_SenIn, 0x00, sizeof(AbdOutputData_t));//In
	memset(&LcfAdapter_AbdOutputData_VehIn, 0x00, sizeof(AbdOutputData_t));//In
	memset(&LcfAdapter_CamObjectList, 0x00, sizeof(EM_t_CamObjectList));//In
	memset(&LcfAdapter_CbOutputs, 0x00, sizeof(CB_t_ProvidedOutputs_t));//In
	memset(&LcfAdapter_CParLdp, 0x00, sizeof(CPAR_LCF_TunParamsLDP_t));//In
	memset(&LcfAdapter_CParLka, 0x00, sizeof(CPAR_LCF_TunParamsLKA_t));//In
	memset(&LcfAdapter_GenObjectList, 0x00, sizeof(EM_t_GenObjectList));//In
	memset(&LcfAdapter_HlaRadarObjectList, 0x00, sizeof(HLA_RadarObjectList_t));//In
	memset(&LcfAdapter_LcfInputData_SenIn, 0x00, sizeof(LCF_GenericInputs_t));//In
	memset(&LcfAdapter_LcfInputData_VehIn, 0x00, sizeof(LCF_GenericInputs_t));//In
	memset(&LcfAdapter_LcfLaDmcIucToSoc_SenIn, 0x00, sizeof(LCF_LaDmcIucToSoc_t));//In
	memset(&LcfAdapter_LcfLaDmcIucToSoc_VehIn, 0x00, sizeof(LCF_LaDmcIucToSoc_t));//In
	memset(&LcfAdapter_LcfSenInputFromVehData_SenIn, 0x00, sizeof(LCF_VehToSen_t));// In
	memset(&LcfAdapter_LcfSenInputFromVehData_VehOut, 0x00, sizeof(LCF_VehToSen_t));// out
	memset(&LcfAdapter_LcfVehOutputData_SenIn, 0x00, sizeof(LCF_VehGenericOutputs_t));//In
	memset(&LcfAdapter_LcfVehOutputData_VehOut, 0x00, sizeof(LCF_VehGenericOutputs_t));//out
	memset(&LcfAdapter_LsdEnvironmentData, 0x00, sizeof(LSD_EnvironmentData_t));//In
	memset(&LcfAdapter_VehDyn_SenIn, 0x00, sizeof(VehDyn_t));//In
	memset(&LcfAdapter_VehPar_SenIn, 0x00, sizeof(VehPar_t));//In
	memset(&LcfAdapter_VehSig_SenIn, 0x00, sizeof(VehPar_t));//In
	memset(&LcfAdapter_VehDyn_VehIn, 0x00, sizeof(VehDyn_t));//In
	memset(&LcfAdapter_VehPar_VehIn, 0x00, sizeof(VehPar_t));//In
	memset(&LcfAdapter_VehSig_VehIn, 0x00, sizeof(VehPar_t));//In
	memset(&LcfAdapter_AlgoCompState_Sen, 0x00, sizeof(AlgoCompState_t));//Out
	memset(&LcfAdapter_LcfSenOutputData_VehIn, 0x00, sizeof(LCF_SenGenericOutputs_t));//In
	memset(&LcfAdapter_LcfSenOutputData_SenOut, 0x00, sizeof(LCF_SenGenericOutputs_t));//Out
	memset(&LcfAdapter_LcfVehInputFromSenData_VehIn, 0x00, sizeof(LCF_SenToVeh_t));//In
	memset(&LcfAdapter_LcfVehInputFromSenData_SenOut, 0x00, sizeof(LCF_SenToVeh_t));//Out
	memset(&LcfAdapter_CParDmc, 0x00, sizeof(CPAR_LCF_TunParamsDMC_t));//In
	memset(&LcfAdapter_CParKmc, 0x00, sizeof(CPAR_LCF_TunParamsKMC_t));//In
	memset(&LcfAdapter_NvmLcfData, 0x00, sizeof(NVM_LcfLearningData_t));//In/Out
	memset(&LcfAdapter_VdyOffsets, 0x00, sizeof(VDYOffsets_t));//In
	memset(&LcfAdapter_AlgoCompState_Veh, 0x00, sizeof(AlgoCompState_t));//Out
	memset(&LcfAdapter_LcfLaDmcSocToIuc, 0x00, sizeof(LCF_LaDmcSocToIuc_t));//Out

	/*TODO : Mapping local variable to pointer of LcfAdapter_reqLcfSenPrtData*/
	LcfAdapter_reqLcfSenPrtData.pBaseCtrlData = &LcfAdapter_BaseCtrlData_SenIn;//In
	LcfAdapter_reqLcfSenPrtData.pAbdOutputData = &LcfAdapter_AbdOutputData_SenIn;//In
	LcfAdapter_reqLcfSenPrtData.pCamObjectList = &LcfAdapter_CamObjectList;//In
	LcfAdapter_reqLcfSenPrtData.pCbOutputs = &LcfAdapter_CbOutputs;//In
	LcfAdapter_reqLcfSenPrtData.pCParLdp = &LcfAdapter_CParLdp;//In
	LcfAdapter_reqLcfSenPrtData.pCParLka = &LcfAdapter_CParLka;//In
	LcfAdapter_reqLcfSenPrtData.pGenObjectList = &LcfAdapter_GenObjectList;//In
	LcfAdapter_reqLcfSenPrtData.pHlaRadarObjectList = &LcfAdapter_HlaRadarObjectList;//In
	LcfAdapter_reqLcfSenPrtData.pLcfInputData = &LcfAdapter_LcfInputData_SenIn;//In
	LcfAdapter_reqLcfSenPrtData.pLcfLaDmcIucToSoc = &LcfAdapter_LcfLaDmcIucToSoc_SenIn;//In
	LcfAdapter_reqLcfSenPrtData.pLcfSenInputFromVehData = &LcfAdapter_LcfSenInputFromVehData_SenIn;//In
	LcfAdapter_reqLcfSenPrtData.pLcfVehOutputData = &LcfAdapter_LcfVehOutputData_SenIn;//In
	LcfAdapter_reqLcfSenPrtData.pLsdEnvironmentData = &LcfAdapter_LsdEnvironmentData;//In
	LcfAdapter_reqLcfSenPrtData.pVehDyn = &LcfAdapter_VehDyn_SenIn;//In
	LcfAdapter_reqLcfSenPrtData.pVehPar = &LcfAdapter_VehPar_SenIn;//In
	LcfAdapter_reqLcfSenPrtData.pVehSig = &LcfAdapter_VehSig_SenIn;//In

	/*TODO : Mapping local variable to pointer of LcfAdapter_proLcfSenPrtData*/
	LcfAdapter_proLcfSenPrtData.pAlgoCompState = &LcfAdapter_AlgoCompState_Sen;//Out
	LcfAdapter_proLcfSenPrtData.pLcfSenOutputData = &LcfAdapter_LcfSenOutputData_SenOut;//Out
	LcfAdapter_proLcfSenPrtData.pLcfSenOutputToVehData = &LcfAdapter_LcfVehInputFromSenData_SenOut;//Out

	/*TODO : Mapping local variable to pointer of LcfAdapter_reqLcfVehPrtData*/
	LcfAdapter_reqLcfVehPrtData.pBaseCtrlData = &LcfAdapter_BaseCtrlData_VehIn;//In
	LcfAdapter_reqLcfVehPrtData.pAbdOutputData = &LcfAdapter_AbdOutputData_VehIn;//In
	LcfAdapter_reqLcfVehPrtData.pCParDmc = &LcfAdapter_CParDmc;//In
	LcfAdapter_reqLcfVehPrtData.pCParKmc = &LcfAdapter_CParKmc;//In
	LcfAdapter_reqLcfVehPrtData.pLcfInputData = &LcfAdapter_LcfInputData_VehIn;//In
	LcfAdapter_reqLcfVehPrtData.pLcfLaDmcIucToSoc = &LcfAdapter_LcfLaDmcIucToSoc_VehIn;//In
	LcfAdapter_reqLcfVehPrtData.pLcfSenOutputData = &LcfAdapter_LcfSenOutputData_VehIn;//In
	LcfAdapter_reqLcfVehPrtData.pLcfVehInputFromSenData = &LcfAdapter_LcfVehInputFromSenData_VehIn;//In
	LcfAdapter_reqLcfVehPrtData.pNvmLcfData = &LcfAdapter_NvmLcfData;//In/Out
	LcfAdapter_reqLcfVehPrtData.pVdyOffsets = &LcfAdapter_VdyOffsets;//In
	LcfAdapter_reqLcfVehPrtData.pVehDyn = &LcfAdapter_VehDyn_VehIn;//In
	LcfAdapter_reqLcfVehPrtData.pVehPar = &LcfAdapter_VehPar_VehIn;//In
	LcfAdapter_reqLcfVehPrtData.pVehSig = &LcfAdapter_VehSig_VehIn;//In

	/*TODO : Mapping local variable to pointer of LcfAdapter_proLcfVehPrtData*/
	LcfAdapter_proLcfVehPrtData.pAlgoCompState = &LcfAdapter_AlgoCompState_Veh;//Out
	LcfAdapter_proLcfVehPrtData.pLcfLaDmcSocToIuc = &LcfAdapter_LcfLaDmcSocToIuc;//Out
	LcfAdapter_proLcfVehPrtData.pLcfVehOutputData = &LcfAdapter_LcfVehOutputData_VehOut;//Out
	LcfAdapter_proLcfVehPrtData.pLcfVehOutputToSenData = &LcfAdapter_LcfSenInputFromVehData_VehOut;//Out

	LcfAdapter_proLcfVehPrtData.pNvmLcfData = &LcfAdapter_NvmLcfData;//In/Out

	/*TODO : Mapping local variable to pointer of LcfAdapter_LcfServiceFunctionsTable*/
	LcfAdapter_LcfServiceFunctionsTable.pfMeasFreeze = LcfAdapter_Cot_MeasHdlr;
	LcfAdapter_LcfServiceFunctionsTable.pfRTAAlgoServiceAddEvent = LcfAdapter_Cot_RTAAlgoServiceAddEvent;
	LcfAdapter_LcfServiceFunctionsTable.pfDem_SetEventStatus = LcfAdapter_Cot_Dem_SetEventStatus;

#endif
}

/**
 * \functions LcfAdapter_LcfSenExec
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */

FUNC(void, RTE_CODE) LcfAdapter_LcfSenExec (void)
{
#if (DBG_LCFADAPTER_DEBUG_ENABLE == STD_ON)
	Debug_LcfAdapter_LcfSenExec_Counter++;
    Time_MeasRunCycleTimeMs(&Debug_LcfAdapter_LcfSenExec_Cycle);
    Time_MeasRunIntervalTimeMs_Start(&Debug_LcfAdapter_LcfSenExec_RunInterval);
#endif

#if	(DBG_LCFADAPTER_ALGO_ENABLE == STD_ON)

	/*TODO : Get the Input data from Rte*/
	Rte_Read_RP_Fcu_BaseCtrlData_BaseCtrlData(&LcfAdapter_BaseCtrlData_SenIn);
    // Ioc_Read_Ioc_BaseCtrlData(&LcfAdapter_BaseCtrlData_SenIn);
    Rte_Read_RP_Sdc_Perception_AbdOutputData_AbdOutputData_t(&LcfAdapter_AbdOutputData_SenIn);
    // Ioc_Read_Ioc_AbdOutputData(&LcfAdapter_AbdOutputData);
    Rte_Read_RP_Fcu_LcfGenericInputData_LcfGenericInputData(&LcfAdapter_LcfInputData_SenIn);
    //Ioc_Read_Ioc_LcfGenericInputs(&LcfAdapter_LcfInputData_SenIn);
    Rte_Read_RP_VdyAdapter_VehDyn_VehDyn(&LcfAdapter_VehDyn_SenIn);
    //Ioc_Read_Ioc_VehDyn(&LcfAdapter_VehDyn_SenIn);
    Rte_Read_RP_Fcu_VehPar_VehPar(&LcfAdapter_VehPar_SenIn);
    //Ioc_Read_Ioc_VehPar(&LcfAdapter_VehPar_SenIn);
    Rte_Read_RP_Fcu_VehSig_VehSig(&LcfAdapter_VehSig_SenIn);
    //Ioc_Read_Ioc_VehSig(&LcfAdapter_VehSig_SenIn);
    Rte_Read_RP_Sdc_Cem_GenObjectList_GenObjectList(&LcfAdapter_GenObjectList);
    //Ioc_Read_Ioc_GenObjectList(&LcfAdapter_GenObjectList);

	//DEBUG Freeze version number:
    /*----------------------------Debug Begin----------------------------*/
	LcfAdapter_AbdOutputData_SenIn.uiVersionNumber =2;
	LcfAdapter_BaseCtrlData_SenIn.uiVersionNumber =2;
	LcfAdapter_CamObjectList.uiVersionNumber =131083;
	LcfAdapter_CbOutputs.uiVersionNumber =9;
	LcfAdapter_CParLdp.uiVersionNumber =7;
	LcfAdapter_CParLka.uiVersionNumber =7;
	LcfAdapter_GenObjectList.uiVersionNumber =262159;
	LcfAdapter_HlaRadarObjectList.uiVersionNumber =1;
	LcfAdapter_LcfInputData_SenIn.uiVersionNumber =21;
	LcfAdapter_LcfLaDmcIucToSoc_SenIn.uiVersionNumber =6;
	LcfAdapter_LcfSenInputFromVehData_SenIn.uiVersionNumber =11;
	LcfAdapter_LcfVehOutputData_SenIn.uiVersionNumber =10;
	LcfAdapter_LsdEnvironmentData.uiVersionNumber =256;
	LcfAdapter_VehDyn_SenIn.uiVersionNumber =33;
	LcfAdapter_VehPar_SenIn.uiVersionNumber =8;
	LcfAdapter_VehSig_SenIn.uiVersionNumber =10;

    LcfAdapter_VehDyn_SenIn.Lateral.YawRate.YawRate = LcfAdapter_VehDyn_SenIn.Lateral.YawRate.YawRate;
	// LcfAdapter_VehDyn_SenIn.Lateral.Curve.Curve = -LcfAdapter_VehDyn_SenIn.Lateral.Curve.Curve;
	// LcfAdapter_VehDyn_SenIn.Lateral.DrvIntCurve.Curve = -LcfAdapter_VehDyn_SenIn.Lateral.DrvIntCurve.Curve;
	LcfAdapter_VehSig_SenIn.VehSigMain.YawRate = LcfAdapter_VehSig_SenIn.VehSigMain.YawRate;
	LcfAdapter_VehSig_SenIn.VehSigMain.LatAccel = LcfAdapter_VehSig_SenIn.VehSigMain.LatAccel;
	LcfAdapter_VehPar_SenIn.VehParMain.SelfSteerGrad = 0.004;

/***********************************************************************************/
    //TODO: temp set same as VehDyn
	AlgoDataTimeStamp_t u32_base_Time_stamp = LcfAdapter_BaseCtrlData_SenIn.sSigHeader.uiTimeStamp * 1000; // from system time

	LcfAdapter_BaseCtrlData_SenIn.sSigHeader.uiTimeStamp = LcfAdapter_BaseCtrlData_SenIn.sSigHeader.uiTimeStamp*1000; // from system time
	LcfAdapter_AbdOutputData_SenIn.sSigHeader.uiTimeStamp = LcfAdapter_VehDyn_SenIn.sSigHeader.uiTimeStamp*1000; // Use VDY instead /*******!! to be confirmed*********/
	LcfAdapter_CamObjectList.sSigHeader.uiTimeStamp = u32_base_Time_stamp; //Not used
	LcfAdapter_CbOutputs.sSigHeader.uiTimeStamp = u32_base_Time_stamp; // Not used
	LcfAdapter_CParLdp.sSigHeader.uiTimeStamp = u32_base_Time_stamp; // Not used
	LcfAdapter_CParLka.sSigHeader.uiTimeStamp =  u32_base_Time_stamp; // Not used
	LcfAdapter_GenObjectList.sSigHeader.uiTimeStamp = u32_base_Time_stamp; // Not used
	LcfAdapter_HlaRadarObjectList.sSigHeader.uiTimeStamp = u32_base_Time_stamp; // Not used
	LcfAdapter_LcfInputData_SenIn.sSigHeader.uiTimeStamp = LcfAdapter_LcfInputData_SenIn.sSigHeader.uiTimeStamp*1000; //Get system time
	LcfAdapter_LcfLaDmcIucToSoc_SenIn.sSigHeader.uiTimeStamp = u32_base_Time_stamp;

	LcfAdapter_VehDyn_SenIn.Lateral.Accel.LatAccelTimestamp.uiTimeStamp = u32_base_Time_stamp;
	LcfAdapter_VehDyn_SenIn.Lateral.YawRateTimestamp.uiTimeStamp = u32_base_Time_stamp;
	LcfAdapter_VehDyn_SenIn.Lateral.Curve.CurveTimestamp.uiTimeStamp = u32_base_Time_stamp;
	LcfAdapter_VehDyn_SenIn.Lateral.DrvIntCurve.CurveTimestamp.uiTimeStamp = u32_base_Time_stamp;
	//LcfAdapter_LcfSenInputFromVehData_SenIn.sSigHeader.uiTimeStamp; VehToSen, no change
    LcfAdapter_LcfVehOutputData_SenIn.sSigHeader.uiTimeStamp = u32_base_Time_stamp; // Veh output no change
	LcfAdapter_LsdEnvironmentData.sSigHeader.uiTimeStamp = u32_base_Time_stamp;
	LcfAdapter_VehPar_SenIn.sSigHeader.uiTimeStamp = LcfAdapter_VehPar_SenIn.sSigHeader.uiTimeStamp * 1000; //From system time
	LcfAdapter_VehSig_SenIn.sSigHeader.uiTimeStamp = LcfAdapter_VehSig_SenIn.sSigHeader.uiTimeStamp * 1000; //From system time
	LcfAdapter_VehDyn_SenIn.sSigHeader.uiTimeStamp = LcfAdapter_VehDyn_SenIn.sSigHeader.uiTimeStamp * 1000; //from LcfAdapter_BaseCtrlData_SenIn(fromt system time)

	LcfAdapter_VehSig_SenIn.VehSigMain.LatAccelTimeStamp = LcfAdapter_VehDyn_SenIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_SenIn.VehSigMain.YawRateTimeStamp = LcfAdapter_VehSig_SenIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_SenIn.VehSigMain.StWheelAngleTimeStamp = LcfAdapter_VehDyn_SenIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_SenIn.VehSigMain.VehLongAccelExtTimeStamp = LcfAdapter_VehDyn_SenIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_SenIn.VehSigMain.VehVelocityExtTimeStamp = LcfAdapter_VehDyn_SenIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_SenIn.VehSigMain.WhlTicksDevFrLeftTimeStamp = LcfAdapter_VehDyn_SenIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_SenIn.VehSigMain.WhlTicksDevFrRightTimeStamp = LcfAdapter_VehDyn_SenIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_SenIn.VehSigMain.WhlTicksDevReLeftTimeStamp = LcfAdapter_VehDyn_SenIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_SenIn.VehSigMain.WhlVelFrLeftTimeStamp = LcfAdapter_VehDyn_SenIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_SenIn.VehSigMain.WhlVelFrRightTimeStamp = LcfAdapter_VehDyn_SenIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_SenIn.VehSigMain.WhlVelReLeftTimeStamp = LcfAdapter_VehDyn_SenIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_SenIn.VehSigMain.WhlVelReRightTimeStamp = LcfAdapter_VehDyn_SenIn.sSigHeader.uiTimeStamp;

	/***********************************************************************************/

  	/*----------------------------Debug End----------------------------*/

#	if(DBG_LCFADAPTER_MEASFREEZE_ENABLE == STD_ON)
	(void)MTSI_DriverStartTaskCycle(90);		/*Update ID 90 counter*/
	LcfAdapter_MTSI_FreezeData_Proxy_90_In();	/*Update Lcf Sen input meas freeze data*/
#	endif

	/* Call the main logic function*/
	LcfSenExec(&LcfAdapter_reqLcfSenPrtData, &LcfAdapter_proLcfSenPrtData, &LcfAdapter_LcfServiceFunctionsTable);

#	if(DBG_LCFADAPTER_MEASFREEZE_ENABLE == STD_ON)
	LcfAdapter_MTSI_FreezeData_Proxy_90_Out();	/*Update Lcf Sen output meas freeze data*/
#	endif

	/*TODO : set the output data To Rte*/
	Rte_Write_PP_LcfAdapter_LcfSenGenericOutputData_LcfSenGenericOutputData(&LcfAdapter_LcfSenOutputData_SenOut);
    //Ioc_Write_Ioc_LcfSenGenericOutputs(LcfAdapter_LcfSenOutputData);
	SuspendAllInterrupts();

	(void)memcpy(&LcfAdapter_LcfSenOutputData_VehIn, &LcfAdapter_LcfSenOutputData_SenOut, sizeof(LCF_SenGenericOutputs_t));
	(void)memcpy(&LcfAdapter_LcfVehInputFromSenData_VehIn, &LcfAdapter_LcfVehInputFromSenData_SenOut, sizeof(LCF_SenToVeh_t));

	ResumeAllInterrupts();
#endif

#if (DBG_LCFADAPTER_DEBUG_ENABLE == STD_ON)
    Time_MeasRunIntervalTimeMs_End(&Debug_LcfAdapter_LcfSenExec_RunInterval);
#endif
}
/**
 * \functions LcfAdapter_LcfSenExec
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */


/**
 * \functions LcfAdapter_LcfVehExec_Debug
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */

FUNC(void, RTE_CODE) LcfAdapter_LcfVehExec (void)
{
	uint32 u32_Time_stamp;

#if (DBG_LCFADAPTER_DEBUG_ENABLE == STD_ON)
	Debug_LcfAdapter_LcfVehExec_Counter++;
    Time_MeasRunCycleTimeMs(&Debug_LcfAdapter_LcfVehExec_Cycle);
    Time_MeasRunIntervalTimeMs_Start(&Debug_LcfAdapter_LcfVehExec_RunInterval);
#endif

#if	(DBG_LCFADAPTER_ALGO_ENABLE == STD_ON)
	/*TODO : Get the Input data from Rte*/
	Rte_Read_RP_Fcu_BaseCtrlData_BaseCtrlData(&LcfAdapter_BaseCtrlData_VehIn);
    // Ioc_Read_Ioc_BaseCtrlData(&LcfAdapter_BaseCtrlData_VehIn);

	Rte_Read_RP_Sdc_Perception_AbdOutputData_AbdOutputData_t(&LcfAdapter_AbdOutputData_VehIn);
    // Ioc_Read_Ioc_AbdOutputData(&LcfAdapter_AbdOutputData);
    Rte_Read_RP_Fcu_LcfGenericInputData_LcfGenericInputData(&LcfAdapter_LcfInputData_VehIn);
    //IocRead_Ioc_LcfGenericInputs(&LcfAdapter_LcfInputData_VehIn);
    Rte_Read_RP_VdyAdapter_VehDyn_VehDyn(&LcfAdapter_VehDyn_VehIn);
    //Ioc_Read_Ioc_VehDyn(&LcfAdapter_VehDyn_VehIn);
	Rte_Read_RP_Fcu_VehPar_VehPar(&LcfAdapter_VehPar_VehIn);
    //Ioc_Read_Ioc_VehPar(&LcfAdapter_VehPar_VehIn);
    Rte_Read_RP_Fcu_VehSig_VehSig(&LcfAdapter_VehSig_VehIn);
    //Ioc_Read_Ioc_VehSig(&LcfAdapter_VehSig_VehIn);
    Rte_Read_RP_VdyAdapter_VdyOffsets_VdyOffsets(&LcfAdapter_VdyOffsets);
    //Ioc_Read_Ioc_VDYOffsets(&LcfAdapter_VdyOffsets);

	/*TODO : Call the main logic function*/
    //DEBUG freeze version number:
    /*----------------------------Debug Begin----------------------------*/
    LcfAdapter_AbdOutputData_VehIn.uiVersionNumber = 2;
    LcfAdapter_BaseCtrlData_VehIn.uiVersionNumber = 2;
    LcfAdapter_CParDmc.uiVersionNumber = 7;
    LcfAdapter_CParKmc.uiVersionNumber = 9;
    LcfAdapter_LcfInputData_VehIn.uiVersionNumber = 21;
    LcfAdapter_LcfLaDmcIucToSoc_VehIn.uiVersionNumber = 6;
    LcfAdapter_LcfSenOutputData_VehIn.uiVersionNumber = 19;
    LcfAdapter_LcfVehInputFromSenData_VehIn.uiVersionNumber = 15;
    LcfAdapter_NvmLcfData.uiVersionNumber = 2;
	LcfAdapter_VdyOffsets.uiVersionNumber = 2;
    LcfAdapter_VehDyn_VehIn.uiVersionNumber = 33;
    LcfAdapter_VehPar_VehIn.uiVersionNumber = 8;
    LcfAdapter_VehSig_VehIn.uiVersionNumber = 10;

	LcfAdapter_AbdOutputData_VehIn.sSigHeader.eSigStatus = 1;
	LcfAdapter_BaseCtrlData_VehIn.sSigHeader.eSigStatus = 1;
	LcfAdapter_CParDmc.sSigHeader.eSigStatus = 1;
	LcfAdapter_CParKmc.sSigHeader.eSigStatus = 1;
	LcfAdapter_LcfInputData_VehIn.sSigHeader.eSigStatus = 1;
	LcfAdapter_LcfLaDmcIucToSoc_VehIn.sSigHeader.eSigStatus = 1;
	LcfAdapter_LcfSenOutputData_VehIn.sSigHeader.eSigStatus = 1;
	LcfAdapter_LcfVehInputFromSenData_VehIn.sSigHeader.eSigStatus = 1;
	LcfAdapter_NvmLcfData.sSigHeader.eSigStatus = 1;
	LcfAdapter_VdyOffsets.sSigHeader.eSigStatus = 1;
	LcfAdapter_VehDyn_VehIn.sSigHeader.eSigStatus = 1;
	LcfAdapter_VehPar_VehIn.sSigHeader.eSigStatus = 1;
	LcfAdapter_VehSig_VehIn.sSigHeader.eSigStatus = 1;

    LcfAdapter_VehDyn_VehIn.Lateral.YawRate.YawRate = LcfAdapter_VehDyn_VehIn.Lateral.YawRate.YawRate;
	// LcfAdapter_VehDyn_VehIn.Lateral.Curve.Curve = -LcfAdapter_VehDyn_VehIn.Lateral.Curve.Curve;
	// LcfAdapter_VehDyn_VehIn.Lateral.DrvIntCurve.Curve = -LcfAdapter_VehDyn_VehIn.Lateral.DrvIntCurve.Curve;
	LcfAdapter_VehSig_VehIn.VehSigMain.LatAccel = LcfAdapter_VehSig_VehIn.VehSigMain.LatAccel;
	LcfAdapter_VehSig_VehIn.VehSigMain.YawRate = LcfAdapter_VehSig_VehIn.VehSigMain.YawRate;

	 LcfAdapter_VehPar_VehIn.VehParMain.SelfSteerGrad = 0.004;
/***********************************************************************************/
	AlgoDataTimeStamp_t u32_base_Time_stamp = LcfAdapter_VehDyn_VehIn.sSigHeader.uiTimeStamp * 1000; // from system time
	
	LcfAdapter_BaseCtrlData_VehIn.sSigHeader.uiTimeStamp = LcfAdapter_BaseCtrlData_VehIn.sSigHeader.uiTimeStamp*1000;
	LcfAdapter_AbdOutputData_VehIn.sSigHeader.uiTimeStamp = LcfAdapter_VehDyn_VehIn.sSigHeader.uiTimeStamp*1000; // Use VehDyn time stamp instead, TODO to be confirmed
	LcfAdapter_CParDmc.sSigHeader.uiTimeStamp = u32_base_Time_stamp; //Not used
	LcfAdapter_CParKmc.sSigHeader.uiTimeStamp = u32_base_Time_stamp; //Not used
	LcfAdapter_LcfInputData_VehIn.sSigHeader.uiTimeStamp = LcfAdapter_LcfInputData_VehIn.sSigHeader.uiTimeStamp * 1000; // From system time
	LcfAdapter_LcfLaDmcIucToSoc_VehIn.sSigHeader.uiTimeStamp = u32_base_Time_stamp; //Not uesed
	LcfAdapter_LcfSenOutputData_VehIn.sSigHeader.uiTimeStamp = u32_base_Time_stamp; //same as veh, no need to change
	LcfAdapter_LcfVehInputFromSenData_VehIn.sSigHeader.uiTimeStamp = u32_base_Time_stamp; //same as veh, no need to change
	//LcfAdapter_NvmLcfData.sSigHeader.uiTimeStamp = 1; // Pport
	LcfAdapter_VehDyn_VehIn.Lateral.Accel.LatAccelTimestamp.uiTimeStamp = u32_base_Time_stamp;
	LcfAdapter_VehDyn_VehIn.Lateral.YawRateTimestamp.uiTimeStamp = u32_base_Time_stamp;
	LcfAdapter_VehDyn_VehIn.Lateral.Curve.CurveTimestamp.uiTimeStamp = u32_base_Time_stamp;
	LcfAdapter_VehDyn_VehIn.Lateral.DrvIntCurve.CurveTimestamp.uiTimeStamp = u32_base_Time_stamp;

	LcfAdapter_VdyOffsets.sSigHeader.uiTimeStamp = LcfAdapter_VdyOffsets.sSigHeader.uiTimeStamp * 1000; // From Base control data
	LcfAdapter_VehDyn_VehIn.sSigHeader.uiTimeStamp = LcfAdapter_VehDyn_VehIn.sSigHeader.uiTimeStamp * 1000; // From Base control data
	LcfAdapter_VehPar_VehIn.sSigHeader.uiTimeStamp = LcfAdapter_VehPar_VehIn.sSigHeader.uiTimeStamp * 1000; // From system time
	LcfAdapter_VehSig_VehIn.sSigHeader.uiTimeStamp = LcfAdapter_VehSig_VehIn.sSigHeader.uiTimeStamp * 1000; // From Base control data
	LcfAdapter_VehSig_VehIn.VehSigMain.LatAccelTimeStamp = LcfAdapter_VehSig_VehIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_VehIn.VehSigMain.YawRateTimeStamp = LcfAdapter_VehSig_VehIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_VehIn.VehSigMain.StWheelAngleTimeStamp = LcfAdapter_VehSig_VehIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_VehIn.VehSigMain.VehLongAccelExtTimeStamp = LcfAdapter_VehSig_VehIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_VehIn.VehSigMain.VehVelocityExtTimeStamp = LcfAdapter_VehSig_VehIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_VehIn.VehSigMain.WhlTicksDevFrLeftTimeStamp = LcfAdapter_VehSig_VehIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_VehIn.VehSigMain.WhlTicksDevFrRightTimeStamp = LcfAdapter_VehSig_VehIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_VehIn.VehSigMain.WhlTicksDevReLeftTimeStamp = LcfAdapter_VehSig_VehIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_VehIn.VehSigMain.WhlVelFrLeftTimeStamp = LcfAdapter_VehSig_VehIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_VehIn.VehSigMain.WhlVelFrRightTimeStamp = LcfAdapter_VehSig_VehIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_VehIn.VehSigMain.WhlVelReLeftTimeStamp = LcfAdapter_VehSig_VehIn.sSigHeader.uiTimeStamp;
	LcfAdapter_VehSig_VehIn.VehSigMain.WhlVelReRightTimeStamp = LcfAdapter_VehSig_VehIn.sSigHeader.uiTimeStamp;

/***********************************************************************************/

    /*----------------------------Debug End----------------------------*/
#	if(DBG_LCFADAPTER_MEASFREEZE_ENABLE == STD_ON)
	// if(0 == (Debug_LcfAdapter_LcfVehExec_Counter % 2))
	// {
	(void)MTSI_DriverStartTaskCycle(23);		/*Update ID 23 counter*/
	LcfAdapter_MTSI_FreezeData_Proxy_23_In();	/*Update Lcf Veh input meas freeze data*/
	// }
#	endif
	/* Call the main logic function*/
	LcfVehExec(&LcfAdapter_reqLcfVehPrtData, &LcfAdapter_proLcfVehPrtData, &LcfAdapter_LcfServiceFunctionsTable);

#	if(DBG_LCFADAPTER_MEASFREEZE_ENABLE == STD_ON)
	// if(0 == (Debug_LcfAdapter_LcfVehExec_Counter % 2))
	// {
	LcfAdapter_MTSI_FreezeData_Proxy_23_Out();	/*Update Lcf Veh output meas freeze data*/
	// }
#	endif

    Rte_Write_PP_LcfAdapter_LcfVehGenericOutputData_LcfVehGenricOutputData(&LcfAdapter_LcfVehOutputData_VehOut);
    //Ioc_Write_Ioc_LcfVehGenericOutputs(LcfAdapter_LcfVehOutputData);

	SuspendAllInterrupts();

	(void)memcpy(&LcfAdapter_LcfSenInputFromVehData_SenIn, &LcfAdapter_LcfSenInputFromVehData_VehOut, sizeof(LCF_VehToSen_t));
	(void)memcpy(&LcfAdapter_LcfVehOutputData_SenIn, &LcfAdapter_LcfVehOutputData_VehOut, sizeof(LCF_VehGenericOutputs_t));

	ResumeAllInterrupts();
#endif
#if (DBG_LCFADAPTER_DEBUG_ENABLE == STD_ON)
    Time_MeasRunIntervalTimeMs_End(&Debug_LcfAdapter_LcfVehExec_RunInterval);
#endif

}

/**
 * \functions LcfAdapter_MainFunction
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */

extern VehDyn_t VdyAdapter_VehDyn;//Out
extern VDYOffsets_t VdyAdapter_VdyOffsets;//Out

void LCF_filledfixParm(void)
{
#if	(DBG_LCFADAPTER_ALGO_ENABLE == STD_ON)
	// Sdc_Perception_AbdOutputData.uiVersionNumber = 2;		//defined in Sdc.c
	// Sdc_Perception_AbdOutputData.sSigHeader.eSigStatus = 1;
	
	// Sdc_GenObjectList.uiVersionNumber = (AlgoInterfaceVersionNumber_t)EM_CAM_OBJECT_LIST_INTFVER;//defined in Sdc.c
 	// Sdc_GenObjectList.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

	// Fcu_LcfGenericInputData.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LCF_INPUT_INTFVER; //defined in Fcu.c
 	// Fcu_LcfGenericInputData.sSigHeader.eSigStatus = AL_SIG_STATE_OK;
	
	VdyAdapter_VehDyn.uiVersionNumber = (AlgoInterfaceVersionNumber_t)VDY_VEH_DYN_INTFVER_LCF;
 	VdyAdapter_VehDyn.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

	
	// Fcu_VehPar.uiVersionNumber = (AlgoInterfaceVersionNumber_t)BSW_VEH_PAR_INTFVER_LCF; //defined in Fcu.c
 	// Fcu_VehPar.sSigHeader.eSigStatus = AL_SIG_STATE_OK;
 	
	// Fcu_VehSigData.uiVersionNumber = (AlgoInterfaceVersionNumber_t)BSW_VEH_SIG_INTFVER_LCF; //defined in Fcu.c
 	// Fcu_VehSigData.sSigHeader.eSigStatus = AL_SIG_STATE_OK; 
 	
	LcfAdapter_AlgoCompState_Sen.uiVersionNumber = 0;						//need to confirm
 	LcfAdapter_AlgoCompState_Sen.sSigHeader.eSigStatus = AL_SIG_STATE_OK;
	LcfAdapter_proLcfSenPrtData.pAlgoCompState = &LcfAdapter_AlgoCompState_Sen;	
	
	// LcfAdapter_LcfSenOutputData.uiVersionNumber = 0;
 	// LcfAdapter_LcfSenOutputData.sSigHeader.eSigStatus = AL_SIG_STATE_OK;
	
	VdyAdapter_VdyOffsets.uiVersionNumber = (AlgoInterfaceVersionNumber_t)VDY_OFFSETS_INTFVER;
 	VdyAdapter_VdyOffsets.sSigHeader.eSigStatus = AL_SIG_STATE_OK;
	
	LcfAdapter_AlgoCompState_Veh.uiVersionNumber = 0;
 	LcfAdapter_AlgoCompState_Veh.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

	//debug , seams no need anaymore since Version number and sigstatus are freezed before LcfSenExec and LcfVehExec

	// LcfAdapter_LcfSenInputFromVehData.uiVersionNumber = 11;
	// LcfAdapter_LcfSenInputFromVehData.sSigHeader.eSigStatus = 1;
	LcfAdapter_LcfSenInputFromVehData_VehOut.uiVersionNumber = 11;
    LcfAdapter_LcfSenInputFromVehData_VehOut.sSigHeader.eSigStatus = 1;

	// LcfAdapter_LcfInputData.uiVersionNumber = 21; //defined in Fcu.c
	// LcfAdapter_LcfInputData.sSigHeader.eSigStatus = 1;

	//LcfAdapter_BaseCtrlData//defined in Fcu.c

	//LcfAdapter_LcfVehInputFromSenData.uiVersionNumber = 15;
	//LcfAdapter_LcfVehInputFromSenData.sSigHeader.eSigStatus = 1;

 	LcfAdapter_VehDyn_VehIn.uiVersionNumber = (AlgoInterfaceVersionNumber_t)VDY_VEH_DYN_INTFVER_LCF;
 	LcfAdapter_VehDyn_VehIn.sSigHeader.eSigStatus = AL_SIG_STATE_OK;
 	LcfAdapter_VehSig_VehIn.uiVersionNumber = (AlgoInterfaceVersionNumber_t)BSW_VEH_SIG_INTFVER_LCF;
 	LcfAdapter_VehSig_VehIn.sSigHeader.eSigStatus = AL_SIG_STATE_OK; 

	LcfAdapter_VehDyn_SenIn.uiVersionNumber = (AlgoInterfaceVersionNumber_t)VDY_VEH_DYN_INTFVER_LCF;
 	LcfAdapter_VehDyn_SenIn.sSigHeader.eSigStatus = AL_SIG_STATE_OK;
 	LcfAdapter_VehSig_SenIn.uiVersionNumber = (AlgoInterfaceVersionNumber_t)BSW_VEH_SIG_INTFVER_LCF;
 	LcfAdapter_VehSig_SenIn.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

#endif
}

FUNC(void, RTE_CODE) LcfAdapter_MainFunction (void)
{
#if	(DBG_LCFADAPTER_ALGO_ENABLE == STD_ON)
	LcfAdapter_CbOutputs.uiVersionNumber = (AlgoInterfaceVersionNumber_t)CB_PROVIDED_OUTPUTS_INTFVER;
	LcfAdapter_CbOutputs.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

	LcfAdapter_CParLdp.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LCF_TUN_PAR_LDP_INTFVER;
	LcfAdapter_CParLdp.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

	LcfAdapter_CParLka.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LCF_TUN_PAR_LKA_INTFVER;
	LcfAdapter_CParLka.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

	LcfAdapter_HlaRadarObjectList.uiVersionNumber = (AlgoInterfaceVersionNumber_t)HLA_RADAR_OBJECT_LIST_INTFVER;
	LcfAdapter_HlaRadarObjectList.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

	LcfAdapter_LcfLaDmcIucToSoc_SenIn.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LCF_IUC2SOC_INTFVER;;
	LcfAdapter_LcfLaDmcIucToSoc_SenIn.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

	LcfAdapter_LcfLaDmcIucToSoc_VehIn.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LCF_IUC2SOC_INTFVER;;
	LcfAdapter_LcfLaDmcIucToSoc_VehIn.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

	LcfAdapter_LsdEnvironmentData.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LSD_ENVIRONMENT_DATA_INTFVER;
	LcfAdapter_LsdEnvironmentData.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

	LcfAdapter_CParDmc.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LCF_TUN_PAR_DMC_INTFVER;

	LcfAdapter_CParKmc.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LCF_TUN_PAR_KMC_INTFVER;

	LcfAdapter_CamObjectList.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

	/*Debug,from Sdc*/
	LcfAdapter_GenObjectList.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

#endif





#if (DBG_LCFADAPTER_INTEGRATION_TEST_ENABLE == STD_ON )
	static uint32 AbdOutputData_t_t_counter8 = 0;

	LcfAdapter_AbdOutputData.uiVersionNumber = 2;
	LcfAdapter_AbdOutputData.sSigHeader.eSigStatus = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[0].sStatus.bAvailable = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[0].sStatus.iQuality = 95;
	LcfAdapter_AbdOutputData.asLaneBoundary[0].sAttributes.sType.eType = 2;
	LcfAdapter_AbdOutputData.asLaneBoundary[0].sAttributes.eColor = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[0].sGeometry.sParameters.fDistanceStdMeter = 0.0157800000;
	LcfAdapter_AbdOutputData.asLaneBoundary[0].sGeometry.sParameters.fYawAngleRad = 0.00462861871;
	LcfAdapter_AbdOutputData.asLaneBoundary[0].sGeometry.sParameters.fYawAngleStdRad = 0.00179999997;
	LcfAdapter_AbdOutputData.asLaneBoundary[0].sGeometry.sParameters.sClothoidNear.fCurvature = -1.37201105e-05;
	LcfAdapter_AbdOutputData.asLaneBoundary[0].sGeometry.sParameters.sClothoidNear.fCurvatureStd = 0.000160800002;
	LcfAdapter_AbdOutputData.asLaneBoundary[0].sGeometry.sParameters.sClothoidNear.fCurvatureRate = 0.000000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[0].sGeometry.sParameters.sClothoidNear.fCurvatureRateStd	= 1.37799998e-06;
	LcfAdapter_AbdOutputData.asLaneBoundary[0].sGeometry.sParameters.sClothoidNear.fValidLengthMeter	= 60.0000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[1].sStatus.bAvailable = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[1].sStatus.iQuality = 95;
	LcfAdapter_AbdOutputData.asLaneBoundary[1].sAttributes.sType.eType = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[1].sAttributes.eColor = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[1].sGeometry.sParameters.fDistanceMeter = -2.01524639;
	LcfAdapter_AbdOutputData.asLaneBoundary[1].sGeometry.sParameters.fDistanceStdMeter = 0.0157800000;
	LcfAdapter_AbdOutputData.asLaneBoundary[1].sGeometry.sParameters.fYawAngleRad = 0.00462861871;
	LcfAdapter_AbdOutputData.asLaneBoundary[1].sGeometry.sParameters.fYawAngleStdRad = 0.00179999997;
	LcfAdapter_AbdOutputData.asLaneBoundary[1].sGeometry.sParameters.sClothoidNear.fCurvature = -1.37201105e-05;
	LcfAdapter_AbdOutputData.asLaneBoundary[1].sGeometry.sParameters.sClothoidNear.fCurvatureStd = 0.000160800002;
	LcfAdapter_AbdOutputData.asLaneBoundary[1].sGeometry.sParameters.sClothoidNear.fCurvatureRate = 0.000000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[1].sGeometry.sParameters.sClothoidNear.fCurvatureRateStd	= 1.37799998e-06;
	LcfAdapter_AbdOutputData.asLaneBoundary[1].sGeometry.sParameters.sClothoidNear.fValidLengthMeter	= 60.0000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[2].sStatus.bAvailable = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[2].sStatus.iQuality = 100;
	LcfAdapter_AbdOutputData.asLaneBoundary[2].sAttributes.sType.eType = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[2].sAttributes.eColor = 1;
	//LcfAdapter_AbdOutputData.asLaneBoundary[2].sGeometry.sParameters.fDistanceMeter = 4.24556828;
	LcfAdapter_AbdOutputData.asLaneBoundary[2].sGeometry.sParameters.fDistanceStdMeter = 0.0157800000;
	LcfAdapter_AbdOutputData.asLaneBoundary[2].sGeometry.sParameters.fYawAngleRad = 0.00462861871;
	LcfAdapter_AbdOutputData.asLaneBoundary[2].sGeometry.sParameters.fYawAngleStdRad = 0.00179999997;
	LcfAdapter_AbdOutputData.asLaneBoundary[2].sGeometry.sParameters.sClothoidNear.fCurvature = -1.37201105e-05;
	LcfAdapter_AbdOutputData.asLaneBoundary[2].sGeometry.sParameters.sClothoidNear.fCurvatureStd = 0.000160800002;
	LcfAdapter_AbdOutputData.asLaneBoundary[2].sGeometry.sParameters.sClothoidNear.fCurvatureRate = 0.000000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[2].sGeometry.sParameters.sClothoidNear.fCurvatureRateStd	= 1.37799998e-06;
	LcfAdapter_AbdOutputData.asLaneBoundary[2].sGeometry.sParameters.sClothoidNear.fValidLengthMeter	= 60.0000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[3].sStatus.bAvailable = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[3].sStatus.iQuality = 100;
	LcfAdapter_AbdOutputData.asLaneBoundary[3].sAttributes.sType.eType = 0;
	LcfAdapter_AbdOutputData.asLaneBoundary[3].sAttributes.eColor = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[3].sGeometry.sParameters.fDistanceMeter = 0.000000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[3].sGeometry.sParameters.fDistanceStdMeter = 0.0157800000;
	LcfAdapter_AbdOutputData.asLaneBoundary[3].sGeometry.sParameters.fYawAngleRad = 0.00462861871;
	LcfAdapter_AbdOutputData.asLaneBoundary[3].sGeometry.sParameters.fYawAngleStdRad = 0.00179999997;
	LcfAdapter_AbdOutputData.asLaneBoundary[3].sGeometry.sParameters.sClothoidNear.fCurvature = -1.37201105e-05;
	LcfAdapter_AbdOutputData.asLaneBoundary[3].sGeometry.sParameters.sClothoidNear.fCurvatureStd = 0.000160800002;
	LcfAdapter_AbdOutputData.asLaneBoundary[3].sGeometry.sParameters.sClothoidNear.fCurvatureRate = 0.000000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[3].sGeometry.sParameters.sClothoidNear.fCurvatureRateStd	= 1.37799998e-06;
	LcfAdapter_AbdOutputData.asLaneBoundary[3].sGeometry.sParameters.sClothoidNear.fValidLengthMeter	= 60.0000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[4].sStatus.bAvailable = 0;
	LcfAdapter_AbdOutputData.asLaneBoundary[4].sStatus.iQuality = 0;
	LcfAdapter_AbdOutputData.asLaneBoundary[4].sAttributes.sType.eType = 2;
	LcfAdapter_AbdOutputData.asLaneBoundary[4].sAttributes.eColor = 1;
	//LcfAdapter_AbdOutputData.asLaneBoundary[4].sGeometry.sParameters.fDistanceMeter = 4.38475370;
	LcfAdapter_AbdOutputData.asLaneBoundary[4].sGeometry.sParameters.fDistanceStdMeter = 0.0157800000;
	LcfAdapter_AbdOutputData.asLaneBoundary[4].sGeometry.sParameters.fYawAngleRad = 0.00462861871;
	LcfAdapter_AbdOutputData.asLaneBoundary[4].sGeometry.sParameters.fYawAngleStdRad = 0.00179999997;
	LcfAdapter_AbdOutputData.asLaneBoundary[4].sGeometry.sParameters.sClothoidNear.fCurvature = -1.37201105e-05;
	LcfAdapter_AbdOutputData.asLaneBoundary[4].sGeometry.sParameters.sClothoidNear.fCurvatureStd = 0.000160800002;
	LcfAdapter_AbdOutputData.asLaneBoundary[4].sGeometry.sParameters.sClothoidNear.fCurvatureRate = 0.000000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[4].sGeometry.sParameters.sClothoidNear.fCurvatureRateStd	= 1.37799998e-06;
	LcfAdapter_AbdOutputData.asLaneBoundary[4].sGeometry.sParameters.sClothoidNear.fValidLengthMeter	= 0.0000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[5].sStatus.bAvailable = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[5].sStatus.iQuality = 100;
	LcfAdapter_AbdOutputData.asLaneBoundary[5].sAttributes.sType.eType = 9;
	LcfAdapter_AbdOutputData.asLaneBoundary[5].sAttributes.eColor = 1;
	//LcfAdapter_AbdOutputData.asLaneBoundary[5].sGeometry.sParameters.fDistanceMeter = -2.11524630;
	LcfAdapter_AbdOutputData.asLaneBoundary[5].sGeometry.sParameters.fDistanceStdMeter = 0.0157800000;
	LcfAdapter_AbdOutputData.asLaneBoundary[5].sGeometry.sParameters.fYawAngleRad = 0.00462861871;
	LcfAdapter_AbdOutputData.asLaneBoundary[5].sGeometry.sParameters.fYawAngleStdRad = 0.00179999997;
	LcfAdapter_AbdOutputData.asLaneBoundary[5].sGeometry.sParameters.sClothoidNear.fCurvature = -1.37201105e-05;
	LcfAdapter_AbdOutputData.asLaneBoundary[5].sGeometry.sParameters.sClothoidNear.fCurvatureStd = 0.000160800002;
	LcfAdapter_AbdOutputData.asLaneBoundary[5].sGeometry.sParameters.sClothoidNear.fCurvatureRate = 0.000000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[5].sGeometry.sParameters.sClothoidNear.fCurvatureRateStd	= 1.37799998e-06;
	LcfAdapter_AbdOutputData.asLaneBoundary[5].sGeometry.sParameters.sClothoidNear.fValidLengthMeter	= 60.0000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[6].sStatus.bAvailable = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[6].sStatus.iQuality = 95;
	LcfAdapter_AbdOutputData.asLaneBoundary[6].sAttributes.sType.eType = 2;
	LcfAdapter_AbdOutputData.asLaneBoundary[6].sAttributes.eColor = 1;
	// LcfAdapter_AbdOutputData.asLaneBoundary[6].sGeometry.sParameters.fDistanceMeter = 1.03475356;
	LcfAdapter_AbdOutputData.asLaneBoundary[6].sGeometry.sParameters.fDistanceStdMeter = 0.0157800000;
	LcfAdapter_AbdOutputData.asLaneBoundary[6].sGeometry.sParameters.fYawAngleRad = 0.00462861871;
	LcfAdapter_AbdOutputData.asLaneBoundary[6].sGeometry.sParameters.fYawAngleStdRad = 0.00179999997;
	LcfAdapter_AbdOutputData.asLaneBoundary[6].sGeometry.sParameters.sClothoidNear.fCurvature = -1.37201105e-05;
	LcfAdapter_AbdOutputData.asLaneBoundary[6].sGeometry.sParameters.sClothoidNear.fCurvatureStd = 0.000160800002;
	LcfAdapter_AbdOutputData.asLaneBoundary[6].sGeometry.sParameters.sClothoidNear.fCurvatureRate = 0.000000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[6].sGeometry.sParameters.sClothoidNear.fCurvatureRateStd	= 1.37799998e-06;
	LcfAdapter_AbdOutputData.asLaneBoundary[6].sGeometry.sParameters.sClothoidNear.fValidLengthMeter	= 60.0000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[7].sStatus.bAvailable = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[7].sStatus.iQuality = 95;
	LcfAdapter_AbdOutputData.asLaneBoundary[7].sAttributes.sType.eType = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[7].sAttributes.eColor = 1;
	//LcfAdapter_AbdOutputData.asLaneBoundary[7].sGeometry.sParameters.fDistanceMeter = -2.01524639;
	LcfAdapter_AbdOutputData.asLaneBoundary[7].sGeometry.sParameters.fDistanceStdMeter = 0.0157800000;
	LcfAdapter_AbdOutputData.asLaneBoundary[7].sGeometry.sParameters.fYawAngleRad = 0.00462861871;
	LcfAdapter_AbdOutputData.asLaneBoundary[7].sGeometry.sParameters.fYawAngleStdRad = 0.00179999997;
	LcfAdapter_AbdOutputData.asLaneBoundary[7].sGeometry.sParameters.sClothoidNear.fCurvature = -1.37201105e-05;
	LcfAdapter_AbdOutputData.asLaneBoundary[7].sGeometry.sParameters.sClothoidNear.fCurvatureStd = 0.000160800002;
	LcfAdapter_AbdOutputData.asLaneBoundary[7].sGeometry.sParameters.sClothoidNear.fCurvatureRate = 0.000000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[7].sGeometry.sParameters.sClothoidNear.fCurvatureRateStd	= 1.37799998e-06;
	LcfAdapter_AbdOutputData.asLaneBoundary[7].sGeometry.sParameters.sClothoidNear.fValidLengthMeter	= 60.0000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[8].sStatus.bAvailable = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[8].sStatus.iQuality = 95;
	LcfAdapter_AbdOutputData.asLaneBoundary[8].sAttributes.sType.eType = 2;
	LcfAdapter_AbdOutputData.asLaneBoundary[8].sAttributes.eColor = 1;

	LcfAdapter_AbdOutputData.asLaneBoundary[8].sGeometry.sParameters.fDistanceStdMeter = 0.0157800000;
	LcfAdapter_AbdOutputData.asLaneBoundary[8].sGeometry.sParameters.fYawAngleRad = 0.00462861871;
	LcfAdapter_AbdOutputData.asLaneBoundary[8].sGeometry.sParameters.fYawAngleStdRad = 0.00179999997;
	LcfAdapter_AbdOutputData.asLaneBoundary[8].sGeometry.sParameters.sClothoidNear.fCurvature = -1.37201105e-05;
	LcfAdapter_AbdOutputData.asLaneBoundary[8].sGeometry.sParameters.sClothoidNear.fCurvatureStd = 0.000160800002;
	LcfAdapter_AbdOutputData.asLaneBoundary[8].sGeometry.sParameters.sClothoidNear.fCurvatureRate = 0.000000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[8].sGeometry.sParameters.sClothoidNear.fCurvatureRateStd	= 1.37799998e-06;
	LcfAdapter_AbdOutputData.asLaneBoundary[8].sGeometry.sParameters.sClothoidNear.fValidLengthMeter	= 60.0000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[9].sStatus.bAvailable = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[9].sStatus.iQuality = 95;
	LcfAdapter_AbdOutputData.asLaneBoundary[9].sAttributes.sType.eType = 1;
	LcfAdapter_AbdOutputData.asLaneBoundary[9].sAttributes.eColor = 1;
	//LcfAdapter_AbdOutputData.asLaneBoundary[9].sGeometry.sParameters.fDistanceMeter = -2.01524639;
	LcfAdapter_AbdOutputData.asLaneBoundary[9].sGeometry.sParameters.fDistanceStdMeter = 0.0157800000;
	LcfAdapter_AbdOutputData.asLaneBoundary[9].sGeometry.sParameters.fYawAngleRad = 0.00462861871;
	LcfAdapter_AbdOutputData.asLaneBoundary[9].sGeometry.sParameters.fYawAngleStdRad = 0.00179999997;
	LcfAdapter_AbdOutputData.asLaneBoundary[9].sGeometry.sParameters.sClothoidNear.fCurvature = -1.37201105e-05;
	LcfAdapter_AbdOutputData.asLaneBoundary[9].sGeometry.sParameters.sClothoidNear.fCurvatureStd = 0.000160800002;
	LcfAdapter_AbdOutputData.asLaneBoundary[9].sGeometry.sParameters.sClothoidNear.fCurvatureRate = 0.000000000;
	LcfAdapter_AbdOutputData.asLaneBoundary[9].sGeometry.sParameters.sClothoidNear.fCurvatureRateStd	= 1.37799998e-06;
	LcfAdapter_AbdOutputData.asLaneBoundary[9].sGeometry.sParameters.sClothoidNear.fValidLengthMeter	= 60.0000000;
	LcfAdapter_AbdOutputData.sLaneInformation.aiLaneBoundariesRight[0] = 1;
	LcfAdapter_AbdOutputData.sLaneInformation.aiLaneBoundariesRight[1] = -1;
	LcfAdapter_AbdOutputData.sLaneInformation.aiLaneBoundariesRight[2] = 5;
	LcfAdapter_AbdOutputData.sLaneInformation.aiLaneBoundariesLeft[0] = 0;
	LcfAdapter_AbdOutputData.sLaneInformation.aiLaneBoundariesLeft[1] = 2;
	LcfAdapter_AbdOutputData.sLaneInformation.aiLaneBoundariesLeft[2] = -1;
	LcfAdapter_AbdOutputData.sLaneInformation.sEventRight.eLaneEventType =	0;
	LcfAdapter_AbdOutputData.sLaneInformation.sEventRight.fEventDist =	0.000000000;
	LcfAdapter_AbdOutputData.sLaneInformation.sEventRight.iEventQuality = 0;
	LcfAdapter_AbdOutputData.sLaneInformation.sEventRight.iMergeSplitToTrackId = 0;
	LcfAdapter_AbdOutputData.sLaneInformation.sEventLeft.eLaneEventType =	0;
	LcfAdapter_AbdOutputData.sLaneInformation.sEventLeft.fEventDist =	0.000000000;
	LcfAdapter_AbdOutputData.sLaneInformation.sEventLeft.iEventQuality = 0;
	LcfAdapter_AbdOutputData.sLaneInformation.sEventLeft.iMergeSplitToTrackId = 0;
	LcfAdapter_AbdOutputData.eParallelModelActive = 0;
	LcfAdapter_AbdOutputData.eLaneChange =	0;
	if (AbdOutputData_t_t_counter8>100)
	{
		LcfAdapter_AbdOutputData.asLaneBoundary[8].sGeometry.sParameters.fDistanceMeter = 1.525 - 0.083 * (AbdOutputData_t_t_counter8-100)*0.2;
		LcfAdapter_AbdOutputData.asLaneBoundary[0].sGeometry.sParameters.fDistanceMeter = 1.495 - 0.083 * (AbdOutputData_t_t_counter8-100)*0.2;
		LcfAdapter_AbdOutputData.asLaneBoundary[6].sGeometry.sParameters.fDistanceMeter = 1.495 - 0.083 * (AbdOutputData_t_t_counter8-100)*0.2;
		LcfAdapter_AbdOutputData.asLaneBoundary[2].sGeometry.sParameters.fDistanceMeter = 4.7 - 0.083 * (AbdOutputData_t_t_counter8-100)*0.2;
		LcfAdapter_AbdOutputData.asLaneBoundary[4].sGeometry.sParameters.fDistanceMeter = 4.84 - 0.083 * (AbdOutputData_t_t_counter8-100)*0.2;
		LcfAdapter_AbdOutputData.asLaneBoundary[1].sGeometry.sParameters.fDistanceMeter = -1.565 - 0.083 * (AbdOutputData_t_t_counter8-100)*0.2;
		LcfAdapter_AbdOutputData.asLaneBoundary[7].sGeometry.sParameters.fDistanceMeter = -1.565 - 0.083 * (AbdOutputData_t_t_counter8-100)*0.2;
		LcfAdapter_AbdOutputData.asLaneBoundary[9].sGeometry.sParameters.fDistanceMeter = -1.565 - 0.083 * (AbdOutputData_t_t_counter8-100)*0.2;
		LcfAdapter_AbdOutputData.asLaneBoundary[5].sGeometry.sParameters.fDistanceMeter = -1.665 - 0.083 * (AbdOutputData_t_t_counter8-100)*0.2;
	}
	else
	{
		LcfAdapter_AbdOutputData.asLaneBoundary[8].sGeometry.sParameters.fDistanceMeter = 1.525;
		LcfAdapter_AbdOutputData.asLaneBoundary[0].sGeometry.sParameters.fDistanceMeter = 1.495;
		LcfAdapter_AbdOutputData.asLaneBoundary[6].sGeometry.sParameters.fDistanceMeter = 1.495;
		LcfAdapter_AbdOutputData.asLaneBoundary[2].sGeometry.sParameters.fDistanceMeter = 4.7;
		LcfAdapter_AbdOutputData.asLaneBoundary[4].sGeometry.sParameters.fDistanceMeter = 4.84;
		LcfAdapter_AbdOutputData.asLaneBoundary[1].sGeometry.sParameters.fDistanceMeter = -1.565;
		LcfAdapter_AbdOutputData.asLaneBoundary[7].sGeometry.sParameters.fDistanceMeter = -1.565;
		LcfAdapter_AbdOutputData.asLaneBoundary[9].sGeometry.sParameters.fDistanceMeter = -1.565;
		LcfAdapter_AbdOutputData.asLaneBoundary[5].sGeometry.sParameters.fDistanceMeter = -1.665;
	}
	if(LcfAdapter_AbdOutputData.asLaneBoundary[8].sGeometry.sParameters.fDistanceMeter <=1)
	{
		LcfAdapter_AbdOutputData.asLaneBoundary[8].sGeometry.sParameters.fDistanceMeter = 1;
	}
	AbdOutputData_t_t_counter8++;

	LcfAdapter_GenObjectList.uiVersionNumber = (AlgoInterfaceVersionNumber_t)EM_CAM_OBJECT_LIST_INTFVER;
 	LcfAdapter_GenObjectList.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

//	LcfAdapter_CParLdp.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LCF_TUN_PAR_LDP_INTFVER;
//	LcfAdapter_CParLdp.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

//	LcfAdapter_CParLka.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LCF_TUN_PAR_LKA_INTFVER;
//	LcfAdapter_CParLka.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

//	LcfAdapter_HlaRadarObjectList.uiVersionNumber = (AlgoInterfaceVersionNumber_t)HLA_RADAR_OBJECT_LIST_INTFVER;
//	LcfAdapter_HlaRadarObjectList.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

//	LcfAdapter_LsdEnvironmentData.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LSD_ENVIRONMENT_DATA_INTFVER;
//	LcfAdapter_LsdEnvironmentData.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

    LcfAdapter_LcfInputData.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LCF_INPUT_INTFVER;
 	LcfAdapter_LcfInputData.sSigHeader.eSigStatus = AL_SIG_STATE_OK;
	LcfAdapter_LcfInputData.SteerHandWheelAngle_rad = -0.00980121084;
	LcfAdapter_LcfInputData.SteerHandWheelAngleRate_rps = 0.0305393059;
	LcfAdapter_LcfInputData.DeltaFSteerAngle_deg = -0.561567247;
	LcfAdapter_LcfInputData.DeltaFSteerAngleRate_degps = 1.74977088;
	LcfAdapter_LcfInputData.DrvSteerWheelTrq_nm = -0.298546821;
	LcfAdapter_LcfInputData.VehicleReadyState_nu = 1;
	LcfAdapter_LcfInputData.EPS_Toi_Active_nu = 1;
	LcfAdapter_LcfInputData.LDPSwitch_nu = 1;
	LcfAdapter_LcfInputData.LDWSwitch_nu = 1;
	LcfAdapter_LcfInputData.LKAMainSwitch_nu = 1;
	LcfAdapter_LcfInputData.HDAOn_nu = 1;
	LcfAdapter_LcfInputData.LcfVariantInfo_nu = 1;
	LcfAdapter_LcfInputData.OIQualifierFlag_RearLeft_nu = 1;
	LcfAdapter_LcfInputData.OIQualifierFlag_RearRight_nu = 1;

//	LcfAdapter_LcfLaDmcIucToSoc.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LCF_IUC2SOC_INTFVER;;
//	LcfAdapter_LcfLaDmcIucToSoc.sSigHeader.eSigStatus = AL_SIG_STATE_OK;
	
	/*TODO : the data is from LcfVeh,not set any value*/
//    LcfAdapter_LcfSenInputFromVehData.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LCF_VEH2SEN_INTFVER;
// 	LcfAdapter_LcfSenInputFromVehData.sSigHeader.eSigStatus = AL_SIG_STATE_OK;
//	LcfAdapter_LcfSenInputFromVehData.DrvAttention_perc = 100.000000;
//	LcfAdapter_LcfSenInputFromVehData.DrvAttentionConf_perc = 100;
//	LcfAdapter_LcfSenInputFromVehData.EstHandTor_nm = -0.306646407;
//	LcfAdapter_LcfSenInputFromVehData.ReplanValues.TrajGuiQualifier_nu = 1;
//	LcfAdapter_LcfSenInputFromVehData.TrajError.CurDistY_m = 2.01168060;
//	LcfAdapter_LcfSenInputFromVehData.TrajError.CurHeading_rad = 0.00416467944;
//	LcfAdapter_LcfSenInputFromVehData.TrajError.LtcyComp_DevHeading_rad = 0.00416467944;
//	LcfAdapter_LcfSenInputFromVehData.DesiredTraj.TrajDistY_m = 2.01340556;
//	LcfAdapter_LcfSenInputFromVehData.DesiredTraj.TrajHeading_rad = 0.00410576537;
//	LcfAdapter_LcfSenInputFromVehData.DesiredTraj.TrajHeadingInclPreview_rad = 0.00410576537;
//	LcfAdapter_LcfSenInputFromVehData.TrajPlanCurvatures.TgtTrajCrv_1pm = -0.000128893502;
//	LcfAdapter_LcfSenInputFromVehData.Errors.CtrlErrDistY_m = 0.000905489724;
//	LcfAdapter_LcfSenInputFromVehData.Errors.CtrlErrHeadingAngle_rad = 6.55187323e-05;
//	LcfAdapter_LcfSenInputFromVehData.Curvatures.TgtCrv_DE_1pm = -0.000128893502;
//	LcfAdapter_LcfSenInputFromVehData.Curvatures.TgtCrv_Limited_1pm = -0.000128893502;

	/*TODO : the data is from LcfVeh,not set any value*/
//    LcfAdapter_LcfVehOutputData.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LCF_VEH_OUTPUT_INTFVER;
// 	LcfAdapter_LcfVehOutputData.sSigHeader.eSigStatus = AL_SIG_STATE_OK;
	
 	/*TODO : the data is from LcfVeh,not set any value*/
//	LcfAdapter_LcfVehInputFromSenData.uiVersionNumber = 15;
//	LcfAdapter_LcfVehInputFromSenData.sSigHeader.eSigStatus = 1;

	/*TODO : the data is from LcfVeh,not set any value*/
//    LcfAdapter_NvmLcfData.uiVersionNumber	= (AlgoInterfaceVersionNumber_t)LCF_LEARNDATA_INTFVER;
//	LcfAdapter_NvmLcfData.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

 	LcfAdapter_VehDyn.uiVersionNumber = (AlgoInterfaceVersionNumber_t)VDY_VEH_DYN_INTFVER_LCF;
 	LcfAdapter_VehDyn.sSigHeader.eSigStatus = AL_SIG_STATE_OK;
	LcfAdapter_VehDyn.Longitudinal.Velocity = 20.8291264;
	LcfAdapter_VehDyn.Longitudinal.Accel = -0.00209436845;
	LcfAdapter_VehDyn.Lateral.YawRate.YawRate = -0.000585094851;
	LcfAdapter_VehDyn.Lateral.YawRate.Variance = 0.000249008386;
	LcfAdapter_VehDyn.Lateral.OffCompStWheelAngle = -0.000847072864;
	LcfAdapter_VehDyn.Lateral.Curve.Curve = -2.80902259e-05;
	LcfAdapter_VehDyn.Lateral.DrvIntCurve.Curve = -2.80902259e-05;
	LcfAdapter_VehDyn.Lateral.Accel.LatAccel = -0.0127945784;
	LcfAdapter_VehDyn.Lateral.SlipAngle.SideSlipAngle = 1.13656934e-05;
	LcfAdapter_VehDyn.MotionState.MotState = 1;
	
 	LcfAdapter_VehPar.uiVersionNumber = (AlgoInterfaceVersionNumber_t)BSW_VEH_PAR_INTFVER_LCF;
 	LcfAdapter_VehPar.sSigHeader.eSigStatus = AL_SIG_STATE_OK;
	LcfAdapter_VehPar.VehParMain.WheelBase = 2.7;
	LcfAdapter_VehPar.VehParAdd.VehicleWidth = 1.917;
	LcfAdapter_VehPar.VehParAdd.VehicleLength = 4.56;
	LcfAdapter_VehPar.VehParAdd.OverhangFront = 0.948;

 	LcfAdapter_VehSig.uiVersionNumber = (AlgoInterfaceVersionNumber_t)BSW_VEH_SIG_INTFVER_LCF;
 	LcfAdapter_VehSig.sSigHeader.eSigStatus = AL_SIG_STATE_OK; 
	LcfAdapter_VehSig.VehSigMain.ActGearPos = 2;
	LcfAdapter_VehSig.VehSigAdd.WiperState = 1;
	LcfAdapter_VehSig.VehSigAdd.SpeedoSpeed = 75;
	
 	LcfAdapter_AlgoCompState_Sen.uiVersionNumber = 0;
 	LcfAdapter_AlgoCompState_Sen.sSigHeader.eSigStatus = AL_SIG_STATE_OK;
	
    LcfAdapter_LcfSenOutputData.uiVersionNumber = 0;
 	LcfAdapter_LcfSenOutputData.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

//	LcfAdapter_CParDmc.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LCF_TUN_PAR_DMC_INTFVER;
//
//	LcfAdapter_CParKmc.uiVersionNumber = (AlgoInterfaceVersionNumber_t)LCF_TUN_PAR_KMC_INTFVER;

	LcfAdapter_VdyOffsets.uiVersionNumber = (AlgoInterfaceVersionNumber_t)VDY_OFFSETS_INTFVER;
 	LcfAdapter_VdyOffsets.sSigHeader.eSigStatus = AL_SIG_STATE_OK;
	LcfAdapter_VdyOffsets.Ywr.StandStillState = 1;
	LcfAdapter_VdyOffsets.Swa.State = 1;

	LcfAdapter_AlgoCompState_Veh.uiVersionNumber = 0;
 	LcfAdapter_AlgoCompState_Veh.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

//	LcfAdapter_LcfLaDmcSocToIuc.uiVersionNumber = 0;
//	LcfAdapter_LcfLaDmcSocToIuc.sSigHeader.eSigStatus = AL_SIG_STATE_OK;

	// LcfAdapter_BaseCtrlData.eOpMode  = 0x04;/*BASE_OM_RUN*/

	//mapping the pointer
	LcfAdapter_reqLcfSenPrtData.pBaseCtrlData = &LcfAdapter_BaseCtrlData;
	LcfAdapter_reqLcfSenPrtData.pAbdOutputData = &LcfAdapter_AbdOutputData;
//	LcfAdapter_reqLcfSenPrtData.pCamObjectList = &LcfAdapter_CamObjectList;
//	LcfAdapter_reqLcfSenPrtData.pCbOutputs = &LcfAdapter_CbOutputs;
//	LcfAdapter_reqLcfSenPrtData.pCParLdp = &LcfAdapter_CParLdp;
//	LcfAdapter_reqLcfSenPrtData.pCParLka = &LcfAdapter_CParLka;
	LcfAdapter_reqLcfSenPrtData.pGenObjectList = &LcfAdapter_GenObjectList;
//	LcfAdapter_reqLcfSenPrtData.pHlaRadarObjectList = &LcfAdapter_HlaRadarObjectList;
	LcfAdapter_reqLcfSenPrtData.pLcfInputData = &LcfAdapter_LcfInputData;
//	LcfAdapter_reqLcfSenPrtData.pLcfLaDmcIucToSoc = &LcfAdapter_LcfLaDmcIucToSoc;
	LcfAdapter_reqLcfSenPrtData.pLcfSenInputFromVehData = &LcfAdapter_LcfSenInputFromVehData;
	LcfAdapter_reqLcfSenPrtData.pLcfVehOutputData = &LcfAdapter_LcfVehOutputData;
//	LcfAdapter_reqLcfSenPrtData.pLsdEnvironmentData = &LcfAdapter_LsdEnvironmentData;
	LcfAdapter_reqLcfSenPrtData.pVehDyn = &LcfAdapter_VehDyn;
	LcfAdapter_reqLcfSenPrtData.pVehPar = &LcfAdapter_VehPar;
	LcfAdapter_reqLcfSenPrtData.pVehSig = &LcfAdapter_VehSig;

	LcfAdapter_proLcfSenPrtData.pAlgoCompState = &LcfAdapter_AlgoCompState_Sen;
	LcfAdapter_proLcfSenPrtData.pLcfSenOutputData = &LcfAdapter_LcfSenOutputData;
	LcfAdapter_proLcfSenPrtData.pLcfSenOutputToVehData = &LcfAdapter_LcfVehInputFromSenData;

	LcfAdapter_reqLcfVehPrtData.pBaseCtrlData = &LcfAdapter_BaseCtrlData;
	LcfAdapter_reqLcfVehPrtData.pAbdOutputData = &LcfAdapter_AbdOutputData;
//	LcfAdapter_reqLcfVehPrtData.pCParDmc = &LcfAdapter_CParDmc;
//	LcfAdapter_reqLcfVehPrtData.pCParKmc = &LcfAdapter_CParKmc;
	LcfAdapter_reqLcfVehPrtData.pLcfInputData = &LcfAdapter_LcfInputData;
//	LcfAdapter_reqLcfVehPrtData.pLcfLaDmcIucToSoc = &LcfAdapter_LcfLaDmcIucToSoc;
	LcfAdapter_reqLcfVehPrtData.pLcfSenOutputData = &LcfAdapter_LcfSenOutputData;
	LcfAdapter_reqLcfVehPrtData.pLcfVehInputFromSenData = &LcfAdapter_LcfVehInputFromSenData;
//	LcfAdapter_reqLcfVehPrtData.pNvmLcfData = &LcfAdapter_NvmLcfData;
	LcfAdapter_reqLcfVehPrtData.pVdyOffsets = &LcfAdapter_VdyOffsets;
	LcfAdapter_reqLcfVehPrtData.pVehDyn = &LcfAdapter_VehDyn;
	LcfAdapter_reqLcfVehPrtData.pVehPar = &LcfAdapter_VehPar;
	LcfAdapter_reqLcfVehPrtData.pVehSig = &LcfAdapter_VehSig;

	LcfAdapter_proLcfVehPrtData.pAlgoCompState = &LcfAdapter_AlgoCompState_Veh;
//	LcfAdapter_proLcfVehPrtData.pLcfLaDmcSocToIuc = &LcfAdapter_LcfLaDmcSocToIuc;
	LcfAdapter_proLcfVehPrtData.pLcfVehOutputData = &LcfAdapter_LcfVehOutputData;
	LcfAdapter_proLcfVehPrtData.pLcfVehOutputToSenData = &LcfAdapter_LcfSenInputFromVehData;
	LcfAdapter_proLcfVehPrtData.pNvmLcfData = &LcfAdapter_NvmLcfData;
#else
	/*fill versionnumber and eSigStatus fix value*/
	LCF_filledfixParm();
#endif
// end of function LCFADAPTER_BENCH_TEST_ENABLE
}

/*==================[internal function definitions]=========================*/
#if	(DBG_LCFADAPTER_ALGO_ENABLE == STD_ON)
/**
 * \functions LcfAdapter_Cot_MeasHdlr
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */
static AS_t_MeasReturn LcfAdapter_Cot_MeasHdlr(const AS_t_MeasInfo * const meas_info, const void * data, AS_t_MeasCallback callback)
{
	MEASFreezeDataMTS(meas_info, data, NULL_PTR);
	return 0;
}

static sint32 LcfAdapter_Cot_RTAAlgoServiceAddEvent(const AS_t_RtaEventType RtaEvtType, const uint8 u_IdGlobal, const uint8 u_IdLocal, const uint8 u_OptData)
{
	return 0;
}

static AS_t_Dem_ReturnType LcfAdapter_Cot_Dem_SetEventStatus(const AS_t_Dem_EventIDType u_Dem_EventIdRaw, const AS_t_Dem_EventStatusType u_Dem_EventStatus)
{
	return 0;
}


static void LcfAdapter_Mtsi(uint32 VirtAdd, uint8 funcid, pvoid data_p, uint32 length)
{
	AS_t_MeasInfo meas_info;
	meas_info.VirtualAddress = VirtAdd;
	meas_info.Length = length;
	meas_info.FuncID = funcid;
	MEASFreezeDataMTS(&meas_info, data_p, NULL_PTR);
}

void LcfAdapter_MTSI_FreezeData_Proxy_23_In(void)
{
	/*** Lcf Veh input data: ***/
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_BASECTRL_VI	,23,&LcfAdapter_BaseCtrlData_VehIn,sizeof(LcfAdapter_BaseCtrlData_VehIn));//24
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_ABDOUTPUT_VI	,23,&LcfAdapter_AbdOutputData_VehIn,sizeof(LcfAdapter_AbdOutputData_VehIn));
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_LCFINPUT_VI	,23,&LcfAdapter_LcfInputData_VehIn,sizeof(LcfAdapter_LcfInputData_VehIn));//600
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_LCFSODATA_VI	,23,&LcfAdapter_LcfSenOutputData_VehIn,sizeof(LcfAdapter_LcfSenOutputData_VehIn));
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_LCFVIFS_VI	,23,&LcfAdapter_LcfVehInputFromSenData_VehIn,sizeof(LcfAdapter_LcfVehInputFromSenData_VehIn));
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_NVMLCF_VI		,23,&LcfAdapter_NvmLcfData,sizeof(LcfAdapter_NvmLcfData));//140	
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_VDYOFFSET		,23,&LcfAdapter_VdyOffsets,sizeof(LcfAdapter_VdyOffsets));//56
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_VEHDYN_VI		,23,&LcfAdapter_VehDyn_VehIn,sizeof(LcfAdapter_VehDyn_VehIn));//292
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_VEHPAR_VI		,23,&LcfAdapter_VehPar_VehIn,sizeof(LcfAdapter_VehPar_VehIn));//272
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_VEHSIG_VI		,23,&LcfAdapter_VehSig_VehIn,sizeof(LcfAdapter_VehSig_VehIn));//300
}

void LcfAdapter_MTSI_FreezeData_Proxy_23_Out(void)
{
	/*** Lcf Veh output data: ***/
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_ALGOCOMP_V	,23,&LcfAdapter_AlgoCompState_Veh,sizeof(LcfAdapter_AlgoCompState_Veh));//88
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_LCFLADMC		,23,&LcfAdapter_LcfLaDmcSocToIuc,sizeof(LcfAdapter_LcfLaDmcSocToIuc));//32
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_LCFVODATA_VO	,23,&LcfAdapter_LcfVehOutputData_VehOut,sizeof(LcfAdapter_LcfVehOutputData_VehOut));//72
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_LCFSIFV_VO 	,23,&LcfAdapter_LcfSenInputFromVehData_VehOut,sizeof(LcfAdapter_LcfSenInputFromVehData_VehOut));//136
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_NVMLCF_VO		,23,&LcfAdapter_NvmLcfData,sizeof(LcfAdapter_NvmLcfData));//140
#if (DBG_LCFADAPTER_DEBUG_ENABLE == STD_ON)
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_LCFVRC_VO		,23,&Debug_LcfAdapter_LcfVehExec_Cycle,sizeof(Debug_LcfAdapter_LcfVehExec_Cycle));
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_LCFVRI_VO		,23,&Debug_LcfAdapter_LcfVehExec_RunInterval,sizeof(Debug_LcfAdapter_LcfVehExec_RunInterval));
#endif
}
void LcfAdapter_MTSI_FreezeData_Proxy_90_In(void)
{
	/*** Lcf Sen input data: ***/
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_BASECTRL_SI	,90,&LcfAdapter_BaseCtrlData_SenIn,sizeof(LcfAdapter_BaseCtrlData_SenIn));//24
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_ABDOUTPUT_SI	,90,&LcfAdapter_AbdOutputData_SenIn,sizeof(LcfAdapter_AbdOutputData_SenIn));//5252
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_LCFINPUT_SI	,90,&LcfAdapter_LcfInputData_SenIn,sizeof(LcfAdapter_LcfInputData_SenIn));//600
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_LCFSIFV_SI	,90,&LcfAdapter_LcfSenInputFromVehData_SenIn,sizeof(LcfAdapter_LcfSenInputFromVehData_SenIn));//136
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_LCFVODATA_SI	,90,&LcfAdapter_LcfVehOutputData_SenIn,sizeof(LcfAdapter_LcfVehOutputData_SenIn));//72
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_VEHDYN_SI		,90,&LcfAdapter_VehDyn_SenIn,sizeof(LcfAdapter_VehDyn_SenIn));//292
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_VEHPAR_SI		,90,&LcfAdapter_VehPar_SenIn,sizeof(LcfAdapter_VehPar_SenIn));//272
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_VEHSIG_SI		,90,&LcfAdapter_VehSig_SenIn,sizeof(LcfAdapter_VehSig_SenIn));//300
}
void LcfAdapter_MTSI_FreezeData_Proxy_90_Out(void)
{
	/*** Lcf Sen input data: ***/
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_ALGOCOMP_S	,90,&LcfAdapter_AlgoCompState_Sen,sizeof(LcfAdapter_AlgoCompState_Sen));//88
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_LCFSODATA_SO	,90,&LcfAdapter_LcfSenOutputData_SenOut,sizeof(LcfAdapter_LcfSenOutputData_SenOut));//248
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_LCFVIFS_SO	,90,&LcfAdapter_LcfVehInputFromSenData_SenOut,sizeof(LcfAdapter_LcfVehInputFromSenData_SenOut));//348
#if (DBG_LCFADAPTER_DEBUG_ENABLE == STD_ON)
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_LCFSRC_SO		,90,&Debug_LcfAdapter_LcfSenExec_Cycle,sizeof(Debug_LcfAdapter_LcfSenExec_Cycle));
	LcfAdapter_Mtsi(LCF_MEAS_ADDR_LCFSRI_SO		,90,&Debug_LcfAdapter_LcfSenExec_RunInterval,sizeof(Debug_LcfAdapter_LcfSenExec_RunInterval));
#endif
}

#endif



