% Clear the Workspace
clear
% Clear the Command Window
clc;


currpath = eval('cd');
source_1 = fullfile( currpath, 'PARAMLVC.c');
source_2 = fullfile( currpath, 'PARAMLVC_old.c');
str_search = '#include "dmc_lat.hdb"';
fid = fopen(source_1,'rt') ;
X = fread(fid) ;
X = char(X.') ;
fclose (fid) ;

if isempty(strfind(X,str_search))
copyfile(source_1,source_2,'f')

% source_1 = fullfile( currpath, 'dmc.c');
% source_2 = fullfile( currpath, 'dmc_old.c');
% copyfile(source_1,source_2,'f')
% 
% source_1 = fullfile( currpath, 'dmc.h');
% source_2 = fullfile( currpath, 'dmc_old.h');
% copyfile(source_1,source_2,'f')


%copyfile('myfun.m','myfun2.m')
%------- File .c----
%Initialize the strings
str1 = 'const ';
str2 = '#include "../BFU/BASE_TYP.HE"';
str3 = '#include "hdb_LVC.icl"';
str4 = '#include "../BFU/base_typ.he"';
str2_replace = '#include "hal_base_type_if.he"';
str3_replace = '#include "dmc_lat.hdb"';

%Select the input folder
%souceFolder = uigetdir('D:\', 'Please select <files2convert> folder');

source_1 = fullfile( currpath, 'PARAMLVC.c');
destination_1 = fullfile( currpath, 'PARAMLVC.c');
%source_1 = ('PARAMLVC.c');
%destination_1 = ('Param\PARAMLVC.c');

%Open source file
fid = fopen(source_1,'rt') ;
X = fread(fid) ;
X = char(X.') ;
fclose (fid) ;

% Replace strings
Y = strrep(X, str1, '') ;
Y = strrep(Y, str2, str2_replace);
Y = strrep(Y, str4, str2_replace); 
Y = strrep(Y, str3, str3_replace); 
%Write the new files in param folder
%fid2 = fopen(destination_1,'wt') ;

fid = fopen(source_1,'wt') ;
fwrite(fid,Y) ;
fclose (fid) ;
disp('File PARAMLVC.c modifed, old file PARAMLVC_old.c !')
else
disp('Warning: file PARAMLVC.c already modifed, no changes performed !!!')    
end

%------- File .hdb----
%Initialize the strings

source_1 = fullfile( currpath, 'dmc_lat.hdb');
source_2 = fullfile( currpath, 'dmc_lat_old.hdb');

str_search = '#include "dmc_lat.hdb"';
fid = fopen(source_1,'rt') ;
X = fread(fid) ;
X = char(X.') ;
fclose (fid) ;

str_1 = ' const';
str_2 = '#include "var_cod.hdb"';

if (strfind(X,str_2))
copyfile(source_1,source_2,'f')

%Open source file
source_2 = fullfile( currpath, 'dmc_lat.hdb');
destination_2 = fullfile( currpath, 'dmc_lat.hdb');

fid_1 = fopen(source_2,'rt') ;
X = fread(fid_1) ;

fclose(fid_1) ;
X = char(X.') ;
% Replace strings
Y = strrep(X, str_1, '');
Y = strrep(Y, str_2, '');
%Write the new files in param folder
fid_2 = fopen(destination_2,'wt') ;
fwrite(fid_2,Y) ;
fclose (fid_2) ;

disp('File dmc_lat.hdb modifed, old file dmc_lat_old.hdb !')
else
disp('Warning: file dmc_lat.hdb already modifed, no changes performed !!!')    
end

%------- File DMC_Soc_types.h -----------

%Initialize the strings
str_start = '#include "dmc_ac.h"';
newline = sprintf('\n');
new_structure = ['#include "dmc_ac.h"',newline,...
'typedef struct {',newline,...
'signed_int16_t BUS_EPS_ASSIST_TRQ; ',newline,...
'signed_int16_t BUS_EPS_MOTOR_TRQ;',newline,...
'unsigned_char_t EpsSteerAngleAuthority;',newline,...
'boolean HALFTorqueOverlayFault;',newline,...
'boolean EPS_TEMP_DEACTIVATION_LDW;',newline,...
'boolean HALF_TORQUE_OVERLAY_ACTIVATED;',newline,...
'signed_int16_t SSI_R_DMC_LAT_ACTVN_MOD;',newline,...
'signed_int16_t SSI_R_DMC_CRVT_SUM_CMD;',newline,...
'signed_int16_t SSI_R_DMC_CRVT_FEED_FWD;',newline,...
'signed_int16_t SSI_R_DMC_CRVT_CHG_RATE;',newline,...
'signed_int16_t SSI_R_DMC_CRVT_STEER_ACTR;',newline,...
'signed_int16_t SSI_R_DMC_CRVT_CMD_RATE;',newline,...
'signed_int16_t SSI_R_DMC_STEER_AG_REQ;',newline,...
'signed_int16_t DMC_CAM_CRVT_FEED_FWD;',newline,...
'signed_int16_t DMC_CAM_CRVT_FEED_FWD_QF;',newline,...
'signed_int16_t DMC_CAM_LAT_ERR;',newline,...
'signed_int16_t DMC_CAM_LAT_ERR_QF;',newline,...
'signed_int16_t DMC_CAM_HDNG_AG_ERR;',newline,...
'signed_int16_t DMC_CAM_HDNG_AG_ERR_QF;',newline,...
'unsigned_char_t DMC_FORCE_SHUT_OFF_REQUEST;',newline,...
'unsigned_char_t DMC_SHUT_OFF_ON_ERROR;',newline,...
'unsigned_char_t SSI_R_DMC_STFN_REQ;',newline,...
'unsigned_char_t SSI_R_DMC_OCCRCY_REQ;',newline,...
'signed_int16_t SSI_R_DMC_LAT_ERR;',newline,...
'signed_int16_t SSI_R_DMC_HDNG_AG_ERR;',newline,...
'signed_int16_t SSI_R_EPS_STEER_AG;',newline,...
'signed_int16_t SSI_R_EPS_STEER_AG_RATE;',newline,...
'signed_int16_t SSI_R_DMC_STEER_WHL_VIBR;',newline,...
'signed_int16_t SSI_R_LANE_STATUS;',newline,...
'signed_int16_t EST_REFERENCE_VELOCITY;',newline,...
'signed_int16_t BUS_EPS_TOR_BAR_TORQUE;',newline,...
'unsigned_char_t BUS_EPS_STATUS;',newline,...
'boolean BUS_EPS_TOR_BAR_TORQUE_QF;',newline,...
'boolean AYC_IN_CYCLE;',newline,...
'boolean FINAL_FUNCTION_DISABLE_AYC;',newline,...
'boolean FUNCTION_DISABLE_AYC;',newline,...
'boolean AYC_WARNING_LAMP;',newline,...
'signed_int16_t DMC_FILTERED_YAW_RATE;',newline,...
'signed_int16_t DMC_FILTERED_YAW_RATE_QF;',newline,...
'signed_char_t DMC_FILTERED_LATERAL_ACC_COG;',newline,...
'signed_int16_t DMC_FILTERED_LATERAL_ACC_COG_QF;',newline,...
'signed_int16_t DMC_FILTERED_STEER_ANGLE_QF;',newline,...
'signed_int16_t DMC_FILTERED_STEER_ANGLE_RATE_QF;',newline,...
'signed_int16_t DMC_STEER_ANGLE_OFFSET;',newline,...
'signed_int16_t DMC_STEER_ANGLE_OFFSET_STATE;',newline,...
'signed_int16_t DMC_YAW_RATE_OFFSET;',newline,...
'signed_int16_t DMC_YAW_RATE_OFFSET_STATE;',newline,...
'signed_int16_t DMC_FILTERED_STEER_ANGLE;',newline,...
'signed_int16_t DMC_FILTERED_STEER_ANGLE_RATE;',newline,...
'signed_int16_t UNCALIBRATED_SWA_FIL;',newline,...
'signed_int16_t DMC_EPS_TRQ_REQ;',newline,...        
'signed_int16_t LaDMC_status;',newline,...        
'signed_int16_t LADMC_EPS_TORQUE_REQUEST;',newline,...        
'signed_int16_t LaDMC_Eps_Request_Flag;',newline,...        
'signed_int16_t LADMC_EPS_INTERFACE_ACTIVE_REQ;',newline,...        
'unsigned_char_t DMC_LAT_EPS_DAMP_LVL_REQ;',newline,...        
'signed_int16_t DMC_LAT_STATUS;',newline,...  
'unsigned_int16_t DMC_EPS_STATUS;',newline,...
'unsigned_char_t MTO_HALF_SYSTEM_STS;',newline,...        
'signed_int16_t LADMC_STEER_ANGLE_RATE_REQ;',newline,...        
'unsigned_char_t LADMC_STIFFNESS_LEVEL_REQUEST;',newline,...        
'signed_int16_t DMC_LONG_ENG_TRQ_REQ;',newline,...        
'signed_int16_t DMC_LONG_BRK_TRQ_REQ;',newline,...
'signed_int16_t SaRateSig;',newline,...        
'signed_int16_t SaRateQ;',newline,...        
'float32 DYC_Steer_Angle_Feedforward;',newline,...        
'float32 LAT_Eps_Torque_Request;',newline,...        
'unsigned_char_t SAC_Requested_Damping_Level;',newline,...        
'float32 VEH_Delta_F_Dot_Est_Arb;',newline,...        
'float32 LAT_Delta_Ys;',newline,...        
'float32 LKC_Delta_Ys;',newline,...        
'float32 LAT_Delta_Psi;',newline,...        
'float32 LKC_Delta_Psi;',newline,...        
'float32 LAT_Kappa_Command;',newline,...        
'float32 LAT_Kappa_Prime_Command;',newline,...        
'float32 LAT_Psi;',newline,...        
'float32 SAT_Saturated_Angle_Command;',newline,...        
'float32 SAC_Yrc_Angle_Command;',newline,...        
'unsigned_char_t LAT_Eps_Torque_Request_Flag;',newline,...        
'float32 LAT_Delta_F_Cmd;',newline,...        
'float32 VEH_Delta_F;',newline,...        
'float32 VEH_Yaw_Rate;',newline,...       
'float32 VEH_Vehicle_Velocity;',newline,...        
'float32 VEH_Delta_F_Dot;',newline,...        
'float32 VEH_Steer_Torque;',newline,...        
'float32 EPS_Tie_Rod_Load;',newline,...        
'float32 LAT_Ext_Command;',newline,...        
'float32 EPS_Motor_Torque;',newline,...        
'signed_int16_t VEH_Brake_Force_Front_Axle;',newline,...        
'signed_int16_t EPS_Status;',newline,...        
'signed_int16_t LAT_Dmc_Status;',newline,...        
'signed_int16_t LaKMC_activation;',newline,...       
'float32 LaKMC_kappa_cmd;',newline,...        
'float32 LaKMC_kappaP_cmd;',newline,...        
'float32 LaKMC_steer_kappa_ctrl_cmd;',newline,...        
'float32 LaKMC_steer_angle_ctrl_cmd;',newline,...        
'float32 LaKMC_brake_kappa_ctrl_cmd;',newline,...        
'unsigned_char_t LaKMC_stiffness;',newline,...        
'unsigned_char_t LaKMC_accuracy;',newline,...        
'signed_int16_t LaKMC_steering_wheel_vibration;',newline,...        
'float32 LaKMC_lateral_error;',newline,...        
'float32 LaKMC_heading_error;',newline,...        
'float32 HEC_Psi_Control_Error;',newline,...        
'float32 LDC_Delta_Psi_Dist;',newline,...        
'float32 LDC_Psi_Command;',newline,...        
'float32 HEC_Delta_F_Cmd;',newline,...        
'float32 VEH_Lateral_Accel;',newline,...        
'signed_int16_t LAT_Tdf_Eps_Torque_Request_dbg;',newline,...        
'signed_int16_t LAT_Arb_Eps_Torque_Request_dbg;',newline,...        
'signed_int16_t Lat_max_output_torque_dbg;',newline,...        
'signed_int16_t SAC_Torque_Sat_Out_dbg;',newline,...        
'signed_int16_t SAC_Derating_Torque_dbg;',newline,...        
'signed_int16_t SAC_Torque_Out_Raw_dbg;',newline,...        
'signed_int16_t SAC_Load_Compensation_Torque_dbg;',newline,...        
'signed_int16_t SAC_Limiter_Out_dbg;',newline,...        
'signed_int16_t SAC_Kd_Part_dbg;',newline,...        
'signed_int16_t SAC_Active_Damping_Torque_dbg;',newline,...        
'signed_int16_t SAC_Ki_Part_dbg;',newline,...        
'signed_int16_t SAC_Kx_Part_dbg;',newline,...               
'signed_int16_t SAC_Latency_Compensation_Torque_dbg;',newline,...        
'signed_int16_t SAC_OScillation_Damp_Torque_dbg;',newline,...        
'signed_int16_t SAC_Friction_Comp_Torque_Out_dbg;',newline,...        
'signed_int16_t LAT_Rate_Limit_Control_Out_dbg;',newline,...        
'float32 SAC_Delta_F_Filtered3_;',newline,...        
'unsigned_char_t SAC_Disable;',newline,...        
'unsigned_int16_t Obs_observer_mode_sig;',newline,...        
'float32 VEH_Vehicle_Speed;',newline,...        
'float32 LKA_Eps_Torque_Request_delayed;',newline,...        
'float32 SAC_Requested_Damping_Level_delayed;',newline,...        
'float32 TDF_Sac_Dos_Limit_Scale_delayed;',newline,...        
'float32 Lat_max_output_torque_sig;',newline,...        
'float32 SAC_Rate_Lim_Feed_Fwd_Torque;',newline,...              
'float32 SAC_Eps_Trq_Load_Est;',newline,...        
'unsigned_int16_t SAC_Steer_Velocity_Source;',newline,...        
'unsigned_char_t SAC_Obs_Var_Delay;',newline,...        
'signed_int16_t LaKMC_kappa_cmd_dbg;',newline,...        
'signed_int16_t VEH_Delta_F_dbg;',newline,... 
'signed_int16_t VEH_Delta_clm_sens_F_dbg;',newline,...
'signed_int16_t VEH_Delta_F_Dot_dbg;',newline,...        
'signed_int16_t VEH_Steer_Torque_dbg;',newline,...        
'signed_int16_t EPS_Tie_Rod_Load_dbg;',newline,...        
'signed_int16_t EPS_Motor_Torque_dbg;',newline,...        
'signed_int16_t EPS_Status_dbg;',newline,...        
'signed_int16_t LaDMC_Eps_Torque_Request_dbg;',newline,...;        
'signed_int16_t SAT_Saturated_Angle_Command_dbg;',newline,...
'signed_int16_t SAC_Eps_Trq_Load_Est_dbg;',newline,...
'signed_int16_t LAT_Dmc_Status_dbg;',newline,...        
'signed_int16_t LDC_Psi_Command_dbg;',newline,...        
'signed_int16_t DYC_Steer_Angle_Feedforward_dbg;',newline,...        
'signed_int16_t LAT_Delta_Ys_dbg;',newline,...        
'signed_int16_t LAT_Delta_Psi_dbg;',newline,...        
'signed_int16_t LAT_Kappa_Command_dbg;',newline,...       
'signed_int16_t HEC_Psi_Control_Error_dbg;',newline,...
'signed_int16_t HEC_Delta_F_Cmd_dbg;',newline,...
'signed_int16_t LDC_Delta_Psi_Dist_dbg;',newline,...    
'signed_int16_t SAC_Yrc_Angle_Command_dbg;',newline,...
'unsigned_int16_t LAT_Kappa_Linz_Omega_dbg;',newline,...
'signed_int16_t LAT_Kappa_Filter_Output_dbg;',newline,...
'signed_int16_t LAT_Filtered_Delta_F_Offset_dbg;',newline,...
'signed_int16_t LAT_Oc_Integrator_Input_Kappa_dbg;',newline,...
'signed_int16_t LAT_Oc_Integrator_Input_Raw_dbg;',newline,...
'signed_int16_t CAM_Kappa_Cmd_dbg;',newline,...
'signed_int16_t DMC_LAT_DEGRADATION;',newline,...
'signed_int16_t DMC_LAT_DEGRADATION_TEMP;',newline,...
'unsigned_char_t VEH_Stability_Control_Active;   ',newline,...
'unsigned_char_t VEH_Stability_Control_Active_temp;',newline,...
'signed_int16_t LKC_Lane_Status;',newline,...
'signed_int16_t Lat_rate_limited_offset_dbg;',newline,...
'unsigned_int16_t SAC_Trq_Derating_Factor_dbg;',newline,...
'unsigned_int16_t TDF_Torque_Derating_Factor_dbg;',newline,...
'unsigned_int16_t TDF_Sac_Dos_Limit_Scale_dbg;',newline,...
'float32 Cam_kappa_feedfwd;',newline,...
'float32 LaKMC_kappa_sum_command;',newline,...
'signed_int16_t Cam_kappa_qf;',newline,...
'signed_int16_t LKC_Lane_Status_dbg;',newline,...
'signed_int16_t LAT_Oc_Kappa_Status_dbg;',newline,...
'signed_int16_t LAT_Oc_Dys_Status_dbg;',newline,...
'signed_int16_t LAT_Gen_Purpose_dbg; ',newline,...
'signed_int16_t MOT_Modulated_Torque_dbg;',newline,...
'signed_int16_t VEH_Delta_F_Oc_dbg;',newline,...
'signed_int16_t SAT_Req_Angle_Supp_Control_dbg;',newline,...
'signed_int16_t TDF_Steer_Torque_Sample_dbg;',newline,...
'unsigned_int16_t SAC_Factor_Kp_dbg;',newline,...
'signed_int16_t SAC_Enhanced_Angle_Cmd_dbg;',newline,...
'signed_int16_t SAC_Fading_Offset_dbg;',newline,...
'signed_int16_t DYC_Boost_Filter_Out_dbg;',newline,...
'unsigned_int16_t SAC_Load_Comp_Factor_Varia_dbg;',newline,...
'signed_int16_t SAC_Faded_Angle_Command_dbg;',newline,...
'signed_int16_t SAC_Arb_Angle_Cmd_Raw_dbg;',newline,...
'signed_int16_t DYC_Boost_Request_dbg;',newline,...
'signed_int16_t LAT_Debug1_dbg;',newline,...
'signed_int16_t LAT_Debug2_dbg;',newline,...
'signed_int16_t LAT_Debug3_dbg;',newline,...
'signed_int16_t LAT_Debug4_dbg;',newline,...
'signed_int16_t LAT_Debug5_dbg;',newline,...
'signed_int16_t LAT_Debug6_dbg;',newline,...
'signed_int16_t LAT_Debug7_dbg;',newline,...
'signed_int16_t LAT_Debug8_dbg;',newline,...
'float32 Cam_heading_error;',newline,...
'float32 VDY_Steer_Angle_Offset;',newline,...
'float32 Cam_lateral_error;',newline,...
'unsigned_int16_t SAC_Load_Comp_Factor_Straight_dbg;',newline,...
'float32 VEH_Yaw_Rate_Offset;',newline,...
'signed_int16_t VEH_Yaw_Rate_Oc_dbg;',newline,...
'unsigned_int16_t OBS_Discharge_Req_Level_dbg;',newline,...
'unsigned_int16_t OBS_Boost_Request_Level_dbg;',newline,...
'signed_int16_t SAC_Steering_Wheel_Angle_Cmd_dbg;',newline,...
'signed_int16_t SAC_Filtered_Angle_Command_dbg;',newline,...
'float32 DYC_Angle_Per_Kappa;',newline,...
'float32 LKC_Kappa_Command_Arb;',newline,...
'float32 LKC_Kappa_Dot_Command_Arb;',newline,...
'float32 LKC_Steer_Kappa_Ctrl_Command;',newline,...
'unsigned_int32_t SAC_Controller_Mode_Sig;',newline,...
'unsigned_char_t LDP_Active;',newline,...
'float32 SAC_R_Factor;',newline,...
'signed_int16_t LADMC_STEER_ANGLE_REQ;',newline,...
'unsigned_char_t LADMC_ACCURACY_LEVEL_REQUEST;',newline,... 
'signed_int16_t TDF_Idle_Status_dbg;',newline,...
'signed_int16_t SAC_Dyn_Corrected_Angle_Cmd_dbg;',newline,...
'unsigned_char_t DMC_STIFFNESS_LIMIT;',newline,... 
'signed_int16_t DMC_STIFFNESS_GRAD;',newline,... 
'unsigned_char_t DMC_TORQUE_SCALE_LIMIT;',newline,... 
'signed_int16_t DMC_TORQUE_SCALE_GRAD;',newline,... 
'signed_int16_t DMC_TORQUE_RAMP_GRAD;',newline,... 
'unsigned_char_t DMC_HIGH_ACCURACY_REQUEST;',newline,...
'signed_int16_t SAC_Max_Torque_Scale_dbg;',newline,... 
'signed_int16_t VEH_Steer_Torque_Comp_dbg;',newline,...
'signed_int16_t SAC_Accuracy_Request_dbg;',newline,...
'unsigned_char_t LADMC_DERATING_FACTOR_REQUEST;',newline,...
'unsigned_char_t LAT_Activation_Request__nu;',newline,...
'unsigned_char_t LAT_Activation_Request_Qf__nu;',newline,...
'unsigned_char_t LAT_Force_Shut_Off_Request;',newline,...
'signed_int16_t LAT_Steer_Angle_Command__deg;',newline,...
'signed_int16_t LAT_Torque_Overlay_Request__nm;',newline,...
'unsigned_char_t LAT_Stiffness_Request__per;',newline,...
'unsigned_char_t LAT_Accuracy_Request__per;',newline,...
'unsigned_char_t LAT_Steering_Wheel_Vibration__nu;',newline,...
'unsigned_char_t LAT_Lane_Status__nu;',newline,...
'unsigned_char_t LAT_Derating_Level_Request__per;',newline,...
'unsigned_char_t LAT_Dmc_Status__nu;',newline,...
'signed_int16_t LAT_Eps_Torque_Request__nm;',newline,...    
'signed_int16_t SAC_Ayc_Residual_dbg;',newline,...
'unsigned_int16_t TRL_Torque_Gradient_dbg;',newline,...
'signed_int16_t SAC_Delta_F_Cmd_Grad_Param_dbg;',newline,...
'signed_int16_t SAC_Control_Error_Eps_dbg;',newline,...
'signed_int16_t SAC_Yrc_Residual_dbg;',newline,...
'unsigned_char_t LAT_Torque_Ramp_Factor__per;',newline,...
'unsigned_char_t DMC_ANGLE_FADING_REQ;',newline,...
'unsigned_char_t DMC_RAMPING_DOWN_REQ;',newline,...
'unsigned_char_t DMC_ANGLE_REQ_MAX_LIMIT_SCALE;',newline,...
'unsigned_char_t DMC_ANGLE_REQ_MAX_GRAD_SCALE;',newline,...
'signed_int16_t SAC_Angle_Command_Raw_dbg;',newline,...
'unsigned_char_t SAC_Soc_Disable;',newline,...
'unsigned_int16_t SAC_Load_Cmp_Fct_Curv_Chg_dbg;',newline,...
'float32 ADP_Dyc_Corr_Factor;',newline,...
'float32 ADP_Dyc_Corr_Factor_Ls;',newline,...
'float32 ADP_Dyc_Corr_Factor_Rs;',newline,...
'unsigned_char_t Turn_And_Error_Side;',newline,...
'float32 CAM_Lateral_Error_Mean;',newline,...
'float32 CAM_Lateral_Error_Delta;',newline,...
'unsigned_int16_t Maximum_Waiting_Counter;',newline,...
'float32 Factor_Increase;',newline,...
'float32 Factor_Decrease;',newline,...
'unsigned_int16_t LTLE_Waiting_Counter;',newline,...
'unsigned_int16_t LTRE_Waiting_Counter;',newline,...
'unsigned_int16_t RTLE_Waiting_Counter;',newline,...
'unsigned_int16_t RTRE_Waiting_Counter;',newline,...
'unsigned_char_t Factor_Corr_Enable_Flag;',newline,...
'float32 ADP_Dyc_Corr_Factor_Left_Vect[20];',newline,...
'float32 ADP_Dyc_Corr_Factor_Right_Vect[20];',newline,...
'float32 Mean_Kappa_Command;',newline,...
'float32 Mean_Vehicle_Velocity;',newline,...
'signed_int16_t DMC_ANGLE_OFF_LOOP0;',newline,... 
'unsigned_int16_t DMC_ANGLE_OFF_CALIB_CNT_LOOP0;',newline,...
'unsigned_char_t DMC_ANGLE_OFF_READ_ERROR;',newline,...
'signed_int16_t DMC_ANGLE_OFF;',newline,... 
'signed_int16_t DMC_Eps_Integrator_Hold_Req__nu;',newline,... 
'unsigned_int16_t DMC_ANGLE_OFF_CALIB_CNT;',newline,...
'signed_int16_t SAC_Derated_Angle_Command_dbg;',newline,...
'unsigned_char_t DMC_ADP_CORR_FACTOR_POS[20];',newline,...
'unsigned_char_t DMC_ADP_CORR_FACTOR_NEG[20];',newline,...
'unsigned_int16_t DMC_ADP_CORR_COUNTER_POS[20];',newline,...
'unsigned_int16_t DMC_ADP_CORR_COUNTER_NEG[20];',newline,...
'unsigned_char_t DMC_ADP_CORR_FACTOR_POS_LOOP0[20];',newline,...
'unsigned_char_t DMC_ADP_CORR_FACTOR_NEG_LOOP0[20];',newline,...
'unsigned_int16_t DMC_ADP_CORR_COUNTER_POS_LOOP0[20];',newline,...
'unsigned_int16_t DMC_ADP_CORR_COUNTER_NEG_LOOP0[20];',newline,...
'unsigned_char_t DMC_ADP_CORR_FACTOR_READ_ERROR;',newline,...
'unsigned_char_t DMC_DERATING_LEVEL_REQ;',newline,...
'signed_int16_t SAT_Angle_Rate_Residual_dbg;',newline,...
'signed_int16_t SAC_Damping_Angle_Command_dbg;',newline,...
'unsigned_int16_t SAC_Ctrl_Err_Memshp_Low_Dyn_dbg;',newline,...
'unsigned_int16_t SAC_Control_Err_Membership_dbg;',newline,...
'signed_int16_t LAT_Kappa_Sum_Command__1pm;',newline,...
'signed_int16_t SAT_Req_Steer_Angle_Max_Ay_dbg;',newline,...
'signed_int16_t LAT_Ay_Control_Limit_Bias_dbg;',newline,...
'signed_int16_t SAC_Delta_F_Sat_Command_dbg;',newline,...
'unsigned_int16_t SAT_Active_Saturation_dbg;',newline,...
'signed_int16_t SAT_Req_Dyn_Steer_Angle_Max_dbg;',newline,...
'signed_int16_t SAC_Angle_Cmd_Yawrate_Fback_dbg;',newline,...
'signed_int16_t LAT_Oc_Delta_Ys_Filtered_dbg;',newline,...
'unsigned_char_t DMC_DRIVING_MODE;',newline,...
'signed_int16_t DMC_BANK_ANGLE;',newline,...
'signed_int16_t LAT_Oc_Rls_Delta_L_Offset_Raw_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_Delta_L_Offst_Lim_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_Status_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_stiffness_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_variance_stiffnes_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_variance_offset_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_cov_stiffnes_offs_dbg;',newline,...
'unsigned_int16_t LAT_Ay_Dynamic_Threshold_dbg;',newline,...
'signed_int16_t SAT_Req_Steer_Angle_Max_dbg;',newline,...
'unsigned_int16_t LCF_Operation_Mode;',newline,...
'signed_int16_t DMC_GPIO;',newline,...
'signed_int16_t DMC_GPIO2;',newline,...
'signed_int16_t DMC_GPIO3;',newline,...
'signed_int16_t DMC_GPIO4;',newline,...
'signed_int16_t EMO_PITCH_ANGLE;',newline,...
'signed_int16_t LAT_Pitch_Angle_Deviation_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_var1_stiff_V4_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_var1_off_V4_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_var_stiff_V2_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_cov_stiff_off_V2_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_var_off_V2_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_var1_stiff_V3_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_var1_off_V3_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_stiff_V3_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_stiff_V4_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_Delta_L_dead_V4_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_Delta_L_Off_V4_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_stiffness_V2_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_Delta_L_Offset_V2_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_Delta_L_dead_V3_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_Delta_L_Off_V3_dbg;',newline,...
'signed_int16_t DMC_Steer_Angle_Oc__deg;',newline,...
'unsigned_int16_t SAC_Dynamic_Correction_Factor_dbg;',newline,...
'signed_int16_t SAC_Derated_Eps_Torque_dbg;',newline,...
'signed_int16_t DMC_ROAD_WHEEL_ANGLE;',newline,...
'signed_int16_t LAT_Road_Wheel_Angle_Cmd__deg;',newline,...
'unsigned_int16_t LAT_Gi_Status_dbg;',newline,...
'float32 VDY_Bank_Angle;',newline,...
'} LaDMC_DebugBus_Type;'];
source_3 = fullfile( currpath, 'DMC_Soc_types.h');
destination_3 = fullfile( currpath, 'DMC_Soc_types_old.h');
%Create the file dmc_old.h
%Open source file
fid_1 = fopen(source_3,'rt') ;
X = fread(fid_1) ;
fclose(fid_1) ;
X = char(X.');
if (strfind(X, 'LaDMC_DebugBus_Type'))
    disp('Warning: file DMC_Soc_types.h already modifed, no changes performed !!!')
else
copyfile(source_3,destination_3,'f')
 %Replace the strings
Y = strrep(X, str_start, new_structure);
%Copy new data 
fid_2 = fopen(source_3,'wt') ;
fwrite(fid_2,Y) ;
fclose (fid_2) ;
disp('File DMC_Soc_types.h modifed, old file DMC_Soc_types_old.h !')
end
%------- File dmc.c-----------

%Initialize
str1 = '/* Block signals (auto storage) */';
str_replace = {'/* ClPr: added because linking errors (variables are declared extern in dmc_ac.h and dmc_if.h and dmc_ram.h) */',newline,...
'signed_int16_t BUS_EPS_ASSIST_TRQ;',newline,...
'signed_int16_t BUS_EPS_MOTOR_TRQ;',newline,...
'unsigned_char_t EpsSteerAngleAuthority;',newline,...
'boolean HALFTorqueOverlayFault;',newline,...
'boolean EPS_TEMP_DEACTIVATION_LDW;',newline,...
'boolean HALF_TORQUE_OVERLAY_ACTIVATED;',newline,...
'signed_int16_t SSI_R_DMC_LAT_ACTVN_MOD;',newline,...
'signed_int16_t SSI_R_DMC_CRVT_SUM_CMD;',newline,...
'signed_int16_t SSI_R_DMC_CRVT_FEED_FWD;',newline,...
'signed_int16_t SSI_R_DMC_CRVT_CHG_RATE;',newline,...
'signed_int16_t SSI_R_DMC_CRVT_STEER_ACTR;',newline,...
'signed_int16_t SSI_R_DMC_CRVT_CMD_RATE;',newline,...
'signed_int16_t SSI_R_DMC_STEER_AG_REQ;',newline,...
'signed_int16_t DMC_CAM_CRVT_FEED_FWD;',newline,...
'signed_int16_t DMC_CAM_LAT_ERR;',newline,...
'signed_int16_t DMC_CAM_HDNG_AG_ERR;',newline,...
'signed_int16_t DMC_CAM_CRVT_FEED_FWD_QF;',newline,...
'signed_int16_t DMC_CAM_LAT_ERR_QF;',newline,...
'signed_int16_t DMC_CAM_HDNG_AG_ERR_QF;',newline,...
'unsigned_char_t DMC_FORCE_SHUT_OFF_REQUEST;',newline,...
'unsigned_char_t DMC_SHUT_OFF_ON_ERROR;',newline,...
'unsigned_char_t SSI_R_DMC_STFN_REQ;',newline,...
'unsigned_char_t SSI_R_DMC_OCCRCY_REQ;',newline,...
'signed_int16_t SSI_R_DMC_LAT_ERR;',newline,...
'signed_int16_t SSI_R_DMC_HDNG_AG_ERR;',newline,...
'signed_int16_t SSI_R_EPS_STEER_AG;',newline,...
'signed_int16_t SSI_R_EPS_STEER_AG_RATE;',newline,...
'signed_int16_t SSI_R_DMC_STEER_WHL_VIBR;',newline,...
'signed_int16_t SSI_R_LANE_STATUS;',newline,...
'signed_int16_t EST_REFERENCE_VELOCITY;',newline,...
'signed_int16_t BUS_EPS_TOR_BAR_TORQUE;',newline,...
'unsigned_char_t BUS_EPS_STATUS;',newline,...
'boolean BUS_EPS_TOR_BAR_TORQUE_QF;',newline,...
'boolean AYC_IN_CYCLE;',newline,...
'boolean FINAL_FUNCTION_DISABLE_AYC;',newline,...
'boolean FUNCTION_DISABLE_AYC;',newline,...
'boolean AYC_WARNING_LAMP;',newline,...
'signed_int16_t DMC_FILTERED_YAW_RATE;',newline,...
'signed_int16_t DMC_FILTERED_YAW_RATE_QF;',newline,...
'signed_char_t DMC_FILTERED_LATERAL_ACC_COG;',newline,...
'signed_int16_t DMC_FILTERED_LATERAL_ACC_COG_QF;',newline,...
'signed_int16_t DMC_FILTERED_STEER_ANGLE_QF;',newline,...
'signed_int16_t DMC_FILTERED_STEER_ANGLE_RATE_QF;',newline,...
'signed_int16_t DMC_STEER_ANGLE_OFFSET;',newline,...
'signed_int16_t DMC_STEER_ANGLE_OFFSET_STATE;',newline,...
'signed_int16_t DMC_YAW_RATE_OFFSET;',newline,...
'signed_int16_t DMC_YAW_RATE_OFFSET_STATE;',newline,...
'signed_int16_t DMC_FILTERED_STEER_ANGLE;',newline,...
'signed_int16_t DMC_FILTERED_STEER_ANGLE_RATE;',newline,...
'signed_int16_t UNCALIBRATED_SWA_FIL;',newline,...
'signed_int16_t DMC_EPS_TRQ_REQ;',newline,...
'/*!< @ASAP_NAME DMC_EPS_TRQ_REQ @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Vehicle yaw torque request for actuator wheel brake (DMC_EPS_TRQ_REQ) */',newline,...
'signed_int16_t LaDMC_status;',newline,...
'/*!< @ASAP_NAME LaDMC_status @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 7 @OFFSET 0 @brief comment (LaDMC_status) */',newline,...       
'signed_int16_t LADMC_EPS_TORQUE_REQUEST;',newline,...
'/*!< @ASAP_NAME LADMC_EPS_TORQUE_REQUEST @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LADMC_EPS_TORQUE_REQUEST) */',newline,...
'signed_int16_t LaDMC_Eps_Request_Flag;',newline,...
'/*!< @ASAP_NAME LaDMC_Eps_Request_Flag @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 7 @OFFSET 0 @brief comment (LaDMC_Eps_Request_Flag) */',newline,...        
'signed_int16_t LADMC_EPS_INTERFACE_ACTIVE_REQ;',newline,...
'/*!< @ASAP_NAME LADMC_EPS_INTERFACE_ACTIVE_REQ @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 7 @OFFSET 0 @brief comment (LADMC_EPS_INTERFACE_ACTIVE_REQ) */',newline,...    
'unsigned_char_t DMC_LAT_EPS_DAMP_LVL_REQ;',newline,...
'/*!< @ASAP_NAME DMC_LAT_EPS_DAMP_LVL_REQ @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 100 @OFFSET 0 @brief comment (DMC_LAT_EPS_DAMP_LVL_REQ) */',newline,...  
'signed_int16_t DMC_LAT_STATUS;',newline,...
'/*!< @ASAP_NAME DMC_LAT_STATUS @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 100 @OFFSET 0 @brief comment (DMC_LAT_STATUS) */',newline,...
'unsigned_int16_t DMC_EPS_STATUS;',newline,...
'/*!< @ASAP_NAME DMC_EPS_STATUS @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 100 @OFFSET 0 @brief comment (DMC_EPS_STATUS) */',newline,...
'unsigned_char_t MTO_HALF_SYSTEM_STS;',newline,...
'/*!< @ASAP_NAME MTO_HALF_SYSTEM_STS @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 1 @OFFSET 0 @brief comment (MTO_HALF_SYSTEM_STS) */',newline,... 
'signed_int16_t LADMC_STEER_ANGLE_RATE_REQ;',newline,...
'/*!< @ASAP_NAME LADMC_STEER_ANGLE_RATE_REQ @UNIT - @LSB 0.0039062500 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LADMC_STEER_ANGLE_RATE_REQ) */',newline,...
'unsigned_char_t LADMC_STIFFNESS_LEVEL_REQUEST;',newline,...
'/*!< @ASAP_NAME LADMC_STIFFNESS_LEVEL_REQUEST @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 100 @OFFSET 0 @brief comment (LADMC_STIFFNESS_LEVEL_REQUEST) */',newline,...
'signed_int16_t DMC_LONG_ENG_TRQ_REQ;',newline,...
'/*!< @ASAP_NAME DMC_LONG_ENG_TRQ_REQ @UNIT Nm @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief - (DMC_LONG_ENG_TRQ_REQ) */',newline,...  
'signed_int16_t DMC_LONG_BRK_TRQ_REQ;',newline,...
'/*!< @ASAP_NAME DMC_LONG_BRK_TRQ_REQ @UNIT Nm @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief - (DMC_LONG_BRK_TRQ_REQ) */',newline,...        
'signed_int16_t SaRateSig;',newline,...
'/*!< @ASAP_NAME SaRateSig @UNIT Nm @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SaRateSig) */',newline,...        
'signed_int16_t SaRateQ;',newline,...
'/*!< @ASAP_NAME SaRateQ @UNIT Nm @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SaRateQ) */',newline,...      
'float32 DYC_Steer_Angle_Feedforward;',newline,...
'/*!< @ASAP_NAME DYC_Steer_Angle_Feedforward @UNIT deg @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (DYC_Steer_Angle_Feedforward) */',newline,...
'float32 LAT_Eps_Torque_Request;',newline,...
'/*!< @ASAP_NAME LAT_Eps_Torque_Request @UNIT Nm @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Eps_Torque_Request) */',newline,...        
'unsigned_char_t SAC_Requested_Damping_Level;',newline,...
'/*!< @ASAP_NAME SAC_Requested_Damping_Level @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Requested_Damping_Level) */',newline,...        
'float32 VEH_Delta_F_Dot_Est_Arb;',newline,...
'/*!< @ASAP_NAME VEH_Delta_F_Dot_Est_Arb @UNIT deg/s @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VEH_Delta_F_Dot_Est_Arb) */',newline,...
'float32 LAT_Delta_Ys;',newline,...
'/*!< @ASAP_NAME LAT_Delta_Ys @UNIT m @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Delta_Ys) */',newline,...      
'float32 LKC_Delta_Ys;',newline,...
'/*!< @ASAP_NAME LKC_Delta_Ys @UNIT m @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LKC_Delta_Ys) */',newline,...       
'float32 LAT_Delta_Psi;',newline,...
'/*!< @ASAP_NAME LAT_Delta_Psi @UNIT rad @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Delta_Psi) */',newline,...       
'float32 LKC_Delta_Psi;',newline,...
'/*!< @ASAP_NAME LKC_Delta_Psi @UNIT rad @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LKC_Delta_Psi) */',newline,...        
'float32 LAT_Kappa_Command;',newline,...
'/*!< @ASAP_NAME LAT_Kappa_Command @UNIT 1/m @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Kappa_Command) */',newline,...        
'float32 LAT_Kappa_Prime_Command;',newline,...
'/*!< @ASAP_NAME LAT_Kappa_Prime_Command @UNIT 1/m/m @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Kappa_Prime_Command) */',newline,...        
'float32 LAT_Psi;',newline,...
'/*!< @ASAP_NAME LAT_Psi @UNIT rad @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Psi) */',newline,...       
'float32 SAT_Saturated_Angle_Command;',newline,...
'/*!< @ASAP_NAME SAT_Saturated_Angle_Command @UNIT deg @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAT_Saturated_Angle_Command) */',newline,...       
'float32 SAC_Yrc_Angle_Command;',newline,...
'/*!< @ASAP_NAME SAC_Yrc_Angle_Command @UNIT deg @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Yrc_Angle_Command) */',newline,...        
'unsigned_char_t LAT_Eps_Torque_Request_Flag;',newline,...
'/*!< @ASAP_NAME LAT_Eps_Torque_Request_Flag @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Eps_Torque_Request_Flag) */',newline,...       
'float32 LAT_Delta_F_Cmd;',newline,...
'/*!< @ASAP_NAME LAT_Delta_F_Cmd @UNIT deg/s @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Delta_F_Cmd) */',newline,...       
'float32 VEH_Delta_F;',newline,...
'/*!< @ASAP_NAME VEH_Delta_F @UNIT deg @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VEH_Delta_F) */',newline,...       
'float32 VEH_Yaw_Rate;',newline,...
'/*!< @ASAP_NAME VEH_Yaw_Rate @UNIT rad/s @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VEH_Yaw_Rate) */',newline,...        
'float32 VEH_Delta_clm_sens_F;',newline,...
'/*!< @ASAP_NAME VEH_Delta_Clm_Sens_F @UNIT deg @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VEH_Delta_clm_sens_F) */',newline,...        
'float32 VEH_Vehicle_Velocity;',newline,...
'/*!< @ASAP_NAME VEH_Vehicle_Velocity @UNIT m/s @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VEH_Vehicle_Velocity) */',newline,...  
'float32 VEH_Delta_F_Dot;',newline,...
'/*!< @ASAP_NAME VEH_Delta_F_Dot @UNIT deg/s @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VEH_Delta_F_Dot) */',newline,...      
'float32 VEH_Steer_Torque;',newline,...
'/*!< @ASAP_NAME VEH_Steer_Torque @UNIT Nm @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VEH_Steer_Torque) */',newline,...       
'float32 EPS_Tie_Rod_Load;',newline,...
'/*!< @ASAP_NAME EPS_Tie_Rod_Load @UNIT Nm @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (EPS_Tie_Rod_Load) */',newline,...     
'float32 LAT_Ext_Command;',newline,...
'/*!< @ASAP_NAME LAT_Ext_Command @UNIT deg @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Ext_Command) */',newline,...    
'float32 EPS_Motor_Torque;',newline,...
'/*!< @ASAP_NAME EPS_Motor_Torque @UNIT Nm @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (EPS_Motor_Torque) */',newline,...      
'signed_int16_t VEH_Brake_Force_Front_Axle;',newline,...
'/*!< @ASAP_NAME VEH_Brake_Force_Front_Axle @UNIT N @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VEH_Brake_Force_Front_Axle) */',newline,...    
'signed_int16_t EPS_Status;',newline,...
'/*!< @ASAP_NAME EPS_Status @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (EPS_Status) */',newline,...      
'signed_int16_t LAT_Dmc_Status;',newline,...
'/*!< @ASAP_NAME LAT_Dmc_Status @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Dmc_Status) */',newline,...     
'signed_int16_t LaKMC_activation;',newline,...
'/*!< @ASAP_NAME LaKMC_activation @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 7 @OFFSET 0 @brief comment (LaKMC_activation) */',newline,...       
'float32 LaKMC_kappa_cmd;',newline,...
'/*!< @ASAP_NAME LaKMC_kappa_cmd @UNIT 1/m @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LaKMC_kappa_cmd) */',newline,...     
'float32 LaKMC_kappaP_cmd;',newline,...
'/*!< @ASAP_NAME LaKMC_kappaP_cmd @UNIT 1/ms @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LaKMC_kappaP_cmd) */',newline,...      
'float32 LaKMC_steer_kappa_ctrl_cmd;',newline,...
'/*!< @ASAP_NAME LaKMC_steer_kappa_ctrl_cmd @UNIT 1/m @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LaKMC_steer_kappa_ctrl_cmd) */',newline,...
'float32 LaKMC_steer_angle_ctrl_cmd;',newline,...
'/*!< @ASAP_NAME LaKMC_steer_angle_ctrl_cmd @UNIT deg @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LaKMC_steer_angle_ctrl_cmd) */',newline,...
'float32 LaKMC_brake_kappa_ctrl_cmd;',newline,...
'/*!< @ASAP_NAME LaKMC_brake_kappa_ctrl_cmd @UNIT 1/m @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LaKMC_brake_kappa_ctrl_cmd) */',newline,...
'unsigned_char_t LaKMC_stiffness;',newline,...
'/*!< @ASAP_NAME LaKMC_stiffness @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LaKMC_stiffness) */',newline,...
'unsigned_char_t LaKMC_accuracy;',newline,...
'/*!< @ASAP_NAME LaKMC_accuracy @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LaKMC_accuracy) */',newline,...
'signed_int16_t LaKMC_steering_wheel_vibration;',newline,...
'/*!< @ASAP_NAME LaKMC_steering_wheel_vibration @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LaKMC_steering_wheel_vibration) */',newline,...
'float32 LaKMC_lateral_error;',newline,...
'/*!< @ASAP_NAME LaKMC_lateral_error @UNIT m @LSB 1.0000000000 @MIN -2 @MAX 2 @OFFSET 0 @brief comment (LaKMC_lateral_error) */',newline,...
'float32 LaKMC_heading_error;',newline,...
'/*!< @ASAP_NAME LaKMC_heading_error @UNIT deg @LSB 1.0000000000 @MIN -20 @MAX 20 @OFFSET 0 @brief comment (LaKMC_heading_error) */',newline,...
'float32 HEC_Psi_Control_Error;',newline,...
'/*!< @ASAP_NAME HEC_Psi_Control_Error @UNIT rad @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (HEC_Psi_Control_Error) */',newline,...
'float32 LDC_Delta_Psi_Dist;',newline,...
'/*!< @ASAP_NAME LDC_Delta_Psi_Dist @UNIT rad @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LDC_Delta_Psi_Dist) */',newline,...
'float32 LDC_Psi_Command;',newline,...
'/*!< @ASAP_NAME LDC_Psi_Command @UNIT rad @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LDC_Psi_Command) */',newline,...
'float32 HEC_Delta_F_Cmd;',newline,...
'/*!< @ASAP_NAME HEC_Delta_F_Cmd @UNIT deg @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (HEC_Delta_F_Cmd) */',newline,...
'float32 VEH_Lateral_Accel;',newline,...
'/*!< @ASAP_NAME VEH_Lateral_Accel @UNIT m/s/s @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VEH_Lateral_Accel) */',newline,...
'signed_int16_t LAT_Tdf_Eps_Torque_Request_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Tdf_Eps_Torque_Request_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Tdf_Eps_Torque_Request_dbg) */',newline,...
'signed_int16_t LAT_Arb_Eps_Torque_Request_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Arb_Eps_Torque_Request_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Arb_Eps_Torque_Request_dbg) */',newline,...
'signed_int16_t Lat_max_output_torque_dbg;',newline,...
'/*!< @ASAP_NAME Lat_max_output_torque_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (Lat_max_output_torque_dbg) */',newline,...
'signed_int16_t SAC_Torque_Sat_Out_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Torque_Sat_Out_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Torque_Sat_Out_dbg) */',newline,...
'signed_int16_t SAC_Derating_Torque_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Derating_Torque_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Derating_Torque_dbg) */',newline,...
'signed_int16_t SAC_Torque_Out_Raw_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Torque_Out_Raw_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Torque_Out_Raw_dbg) */',newline,...
'signed_int16_t SAC_Load_Compensation_Torque_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Load_Compensation_Torque_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Load_Compensation_Torque_dbg) */',newline,...
'signed_int16_t SAC_Limiter_Out_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Limiter_Out_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Limiter_Out_dbg) */',newline,...
'signed_int16_t SAC_Kd_Part_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Kd_Part_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Kd_Part_dbg) */',newline,...
'signed_int16_t SAC_Active_Damping_Torque_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Active_Damping_Torque_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Active_Damping_Torque_dbg) */',newline,...
'signed_int16_t SAC_Ki_Part_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Ki_Part_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Ki_Part_dbg) */',newline,...
'signed_int16_t SAC_Kx_Part_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Kx_Part_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Kx_Part_dbg) */',newline,...
'signed_int16_t SAC_Latency_Compensation_Torque_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Latency_Compensation_Torque_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Latency_Compensation_Torque_dbg) */',newline,...
'signed_int16_t SAC_OScillation_Damp_Torque_dbg;',newline,...
'/*!< @ASAP_NAME SAC_OScillation_Damp_Torque_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_OScillation_Damp_Torque_dbg) */',newline,...
'signed_int16_t SAC_Friction_Comp_Torque_Out_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Friction_Comp_Torque_Out_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Friction_Comp_Torque_Out_dbg) */',newline,...
'signed_int16_t LAT_Rate_Limit_Control_Out_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Rate_Limit_Control_Out_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Rate_Limit_Control_Out_dbg) */',newline,...
'float32 SAC_Delta_F_Filtered3_;',newline,...
'/*!< @ASAP_NAME SAC_Delta_F_Filtered3_ @UNIT deg @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Delta_F_Filtered3_) */',newline,...
'unsigned_char_t SAC_Disable;',newline,...
'/*!< @ASAP_NAME OBS_Disable @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Disable) */',newline,...
'unsigned_int16_t Obs_observer_mode_sig;',newline,...
'/*!< @ASAP_NAME Obs_observer_mode_sig @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (Obs_observer_mode_sig) */',newline,...
'float32 VEH_Vehicle_Speed;',newline,...
'/*!< @ASAP_NAME VEH_Vehicle_Speed @UNIT m/s @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VEH_Vehicle_Speed) */',newline,...
'float32 LKA_Eps_Torque_Request_delayed;',newline,...
'/*!< @ASAP_NAME LKA_Eps_Torque_Request_delayed @UNIT Nm @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LKA_Eps_Torque_Request_delayed) */',newline,...
'float32 SAC_Requested_Damping_Level_delayed;',newline,...
'/*!< @ASAP_NAME SAC_Requested_Damping_Level_delayed @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Requested_Damping_Level_delayed) */',newline,...
'float32 TDF_Sac_Dos_Limit_Scale_delayed;',newline,...
'/*!< @ASAP_NAME TDF_Sac_Dos_Limit_Scale_delayed @UNIT  @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (TDF_Sac_Dos_Limit_Scale_delayed) */',newline,...
'float32 Lat_max_output_torque_sig;',newline,...
'/*!< @ASAP_NAME Lat_max_output_torque_sig @UNIT Nm @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (Lat_max_output_torque_sig) */',newline,...
'float32 SAC_Rate_Lim_Feed_Fwd_Torque;',newline,...
'/*!< @ASAP_NAME SAC_Rate_Lim_Feed_Fwd_Torque @UNIT Nm @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Rate_Lim_Feed_Fwd_Torque) */',newline,...
'float32 SAC_Eps_Trq_Load_Est;',newline,...
'/*!< @ASAP_NAME SAC_Eps_Trq_Load_Est @UNIT Nm @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Eps_Trq_Load_Est) */',newline,...
'unsigned_int16_t SAC_Steer_Velocity_Source;',newline,...
'/*!< @ASAP_NAME SAC_Steer_Velocity_Source @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Steer_Velocity_Source) */',newline,...
'unsigned_char_t SAC_Obs_Var_Delay;',newline,...
'/*!< @ASAP_NAME SAC_Obs_Var_Delay @UNIT  @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Obs_Var_Delay) */',newline,...
'signed_int16_t LaKMC_kappa_cmd_dbg;',newline,...
'/*!< @ASAP_NAME LaKMC_kappa_cmd_dbg @UNIT 1/m @LSB 0.0000200000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LaKMC_kappa_cmd_dbg) */',newline,...
'signed_int16_t VEH_Delta_F_dbg;',newline,...
'/*!< @ASAP_NAME VEH_Delta_F_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VEH_Delta_F_dbg) */',newline,...
'signed_int16_t VEH_Delta_clm_sens_F_dbg;',newline,...
'/*!< @ASAP_NAME VEH_Delta_clm_sens_F_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VEH_Delta_clm_sens_F_dbg) */',newline,...
'signed_int16_t VEH_Delta_F_Dot_dbg;',newline,...
'/*!< @ASAP_NAME VEH_Delta_F_Dot_dbg @UNIT - @LSB 0.0437500000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VEH_Delta_F_Dot_dbg) */',newline,...
'signed_int16_t VEH_Steer_Torque_dbg;',newline,...
'/*!< @ASAP_NAME VEH_Steer_Torque_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VEH_Steer_Torque_dbg) */',newline,...
'signed_int16_t EPS_Tie_Rod_Load_dbg;',newline,...
'/*!< @ASAP_NAME EPS_Tie_Rod_Load_dbg @UNIT Nm @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (EPS_Tie_Rod_Load_dbg) */',newline,...
'signed_int16_t EPS_Motor_Torque_dbg;',newline,...
'/*!< @ASAP_NAME EPS_Motor_Torque_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (EPS_Motor_Torque_dbg) */',newline,...
'signed_int16_t EPS_Status_dbg;',newline,...
'/*!< @ASAP_NAME EPS_Status_dbg @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (EPS_Status_dbg) */',newline,...
'signed_int16_t LaDMC_Eps_Torque_Request_dbg;',newline,...
'/*!< @ASAP_NAME LaDMC_Eps_Torque_Request_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LaDMC_Eps_Torque_Request_dbg) */',newline,...
'signed_int16_t SAT_Saturated_Angle_Command_dbg;',newline,...
'/*!< @ASAP_NAME SAT_Saturated_Angle_Command_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief steer angle target command (SAT_Saturated_Angle_Command_dbg) */',newline,...
'signed_int16_t SAC_Eps_Trq_Load_Est_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Eps_Trq_Load_Est_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief estimated EPS motor load (SAC_Eps_Trq_Load_Est_dbg) */',newline,...
'signed_int16_t LAT_Dmc_Status_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Dmc_Status_dbg @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief DMC status (LAT_Dmc_Status_dbg) */',newline,...
'signed_int16_t LDC_Psi_Command_dbg;',newline,...
'/*!< @ASAP_NAME LDC_Psi_Command_dbg @UNIT rad @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief psi command to the heading controller (LDC_Psi_Command_dbg) */',newline,...
'signed_int16_t DYC_Steer_Angle_Feedforward_dbg;',newline,...
'/*!< @ASAP_NAME DYC_Steer_Angle_Feedforward_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief fed forward steer angle command (DYC_Steer_Angle_Feedforward_dbg) */',newline,...
'signed_int16_t LAT_Delta_Ys_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Delta_Ys_dbg @UNIT m @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief lateral deviation error (LAT_Delta_Ys_dbg) */',newline,...
'signed_int16_t LAT_Delta_Psi_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Delta_Psi_dbg @UNIT rad @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief heading angle error (LAT_Delta_Psi_dbg) */',newline,...
'signed_int16_t LAT_Kappa_Command_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Kappa_Command_dbg @UNIT 1/m @LSB 0.0000200000 @MIN -Inf @MAX Inf @OFFSET 0 @brief kappa command (LAT_Kappa_Command_dbg) */',newline,...
'signed_int16_t HEC_Psi_Control_Error_dbg;',newline,...
'/*!< @ASAP_NAME HEC_Psi_Control_Error_dbg @UNIT rad @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief control error of the heading angle controller (HEC_Psi_Control_Error_dbg) */',newline,...
'signed_int16_t HEC_Delta_F_Cmd_dbg;',newline,...
'/*!< @ASAP_NAME HEC_Delta_F_Cmd_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief steer angle command from the heading controller (HEC_Delta_F_Cmd_dbg) */',newline,...
'signed_int16_t LDC_Delta_Psi_Dist_dbg;',newline,...
'/*!< @ASAP_NAME LDC_Delta_Psi_Dist_dbg @UNIT rad @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief lateral disturbance psi command (LDC_Delta_Psi_Dist_dbg) */',newline,...
'signed_int16_t SAC_Yrc_Angle_Command_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Yrc_Angle_Command_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief steer angle command from the active yaw rate controller (SAC_Yrc_Angle_Command_dbg) */',newline,...
'unsigned_int16_t LAT_Kappa_Linz_Omega_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Kappa_Linz_Omega_dbg @UNIT rad/s @LSB 0.0078125000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Omega of the kappa input filter (LAT_Kappa_Linz_Omega_dbg) */',newline,...
'signed_int16_t LAT_Kappa_Filter_Output_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Kappa_Filter_Output_dbg @UNIT 1/m @LSB 0.0000200000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Output of the kappa input filter (LAT_Kappa_Filter_Output_dbg) */',newline,...
'signed_int16_t LAT_Filtered_Delta_F_Offset_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Filtered_Delta_F_Offset_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Filtered angle offset (LAT_Filtered_Delta_F_Offset_dbg) */',newline,...
'signed_int16_t LAT_Oc_Integrator_Input_Kappa_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Oc_Integrator_Input_Kappa_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Kappa based integrator input (LAT_Oc_Integrator_Input_Kappa_dbg) */',newline,...
'signed_int16_t LAT_Oc_Integrator_Input_Raw_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Oc_Integrator_Input_Raw_dbg @UNIT m @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Raw input of the Oc integrator (LAT_Oc_Integrator_Input_Raw_dbg) */',newline,...
'signed_int16_t CAM_Kappa_Cmd_dbg;',newline,...
'/*!< @ASAP_NAME CAM_Kappa_Cmd_dbg @UNIT 1/m @LSB 0.0000200000 @MIN -Inf @MAX Inf @OFFSET 0 @brief curvature signal provided by the camera (CAM_Kappa_Cmd_dbg) */',newline,...
'signed_int16_t DMC_LAT_DEGRADATION;',newline,...
'/*!< @ASAP_NAME DMC_LAT_DEGRADATION @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief  (DMC_LAT_DEGRADATION) */',newline,...
'signed_int16_t DMC_LAT_DEGRADATION_TEMP;',newline,...
'/*!< @ASAP_NAME DMC_LAT_DEGRADATION_TEMP @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief  (DMC_LAT_DEGRADATION_TEMP) */',newline,...
'unsigned_char_t VEH_Stability_Control_Active;',newline,...
'/*!< @ASAP_NAME VEH_Stability_Control_Active @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief ABS, ESC or TCS controller active (VEH_Stability_Control_Active) */',newline,...
'unsigned_char_t VEH_Stability_Control_Active_temp;',newline,...
'/*!< @ASAP_NAME VEH_Stability_Control_Active_temp @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief ABS, ESC or TCS controller active (VEH_Stability_Control_Active_temp) */',newline,...
'signed_int16_t LKC_Lane_Status;',newline,...
'/*!< @ASAP_NAME LKC_Lane_Status @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LKC_Lane_Status) */',newline,...
'signed_int16_t Lat_rate_limited_offset_dbg;',newline,...
'/*!< @ASAP_NAME Lat_rate_limited_offset_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (Lat_rate_limited_offset_dbg) */',newline,...       
'unsigned_int16_t SAC_Trq_Derating_Factor_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Trq_Derating_Factor_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Trq_Derating_Factor_dbg) */',newline,...
'unsigned_int16_t TDF_Torque_Derating_Factor_dbg;',newline,...
'unsigned_int16_t TDF_Sac_Dos_Limit_Scale_dbg;',newline,...
'/*!< @ASAP_NAME TDF_Sac_Dos_Limit_Scale_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (TDF_Sac_Dos_Limit_Scale_dbg) */',newline,...
'float32 Cam_kappa_feedfwd;',newline,...
'/*!< @ASAP_NAME Cam_kappa_feedfwd @UNIT 1/m @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (Cam_kappa_feedfwd) */',newline,...
'float32 LaKMC_kappa_sum_command;',newline,...
'/*!< @ASAP_NAME LaKMC_kappa_sum_command @UNIT 1/m @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LaKMC_kappa_sum_command) */',newline,...
'signed_int16_t Cam_kappa_qf;',newline,...
'/*!< @ASAP_NAME Cam_kappa_qf @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (Cam_kappa_qf) */',newline,...
'signed_int16_t LKC_Lane_Status_dbg;',newline,...
'/*!< @ASAP_NAME LKC_Lane_Status_dbg @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Lane status (LKC_Lane_Status_dbg) */',newline,...
'signed_int16_t LAT_Oc_Kappa_Status_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Oc_Kappa_Status_dbg @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Oc_Kappa_Status_dbg) */',newline,...
'signed_int16_t LAT_Oc_Dys_Status_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Oc_Dys_Status_dbg @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Oc_Dys_Status_dbg) */',newline,...
'signed_int16_t LAT_Gen_Purpose_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Gen_Purpose_dbg @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Gen_Purpose_dbg) */',newline,...
'signed_int16_t VEH_Delta_F_Oc_dbg;',newline,...
'/*!< @ASAP_NAME VEH_Delta_F_Oc_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Offset corrected steer angle (VEH_Delta_F_Oc_dbg) */',newline,...
'signed_int16_t SAT_Req_Angle_Supp_Control_dbg;',newline,...
'/*!< @ASAP_NAME SAT_Req_Angle_Supp_Control_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Contribution of the support torque controller (SAT_Req_Angle_Supp_Control_dbg) */',newline,...
'signed_int16_t MOT_Modulated_Torque_dbg;',newline,...
'/*!< @ASAP_NAME MOT_Modulated_Torque_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Torque output of the vibration unit (MOT_Modulated_Torque_dbg) */',newline,...
'signed_int16_t TDF_Steer_Torque_Sample_dbg;',newline,...
'/*!< @ASAP_NAME TDF_Steer_Torque_Sample_dbg @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief starting torque of the output torque derating (TDF_Steer_Torque_Sample_dbg) */',newline,...
'unsigned_int16_t SAC_Factor_Kp_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Factor_Kp_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Factor_Kp_dbg) */',newline,...
'signed_int16_t SAC_Enhanced_Angle_Cmd_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Enhanced_Angle_Cmd_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Enhanced_Angle_Cmd_dbg) */',newline,...
'signed_int16_t SAC_Fading_Offset_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Fading_Offset_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (SAC_Fading_Offset_dbg) */',newline,...
'signed_int16_t DYC_Boost_Filter_Out_dbg;',newline,...
'/*!< @ASAP_NAME DYC_Boost_Filter_Out_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Contribution of the DYC booster function (DYC_Boost_Filter_Out_dbg) */',newline,...
'unsigned_int16_t SAC_Load_Comp_Factor_Varia_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Load_Comp_Factor_Varia_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief Variation of the load compensation factor (SAC_Load_Comp_Factor_Varia_dbg) */',newline,...
'signed_int16_t SAC_Arb_Angle_Cmd_Raw_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Arb_Angle_Cmd_Raw_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Raw angle command (SAC_Arb_Angle_Cmd_Raw_dbg) */',newline,...
'signed_int16_t SAC_Faded_Angle_Command_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Faded_Angle_Command_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Rate limited angle command (SAC_Faded_Angle_Command_dbg) */',newline,...
'signed_int16_t DYC_Boost_Request_dbg;',newline,...
'/*!< @ASAP_NAME DYC_Boost_Request_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief DYC_Boost_Request_dbg (DYC_Boost_Request_dbg) */',newline,...
'signed_int16_t LAT_Debug1_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Debug1_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief Debug signal 1 (LAT_Debug1_dbg) */',newline,...
'signed_int16_t LAT_Debug2_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Debug2_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief Debug signal 2 (LAT_Debug2_dbg) */',newline,...
'signed_int16_t LAT_Debug3_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Debug3_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief Debug signal 3 (LAT_Debug3_dbg) */',newline,...
'signed_int16_t LAT_Debug4_dbg;',newline,...
'/*!< @ASAP_NAME LAT_Debug4_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief Debug signal 4 (LAT_Debug4_dbg) */',newline,...
'float32 Cam_heading_error;',newline,...
'signed_int16_t LAT_Debug5_dbg;',newline,...
'signed_int16_t LAT_Debug6_dbg;',newline,...
'signed_int16_t LAT_Debug7_dbg;',newline,...
'signed_int16_t LAT_Debug8_dbg;',newline,...
'/*!< @ASAP_NAME Cam_heading_error @UNIT rad @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (Cam_heading_error) */',newline,...
'float32 VDY_Steer_Angle_Offset;',newline,...
'/*!< @ASAP_NAME VDY_Steer_Angle_Offset @UNIT deg @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VDY_Steer_Angle_Offset) */',newline,...
'float32 Cam_lateral_error;',newline,...
'/*!< @ASAP_NAME Cam_lateral_error @UNIT m @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (Cam_lateral_error) */',newline,...
'unsigned_int16_t SAC_Load_Comp_Factor_Straight_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Load_Comp_Factor_Straight_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief Load compensation factor request during driving straight forward (SAC_Load_Comp_Factor_Straight_dbg) */',newline,...
'signed_int16_t VEH_Yaw_Rate_Oc_dbg;',newline,...
'/*!< @ASAP_NAME VEH_Yaw_Rate_Oc_dbg @UNIT - @LSB 0.0028600000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Offset correctetd yaw rate (VEH_Yaw_Rate_Oc_dbg) */',newline,...
'float32 VEH_Yaw_Rate_Offset;',newline,...
'/*!< @ASAP_NAME VEH_Yaw_Rate_Offset @UNIT rad/s @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (VEH_Yaw_Rate_Offset) */',newline,...
'signed_int16_t SAC_Steering_Wheel_Angle_Cmd_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Steering_Wheel_Angle_Cmd_dbg @UNIT deg @LSB 0.0437500000 @MIN -Inf @MAX Inf @OFFSET 0 @brief steering wheel angle target command (SAC_Steering_Wheel_Angle_Cmd_dbg) */',newline,...
'signed_int16_t SAC_Filtered_Angle_Command_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Filtered_Angle_Command_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief filtered steer angle target command (SAC_Filtered_Angle_Command_dbg) */',newline,...
'unsigned_int16_t OBS_Discharge_Req_Level_dbg;',newline,...
'/*!< @ASAP_NAME OBS_Discharge_Req_Level_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (OBS_Discharge_Req_Level_dbg) */',newline,...
'unsigned_int16_t OBS_Boost_Request_Level_dbg;',newline,...
'/*!< @ASAP_NAME OBS_Boost_Request_Level_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (OBS_Boost_Request_Level_dbg) */',newline,...
'float32 DYC_Boost_Request;',newline,...
'/*!< @ASAP_NAME DYC_Boost_Request @UNIT  @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Dynamic compensation filter boost request (DYC_Boost_Request) */',newline,...
'float32 DYC_Angle_Per_Kappa;',newline,...
'/*!< @ASAP_NAME DYC_Angle_Per_Kappa @UNIT  @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Dynamic compensation filter angle per curvature command (DYC_Angle_Per_Kappa) */',newline,...
'float32 LKC_Kappa_Command_Arb;',newline,...
'/*!< @ASAP_NAME LKC_Kappa_Command_Arb @UNIT 1/m @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Arbitrated curvature command (LKC_Kappa_Command_Arb) */',newline,...
'float32 LKC_Kappa_Dot_Command_Arb;',newline,...
'/*!< @ASAP_NAME LKC_Kappa_Dot_Command @UNIT 1/m/m @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Arbitrated curvature rate command (LKC_Kappa_Dot_Command_Arb) */',newline,...
'float32 LKC_Steer_Kappa_Ctrl_Command;',newline,...
'/*!< @ASAP_NAME LKC_Steer_Kappa_Ctrl_Command @UNIT 1/m @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Curvature command from trajectory controller (LKC_Steer_Kappa_Ctrl_Command) */',newline,...
'unsigned_int32_t SAC_Controller_Mode_Sig;',newline,...
'/*!< @ASAP_NAME SAC_Controller_Mode_Sig @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Steering angle controller mode (SAC_Controller_Mode_Sig) */',newline,...
'unsigned_char_t LDP_Active;',newline,...
'/*!< @ASAP_NAME LDP_Active @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Lane departure protection function active (LDP_Active) */',newline,...
'float32 SAC_R_Factor;',newline,...
'/*!< @ASAP_NAME SAC_R_Factor @UNIT  @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Feedback factor of yaw rate controller (SAC_R_Factor) */',newline,...
'signed_int16_t LADMC_STEER_ANGLE_REQ;',newline,...
'/*!< @ASAP_NAME LADMC_STEER_ANGLE_REQ @UNIT deg @LSB 0.0437500000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LADMC_STEER_ANGLE_REQ) */',newline,...
'unsigned_char_t LADMC_ACCURACY_LEVEL_REQUEST;',newline,...
'/*!< @ASAP_NAME LADMC_ACCURACY_LEVEL_REQUEST @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 100 @OFFSET 0 @brief comment (LADMC_ACCURACY_LEVEL_REQUEST) */',newline,...
'signed_int16_t TDF_Idle_Status_dbg;',newline,...
'/*!< @ASAP_NAME TDF_Idle_Status_dbg @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Tdf idle status (TDF_Idle_Status_dbg) */',newline,...
'signed_int16_t SAC_Dyn_Corrected_Angle_Cmd_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Dyn_Corrected_Angle_Cmd_dbg @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Dynamically corrected steer angle command (SAC_Dyn_Corrected_Angle_Cmd_dbg) */',newline,...
'unsigned_char_t DMC_STIFFNESS_LIMIT;',newline,... 
'signed_int16_t DMC_STIFFNESS_GRAD;',newline,... 
'unsigned_char_t DMC_TORQUE_SCALE_LIMIT;',newline,... 
'signed_int16_t DMC_TORQUE_SCALE_GRAD;',newline,... 
'signed_int16_t DMC_TORQUE_RAMP_GRAD;',newline,... 
'unsigned_char_t DMC_HIGH_ACCURACY_REQUEST;',newline,...
'signed_int16_t SAC_Max_Torque_Scale_dbg;',newline,... 
'/*!< @ASAP_NAME SAC_Max_Torque_Scale_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief Max torque scaling factor (SAC_Max_Torque_Scale_dbg) */',newline,...
'signed_int16_t VEH_Steer_Torque_Comp_dbg;',newline,...
'signed_int16_t SAC_Accuracy_Request_dbg;',newline,...
'/*!< @ASAP_NAME SAC_Accuracy_Request_dbg @UNIT - @LSB 0.0009765625 @MIN -Inf @MAX Inf @OFFSET 0 @brief Accuracy request */',newline,...
'unsigned_char_t LADMC_DERATING_FACTOR_REQUEST;',newline,...
'unsigned_char_t LAT_Activation_Request__nu;',newline,...
'/*!< @ASAP_NAME LAT_Activation_Request__nu @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 100 @OFFSET 0 @brief comment (LAT_Activation_Request__nu) */',newline,...
'unsigned_char_t LAT_Activation_Request_Qf__nu;',newline,...
'/*!< @ASAP_NAME LAT_Activation_Request_Qf__nu @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 100 @OFFSET 0 @brief comment (LAT_Activation_Request_Qf__nu) */',newline,...
'unsigned_char_t LAT_Force_Shut_Off_Request;',newline,...
'/*!< @ASAP_NAME LAT_Force_Shut_Off_Request @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 100 @OFFSET 0 @brief comment (LAT_Force_Shut_Off_Request) */',newline,...
'signed_int16_t LAT_Steer_Angle_Command__deg;',newline,...
'/*!< @ASAP_NAME LAT_Steer_Angle_Command__deg @UNIT deg @LSB 0.0437500000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Steer_Angle_Command__deg) */',newline,...
'signed_int16_t LAT_Torque_Overlay_Request__nm;',newline,...
'/*!< @ASAP_NAME LAT_Torque_Overlay_Request__nm @UNIT Nm @LSB 0.0010000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Torque_Overlay_Request__nm) */',newline,...
'unsigned_char_t LAT_Stiffness_Request__per;',newline,...
'/*!< @ASAP_NAME LAT_Stiffness_Request__per @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 100 @OFFSET 0 @brief comment (LAT_Stiffness_Request__per) */',newline,...
'unsigned_char_t LAT_Accuracy_Request__per;',newline,...
'/*!< @ASAP_NAME LAT_Accuracy_Request__per @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 100 @OFFSET 0 @brief comment (LAT_Accuracy_Request__per) */',newline,...
'unsigned_char_t LAT_Steering_Wheel_Vibration__nu;',newline,...
'/*!< @ASAP_NAME LAT_Steering_Wheel_Vibration__nu @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 100 @OFFSET 0 @brief comment (LAT_Steering_Wheel_Vibration__nu) */',newline,...
'unsigned_char_t LAT_Lane_Status__nu;',newline,...
'/*!< @ASAP_NAME LAT_Lane_Status__nu @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 100 @OFFSET 0 @brief comment (LAT_Lane_Status__nu) */',newline,...
'unsigned_char_t LAT_Derating_Level_Request__per;',newline,...
'/*!< @ASAP_NAME LAT_Derating_Level_Request__per @UNIT - @LSB 1.0000000000 @MIN 0 @MAX 100 @OFFSET 0 @brief comment (LAT_Derating_Level_Request__per) */',newline,...
'unsigned_char_t LAT_Torque_Ramp_Factor__per;',newline,...
'/*!< @ASAP_NAME LAT_TRQ_RAMP_FACTOR @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief - (LAT_Torque_Ramp_Factor__per) */',newline,...
'unsigned_char_t LAT_Dmc_Status__nu;',newline,...
'signed_int16_t LAT_Eps_Torque_Request__nm;',newline,...
'signed_int16_t SAC_Ayc_Residual_dbg;',newline,...
'unsigned_int16_t TRL_Torque_Gradient_dbg;',newline,...
'signed_int16_t SAC_Delta_F_Cmd_Grad_Param_dbg;',newline,...
'signed_int16_t SAC_Control_Error_Eps_dbg;',newline,...
'signed_int16_t SAC_Yrc_Residual_dbg;',newline,...
'unsigned_char_t DMC_ANGLE_FADING_REQ;',newline,...
'unsigned_char_t DMC_RAMPING_DOWN_REQ;',newline,...
'unsigned_char_t DMC_ANGLE_REQ_MAX_LIMIT_SCALE;',newline,...
'unsigned_char_t DMC_ANGLE_REQ_MAX_GRAD_SCALE;',newline,...
'signed_int16_t SAC_Angle_Command_Raw_dbg;',newline,...
'unsigned_char_t SAC_Soc_Disable;',newline,...
'unsigned_int16_t SAC_Load_Cmp_Fct_Curv_Chg_dbg;',newline,...
'float32 ADP_Dyc_Corr_Factor;',newline,...
'float32 ADP_Dyc_Corr_Factor_Ls;',newline,...
'float32 ADP_Dyc_Corr_Factor_Rs;',newline,...
'unsigned_char_t Turn_And_Error_Side;',newline,...
'float32 CAM_Lateral_Error_Mean;',newline,...
'float32 CAM_Lateral_Error_Delta;',newline,...
'unsigned_int16_t Maximum_Waiting_Counter;',newline,...
'float32 Factor_Increase;',newline,...
'float32 Factor_Decrease;',newline,...
'unsigned_int16_t LTLE_Waiting_Counter;',newline,...
'unsigned_int16_t LTRE_Waiting_Counter;',newline,...
'unsigned_int16_t RTLE_Waiting_Counter;',newline,...
'unsigned_int16_t RTRE_Waiting_Counter;',newline,...
'unsigned_char_t Factor_Corr_Enable_Flag;',newline,...
'float32 ADP_Dyc_Corr_Factor_Left_Vect[20];',newline,...
'float32 ADP_Dyc_Corr_Factor_Right_Vect[20];',newline,...
'float32 Mean_Kappa_Command;',newline,...
'float32 Mean_Vehicle_Velocity;',newline,...
'signed_int16_t DMC_ANGLE_OFF_LOOP0;',newline,... 
'unsigned_int16_t DMC_ANGLE_OFF_CALIB_CNT_LOOP0;',newline,...
'unsigned_char_t DMC_ANGLE_OFF_READ_ERROR;',newline,...
'signed_int16_t DMC_ANGLE_OFF;',newline,... 
'/*!< @ASAP_NAME DMC_ANGLE_OFF @UNIT deg @LSB 0.0015260000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Steer angle offset to be written to the Eeprom (DMC_ANGLE_OFF) */',newline,...
'signed_int16_t DMC_Eps_Integrator_Hold_Req__nu;',newline,... 
'unsigned_int16_t DMC_ANGLE_OFF_CALIB_CNT;',newline,...
'/*!< @ASAP_NAME DMC_ANGLE_OFF_CALIB_CNT @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Steer angle offset calibration counter to be written to the Eeprom (DMC_ANGLE_OFF_CALIB_CNT) */',newline,...
'signed_int16_t SAC_Derated_Angle_Command_dbg;',newline,...
'unsigned_char_t DMC_ADP_CORR_FACTOR_POS[20];',newline,...
'/*!< @ASAP_NAME DMC_ADP_CORR_FACTOR_POS @UNIT - @LSB 0.0078125000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Steering characteristic correction factor left vector (DMC_ADP_CORR_FACTOR_POS) */',newline,...
'unsigned_char_t DMC_ADP_CORR_FACTOR_NEG[20];',newline,...
'/*!< @ASAP_NAME DMC_ADP_CORR_FACTOR_NEG @UNIT - @LSB 0.0078125000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Steering characteristic correction factor right vector (DMC_ADP_CORR_FACTOR_NEG) */',newline,...
'unsigned_int16_t DMC_ADP_CORR_COUNTER_POS[20];',newline,...
'/*!< @ASAP_NAME DMC_ADP_CORR_COUNTER_POS @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Steering characteristic correction factor counter left vector (DMC_ADP_CORR_COUNTER_POS) */',newline,...
'unsigned_int16_t DMC_ADP_CORR_COUNTER_NEG[20];',newline,...
'/*!< @ASAP_NAME DMC_ADP_CORR_COUNTER_NEG @UNIT - @LSB 1.0000000000 @MIN -Inf @MAX Inf @OFFSET 0 @brief Steering characteristic correction factor counter right vector (DMC_ADP_CORR_COUNTER_NEG) */',newline,...
'unsigned_char_t DMC_ADP_CORR_FACTOR_POS_LOOP0[20];',newline,...
'unsigned_char_t DMC_ADP_CORR_FACTOR_NEG_LOOP0[20];',newline,...
'unsigned_int16_t DMC_ADP_CORR_COUNTER_POS_LOOP0[20];',newline,...
'unsigned_int16_t DMC_ADP_CORR_COUNTER_NEG_LOOP0[20];',newline,...
'unsigned_char_t DMC_ADP_CORR_FACTOR_READ_ERROR;',newline,...
'unsigned_char_t DMC_DERATING_LEVEL_REQ;',newline,...
'signed_int16_t SAT_Angle_Rate_Residual_dbg;',newline,...
'signed_int16_t SAC_Damping_Angle_Command_dbg;',newline,...
'unsigned_int16_t SAC_Ctrl_Err_Memshp_Low_Dyn_dbg;',newline,...
'unsigned_int16_t SAC_Control_Err_Membership_dbg;',newline,...
'signed_int16_t LAT_Kappa_Sum_Command__1pm;',newline,...
'/*!< @ASAP_NAME LAT_Kappa_Sum_Command__1pm @UNIT 1/m @LSB 0.0000200000 @MIN -Inf @MAX Inf @OFFSET 0 @brief comment (LAT_Kappa_Sum_Command__1pm) */',newline,...
'signed_int16_t SAT_Req_Steer_Angle_Max_Ay_dbg;',newline,...
'signed_int16_t LAT_Ay_Control_Limit_Bias_dbg;',newline,...
'signed_int16_t SAC_Delta_F_Sat_Command_dbg;',newline,...
'unsigned_int16_t SAT_Active_Saturation_dbg;',newline,...
'signed_int16_t SAT_Req_Dyn_Steer_Angle_Max_dbg;',newline,...
'signed_int16_t SAC_Angle_Cmd_Yawrate_Fback_dbg;',newline,...
'signed_int16_t LAT_Oc_Delta_Ys_Filtered_dbg;',newline,...
'unsigned_char_t DMC_DRIVING_MODE;',newline,...
'signed_int16_t DMC_BANK_ANGLE;',newline,...
'signed_int16_t LAT_Oc_Rls_Delta_L_Offset_Raw_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_Delta_L_Offst_Lim_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_Status_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_stiffness_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_variance_stiffnes_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_variance_offset_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_cov_stiffnes_offs_dbg;',newline,...
'unsigned_int16_t LAT_Ay_Dynamic_Threshold_dbg;',newline,...
'signed_int16_t SAT_Req_Steer_Angle_Max_dbg;',newline,...
'unsigned_int16_t LCF_Operation_Mode;',newline,...
'signed_int16_t DMC_GPIO;',newline,...
'signed_int16_t DMC_GPIO2;',newline,...
'signed_int16_t DMC_GPIO3;',newline,...
'signed_int16_t DMC_GPIO4;',newline,...
'signed_int16_t EMO_PITCH_ANGLE;',newline,...
'signed_int16_t LAT_Pitch_Angle_Deviation_dbg;',newline,...
'signed_int16_t LAT_Pitch_Angle_Deviation_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_var1_stiff_V4_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_var1_off_V4_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_var_stiff_V2_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_cov_stiff_off_V2_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_var_off_V2_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_var1_stiff_V3_dbg;',newline,...
'unsigned_int16_t LAT_Oc_Rls_var1_off_V3_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_stiff_V3_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_stiff_V4_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_Delta_L_dead_V4_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_Delta_L_Off_V4_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_stiffness_V2_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_Delta_L_Offset_V2_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_Delta_L_dead_V3_dbg;',newline,...
'signed_int16_t LAT_Oc_Rls_Delta_L_Off_V3_dbg;',newline,...
'signed_int16_t DMC_Steer_Angle_Oc__deg;',newline,...
'unsigned_int16_t SAC_Dynamic_Correction_Factor_dbg;',newline,...
'signed_int16_t SAC_Derated_Eps_Torque_dbg;',newline,...
'signed_int16_t DMC_ROAD_WHEEL_ANGLE;',newline,...
'signed_int16_t LAT_Road_Wheel_Angle_Cmd__deg;',newline,...
'unsigned_int16_t LAT_Gi_Status_dbg;',newline,...
'float32 VDY_Bank_Angle;',newline,...
};
%'signed_int16_t SAC_Rate_Limit_Residual_Flag;',newline,...
%'signed_int16_t TDF_Idle_Status_dbg;',newline,...SAC_Dyn_Corrected_Angle_Cmd_dbg

% Keywords to find in code
string1 = 'pressure_tmc_t';
string2 = 'pressure_tmc_grad_t ';
string3 = 'GET_SIG_BOX_DATA';
string4 = 'GET_SENS_PRESSURE_TMC';
string5 = '(eps_cmd_mode_t)';
string6 = '(eps_cmd_comp_t)';

source_4 = fullfile( currpath, 'dmc_soc.c');
destination_4 = fullfile( currpath, 'dmc_soc_old.c');
%copyfile(source_4,destination_4,'f');

%Open source file
fid_1 = fopen(source_4,'rt') ; %dmc.c
X = fread(fid_1) ;
X = char(X.') ;
if (strfind(X, '@ASAP_NAME'))
    disp('Warning: file dmc_soc.c already modifed, no changes performed !!!')
else
    a = 0;
copyfile(source_4,destination_4,'f');
fclose(fid_1);
fid_1 = fopen(destination_4,'rt') ; %dmc.c
fid_2 = fopen(source_4,'wt') ;
%lines=textscan(fid_1,'%s','delimiter','\n');
while ( ~feof(fid_1) )
    % read line from reading file
    tline = fgets(fid_1) ;
    a = a+1;
    if isempty(strfind(tline,str1))
        %Do nothing
    else
        for i=1:length(str_replace)
            fprintf(fid_2,[str_replace{i}]) ;
        end
    end
    
% Check if any of the searched variable are in the current line
    if xor((isempty(strfind(tline,string1))),...
            xor((isempty(strfind(tline,string2))),...
            xor((isempty(strfind(tline,string3))),...
            xor((isempty(strfind(tline,string4))),...
            xor((isempty(strfind(tline,string5))),((isempty(strfind(tline,string6)))))))))
        
    fprintf(fid_2,['//' tline]) ;
    else
    fwrite(fid_2,tline) ;
    end
end
%Create the file dmc_old.c
fclose(fid_2);
disp('File dmc_soc.c modifed, old file dmc_soc_old.c !')
end
fclose(fid_1);
