/*.?Checksum:3542033646.?*/
/*.?ParameterSetName:JAPAN_LKA_LDP_RDP_AOLC_DEMO.?*/
/*.?FileName:PARAMLVC.c.?*/
/*.?Option:project.?*/
/*.?CodeGeneratorBuild:ccg..?*/
/*
*************************************************************************************************
 Confidential and proprietary. This document and its contents are the exclusive property of
 Continental Teves AG & Co. OHG (Teves) and Conti Temic microelectronic GmbH (Temic) and their
 associated companies. They are not to be copied, distributed, or otherwise disclosed or used
 without the prior written consent of Teves and Temic. All rights reserved.
*************************************************************************************************
Functionmodel:  LVC - VA21 @10ms
Function:       
Filename:       PARAMLVC.c
*************************************************************************************************
File Generated by PACS Code-Generator
*************************************************************************************************
*/

#include "hal_base_type_if.h"  //MFC5J3
#include "dmc_lat.h"  //MFC5J3

/* Justification 3116: #pragma needed to prevent wrong optimization */
#ifdef _PACS_NO_CONST_OPT_
   #pragma option -Xwhole-program-optim=0 /* PRQA S 3116 */
#endif

unsigned_int16_t ACF_MIN_SAC_ENABLED_TIME[1] = {320}; /* @5@ */
unsigned_char_t ACF_NO_OF_ITEMS_IN_SAMPLE[1] = {50}; /* @50@ */
unsigned_char_t ACF_NO_OF_SEGMENT_SELECTION[1] = {3}; /* @3@ */
unsigned_int16_t ACF_SLOP_LATERAL_ERROR_FACT_DEC[1] = {1229}; /* @1.2@ */
unsigned_int16_t ACF_SLOP_LATERAL_ERROR_FACT_INC[1] = {1229}; /* @1.2@ */
unsigned_int16_t ACF_SLOP_ROAD_GRADIENT_FACT_DEC[1] = {410}; /* @0.4@ */
unsigned_int16_t ACF_SLOP_ROAD_GRADIENT_FACT_INC[1] = {410}; /* @0.4@ */
unsigned_int16_t ADP_DYC_CORR_FACTOR_GRADIENT[1] = {10240}; /* @10@ */
unsigned_int16_t ADP_DYC_CORR_FACTOR_LOWER_LIMIT[1] = {819}; /* @0.8@ */
unsigned_int16_t ADP_DYC_CORR_FACTOR_UPPER_LIMIT[1] = {1229}; /* @1.2@ */
unsigned_int16_t ADP_DYC_CORR_FACT_DEC_X_SCHED[12] = 
{
   0, 640, 1280, 1920, 2560, 3200, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t ADP_DYC_CORR_FACT_DEC_Y_SCHED[12] = 
{
   22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 
/* @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@ */
};
unsigned_int16_t ADP_DYC_CORR_FACT_INC_X_SCHED[12] = 
{
   0, 640, 1280, 1920, 2560, 3200, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t ADP_DYC_CORR_FACT_INC_Y_SCHED[12] = 
{
   22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 
/* @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@ */
};
unsigned_int16_t DIT_DIRAC_LOOP_COUNT[1] = {1024}; /* @1@ */
unsigned_int16_t DIT_SIGNAL_GEN_FREQUENCY[1] = {15360}; /* @15@ */
unsigned_int16_t DIT_SIGNAL_GEN_DUTY_CYCLE[1] = {410}; /* @0.4@ */
unsigned_int16_t DIT_TORQUE_PULSE_AMPLITUDE[1] = {410}; /* @0.4@ */
unsigned_int16_t DMC_CONFIGURATION_MODE[1] = {1635}; /* @1125@  */ /* +32: use VDY yaw rate offset */ /* Kuboyama(180305)69 -> 1093 (enable angle command fading but disable fading by TDF -> TDF active torque threshold(TDF_TORQUE_DERATING_THRESHOLD/TDF_TRQ_DERATING_THRESHOLD_DP) were changed from 0.5Nm to 3.5Nm) */ //ElNa increment value by 2
unsigned_int16_t DMC_CONFIGURATION_MODE_2[1] = {489}; /* @489@ */ /* 419 + 64 + 6 variant 2, with short gradient reduction during replanning */
unsigned_int16_t DMC_CONFIGURATION_MODE_3[1] = {38}; /* @3@ */ /* + 32  for using actual steer angle as reference for jerk limiter */ 
unsigned_int16_t DYC_BOOST_SIGNAL_REDUCTION[1] = {98}; /* @0.003@ */
unsigned_int16_t DYC_COMPENSATION_MODE[1] = {310}; /* @310@ */
unsigned_int16_t DYC_KAPPA_A2_BOOST_FACTOR[1] = {0}; /* @0@ */
unsigned_int16_t DYC_KAPPA_A2_BOOST_FACTOR_NEG[1] = {2048}; /* @2@ */ /* (190315 NoYo) A2_LDP = A2(2500) * 2 = 5000*/
unsigned_int16_t DYC_KAPPA_A2_BOOST_FACTOR_POS[1] = {2048}; /* @2@ */ /* (190315 NoYo) A2_LDP = A2(2500) * 2 = 5000*/
unsigned_int16_t DYC_KAPPA_A2_FACTOR[1] = {2100}; /* @0.61@ */ /* (190315 NoYo) 5000 -> 2500, 50% reduced to avoid early curve-in */
unsigned_int16_t DYC_KAPPA_A2_POS_CORR_FACTOR[1] = {2100}; /* @0.61@ */ /* (190315 NoYo) 5000 -> 2500, 50% reduced to avoid early curve-in */
unsigned_int16_t DYC_KAPPA_A2_X_SCHEDULING[12] = 
{
   0, 640, 1280, 1920, 2560, 3200, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t DYC_KAPPA_A2_Y_SCHEDULING[12] = 
{
   1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 
/* @0.293@, @0.293@, @0.293@, @0.293@, @0.293@, @0.293@, @0.293@, @0.293@, @0.293@, @0.293@, @0.293@, @0.293@ */
};
unsigned_int16_t DYC_KAPPA_A3_FACTOR[1] = {0}; /* @0.0@ */ 
unsigned_int16_t DYC_KAPPA_A3_X_SCHEDULING[11] = 
{
   0, 640, 1280, 1920, 2560, 3200, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t DYC_KAPPA_A3_Y_SCHEDULING[11] = 
{
   74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 
/* @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@, @0.018@ */
};
unsigned_int16_t DYC_KAPPA_ANGLE_CORR_FACTOR[1] = {4096}; /* @1@ */
unsigned_int16_t DYC_KAPPA_ANGLE_GEN_CORR_FACTOR[1] = {4096}; // (190306 Y.Kanamori) tuning result from T&V YOK, (190128 NoYo) tuning result from T&V YOK
unsigned_int16_t DYC_KAPPA_ANGLE_GEN_COR_FCT_NEG[1] = {4096}; // (190306 Y.Kanamori)3891 -> 4096 tuning result from T&V YOK, (190227 Y.Kanamori)3750 -> 3891 tuning result from T&V YOK, (190128 NoYo) tuning result from T&V YOK
unsigned_int16_t DYC_KAPPA_ANGLE_LDP_CORR_Y_SCH[12] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t DYC_KAPPA_ANGLE_LPF_CORR_FACTOR[1] = {4096}; /* @1@ */
unsigned_int16_t DYC_KAPPA_ANGLE_T_X_SCHEDULING[12] = 
{
   0, 640, 1280, 1920, 2560, 3200, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t DYC_KAPPA_ANGLE_T_X_SCHEDUL_AES[12] = 
{
   0, 640, 1280, 1920, 3200, 4480, 5120, 6400, 7680, 8320, 9600, 16000, 
/* @0@, @10@, @20@, @30@, @50@, @70@, @80@, @100@, @120@, @130@, @150@, @250@ */
};
unsigned_int16_t DYC_KAPPA_ANGLE_T_X_SCHEDUL_GEN[12] = 
{
   0, 640, 1280, 1920, 3200, 4480, 5120, 6400, 7680, 8320, 9600, 16000, 
/* @0@, @10@, @20@, @30@, @50@, @70@, @80@, @100@, @120@, @130@, @150@, @250@ */
};
unsigned_int16_t DYC_KAPPA_ANGLE_T_Y_SCHEDUL_GEN[12] = 
{
  //4356, 4728, 5100, 5460, 6008, 8363, 9632, 12183, 15441, 17494, 23029, 41758,
/* @136.13@, @147.78@, @159.38@, @170.64@, @187.77@, @261.41@, @300.99@, @380.80@, @482.64@, @546.81@, @719.80@, @1305.23@ */
  //3920, 4255, 4590, 4914, 5407, 7526, 8668, 10964, 13896, 15744, 20726, 37582,  /*0.9*/
  3049, 3309, 3570, 3822, 4205, 5854, 6742, 8528, 10808, 12245, 16120, 29230,   /*0.7*/
  //2178, 2364, 2550, 2730, 3004, 4181, 4816, 6091, 7720, 8747, 11514, 20879,     /*0.5*/
};
unsigned_int16_t DYC_KAPPA_ANGLE_T_Y_SCH_AES_NEG[12] = 
{
   4356, 4728, 5100, 5460, 6008, 8363, 9632, 12183, 15441, 17494, 23029, 41758,
/* @136.13@, @147.78@, @159.38@, @170.64@, @187.77@, @261.41@, @300.99@, @380.80@, @482.64@, @546.81@, @719.80@, @1305.23@ */
};
unsigned_int16_t DYC_KAPPA_ANGLE_T_Y_SCHEDUL_AES[12] = 
{
   4356, 4728, 5100, 5460, 6008, 8363, 9632, 12183, 15441, 17494, 23029, 41758,
/* @136.13@, @147.78@, @159.38@, @170.64@, @187.77@, @261.41@, @300.99@, @380.80@, @482.64@, @546.81@, @719.80@, @1305.23@ */
};
unsigned_int16_t DYC_KAPPA_ANGLE_T_Y_SCHEDUL_NOM[12] = 
{
   4356, 4728, 5100, 5460, 6008, 8363, 9632, 12183, 15441, 17494, 23029, 41758,
/* @136.13@, @147.78@, @159.38@, @170.64@, @187.77@, @261.41@, @300.99@, @380.80@, @482.64@, @546.81@, @719.80@, @1305.23@ */
};
unsigned_int16_t DYC_KAPPA_ANGLE_T_Y_SCH_GEN_NEG[12] = 
{
   //4356, 4728, 5100, 5460, 6008, 8363, 9632, 12183, 15441, 17494, 23029, 41758,
/* @136.13@, @147.78@, @159.38@, @170.64@, @187.77@, @261.41@, @300.99@, @380.80@, @482.64@, @546.81@, @719.80@, @1305.23@ */
  //3920, 4255, 4590, 4914, 5407, 7526, 8668, 10964, 13896, 15744, 20726, 37582,  /*0.9*/
  3049, 3309, 3570, 3822, 4205, 5854, 6742, 8528, 10808, 12245, 16120, 29230,   /*0.7*/
  //2178, 2364, 2550, 2730, 3004, 4181, 4816, 6091, 7720, 8747, 11514, 20879,     /*0.5*/
};
unsigned_int16_t DYC_KAPPA_DOT_BOOST_THRS[1] = {98}; /* @0.003@ */
unsigned_int16_t DYC_KAPPA_DOT_FILTER_COEFF[1] = {32768}; /* @1@ */
unsigned_int16_t DMC_SIDE_OBJECT_STATUS_OVERRIDE[1] = {0}; /* @0@ */ 
unsigned_int16_t DYC_STATE_FILTER_TIME_CONSTANT[1] = {1000}; /* @0.030@ */
unsigned_int16_t DYC_TIME_CONSTANT_X_SCHEDULING[12] = 
{
   0, 641, 1282, 1923, 2564, 3205, 3846, 5128, 6410, 7692, 11538, 16026, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t DYC_TIME_CONSTANT_Y_SCHEDULING[12] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t EMF_DRIVER_INTERFERENCE_THRESH[1] = {993}; /* @0.97@ */
unsigned_int16_t EMF_INTEG_FACTOR_HIGH_THRES[1] = {20480}; /* @20@ */
unsigned_int16_t EMF_EPS_ERROR_INTEG_FACTOR[1] = {10240}; /* @10@ */
unsigned_int16_t EMF_EPS_ERROR_DIFF_FACTOR[1] = {5120}; /* @5@ */
unsigned_int16_t EMF_EPS_ERROR_FORGETTING_GRAD[1] = {410}; /* @0.4@ */
unsigned_int16_t EMF_EPS_ERROR_INTEG_THRESH[1] = {256}; /* @0.25@ */
unsigned_int16_t EMF_EPS_ERROR_MAX_INTEG[1] = {3072}; /* @3@ */
unsigned_int16_t EMF_EPS_ERROR_THRESH[1] = {101}; /* @0.0987@ */
unsigned_int16_t EMF_EPS_MDL_ERROR_THRES[1] = {34}; /* @0.033@ */ 
unsigned_int16_t EMF_EPS_MDL_ERROR_HIGH_THRESH[1] = {101}; /* @0.0987@ */ 
unsigned_int16_t EMF_EPS_STICK_GRAD[1] = {3072}; /* @3@ */
unsigned_int16_t EMF_MAX_DRIVER_TORQUE[1] = {410}; /* @0.4@ */ 
unsigned_int16_t EMF_REF_CTRL_PARITY_COEFF[1] = {2621}; /* @0.08@ */
unsigned_int16_t EMF_TJA_EPS_ERROR_THRES[1] = {135}; /* @0.132@ */ 
unsigned_int16_t EPS_D[1] = {113}; /* @0.1107@ */
unsigned_int16_t EPS_ONE_BY_J_MOTOR[1] = {0}; /* @0@ */
unsigned_int16_t EPS_TORQUE_COMP_FACTOR[1] = {1024}; /* @1@ */
signed_int16_t EXC_CHIRP_AY_OFFSET[1] = {0}; /* @0@ */
signed_int16_t EXC_CHIRP_DELTA_TORQUE[1] = {0}; /* @0@ */
signed_int16_t EXC_CHIRP_START_FREQUENCY[1] = {205}; /* @0.2@ */
signed_int16_t EXC_HEC_SIGNAL_AMPLITUDE[1] = {102}; /* @0.1@ */
unsigned_int16_t EXC_HEC_SIGNAL_GEN_FREQUENCY[1] = {819}; /* @0.2@ */
unsigned_int16_t EXC_RESTART_CHIRP[1] = {0}; /* @0@ */
signed_int16_t EXC_SIGNAL_AMPLITUDE[1] = {307}; /* @0.3@ */
signed_int16_t EXC_SIGNAL_GEN_FREQUENCY[1] = {205}; /* @0.2@ */
signed_int16_t EXC_TRQ_SIGNAL_AMPLITUDE[1] = {0}; /* @0@ */
signed_int16_t EXC_TRQ_SIGNAL_GEN_FREQUENCY[1] = {1024}; /* @1@ */
unsigned_int16_t HEC_CONTROLLER_MODE[1] = {0}; /* @0@ */
unsigned_int16_t HEC_KP[1] = {1024}; /* @1@ */
unsigned_int16_t HEC_R_DOT_FACTOR[1] = {0}; /* @0@ */
unsigned_int16_t HEC_R_DOT_FACTOR_X_SCHEDULING[11] = 
{
   0, 640, 1280, 1920, 2560, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t HEC_R_DOT_FACTOR_Y_SCHEDULING[11] = 
{
   3072, 3072, 3072, 3072, 3072, 3072, 3072, 3072, 3072, 3072, 3072, 
/* @3@, @3@, @3@, @3@, @3@, @3@, @3@, @3@, @3@, @3@, @3@ */
};
unsigned_int16_t HEC_R_FACTOR[1] = {0}; /* @3.9@ */
unsigned_int16_t HEC_R_FACTOR_OBF[1] = {0}; /* @3.9@ */
unsigned_int16_t HEC_R_PT1_FACTOR[1] = {0}; /* @0@ */
unsigned_int16_t HEC_R_X_SCHEDULING[11] = 
{
   0, 640, 1280, 1920, 2560, 3840, 5120, 6400, 7680, 11520, 14080, 
/* @0@, @10@, @20@, @30@, @40@, @60@, @80@, @100@, @120@, @180@, @220@ */
};
unsigned_int16_t HEC_R_OBF_Y_SCHEDULING[11] = 
{ 
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t HEC_R_Y_SCHEDULING[11] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 2560, 4096, 5939, 14336, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @2.5@, @4@, @5.8@, @14@ */
};
unsigned_int16_t HEC_YAW_RATE_FILTER_COEFF[1] = {1250}; /* @0.0784@ */
unsigned_int16_t LAT_2ND_RATE_CTRL_FILTER_COEFF[1] = {327}; /* @0.02@ */
unsigned_int16_t LAT_2ND_RATE_CTRL_MAX_PT1_PART[1] = {2048}; /* @2@ */
unsigned_int16_t LAT_2ND_RATE_CTRL_MAX_P_PART[1] = {1024}; /* @1@ */
unsigned_int16_t LAT_2ND_RATE_LIMIT_CTRL_KP[1] = {0}; /* @0@ */
unsigned_int16_t LAT_2ND_RATE_LIMIT_CTRL_PT1_KP[1] = {0}; /* @0@ */
unsigned_int16_t LAT_AY_ARW_K[1] = {0}; /* @0@ */
unsigned_int16_t LAT_AY_CMD_MARGIN_FACTOR[1] = {1024}; /* @1@ */ 
unsigned_int16_t LAT_AY_COMP_EPS_DAMPING[1] = {1024}; /* @1@ */
unsigned_int16_t LAT_AY_COMP_EPS_TIME_CONST[1] = {205}; /* @0.2@ */
unsigned_int16_t LAT_AY_CONTROLLER_COEFF[1] = {3277}; /* @0.1@ */
unsigned_int16_t LAT_AY_CONTROL_CMD_FILTER_COEFF[1] = {400}; /* @0.8@ */
unsigned_int16_t LAT_AY_CONTROL_KD[1] = {0}; /* @0@ */
unsigned_int16_t LAT_AY_CONTROL_KI[1] = {2500}; /* @2.5@ */ /* 181218 StFe increase dynamic of the lateral accel limitation */
unsigned_int16_t LAT_AY_CONTROL_KP[1] = {154}; /* @0.075@ */
unsigned_int16_t LAT_AY_CONTROL_PT1_KP[1] = {0}; /* @0@ */
unsigned_int16_t LAT_AY_CTRL_DETACH_THRS[1] = {150}; /* @0.5@ */
unsigned_int16_t LAT_AY_CTRL_MIN_JERK[1] = {102}; /* @0.1@ */
unsigned_int16_t LAT_AY_CTRL_I_PART_DECREMENT[1] = {1024}; /* @1@ */
unsigned_int16_t LAT_AY_CTRL_I_PART_MARGIN[1] = {500}; /* @0.5@ */
unsigned_int16_t LAT_AY_CTRL_RESET_THRS[1] = {512}; /* @0.5@ */
unsigned_int16_t LAT_AY_CTRL_TORQUE_THRS[1] = {6144}; /* @6.0@ */ /* StFe avoid jerks due to driver overriding ay limitation */
unsigned_int16_t LAT_AY_DECREASING_THRESHOLD[1] = {205}; /* @0.2@ */
unsigned_int16_t LAT_AY_MAX_SUPPORT_X_SCHEDULING[12] = 
{
   0, 641, 1282, 1923, 2564, 3205, 3846, 5128, 6410, 7692, 11538, 16026, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t LAT_AY_MAX_SUPPORT_Y_SCHEDULING[12] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t LAT_AY_MAX_X_SCHEDULING[12] = 
{
   0, 641, 1282, 1923, 2564, 3205, 3846, 5128, 6410, 7692, 11538, 16026, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t LAT_AY_MAX_Y_SCHEDULING[12] = 
{
   2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 
/* @1.96@, @1.96@, @1.96@, @1.96@, @1.96@, @1.96@, @1.96@, @1.96@, @1.96@, @1.96@, @1.96@, @1.96@ */
};
unsigned_int16_t LAT_AY_PARITY_TIME_CONST[1] = {100}; /* @0.1@ */
unsigned_int16_t LAT_AY_REQUESTED_FILTER_COEFF[1] = {1298}; /* @0.0396@ */
unsigned_int16_t LAT_AY_SAT_MARGIN_FACTOR[1] = {1280}; /* @1.25@ */ /* 181218 lifting angle based thresholds due to model errors */
unsigned_int16_t LAT_AY_THRESHOLD_DECREMENT[1] = {26}; /* @0.025@ */
unsigned_int16_t LAT_DAMP_EPS_DAMPING[1] = {1024}; /* @1@ */
unsigned_int16_t LAT_DAMP_EPS_TIME_CONST[1] = {205}; /* @0.2@ */
unsigned_int16_t LAT_DAMP_LEVEL_GRAD_OFF[1] = {25600}; /* @200@ */
unsigned_int16_t LAT_DAMP_LEVEL_GRAD_ON[1] = {25600}; /* @200@ */
unsigned_int16_t LAT_DELTA_F_DOT_FILTER_COEFF[1] = {10972}; /* @0.64@ */ 
signed_int16_t LAT_DELTA_F_OFFSET[1] = {0}; /* @0@ */
unsigned_int16_t LAT_DELTA_F_OFFSET_MAX_NVM[1] = {300}; /* @0.3@ */
unsigned_int16_t LAT_DELTA_F_OFFSET_MAX_NVM_STRT[1] = {150}; /* @0.15@ */
unsigned_int16_t LAT_DELTA_F_OFFSET_VARIATION[1] = {0}; /* @0@ */
unsigned_int16_t LAT_DELTA_OFFSET_FILTER_COEFF[1] = {17}; /* @0.001@ *//* M.Kuboyama 180126 Adjust for 10ms cyclic */
unsigned_int16_t LAT_DELTA_OFFSET_FILTER_OMEGA[1] = {0}; /* @0@ */
unsigned_int16_t LAT_DELTA_OFF_FLT_INITIAL_LOOPS[1] = {1000}; /* @1000@ */
unsigned_int16_t LAT_DELTA_OFF_FLT_INITIAL_OMEGA[1] = {0}; /* @0@ */
unsigned_int16_t LAT_DERATING_FACTOR_FILT_COEFF[1] = {3113}; /* @0.19@ *//* M.Kuboyama 180126 Adjust for 10ms cyclic */
unsigned_int16_t LAT_DIRECT_FEEDTHROUGH_KAPPA[1] = {0}; /* @0@ */
unsigned_int16_t LAT_DIRECT_FEEDTHROUGH_TRQ_LDP[1] = {0}; /* @0@ */
signed_int16_t LAT_DIRECT_FEEDTHR_HF_PART_TRQ[1] = {102}; /* @0.1@ */
unsigned_int16_t LAT_DIRECT_FEEDTHR_KAPPA_CTRL[1] = {32768}; /* @1@ */
unsigned_int16_t LAT_DMC_STATUS_FLT_OVERRIDE_CYL[1] = {0}; /* @0@ */
unsigned_int16_t LAT_DMC_STATUS_OVERRIDE_CYCLES[1] = {0}; /* @0@ */ /* M.Kuboyama for eAS-R DMC active start 100% dependant on EPSACT = ture <-5 */
signed_int16_t LAT_EPS_TRQ_CAN_SCALING_FACTOR[1] = {1024}; /* @1@ */
unsigned_int16_t LAT_FORCE_TRQ_SHUT_OFF_TIME[1] = {717}; /* @0.7@ */
unsigned_int16_t LAT_GI_DELTA_CMD_DOT_FLT_COEFF[1] = {3276}; /* @0.1@ */
unsigned_int16_t LAT_GI_YAW_DOT_FILTER_COEFF[1] = {655}; /* @0.02@ */
unsigned_int16_t LAT_GI_DOT_FILTER_COEFF[1] = {3276}; /* @0.1@ */
unsigned_int16_t LAT_GI_MIN_YRC_RESIDL_GRADIENT[1] = {15}; /* @0.015@ */
unsigned_int16_t LAT_GI_MIN_YAW_RATE_GRADIENT[1] = {15}; /* @0.015@ */
unsigned_int16_t LAT_GI_MIN_DELTA_F_CMD_GRADIENT[1] = {204}; /* @0.2@ */
unsigned_int16_t LAT_GI_MIN_LATERAL_ERROR[1] = {51}; /* @0.05@ */
unsigned_int16_t LAT_GI_QUADRNT_DISCHARGE_FACTOR[1] = {51}; /* @0.05@ */
unsigned_int16_t LAT_GI_MIN_LATERAL_ERROR_GRADIENT[1] = {25}; /* @0.025@ */
signed_int16_t LAT_GI_YAW_RATE_OFFSET[1] = {17}; /* @0.0175@ */
unsigned_int16_t LAT_GI_YAW_DEBOUNCE_LOOPS[1] = {20}; /* @20@ */
unsigned_int16_t LAT_GI_YAW_DEBOUNCE_THRS[1] = {15}; /* @15@ */
unsigned_int16_t LAT_GI_FORETIME_LOOPS[1] = {100}; /* @100@ */
unsigned_int16_t LAT_GI_MINIMUM_CONFIDENCE[1] = {2}; /* @2@ */
unsigned_int16_t LAT_GI_DEBOUNCE_FACTOR[1] = {921}; /* @0.9@ */
unsigned_int16_t LAT_JERK_EPS_DAMPING[1] = {1024}; /* @1@ */
unsigned_int16_t LAT_JERK_EPS_TIME_CONST[1] = {205}; /* @0.2@ */
unsigned_int16_t LAT_KAPPA_CTRL_DISCHARGE_GRAD[1] = {12}; /* @0.00036@ *//* 171207 kuboyama changed from{33};  @0.001@ */
unsigned_int16_t LAT_KAPPA_CTRL_DISCHARGE_MN_ERR[1] = {100}; /* @0.002@ */
unsigned_int16_t LAT_KAPPA_CTRL_DISCHARGE_SLOPE[1] = {10000}; /* @10000@ */
unsigned_int16_t LAT_KAPPA_CTRL_LAT_ERROR_SLOPE[1] = {10240}; /* @10@ */
unsigned_int16_t LAT_KAPPA_CTRL_MAX_LATERAL_ERR[1] = {205}; /* @0.2@ */
unsigned_int16_t LAT_KAPPA_DISCHARGE_GRADIENT[1] = {33}; /* @0.001@ */
unsigned_int16_t LAT_KAPPA_DISCHARGE_MIN_ERROR[1] = {1000}; /* @0.02@ */
unsigned_int16_t LAT_KAPPA_DISCHARGE_SLOPE[1] = {10000}; /* @10000@ */
unsigned_int16_t LAT_KAPPA_FILTER_COEFF[1] = {32768}; /* @1@ */ /* M.Kuboyama 180126 Adjust for 10ms cyclic default: {32768} @1@ */ //ToDo TaYo U.S. joint test, Sep.12
unsigned_int16_t LAT_KAPPA_GRADIENT_AES[1] = { 32768 }; /* @1@ */
unsigned_int16_t LAT_KAPPA_LATERAL_ERROR_SLOPE[1] = {10240}; /* @10@ */
unsigned_int16_t LAT_KAPPA_LINZ_ERROR_SLOPE[1] = {10000}; /* @10000@ */
unsigned_int16_t LAT_KAPPA_LINZ_FILTER_MAX_OMEGA[1] = {20480}; /* @20@ */
unsigned_int16_t LAT_KAPPA_LINZ_FILTER_MIN_OMEGA[1] = {512}; /* @0.5@ */
unsigned_int16_t LAT_KAPPA_LINZ_FILT_MAX_ERROR[1] = {10}; /* @0.0002@ */
unsigned_int16_t LAT_KAPPA_LINZ_MAX_OMEGA_MEMSHP[1] = {307}; /* @0.3@ */
unsigned_int16_t LAT_KAPPA_LINZ_WEIGHTING_FACTOR[1] = {500}; /* @500@ */
unsigned_int16_t LAT_KAPPA_MAX_LATERAL_ERROR[1] = {820}; /* @0.8@ */
unsigned_int16_t LAT_KPPA_MIN_OMEGA_X_SCHEDULING[12] = 
{
   0, 10, 20, 30, 40, 50, 60, 80, 100, 120, 180, 250, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t LAT_KPPA_MIN_OMEGA_Y_SCHEDULING[12] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t LAT_LDP_STARTUP_TIME[1] = {512}; /* @0.5@ */
unsigned_int16_t LAT_LDP_COUNTER_PRELOAD[1] = {4000}; /* @4@ */
unsigned_int16_t LAT_LDP_SWITCH_DECREMENT[1] = {10}; /* @0.01@ */
unsigned_int16_t LAT_LDP_KAPPA_GAIN[1] = {1024}; /* @1@ */
unsigned_int16_t LAT_LINZ_ERROR_SLOPE[1] = {10240}; /* @10@ */
unsigned_int16_t LAT_LINZ_FILTER_MAX_ERROR[1] = {102}; /* @0.1@ */
unsigned_int16_t LAT_LINZ_FILTER_MAX_OMEGA[1] = {40960}; /* @40@ */
unsigned_int16_t LAT_LINZ_FILTER_MIN_OMEGA[1] = {4096}; /* @4@ */
unsigned_int16_t LAT_LKA_STARTUP_TIME[1] = {512}; /* @0.5@ */
signed_int16_t LAT_MAX_AY[1] = {3072}; /*[20190805, Enae]RO:1184989 Stefan Feick request to change it to 3072 */ /* @1.96@ */ /* T.Yoshida 190314, max lat accl is changed from 2.2 to 1.96[m/s^2] LTA Req Change */
signed_int16_t LAT_MAX_AY_AES[1] = {3072}; /* @3.0@ */ 
signed_int16_t LAT_MAX_AY_TJA[1] = {2500}; /* @1.95@ */  /* T.Yoshida 190524(RO#1128330),  2007 (2.0[m/s^2]) ==> 1857 (1.813 [m/s^2] = 0.185[G]) for LTA */
unsigned_int16_t LAT_MAX_AY_EXTRAPOLATION_GAIN[1] = {512}; /* @0.5@ */
unsigned_int16_t LAT_MAX_AY_HAND_OFF[1] = {3072}; /*[20190805, Enae]RO:1184989 Stefan Feick request to change it to 3072 */ /* @1.96@ */ /* T.Yoshida 190314, max lat accl is changed from 2.2 to 1.96[m/s^2] LTA Req Change */
unsigned_int16_t LAT_MAX_AY_HAND_OFF_KNEEPOINT[1] = {3072}; /*[20190805, Enae]RO:1184989 Stefan Feick request to change it to 3072 */ /* @1.96@ */ /* T.Yoshida 190314, max lat accl is changed from 2.2 to 1.96[m/s^2] LTA Req Change */
unsigned_int16_t LAT_MAX_KAPPA_CTRL_GRADIENT[1] = {12}; /* @0.00036@ *//* 171207 kuboyama changed from{33};  @0.001@ */
unsigned_int16_t LAT_MAX_KAPPA_CTRL_GRAD_X_SCHED[12] = 
{
   0, 641, 1282, 1923, 2564, 3205, 3846, 5128, 6410, 7692, 11538, 16026, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t LAT_MAX_KAPPA_CTRL_GRAD_Y_SCHED[12] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t LAT_MAX_KAPPA_GRADIENT[1] = {380}; /* @0.0116@ */
unsigned_int16_t LAT_MAX_KAPPA_GRAD_X_SCHEDULING[12] = 
{
   0, 641, 1282, 1923, 2564, 3205, 3846, 5128, 6410, 7692, 11538, 16026, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t LAT_MAX_KAPPA_GRAD_Y_SCHEDULING[12] = 
{
   1024, 1024, 441, 441, 441, 441, 308, 176, 156, 108, 48, 24, 
/* @1@, @1@, @0.43@, @0.43@, @0.43@, @0.43@, @0.3@, @0.17@, @0.15@, @0.1@, @0.05@, @0.02@ */ // (Nobuto) To suppress oscillation during mode transition
};
signed_int16_t LAT_MAX_OUTPUT_TORQUE[1] = {1536}; /* @1.5@ */
unsigned_int16_t LAT_MAX_TORQUE_SELECT[1] = {0}; /* @0@ */
signed_int16_t LAT_MIN_OFFSET_STATE[1] = {1}; /* @1@ */
unsigned_int16_t LAT_MIN_ROAD_CONDITION_LEVEL[1] = {66}; /* @66@ */
unsigned_int16_t LAT_MIN_GRAD_SCALE_ROAD_COND[1] = {97}; /* @10@ */
signed_int16_t LAT_MIN_YAW_RATE_OFFSET_STATE[1] = {1}; /* @1@ */ /* use early VDY yaw rate offset */
unsigned_int16_t LAT_OC_CALIB_CNT_GRAD[1] = {102}; /* @0.1@ */
unsigned_int16_t LAT_AY_COMPENSATION_TIME_CONST[1] = {61}; /* @0.06@ */
unsigned_int16_t LAT_OC_CONST_TRQ_CNT_MAX_LIMIT[1] = {500}; /* @500@ */
unsigned_int16_t LAT_OC_CONST_TRQ_CNT_THRESHOLD[1] = {250}; /* @250@ */
unsigned_int16_t LAT_OC_CONST_TRQ_POS_INCREMENT[1] = {2}; /* @2@ */
unsigned_int16_t LAT_OC_DELTA_F_OFFSET[1] = {0}; /* @0@ */
unsigned_int16_t LAT_OC_DELTA_KI[1] = {0}; /* @0@ */
unsigned_int16_t LAT_OC_DYS_MAF_FILTER_LENGTH[1] = {5}; /* @5@ */
unsigned_int16_t LAT_OC_DYS_PRE_FILTER_LENGTH[1] = {250}; /* @250@ */
unsigned_int16_t LAT_OC_DYS_SETTLING_THRS[1] = {51}; /* @0.05@ */
unsigned_int16_t LAT_OC_FAST_KI[1] = {300}; /* @0.0045@ Loop1_All_20180316_wLDP.par , aligned with base project */
unsigned_int16_t LAT_OC_IMPLAUS_LATERAL_ERROR[1] = {820}; /* @0.8@ */
unsigned_int16_t LAT_OC_KAPPA_CMD_FILTER_COEFF[1] = {3113}; /* @0.19@ *//* M.Kuboyama 180126 Adjust for 10ms cyclic */
unsigned_int16_t LAT_OC_KAPPA_FFWD_FILTER_COEFF[1] = {1639}; /* @0.1@ *//* M.Kuboyama 180126 Adjust for 10ms cyclic */
unsigned_int16_t LAT_OC_KAPPA_MAX_DRIVER_TORQUE[1] = {1024}; /* @1@ */
unsigned_int16_t LAT_OC_KAPPA_MAX_HEADING_ERROR[1] = {256}; /* @1@ */
unsigned_int16_t LAT_OC_KAPPA_MAX_LEARNING_RATE[1] = {51}; /* @0.05@ */
unsigned_int16_t LAT_OC_KAPPA_MIN_HEAD_ERR_QUAL[1] = {1}; /* @1@ */
unsigned_int16_t LAT_OC_KAPPA_MIN_LATENCY[1] = {100}; /* @100@ */ 
signed_int16_t LAT_OC_KI[1] = {220}; /* @0.003@ */ /* StFe increase learning rate to cover VDY offset calib issues */
unsigned_int16_t LAT_OC_MAX_DELTA_DELTA_PSI[1] = {0}; /* @0@ */
unsigned_int16_t LAT_OC_MAX_DELTA_F_DOT[1] = {205}; /* @0.2@ */
unsigned_int16_t LAT_OC_MAX_DELTA_OFFSET[1] = {32}; /* @0.72@ */ /* 171107 KuboyamaM tuning result with Feick-san(171026)*/
unsigned_int16_t LAT_OC_MAX_DELTA_OFFSET_KAPPA[1] = {32}; /* @0.72@ */ /* 171107 KuboyamaM tuning result with Feick-san(171026)*/
unsigned_int16_t LAT_OC_MAX_DELTA_PSI[1] = {328}; /* @0.01@ */
unsigned_int16_t LAT_OC_MAX_DRIVER_TORQUE[1] = {410}; /* @0.4@ */ /* S.Feick 180607 shall be the same as TDF_MIN_STEER_TORQUE_CLASS */
unsigned_int16_t LAT_OC_MAX_KAPPA[1] = {100}; /* @0.002@ */
unsigned_int16_t LAT_OC_MAX_KAPPA_DYS[1] = {22}; /* @0.00056@ */ /* 181218 StFe onl offset calibration at driving straight */
unsigned_int16_t LAT_OC_MAX_LATERAL_ACCEL[1] = {2048}; /* @2@ */
unsigned_int16_t LAT_OC_MAX_LATERAL_ERROR[1] = {512}; /* @0.5@ */
unsigned_int16_t LAT_OC_MAX_OFFSET_RATE[1] = {10}; /* @0.01@ */
unsigned_int16_t LAT_OC_MAX_VELOCITY[1] = {9295}; /* @145@ */
unsigned_int16_t LAT_OC_MIN_LATERAL_ERROR[1] = {154}; /* @0.15@ */
unsigned_int16_t LAT_OC_MINIMUM_LATENCY[1] = {250}; /* @250@ */
unsigned_int16_t LAT_OC_MINIMUM_LATENCY_SHRT[1] = {50}; /* @50@ */
signed_int16_t LAT_OC_MIN_KAPPA_QUALITY[1] = {1}; /* @1@ */
unsigned_int16_t LAT_OC_MIN_OFFSET_STATE[1] = {1}; /* @1@ */
unsigned_int16_t LAT_OC_MIN_VELOCITY[1] = {1923}; /* @30@ */
unsigned_int16_t LAT_OC_MIN_VELOCITY_DYS[1] = {2560}; /* @40@ */
unsigned_int16_t LAT_OC_RLS_CONFIDENCE_THRESHOLD[1] = {99}; /* @0.003@ */
unsigned_int16_t LAT_OC_RLS_CONFID_THRESHOLD_2[1] = {2}; /* @0.00006@ */
unsigned_int16_t LAT_OC_RLS_CONTROLLER_MODE[1] = {7}; /* @7@ */
unsigned_int16_t LAT_OC_RLS_DOWNSAMPLE[1] = {8}; /* @8@ */
unsigned_int16_t LAT_OC_RLS_INPUT_FILTER_COEFF[1] = {1310}; /* @0.04@ */
unsigned_int16_t LAT_OC_RLS_LAMBDA[1] = {32768}; /* @1@ */
unsigned_int16_t LAT_OC_RLS_MAX_ANGLE[1] = {5120}; /* @5@ */
unsigned_int16_t LAT_OC_RLS_MAX_ANGLE_SPEED[1] = {5120}; /* @5@ */
unsigned_int16_t LAT_OC_RLS_MAX_HOLDING_TIME[1] = {1024}; /* @1@ */
unsigned_int16_t LAT_OC_RLS_MAX_TORQUE_DEVIATION[1] = {102}; /* @0.1@ */
unsigned_int16_t LAT_OC_RLS_MIN_DRIVER_TORQUE[1] = {512}; /* @0.5@ */
unsigned_int16_t LAT_OC_RLS_MIN_VEH_VELOCITY[1] = {1422}; /* @1.39@ */
unsigned_int16_t LAT_OC_RLS_MIN_STATE_NVM[1] = {0}; /* @3@ */
unsigned_int16_t LAT_OC_RLS_OFFSET_FRACTION[1] = {512}; /* @0.5@ */
unsigned_int16_t LAT_OC_RLS_OFFSET_INCREMENT[1] = {35}; /* @0.001@ */
unsigned_int16_t LAT_OC_RLS_OFFSET_INIT[1] = {0}; /* @0@ */
unsigned_int16_t LAT_OC_RLS_OFFSET_SATURATION[1] = {1024}; /* @1@ */
unsigned_int16_t LAT_OC_RLS_RELOAD_STATE[1] = {10}; /* @10@ */
unsigned_int16_t LAT_OC_RLS_RESET[1] = {1}; /* @1@ */
unsigned_int16_t LAT_OC_RLS_STIFFNESS_CONST[1] = {1536}; /* @1.5@ */
unsigned_int16_t LAT_OC_RLS_STIFFNESS_INIT[1] = {1536}; /* @1.5@ */
unsigned_int16_t LAT_OC_RLS_VARIANCE_OFFSET_INIT[1] = {656}; /* @0.02@ */
unsigned_int16_t LAT_OC_RLS_VAR_STIFFNESS_INIT[1] = {328}; /* @0.01@ */
unsigned_int16_t LAT_OC_RLS_WEIGHTING_POWER[1] = {4}; /* @4@ */
unsigned_int16_t LAT_OC_SIGN_DELTA_YS_WEIGHTING[1] = {0}; /* @0@ */
unsigned_int16_t LAT_OC_SMALL_DRIVER_TORQUE[1] = {205}; /* @0.2@ */
unsigned_int16_t LAT_OC_TOLERATED_DELTA_YS[1] = {51}; /* @0.05@ */
signed_int16_t LAT_OFFSET_INCREMENT_PER_LOOP[1] = {5}; /* @0.00013@ */ 
signed_int16_t LAT_OFFSET_OUT_INCR_PER_LOOP[1] = {5}; /* @0.00013@ */  /* max 0.11 deg/s SWA rate */
signed_int16_t LAT_OFFSET_INC_PER_LOOP_SLOW[1] = {5}; /* @0.000078431@ */
signed_int16_t LAT_OFFSET_INC_PER_LOOP_TURN_ON[1] = {79}; /* @0.0012@ */
signed_int16_t LAT_OFFSET_MAX[1] = {0}; /* @0@ */
signed_int16_t LAT_OFFSET_MAX_CLM_TRQ[1] = {1024}; /* @1@ */
signed_int16_t LAT_OFFSET_MAX_STEER_ANGLE[1] = {385}; /* @0.5882@ */
signed_int16_t LAT_OUT_DIRECT_FEEDTHROUGH_TRQ[1] = {0}; /* @0@ */
unsigned_int16_t LAT_PITCH_FILTER_COEFF[1] = {655}; /* @0.02@ */
unsigned_int16_t LAT_PITCH_MAX_ACCURACY[1] = {10}; /* @10@ */
unsigned_int16_t LAT_PITCH_THRESHOLD[1] = {15}; /* @0.015@ */
unsigned_int16_t LAT_R_FACTOR_LEVEL_DECREMENT[1] = {10}; /* @0.01@ */
unsigned_int16_t LAT_RATE_CONTROL_D_FILTER_COEFF[1] = {3277}; /* @0.1@ */
unsigned_int16_t LAT_RATE_CONTROL_MAX_PT1_PART[1] = {2048}; /* @2@ */
unsigned_int16_t LAT_RATE_CONTROL_MAX_P_PART[1] = {3072}; /* @3@ */
unsigned_int16_t LAT_RATE_CONTROL_MIN_ERROR[1] = {10240}; /* @10@ */
unsigned_int16_t LAT_RATE_CTRL_PT1_FILTER_COEFF[1] = {809}; /* @0.049375@ */
unsigned_int16_t LAT_RATE_LIMIT_CONTROL_KD[1] = {0}; /* @0@ */
unsigned_int16_t LAT_RATE_LIMIT_CONTROL_KP[1] = {0}; /* @0.2@ 205 default */
signed_int16_t LAT_RATE_LIMIT_CONTROL_PT1_KP[1] = {0}; /* @4@ 4096 default */
unsigned_int16_t LAT_RATE_PT1_FILTER_MAX_COEFF[1] = {809}; /* @0.049375@ */
unsigned_int16_t LAT_RATE_YS_KP_PT1_X_SCHEDULING[12] = 
{
   0, 640, 1280, 1920, 2560, 3200, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t LAT_RATE_YS_KP_PT1_Y_SCHEDULING[12] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
signed_int16_t LAT_RATE_YS_KP_X_SCHEDULING[12] = 
{
   0, 640, 1280, 1920, 2560, 3200, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
signed_int16_t LAT_RATE_YS_KP_Y_SCHEDULING[12] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t LAT_REF_CONTROL_KD[1] = {10}; /* @0.02@ *//* 171113 KuboyamaM tuning result with Feick-san(171026)*/
unsigned_int16_t LAT_REF_CONTROL_K_PT1[1] = {100}; /* @0.2@ *//* 171113 KuboyamaM tuning result with Feick-san(171026)*/
unsigned_int16_t LAT_REF_CTRL_DELT_DOT_FLT_COEFF[1] = {6226}; /* @0.19@ */
unsigned_int16_t LAT_REF_CTRL_PARITY_COEFF[1] = {1474}; /* @0.2@ */ 
unsigned_int16_t LAT_REF_PT1_CONTROL_COEFF[1] = {32768}; /* @1@ */
unsigned_int16_t LAT_SATURATION_CLASS_THR[1] = {4096}; /* @1@ */
unsigned_int16_t LAT_SELECT_INPUT_SOURCE[1] = {1}; /* @1@ */
unsigned_int16_t LAT_STATUS_FIRST_RUN_TIME[1] = {5120}; /* @5@ */
unsigned_int16_t LAT_STIFFNESS_FALLING_DECREMENT[1] = {1024}; /* @1@ */
unsigned_int16_t LAT_SUPPORT_ARW_FACTOR_1[1] = {0}; /* @0@ */
unsigned_int16_t LAT_SUPPORT_ARW_FACTOR_2[1] = {0}; /* @0@ */
unsigned_int16_t LAT_SUPPORT_ARW_FACTOR_3[1] = {0}; /* @0@ */
unsigned_int16_t LAT_SUPPORT_AY_FILTER_COEFF[1] = {3276}; /* @0.1@ */
unsigned_int16_t LAT_SUPPORT_DISCHARGE_OMEGA[1] = {30720}; /* @30@ */
unsigned_int16_t LAT_SUPPORT_ENHANCEMENT_FACTOR[1] = {1025}; /* @1.01@ */
unsigned_int16_t LAT_SUPPORT_FACTOR_X_SCHEDUL[12] = 
{
   0, 640, 1280, 1920, 2560, 3200, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t LAT_SUPPORT_FACTOR_Y_SCHEDUL[12] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t LAT_SUPPORT_FEEDBACK_FACTOR_1[1] = {102}; /* @0.1@ */
unsigned_int16_t LAT_SUPPORT_FEEDBACK_FACTOR_2[1] = {1024}; /* @1@ */
unsigned_int16_t LAT_SUPPORT_FEEDBACK_FACTOR_HF[1] = {512}; /* @0.5@ */
unsigned_int16_t LAT_SUPPORT_FILTER_COEFF[1] = {3276}; /* @0.1@ */
unsigned_int16_t LAT_SUPPORT_MEMSHP_FILTER_COEFF[1] = {3276}; /* @0.1@ */
unsigned_int16_t LAT_SUPPORT_MIN_DRIVER_TORQUE[1] = {10240}; /* @10@ */
unsigned_int16_t LAT_SUPPORT_OMEGA_1[1] = {10240}; /* @10@ */
unsigned_int16_t LAT_SUPPORT_OMEGA_2[1] = {51200}; /* @50@ */
unsigned_int16_t LAT_SUPPORT_OMEGA_HF[1] = {0}; /* @0@ */
unsigned_int16_t LAT_SUPPORT_TORQUE_GAIN[1] = {600}; /* @1.2@ */
unsigned_int16_t LAT_SUPPORT_TORQUE_THRESHOLD[1] = {614}; /* @0.6@ */
signed_int16_t LAT_SUPPORT_TOR_X_SCHEDULING[4] = 
{
   0, 1024, 2048, 10240, 
/* @0@, @1@, @2@, @10@ */
};
signed_int16_t LAT_SUPPORT_TOR_Y_SCHEDULING[4] = 
{
   0, 0, 0, 0, 
/* @0@, @0@, @0@, @0@ */
};
unsigned_int16_t LAT_SWITCH_FALLING_RATE[1] = {25600}; /* @100@ */
unsigned_int16_t LAT_SWITCH_FALLING_RATE_2[1] = {2560}; /* @10@ */
unsigned_int16_t LAT_SWITCH_OFF_TIME[1] = {3072}; /* @3@ */
unsigned_int16_t LAT_SWITCH_RISING_RATE[1] = {25600}; /* @100@ */
unsigned_int16_t LAT_SWITCH_RISING_RATE_2[1] = {2560}; /* @10@ */
unsigned_int16_t LAT_SWITCH_RISING_RATE_INITIAL[1] = {256}; /* @1@ */
unsigned_int16_t LAT_TORQUE_GRADIENT[1] = {30}; /* @0.9375@ */
unsigned_int16_t LAT_YAW_RATE_DOT_FILTER_COEFF[1] = {6506}; /* @0.4@ */
unsigned_int16_t LAT_YAW_RATE_FILTER_COEFF[1] = {32768}; /* @1@ */ 
unsigned_int16_t LCO_CURV_DOT_FILTER_FALL_COEFF[1] = {492}; /* @0.015@ */
unsigned_int16_t LCO_CURV_DOT_FILTER_RISNG_COEFF[1] = {32768}; /* @1@ */
unsigned_int16_t LCO_CURV_DOT_PRELOAD_ENH_FACTOR[1] = {0}; /* @0@ */
unsigned_int16_t LCO_ERROR_FILTER_FALLING_COEFF[1] = {493}; /* @0.03@ */
unsigned_int16_t LCO_ERROR_FILTER_RISING_COEFF[1] = {32768}; /* @1@ */
unsigned_int16_t LCO_FILTER_FALLING_COEFF[1] = {493}; /* @0.03@ */
unsigned_int16_t LCO_FILTER_RISING_COEFF[1] = {32768}; /* @1@ */
unsigned_int16_t LCO_MIN_CONTROL_ERROR[1] = {82}; /* @0.08@ */
unsigned_int16_t LCO_MIN_CONTROL_ERROR_SLOPE[1] = {10240}; /* @10@ */
unsigned_int16_t LCO_MIN_CURVATURE_COMMAND[1] = {10}; /* @0.0002@ */
unsigned_int16_t LCO_MIN_CURVATURE_DOT[1] = {500}; /* @0.01@ */
unsigned_int16_t LCO_MIN_CURVATURE_DOT_SLOPE[1] = {500}; /* @500@ */
unsigned_int16_t LCO_MIN_CURVATURE_SLOPE[1] = {1000}; /* @1000@ */
unsigned_int16_t LCO_MIN_ERR_PRELOAD_ENH_FACTOR[1] = {2048}; /* @2@ */
unsigned_int16_t LCO_MIN_LATERAL_ERROR[1] = {205}; /* @0.2@ */
unsigned_int16_t LCO_MIN_LATERAL_ERROR_SLOPE[1] = {10240}; /* @10@ */
unsigned_int16_t LCO_MIN_LOAD_COMP_FACTOR[1] = {0}; /* @0@ */
unsigned_int16_t LCO_PRELOAD_ENHANCEMENT_FACTOR[1] = {2048}; /* @2@ */
unsigned_int16_t LDC_COMP_KD_FACTOR[1] = {20}; /* @0.005@ */
unsigned_int16_t LDC_COMP_KP_FACTOR[1] = {51}; /* @0.05@ */
unsigned_int16_t LDC_CONTROLLER_MODE[1] = {0}; /* @0@ */
unsigned_int16_t LDC_KI[1] = {1024}; /* @0.25@ */
unsigned_int16_t LDC_KI_FB[1] = {205}; /* @0.05@ */
unsigned_int16_t LDC_KP_FACTOR[1] = {307}; /* @0.075@ */
unsigned_int16_t LKA_MAX_ALIGN_TORQUE[1] = {3277}; /* @3.2@ */
unsigned_int16_t MOT_DIRECT_FEEDTHROUGH_TRQ[1] = {0}; /* @0@ */
unsigned_int16_t MOT_MEAN_VALUE_FILTER_COEFF[1] = {0}; /* @0@ */
unsigned_int16_t MOT_MODULATION_DUTY_CYCLE[1] = {1024}; /* @1@ */
unsigned_int16_t MOT_OUT_DIRECT_FEEDTHROUGH_TRQ[1] = {0}; /* @0@ */
signed_int16_t MOT_SIGNAL_GEN_AMPLITUDE[1] = {512}; /* @0.5@ */
unsigned_int16_t MOT_SIGNAL_GEN_FREQUENCY_BASE[1] = {15360}; /* @15@ */
unsigned_int16_t MOT_SIGNAL_GEN_FREQ_MODULATION[1] = {512}; /* @0.5@ */
unsigned_int16_t MOT_TORQUE_DUTY_CYCLE[1] = {410}; /* @0.4@ */
unsigned_int16_t MOT_TORQUE_GRADIENT[1] = {40960}; /* @40@ */
unsigned_int16_t ODM_ODOMETRY_MODE[1] = {3}; /* @3@ */
signed_int16_t PRF_OMEGA[1] = {5120}; /* @10@ */ /* disable high pass filter due to higher dynamic of new KMC */
signed_int16_t PRF_OMEGA_2[1] = {10240}; /* @20@ */
unsigned_int16_t PRF_T_NOM[1] = {102}; /* @0.1@ */
signed_int16_t PRF_T_NOM_2[1] = {51}; /* @0.05@ */
signed_int16_t SAC_ACCEPTED_CONTROL_ERROR[1] = {0}; /* @0@ */
unsigned_int16_t SAC_ACCURACY_FEEDBACK_TRANSF[1] = {10240}; /* @10@ */
unsigned_int16_t SAC_ACCURACY_OVERRIDE[1] = {100}; /* @100@ */
signed_int16_t SAC_ACTIVATION_OVERRIDE[1] = {0}; /* @0@ */
unsigned_int16_t SAC_ANGLERATE_CTRL_SAT_KP[1] = {0}; /* @0 */ /*StFe 181127 prevent cmd spikes from loading angle rate limiter */
unsigned_int16_t SAC_ANGLE_CMD_LIMIT_MARGIN_FACT[1] = {1280}; /* @1.25@ */
unsigned_int16_t SAC_ANGLE_CMD_LIMIT_OUT_MN_FACT[1] = {1024}; /* @1.0@ */
unsigned_int16_t SAC_ANGLE_FADING_MODE[1] = {0}; /* @0@ */
unsigned_int16_t SAC_ANGLE_FADING_TIME[1] = {128}; /* @0.125@ */ 
unsigned_int16_t SAC_ANGLE_FADING_TIME_BUMP[1] = {1536}; /* @1.5@ */
unsigned_int16_t SAC_ANGLE_FADING_TIME_DYS_GRAD[1] = {128}; /* @0.15@ */
unsigned_int16_t SAC_ANGLE_FADING_TIME_MIN[1] = {128}; /* @0.25@ */
unsigned_int16_t SAC_ANGLE_FADING_TIME_MODE_CHG[1] = {128}; /* @0.5@ */ /* StFe 190131: shorter fading time for TJA mode change for improved curve performance */
signed_int16_t SAC_BACKLASH_ANGLE[1] = {0}; /* @0@ */
unsigned_int16_t SAC_BACKLASH_FILTER_COEFF[1] = {32768}; /* @0.1@ */
unsigned_int16_t SAC_BACKLASH_OMEGA[1] = {10240}; /* @10@ */
signed_int16_t SAC_BACKLASH_TORQUE[1] = {0}; /* @0@ */
unsigned_int16_t SAC_BACKLASH_T_NOM[1] = {102}; /* @0.1@ */
unsigned_int16_t SAC_BITMASK_CLOSE_OBJECT[1] = {3840}; /* @3840, F00@ */
unsigned_int16_t SAC_BITMASK_RIGHT_OBJECT[1] = {160}; /* @160, A0@ */
unsigned_int16_t SAC_BITMASK_LEFT_OBJECT[1] = {80}; /* @80, 50@ */
unsigned_int16_t SAC_CMD_BOOST_REQUEST_FACTOR[1] = {0}; /* @0@ */
signed_int16_t SAC_CMD_ENHANCEMENT_GAIN[1] = {0}; /* @0@ */
unsigned_int16_t SAC_CMD_FEEDFORWARD_GAIN[1] = {0}; /* @0@ */
unsigned_int16_t SAC_CMD_OFFSET_GAIN[1] = {15360}; /* @15@ */
signed_int16_t SAC_COMPENSATION_FACTOR[1] = {0}; /* @0@ */
signed_int16_t SAC_COMPENSATION_FILTER_SELECT[1] = {1}; /* @1@ */
unsigned_int16_t SAC_COMP_FACTOR_X_SCHEDULING[13] = 
{
   0, 320, 640, 1280, 1920, 2560, 3200, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @5@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t SAC_COMP_FACTOR_Y_SCHEDULING[13] = 
{ /* StFe 181031 constant compensation as the default, accuracy scheduling as an option */
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t SAC_CONTROLLER_MODE_1[1] = {3657}; /* @1609@ */ /* M.Kuboyama 171128 disable friction comp from 585 */
unsigned_int16_t SAC_CONTROLLER_MODE_2[1] = {64}; /* @64@ */
unsigned_int16_t SAC_CONTROL_ERR_THRS[1] = {102}; /* @0.1@ */
unsigned_int16_t SAC_CTRL_ERROR_RED_FILTER_COEFF[1] = {1932}; /* @0.12@ */
unsigned_int16_t SAC_CTRL_ERROR_RED_HF_SCALE[1] = {1024}; /* @1@ */
unsigned_int16_t SAC_CUT_PRELOAD_ANGLE[1] = {66}; /* @0.065@ */ 
unsigned_int16_t SAC_DC_GAIN_ACCEPTED_CTRL_ERROR[1] = {31}; /* @0.03@ */
unsigned_int16_t SAC_DC_GAIN_CURVATURE_SLOPE[1] = {500}; /* @500@ */
signed_int16_t SAC_DC_GAIN_ERROR_SLOPE[1] = {5}; /* @5@ */
unsigned_int16_t SAC_DC_GAIN_FACTOR_HIGH_CURV[1] = {1024}; /* @1@ */
unsigned_int16_t SAC_DC_GAIN_MIN_CURVATURE[1] = {10}; /* @0.0002@ */
unsigned_int16_t SAC_DELTA_CMD_FFWD_X_SCHEDULING[12] = 
{
   0, 641, 1282, 1923, 2564, 3205, 3846, 5128, 6410, 7692, 11538, 16026, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t SAC_DELTA_CMD_FFWD_Y_SCHEDULING[12] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t SAC_DELTA_F_CMD_FEEDFWD_GAIN[1] = {1024}; /* @1@ */
signed_int16_t SAC_DELTA_F_CMD_FILTER_OMEGA[1] = {6400}; /* @25@ */
unsigned_int16_t SAC_DELTA_F_CMD_GRADIENT[1] = {1024}; /* @1@ */
unsigned_int16_t SAC_DELTA_F_CMD_GRAD_AES[1] = {8192}; /* @30@ */
unsigned_int16_t SAC_DELTA_F_CMD_GRAD_BARRIER[1] = {2048};/* @2.00@ */ /* M.Kuboyama 180907 400BCV1 gain on SWA grad 716->1024 */ 
unsigned_int16_t SAC_DELTA_F_CMD_GRAD_FADING[1] = {207}; /* @0.202@ */ /* M.Kuboyama 180331 3deg/s on steering angle grad during trajectory re-plan & TJA Lat Mode Transition */
unsigned_int16_t SAC_DELTA_F_CMD_GRAD_RAMPOUT[1] = {2659}; /* @2.597@ */ /* StFe ramp out gradient 40 deg/s */
unsigned_int16_t SAC_DELTA_F_CMD_GRAD_STRAIGHT[1] = {1024}; /* @0.195@ */
unsigned_int16_t SAC_DELTA_F_CMD_GRD_AES_CR_X_SC[11] = 
{
   0, 640, 1280, 1920, 2560, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t SAC_DELTA_F_CMD_GRD_AES_CR_Y_SC[11] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t SAC_DELTA_F_CMD_INITIAL_GRAD[1] = {345}; /* @0.334@ */ /* M.Kuboyama 180330 5deg/s on steering angle grad during LCF active start */
unsigned_int16_t SAC_DELTA_F_CMD_MIN_GRAD[1] = {500}; /* @500@ */ /* M.Kuboyama 180914 0deg/s on minimum steering angle grad by LTA output gain ( when output gain = 0%, 0deg/s(this parameter) is used!! */
unsigned_int16_t SAC_DELTA_F_COUNTER_STEER_GRAD[1] = {5000}; /* @5.0@ */ /* 77 deg/s max in case of counter steering */
signed_int16_t SAC_DELTA_F_DOT2_FILTER_COEFF[1] = {3125}; /* @0.19@ */
unsigned_int16_t SAC_DELTA_F_LATENCY[1] = {46}; /* @0.045@ */
unsigned_int16_t SAC_DELTA_GRADIENT_X_SCHEDULING[12] = 
{
   0, 640, 1280, 2560, 3840, 5120, 6400, 7680, 8960, 10240, 11520, 13440, 
/* @0@, @10@, @20@, @40@, @60@, @80@, @100@, @120@, @140@, @160@, @180@, @210@ */
};
unsigned_int16_t SAC_DELTA_GRADIENT_LCF_Y_SCHED[12] = 
{
   1492, 1492, 769, 769, 769, 500, 500, 500, 500, 500, 500, 500, 
/* @1.454@, @1.454@, @0.750@, @0.750@, @0.50@, @0.5@, @0.5@, @0.5@, @0.5@, @0.5@, @0.5@, @0.5@ */
};
unsigned_int16_t SAC_DELTA_GRADIENT_OBF_Y_SCHED[12] = 
{
   1492, 1492, 769, 769, 500, 500, 500, 500, 500, 500, 500, 500,
/* @1.454@, @1.454@, @0.750@, @0.750@, @0.50@, @0.5@, @0.5@, @0.5@, @0.5@, @0.5@, @0.5@, @0.5@ */
};
unsigned_int16_t SAC_DELTA_GRADIENT_Y_SCHEDULING[12] = 
{
   1492, 1492, 1024, 1024, 1024, 615, 512, 512, 512, 512, 512, 512,
/* @1.454@, @1.454@, @0.750@, @0.750@, @0.50@, @0.5@, @0.5@, @0.5@, @0.5@, @0.5@, @0.5@, @0.5@ */
};
unsigned_int16_t SAC_DELTA_GRAD_BARRIER_X_SCHED[12] = 
{
   0, 640, 1280, 2560, 3840, 5120, 6400, 7680, 8960, 10240, 11520, 13440, 
/* @0@, @10@, @20@, @40@, @60@, @80@, @100@, @120@, @140@, @160@, @180@, @210@ */
};
unsigned_int16_t SAC_DELTA_GRAD_BARRIER_Y_SCHED[12] = 
{
   1492, 1492, 1350, 1350, 1350, 1350, 1350, 1350, 1350, 1350, 1350, 1350, 
/* @1.454@, @1.454@, @1.315@, @1.315@, @1.315@, @1.315@, @1.315@, @1.315@, @1.315@, @1.315@, @1.315@, @1.315@ */
};
unsigned_int16_t SAC_DELTA_MAX_INTEGRAL[1] = {5120}; /* @5@ */
unsigned_int16_t SAC_DELTA_PSI_DOT_FACTOR[1] = {0}; /* @0@ */
signed_int16_t SAC_DELTA_PSI_DOT_MAF_LENGTH[1] = {0}; /* @0@ */
signed_int16_t SAC_DELTA_PSI_PT1_FILTER_COEFF[1] = {3277}; /* @0.1@ */
unsigned_int16_t SAC_DERATING_OVERRIDE[1] = {100}; /* @100@ */
unsigned_int16_t SAC_DIFFERENTIAL_2_PART[1] = {0}; /* @0@ */
unsigned_int16_t SAC_DIFFERENTIAL_PART[1] = {0}; /* @0@ */
unsigned_int16_t SAC_DYNAMIC_CORRECTION_FACTOR[1] = {900}; /* @0.73@ */ /* 171107 KuboyamaM Angle req = Angle_req * 0.73 + actual_angle*0.27 with Feick-san(171026)*/
unsigned_int16_t SAC_DYNAMIC_CORR_FACTOR_AES[1] = {1024}; /* @1@ */
unsigned_int16_t SAC_DYNAMIC_CORR_FACTOR_OBF[1] = {900}; /* @0.73@ */ /* (190315 NoYo) sync with base correction factor */
unsigned_int16_t SAC_DYNAMIC_CORR_MIN_FACTOR[1] = {900}; /* @1@ */
unsigned_int16_t SAC_DYNAMIC_CORR_FACTOR_GRDSCAL[1] = {500}; /* @0.5@ */
unsigned_int16_t SAC_DYNAMIC_CORR_MIN_X_SCHEDUL[12] = 
{
   0, 641, 1282, 1923, 2564, 3205, 3846, 5128, 6410, 7692, 11538, 16026, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t SAC_DYNAMIC_CORR_MIN_Y_SCHEDUL[12] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t SAC_DYNAMIC_CORR_OBF_Y_SCHEDUL[12] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t SAC_DYN_CORR_CTRL_ERROR_SLOPE[1] = {1280}; /* @1.25@ */ /* scaled with 16 in code */ 
unsigned_int16_t SAC_DYN_CORR_FACTOR_DECREMENT[1] = {10}; /* @0.01@ */
unsigned_int16_t SAC_EPS_NO_CONTROL_ERROR[1] = {66}; /* @0.065@ */
unsigned_int16_t SAC_ERROR_FILTER_OMEGA[1] = {10240}; /* @10@ */
unsigned_int16_t SAC_ERROR_FILTER_OMEGA_2[1] = {10240}; /* @10@ */
signed_int16_t SAC_FAD_FLT_FALLNG_LW_DYN_COEFF[1] = {524}; /* @0.015936@ */
signed_int16_t SAC_FAD_FLT_RISING_LW_DYN_COEFF[1] = {2000}; /* @0.0625@ */
unsigned_int16_t SAC_FEEDFORWARD_FILTER_COEFF[1] = {32765}; /* @1@ */
unsigned_int16_t SAC_FEEDFWD_FACTOR_X_SCHEDULING[13] = 
{
   0, 640, 1280, 1920, 2560, 3200, 3840, 5120, 6400, 7680, 8960, 10240, 11520, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @140@, @160@, @180@ */
};
unsigned_int16_t SAC_FEEDFWD_FACTOR_Y_SCHEDULING[13] = 
{
   5366, 5366, 5366, 5366, 5366, 5714, 6072, 8038, 13763, 15012, 17869, 17869, 17869, 
/* @5.24@, @5.24@, @5.24@, @5.24@, @5.24@, @5.58@, @5.93@, @7.85@, @13.44@, @14.66@, @17.45@, @17.45@, @17.45@ */
};
unsigned_int16_t SAC_FEEDTHR_INCREMENT_PER_LOOP[1] = {30}; /* @0.03@ */
signed_int16_t SAC_FFWD_DIFF_FILTER_OMEGA[1] = {1024}; /* @1@ */
unsigned_int16_t SAC_FFWD_SCALE_POS_ANGLE_CMD[1] = {1024}; /* @1@ */
unsigned_int16_t SAC_FFWD_SCALING_END[1] = {768}; /* @0.75@ */
unsigned_int16_t SAC_FFWD_SCALING_START[1] = {384}; /* @0.375@ */
signed_int16_t SAC_FILTER_OMEGA[1] = {1024}; /* @4@ */
signed_int16_t SAC_FILTER_TAU[1] = {256}; /* @0.25@ */
unsigned_int16_t SAC_FRC_COMP_B1_FACTOR[1] = {20}; /* @0.02@ */
unsigned_int16_t SAC_FRC_COMP_OMEGA[1] = {51200}; /* @50@ */
unsigned_int16_t SAC_FRC_STATIC_FRICTION_TORQUE[1] = {1024}; /* @1@ */
unsigned_int16_t SAC_FRC_TORQUE_CORR_FACTOR[1] = {0}; /* @0@ */
unsigned_int16_t SAC_FRICTION_COMP_ACTIV_SOURCE[1] = {2}; /* @2@ */
unsigned_int16_t SAC_FRICTION_COMP_ERROR_GAIN[1] = {32000}; /* @1000@ */
unsigned_int16_t SAC_FRICTION_COMP_LINEAR_SLOPE[1] = {1024}; /* @1@ */
signed_int16_t SAC_FRICTION_COMP_SCALING_END[1] = {102}; /* @0.1@ */ /* preparation for torque 2 angle functions */
signed_int16_t SAC_FRICTION_COMP_SCALING_START[1] = {0}; /* @0@ */
unsigned_int16_t SAC_FRICTION_COMP_TORQUE[1] = {50}; /* @0.2929@ */
signed_int16_t SAC_FRICTION_COMP_TORQUE_CW[1] = {50}; /* @0.2929@ */
unsigned_int16_t SAC_FRICTION_COMP_X_SCHEDULING[12] = 
{
   0, 641, 1282, 1923, 2564, 3205, 3846, 5128, 6410, 7692, 11538, 16026, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t SAC_FRICTION_COMP_Y_SCHEDULING[12] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t SAC_FRICTION_CONTROL_ERROR_GAIN[1] = {32000}; /* @1000@ */
unsigned_int16_t SAC_GRAD_SCALE_OBJ_CLOSE[1] = {10}; /* @10@ */
unsigned_int16_t SAC_GRAD_SCALE_SIDE_OBJ[1] = {20};  /* @20@ */
unsigned_int16_t SAC_JERK_ANGLE_SAT_Y_SCHEDULING[12] = 
{
     1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1.0@, @1.0@, @1.0@, @1.0@, @1.0@, @1.0@, @1.0@, @1.0@, @1.0@, @1.0@, @1.0@, @1.0@ */
};
unsigned_int16_t SAC_JERK_GRADIENT[1] = {630}; /* @0.615@ */
unsigned_int16_t SAC_JERK_GRADIENT_Y_SCHEDULING[12] = 
{
   34816, 34816, 8704, 3869, 2176, 1392, 967, 543, 348, 241, 107, 55, 
/* @34@, @34@,  @8.5@, @3.78@, @2.125@, @1.36@, @0.944@, @0.5312@, @0.34@, @0.2361@, @0.1049@, @0.0544@ */
};
unsigned_int16_t SAC_JERK_INVERSE_EG[1] = {2264}; /* @2.2114@ */
unsigned_int16_t SAC_JERK_INVERSE_EG_Y_SCHEDULING[12] = 
{
     0, 40, 163, 368, 655, 1024, 1474, 2621, 4096, 5898, 13271, 25600,
/* @0@, @0.04@, @0.16@, @0.36@, @0.64@, @1.0@, @1.44@, @2.56@, @4.0@, @5.76@, @12.96@, @25@ */
};
unsigned_int16_t SAC_JERK_LIMIT_ENHANCE_AES[1] = {10240}; /* @10@ */ 
unsigned_int16_t SAC_JERK_LIMIT_ENHANCE_DP[1] = {10240}; /* @10@ */
unsigned_int16_t SAC_JERK_MAX[1] = {1360}; /* @1.36@ */
unsigned_int16_t SAC_JERK_PREDICTION_TIME[1] = {0}; /* @0@ */
unsigned_int16_t SAC_JERK_TRQ_DERATNG_AES_X_SCHD[5]= 
{
	0, 717, 1024, 1669, 1843,
/* @0.0@, @0.7@, @1.0@, @1.6@, @1.8@ */
};
unsigned_int16_t SAC_JERK_TORQUE_DERATING_X_SCHD[5]= 
{
	0, 717, 1024, 1669, 1843,
/* @0.0@, @0.7@, @1.0@, @1.6@, @1.8@ */
};
unsigned_int16_t SAC_JERK_TORQ_DERATG_LDP_X_SCHD[5]= 
{
	0, 717, 1024, 1669, 1843,
/* @0.0@, @0.7@, @1.0@, @1.6@, @1.8@ */
};
unsigned_int16_t SAC_JERK_TORQUE_DERATING_Y_AES[5]= 
{
	1024,   1024,   1024,   1024,     1024,
/* @0.1948@, @0.1948@, @0.1948@, @0.0974@, @0.0@ */
};
unsigned_int16_t SAC_JERK_TORQUE_DERATING_Y_SCHD[5]= 
{
	19900,   19900,   19900,   19900,  19900,
/* @1.948@, @1.948@, @1.948@, @1.948@, @1.948@ */
};
unsigned_int16_t SAC_JERK_TORQUE_DERATING_Y_LDP[5]= 
{
	19900,   19900,   19900,   19900,     19900,
/* @0.1948@, @0.1948@, @0.1948@, @0.0974@, @0.0@ */
};
unsigned_int16_t SAC_JERK_WEIGHTING[1] = {0}; /* @0@ */
unsigned_int16_t SAC_KD[1] = {0}; /* @0.0432@ */ /* keep LDP eas2.1 for Ang 2 Trq*/
unsigned_int16_t SAC_KD_FADING_FACTOR[1] = {0}; /* @0@ */ /* keep LDP eas2.1 for Ang 2 Trq*/
signed_int16_t SAC_KD_MAX_FADING_FACTOR[1] = {0}; /* @0@ */
signed_int16_t SAC_KD_OBS[1] = {0}; /* @0@ */
unsigned_int16_t SAC_KD_X_SCHEDULING[12] = 
{
   0, 640, 1280, 1920, 2560, 3200, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t SAC_KD_Y_SCHEDULING[12] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t SAC_KI[1] = {0}; /* @0.0@ */
unsigned_int16_t SAC_KI_BOOST_FACTOR[1] = {5120}; /* @5@ */
unsigned_int16_t SAC_KI_FB[1] = {0}; /* @0@ */
unsigned_int16_t SAC_KI_FB_FACTOR_SCALING_END[1] = {768}; /* @0.75@ */
unsigned_int16_t SAC_KI_FB_MAX[1] = {10240}; /* @10@ */
unsigned_int16_t SAC_KI_FB_X_SCHEDULING[11] = 
{
   0, 640, 1280, 1920, 2560, 3200, 3840, 5120, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @120@, @180@, @250@ */
};
unsigned_int16_t SAC_KI_FB_Y_SCHEDULING[11] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t SAC_KI_X_SCHEDULING[13] = 
{
   0, 384, 640, 1280, 1920, 2560, 3200, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @6@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t SAC_KI_Y_SCHEDULING[13] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @8@, @6@, @4@, @4@, @4@, @4@, @4@, @4.8@, @5.6@, @5.8@, @5.8@, @5.8@, @5.8@ */
};
unsigned_int16_t SAC_KMC_LOOP_GAIN[1] = {1024}; /* @1@ */
unsigned_int16_t SAC_KP[1] = {0}; /* @0@ */
unsigned_int16_t SAC_KP_DC_GAIN_FACTOR[1] = {1024}; /* @1@ */
unsigned_int16_t SAC_KP_DELTA_X_SCHEDULING[6] = 
{
   0, 64, 192, 384, 555, 768, 
/* @0@, @1@, @3@, @6@, @8.6667@, @12@ */
};
signed_int16_t SAC_KP_DELTA_Y_SCHEDULING[6] = 
{
   1024, 1024, 853, 597, 427, 427, 
/* @1@, @1@, @0.8333@, @0.5833@, @0.4167@, @0.4167@ */
};
unsigned_int16_t SAC_KP_DERATING_SLOPE[1] = {20000}; /* @20@ */
signed_int16_t SAC_KP_FADING_FLT_FALLING_COEFF[1] = {524}; /* @0.0975@ *//* M.Kuboyama 180126 10ms cyclic; aligned from base project*/
signed_int16_t SAC_KP_FADING_FLT_RISING_COEFF[1] = {32765}; /* @1@ */
unsigned_int16_t SAC_KP_LDP[1] = {0}; /* @0@ */
unsigned_int16_t SAC_KP_X_SCHEDULING[12] = 
{
   0, 640, 1280, 1920, 2560, 3200, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t SAC_KP_Y_SCHEDULING[12] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t SAC_KX[1] = {0}; /* @0@ */
unsigned_int16_t SAC_KX_X_SCHEDULING[13] = 
{
   0, 384, 640, 1280, 1920, 2560, 3200, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @6@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t SAC_KX_Y_SCHEDULING[13] = 
{
   1024, 1024, 512, 512, 461, 410, 410, 410, 410, 410, 410, 410, 410, 
/* @1@, @1@, @0.5@, @0.5@, @0.45@, @0.4@, @0.4@, @0.4@, @0.4@, @0.4@, @0.4@, @0.4@, @0.4@ */
};
unsigned_int16_t SAC_LIMITER_CONTROL_KI[1] = {10240}; /* @10@ */
unsigned_int16_t SAC_LIN_FADING_ACTIVATION_THRS[1] = {512}; /* @0.5@ */
unsigned_int16_t SAC_LIN_FADING_COEFFICIENT[1] = {50}; /* @0.0975@ *//* M.Kuboyama 180126 Adjust for 10ms cyclic */
unsigned_int16_t SAC_LIN_FADING_GATE_TIME[1] = {307}; /* @0.3@ */
unsigned_int16_t SAC_LIN_FADING_MAX_OFFSET[1] = {2048}; /* @2@ */
unsigned_int16_t SAC_LIN_FADING_MIN_OFFSET[1] = {51}; /* @0.05@ */
unsigned_int16_t SAC_LIN_FAD_ENABLE_MULTI_RAMP[1] = {0}; /* @0@ */
signed_int16_t SAC_LOAD_COMPENSATION_FACTOR[1] = {1024}; /* @1@ */
unsigned_int16_t SAC_LOW_GRAD_MAX_DYS[1] = {154}; /* @0.15@ */
unsigned_int16_t SAC_MAXIMUM_ACCURACY_REQUEST[1] = {1024}; /* @1@ */
unsigned_int16_t SAC_MAXIMUM_STIFFNESS_REQUEST[1] = {1024}; /* @1@ */
unsigned_int16_t SAC_MAX_ANGLE_VELOCITY[1] = {32000}; /* @1000@ */
unsigned_int16_t SAC_MAX_CONTROL_ERROR[1] = {16384}; /* @16@ */
unsigned_int16_t SAC_MAX_INTEG_TORQUE_CORR_FACT[1] = {7168}; /* @7@ */
unsigned_int16_t SAC_MAX_INTEG_TRQ_X_SCHEDULING[11] = 
{
   0, 640, 1280, 1920, 2560, 3200, 3840, 5120, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @120@, @180@, @250@ */
};
unsigned_int16_t SAC_MAX_INTEG_TRQ_Y_SCHEDULING[11] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t SAC_MAX_PRELOAD_ANGLE[1] = {20480}; /* @20@ */
unsigned_int16_t SAC_MIN_COMMAND_GRADIENT[1] = {32000}; /* @1000@ */
unsigned_int16_t SAC_MIN_CONTROL_ERROR[1] = {102}; /* @0.1@ */
signed_int16_t SAC_MIN_KP[1] = {0}; /* @0@ */
unsigned_int16_t SAC_MIN_PROPORTIONAL_PART[1] = {205}; /* @0.2@ */
unsigned_int16_t SAC_MIN_PROPORTIONAL_PART_SCALE[1] = {102}; /* @0.1@ */
unsigned_int16_t SAC_MX_ANGLE_SPEED_X_SCHEDULING[11] = 
{
   0, 640, 1280, 1920, 2560, 3200, 3840, 5120, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @50@, @60@, @80@, @120@, @180@, @250@ */
};
signed_int16_t SAC_MX_ANGLE_SPEED_Y_SCHEDULING[11] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t SAC_NONLIN_FILTER_DAMPING[1] = {32}; /* @32@ */
unsigned_int16_t SAC_NONLIN_FILTER_FRICTION[1] = {40}; /* @40@ */
unsigned_int16_t SAC_NONLIN_FILTER_GAIN[1] = {0}; /* @0@ */
unsigned_int16_t SAC_NONLIN_FILTER_STAT_FRICTION[1] = {0}; /* @0@ */
signed_int16_t SAC_NOTCH_CF[1] = {1024}; /* @1@ */
signed_int16_t SAC_NOTCH_D[1] = {205}; /* @0.2@ */
unsigned_int16_t SAC_NOTCH_HIGH_PASS_OMEGA_1[1] = {0}; /* @0@ */
signed_int16_t SAC_NOTCH_HIGH_PASS_OMEGA_2[1] = {0}; /* @0@ */
signed_int16_t SAC_NOTCH_L1[1] = {0}; /* @0@ */
signed_int16_t SAC_NOTCH_L2[1] = {3072}; /* @3@ */
signed_int16_t SAC_NOTCH_L3[1] = {6144}; /* @6@ */
unsigned_int16_t SAC_NOTCH_ONE_BY_J_MOTOR[1] = {480}; /* @60@ */
unsigned_int16_t SAC_OBS_SCALING_END[1] = {384}; /* @0.375@ */
unsigned_int16_t SAC_OBS_SCALING_START[1] = {0}; /* @0@ */
unsigned_int16_t SAC_OMEGA_ARW[1] = {20480}; /* @20@ */
signed_int16_t SAC_ONE_BY_TS[1] = {100}; /* @100@ */
unsigned_int16_t SAC_OSC_DAMP_CTRL_ERROR_SLOPE[1] = {20480}; /* @20@ */
unsigned_int16_t SAC_OSC_DAMP_DIFF_PART_SLOPE[1] = {10240}; /* @10@ */
signed_int16_t SAC_OSC_DAMP_FLT_FALLING_COEFF[1] = {3195}; /* @0.0975@ */
signed_int16_t SAC_OSC_DAMP_FLT_RISING_COEFF[1] = {32765}; /* @1@ */
unsigned_int16_t SAC_OSC_DAMP_MIN_CONTROL_ERROR[1] = {102}; /* @0.1@ */
signed_int16_t SAC_PARITY_OMEGA[1] = {20480}; /* @20@ */
unsigned_int16_t SAC_PARITY_TIME_CONSTANT[1] = {150}; // src 10 --> 350 tcy/* @0.01@ */ /* StFe udate, tau 0.1 s, M.Kuboyama 180907 consider actual angle delaytau_EPS = 0.35s */
unsigned_int16_t SAC_PARITY_TIME_CONSTANT_INTER[1] = {52}; /* @0.01@ */ /*Nobuto, 3 deg ( = SAC_PARITY_TIME_CONSTANT_INTER / 256 * gear_ratio */ 
unsigned_int16_t SAC_PARITY_TIME_CONSTANT_LDP[1] = {25600}; /* @100@ */
unsigned_int16_t SAC_PARITY_TIME_CONSTANT_LOW[1] = {10}; /* @0.01@ */ 
unsigned_int16_t SAC_PARITY_TIME_CONST_BARRIER[1] = {0}; /* @0@ */
unsigned_int16_t SAC_PID_KD[1] = {0}; /* @0.0432@ */
unsigned_int16_t SAC_PID_KD_DAMP_MODE[1] = {0}; /* @0@ */
unsigned_int16_t SAC_PROP_PART_LIMIT_SCALE[1] = {1024}; /* @1@ */
unsigned_int16_t SAC_PT1_FILTER_COEFF[1] = {10970}; /* @0.64@ */
unsigned_int16_t SAC_PT1_FILTER_COEFF_2[1] = {10485}; /* @0.64@ *//* M.Kuboyama 180126 Adjust for 10ms cyclic */
unsigned_int16_t SAC_PT1_FILTER_COEFF_3[1] = {10970}; /* @0.64@ */
unsigned_int16_t SAC_PT1_FILTER_COEFF_4[1] = {3125}; /* @0.19@ */
unsigned_int16_t SAC_PT1_FILTER_COEFF_5[1] = {3125}; /* @0.19@ */
unsigned_int16_t SAC_PT1_FILTER_COEFF_6[1] = {3125}; /* @0.19@ */
unsigned_int16_t SAC_PT1_FILTER_COEFF_7[1] = {32765}; /* @1@ */
unsigned_int16_t SAC_PT1_MAX_FILTER_COEFF_2[1] = {5596}; /* @0.36@ */
signed_int16_t SAC_P_PART_FILTER_COEFF[1] = {32765}; /* @1@ */
unsigned_int16_t SAC_REDUCED_KMC_LOOP_GAIN[1] = {900}; /* @0.7@ */ /* StFe 190131: reduce oscillation due to rate limitation */
unsigned_int16_t SAC_STIFFNESS_FILTER_COEFF[1] = {3125}; /* @0.19@ */
unsigned_int16_t SAC_STIFFNESS_OVERRIDE[1] = {100}; /* @100@ */
unsigned_int16_t SAC_TOLERATED_TRQ_RATE_RESIDUAL[1] = {30720}; /* @30@ */
signed_int16_t SAC_TORQUE_SCALING_FACTOR[1] = {5120}; /* @5@ */
unsigned_int16_t SAC_TS[1] = {328}; /* @0.01@ */
unsigned_int16_t SAC_YRC_CTRL_CMD_FADING_X_SCHED[11] = 
{
   0, 641, 1282, 1923, 2564, 3846, 5128, 6410, 7692, 11538, 16026, 
/* @0@, @10@, @20@, @30@, @40@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t SAC_YRC_CTRL_CMD_FADING_Y_SCHED[11] = 
{
   1024, 1024, 512, 0, 0, 0, 0, 0, 0, 0, 0, 
/* @1@, @1@, @0.5@, @0@, @0@, @0@, @0@, @0@, @0@, @0@, @0@ */
};
unsigned_int16_t SAC_YRC_KI_GAIN[1] = {0}; /* @0@ */
unsigned_int16_t SAC_YRC_KP_GAIN[1] = {500}; /* @0.488->0@ */ /* 181025 KuboyamaM US demo */
unsigned_int16_t SAC_YRC_KP_PT1_GAIN[1] = {1024}; /* @0.9765625->0@ */ /* KuboyamaM US demo */
unsigned_int16_t SAC_YRC_KP_PT1_X_SCHEDULING[11] = 
{
   0, 640, 1280, 1920, 2560, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t SAC_YRC_KP_PT1_Y_SCHEDULING[11] = 
{
   20480, 20480, 5120, 5120, 5120, 2560, 1536, 1536, 512, 512, 512, 
/* @40@, @40@, @10@, @10@, @10@, @5@, @3@, @3@, @1@, @1@, @1@ */
};
unsigned_int16_t SAC_YRC_KP_X_SCHEDULING[11] = 
{
   0, 640, 1280, 1920, 2560, 3840, 5120, 6400, 7680, 11520, 16000, 
/* @0@, @10@, @20@, @30@, @40@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t SAC_YRC_KP_Y_SCHEDULING[11] = 
{
   512, 512, 512, 512, 512, 512, 512, 512, 512, 512, 512, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t SAC_YRC_KD_FADING_FACTOR[1] = {0}; /* @0@ */ 
unsigned_int16_t SAC_YRC_LOOP_GAIN_CORR[1] = {4096}; /* @1@ */
unsigned_int16_t SAC_YRC_PT1_FILTER_COEFF[1] = {500}; /* @0.03@ */ /* M.Kuboyama 180126 Adjust for 10ms cyclic LKA tuning result with Feick-san(171026) */
unsigned_int16_t SAC_YRC_YR_CMD_DOT_FILTER_COEFF[1] = {6500}; /* @0.1@ */
unsigned_int16_t SAT_DYNAMIC_ENHANCEMENT_FACTOR[1] = {1024}; /* @1@ */
unsigned_int16_t SAT_MAX_CMD_FACTOR_X_SCHEDULING[13] = 
{
   0, 640, 1280, 2560, 3840, 5120, 6400, 7680, 8960, 10240, 11520, 12800, 13440,
/* @0@, @10@, @20@, @40@, @60@, @80@, @100@, @120@, @140@, @160@, @180@, @200@, @210@ */
};
unsigned_int16_t SAT_MAX_CMD_FACTOR_AES_Y_SCHED[13] = 
{
   7270, 7270, 7270, 4370, 2530, 1890, 1426, 1110, 948, 878, 828, 794, 780,
/* @3.549@, @3.549@, @3.549@, @2.134@, @1.1*1.123@, @1.2*0.769@, @1.15*0.606@, @1,05*0.517@, @0.463@, @0.428@, @0.404@, @0.387@, @0.381@ */
}; 
unsigned_int16_t SAT_MAX_CMD_FACTOR_Y_SCHEDULING[13] = 
{
   //3635, 3635, 3635, 2185, 1265, 945, 713, 555, 474, 439, 414, 397, 390,
   3635, 3635, 3635, 3635, 3635, 3635, 713, 555, 474, 439, 414, 397, 390,
   /* @3.549@, @3.549@, @3.549@, @2.134@, @1.1*1.123@, @1.2*0.769@, @1.15*0.606@, @1,05*0.517@, @0.463@, @0.428@, @0.404@, @0.387@, @0.381@ */
}; /* StFe 181031 angle command limitation reduces use case in corners, EG not exactly considered in the limits */
/* 180907 M.Kuboyama LDP tuning result @ HigashiFuji, set LTA TSS2-LTA-PRL-VHL ID19 Value*EPS gear factor */
unsigned_int16_t SAT_MAX_DELTA_F_CMD[1] = {788}; /* @1.25@ */ // (190128 NoYo) in order to be aligned with TMC requirements with variant 1
/* 180907 M.Kuboyama LDP tuning result @ HigashiFuji, set LTA TSS2-LTA-PRL-VHL ID19 */
/* 181218 StFe consider margin due to angle offset and modeling errors, main limitation done by lateral accel control  */
unsigned_int16_t SAT_MAX_DELTA_F_CMD_PHY[1] = {10240}; /* @20@ */
unsigned_int16_t SAT_THRS_CONTROL_KP[1] = {0}; /* @0@ */ /* Kuboyama Use default */
unsigned_int16_t TDF_ACTIVATION_GAIN[1] = {1024}; /* @1@ */
unsigned_int16_t TDF_COMP_FACTOR_FILTER_COEFF[1] = {8191}; /* @0.5@ *//* M.Kuboyama 180126 Adjust for 10ms cyclic */
unsigned_int16_t TDF_COMP_FILTER_MIN_RESIDUAL[1] = {1024}; /* @1@ */
unsigned_int16_t TDF_CONTROL_ERR_DERATING_SLOPE[1] = {0}; /* @0@ */
unsigned_int16_t TDF_CONTROL_ERROR_SIGN_SLOPE[1] = {10240}; /* @10@ */
unsigned_int16_t TDF_CONTROL_ERROR_SIGN_SLOPE_2[1] = {1024}; /* @1@ */
unsigned_int16_t TDF_DAMPING_GAIN[1] = {0}; /* @1@ */
unsigned_int16_t TDF_DELTA_F_LATENCY[1] = {0}; /* @0@ */
unsigned_int16_t TDF_DELTA_F_LATENCY_COMP_COEFF[1] = {6000}; /* @0.19@ */
unsigned_int16_t TDF_DERATING_END[1] = {1024}; /* @1@ */
unsigned_int16_t TDF_DERATING_LEVEL_DECREMENT[1] = {10}; /* @0.01@ */
unsigned_int16_t TDF_DERATING_MAX_FACTOR[1] = {1024}; /* @1@ */
unsigned_int16_t TDF_DERATING_MAX_ANGLE[1] = {1024}; /* @1@ */
unsigned_int16_t TDF_DERATING_MIN_FACTOR[1] = {0}; /* @0@ */
unsigned_int16_t TDF_DERATING_MODE[1] = {148}; /* @8@ */ /* use raw control error instead of filtered error for VA10 */
unsigned_int16_t TDF_DERATING_SLOPE_X_SCHEDULING[11] = 
{
   0, 641, 1282, 1923, 2564, 3846, 5128, 6410, 7692, 11538, 16026, 
/* @0@, @10@, @20@, @30@, @40@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t TDF_DERATING_SLOPE_Y_SCHEDULING[11] = 
{ 
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t TDF_DERATING_START[1] = {0}; /* @0@ */
signed_int16_t TDF_DERATING_THRS_EPS_I_HOLD[1] = {10000}; /* @10@ */ /* StFe fcn disabled via default */
unsigned_int16_t TDF_DERATING_THRS_X_SCHEDULING[11] = 
{
   0, 641, 1282, 1923, 2564, 3846, 5128, 6410, 7692, 11538, 16026, 
/* @0@, @10@, @20@, @30@, @40@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t TDF_DERATING_THRS_Y_SCHEDULING[11] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
signed_int16_t TDF_LAT_ACCEL_SIGN_SLOPE[1] = {10240}; /* @10@ */
unsigned_int16_t TDF_LOAD_COMP_END[1] = {1024}; /* @1@ */
unsigned_int16_t TDF_LOAD_COMP_START[1] = {0}; /* @0@ */
unsigned_int16_t TDF_LOAD_COMP_X_SCHEDULING[11] = 
{
   0, 641, 1282, 1923, 2564, 3846, 5128, 6410, 7692, 11538, 16026, 
/* @0@, @10@, @20@, @30@, @40@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t TDF_LOAD_COMP_Y_SCHEDULING[11] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t TDF_MIN_COMPENSATION_FACTOR[1] = {0}; /* @0@ */
signed_int16_t TDF_MIN_STEER_TORQUE_CLASS[1] = {500}; /* @0.4@ */ /* M.Kuboyama 180331 TJA Tuning result Par008: TDF active torque 0.5 -> 0.4Nm */
unsigned_int16_t TDF_MIN_STEER_TRQ_CLS_X_SCHEDUL[11] = 
{
   0, 641, 1282, 1923, 2564, 3846, 5128, 6410, 7692, 11538, 16026, 
/* @0@, @10@, @20@, @30@, @40@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t TDF_MIN_STEER_TRQ_CLS_Y_SCHEDUL[11] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t TDF_MIN_STR_TRQ_CLASS_HANDSOFF[1] = {300}; /* @0.29296875@ */
unsigned_int16_t TDF_OUT_SCALE_FILT_MIN_RESIDUAL[1] = {102}; /* @0.1@ */
unsigned_int16_t TDF_PAC_REQUEST_SIGN_SLOPE[1] = {0}; /* @0@ no PAC torque available for VA10 */
unsigned_int16_t TDF_PAC_RESIDUE_FILTER_COEFF[1] = {32768}; /* @1@ */
unsigned_int16_t TDF_PAC_RESID_RISING_FILT_COEFF[1] = {983}; /* @0.03@ */
unsigned_int16_t TDF_PAC_TORQUE_FILTER_COEFF[1] = {3276}; /* @0.1@ */
unsigned_int16_t TDF_PAC_TRQ_REQ_FILTER_COEFF[1] = {3276}; /* @0.1@ */
unsigned_int16_t TDF_PAC_TORQUE_VEL_FILTER_COEFF[1] = {32768}; /* @1@ */
unsigned_int16_t TDF_PAC_TORQUE_RESIDUE[1] = {512}; /* @0.5@ */
unsigned_int16_t TDF_STEER_TORQUE_COMP_SLOPE[1] = {1024}; /* @1@ */
unsigned_int16_t TDF_STEER_TORQUE_COMP_THRS_LDP[1] = {2560}; /* @2.5@ */
unsigned_int16_t TDF_STEER_TORQUE_SIGN_SLOPE[1] = {2048}; /* @2@ */
unsigned_int16_t TDF_STEER_TORQUE_SIGN_SLOPE_2[1] = {10240}; /* @10@ */
unsigned_int16_t TDF_STEER_TRQ_CMP_LDP_X_SCHEDUL[11] = 
{
   0, 641, 1282, 1923, 2564, 3846, 5128, 6410, 7692, 11538, 16026, 
/* @0@, @10@, @20@, @30@, @40@, @60@, @80@, @100@, @120@, @180@, @250@ */
};
unsigned_int16_t TDF_STEER_TRQ_CMP_LDP_Y_SCHEDUL[11] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t TDF_STEER_TRQ_CMP_SLP_X_SCHEDUL[12] = 
{
   0, 641, 1282, 1923, 2564, 3846, 5128, 6410, 7692, 8974, 11538, 16026, 
/* @0@, @10@, @20@, @30@, @40@, @60@, @80@, @100@, @120@, @140@, @180@, @250@ */
};
unsigned_int16_t TDF_STEER_TRQ_CMP_SLP_Y_SCHEDUL[12] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t TDF_STEER_TRQ_COMP_REDUCED_THRS[1] = {102}; /* @0.1@ */
unsigned_int16_t TDF_STEER_TRQ_CTRL_FILTER_COEFF[1] = {655}; /* @0.02@ */
unsigned_int16_t TDF_STEER_TRQ_FILTER_COEFF[1] = {3276}; /* @0.1@ */ 
unsigned_int16_t TDF_STEER_TRQ_RESD_FILTER_COEFF[1] = {32768}; /* @1@ */ 
unsigned_int16_t TDF_ST_WHEEL_UNBALANCE_FACTOR[1] = {0}; /* @0@ */
unsigned_int16_t TDF_STEER_TORQUE_FFWD_GAIN[1] = {0}; /* @0@ */
unsigned_int16_t TDF_STEER_TORQUE_FF_FILTER_COEFF[1] = {32768}; /* @1@ */
unsigned_int16_t TDF_STEER_TRQ_FF_GAIN_Y_SCHEDUL[11] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
unsigned_int16_t TDF_TORQUE_REDUC_GAIN_Y_SCHEDUL[11] = 
{
   1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 
/* @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@, @1@ */
};
signed_int16_t TDF_TOQUE_DERATING_SLOPE[1] = {1024}; /* @1.0@ */ /* M.Kuboyama 180907 TJA TDF Adjust TLA spec TSS2-LTA-FCN-STD ID520 */
unsigned_int16_t TDF_TORQUE_DERATING_FILT_COEFF[1] = {5000}; /* @0.305038@ *//* Y.Kanamori(180619) 500 --> 5000:weakly PT1 filter  M.Kuboyama 180126 Adjust for 10ms cyclic */
unsigned_int16_t TDF_TORQUE_DERATING_SLOPE_LDP[1] = {1024}; /* @0.5@ */ /* M.Kuboyama 180907 TJA TDF Adjust TLA spec TSS2-LTA-FCN-STD ID520 */
unsigned_int16_t TDF_TORQUE_DERATING_THRESHOLD[1] = {500}; /* @7.0@ */ /* M.Kuboyama 180907 TJA TDF Adjust TLA spec TSS2-LTA-FCN-STD ID520 */ /*T.Yoshida 190311, disable TDF by setting factor=7168(=7)(same as TDF_TRQ_DERATING_THRESHOLD_DP)*/
unsigned_int16_t TDF_TORQUE_DER_FILT_COEFF_HF[1] = {1638}; /* @0.1@ *//* M.Kuboyama 180126 Adjust for 10ms cyclic */
signed_int16_t TDF_TORQUE_REDUCTION_GAIN[1] = {100}; /* @0.1@ */
signed_int16_t TDF_TORQUE_REDUCTION_P_GAIN[1] = {0}; /* @0.2@ */
unsigned_int16_t TDF_TORQUE_REQUEST_SIGN_SLOPE[1] = {10240}; /* @10@ */
unsigned_int16_t TDF_TORQUE_SUPPORTING_SLOPE[1] = {307}; /* @0.3@ */
unsigned_int16_t TDF_TORQUE_SUPPORTING_THRESHOLD[1] = {10240}; /* @10@ */
unsigned_int16_t TDF_TRQ_DERATING_MAX_INIT_TRQ[1] = {0}; /* @0@ */
unsigned_int16_t TDF_TRQ_DERATING_MIN_INIT_TRQ[1] = {1024}; /* @1@ */
unsigned_int16_t TDF_TRQ_DERATING_SLOPE_HF_PATH[1] = {0}; /* @0@ */
unsigned_int16_t TDF_TRQ_DERATING_SLOPE_HI_SENS[1] = {1024}; /* @1.0*/ /* M.Kuboyama 180907 TJA TDF Adjust TLA spec TSS2-LTA-FCN-STD ID520 */
unsigned_int16_t TDF_TRQ_DERATING_THRESHOLD_DP[1] = {3000}; /* @3.0@ */ /* 3 Nm maximum override torque */
unsigned_int16_t TDF_TRQ_DERATING_THRS_X_SCHEDUL[11] = 
{
   0, 1280, 2560, 3840, 5120, 6400, 7680, 8960, 10240, 11520, 16000,
/* @0@, @20@, @40@, @60@, @80@, @100@, @120@, @140@, @160@, @180@, @210@ */
};
unsigned_int16_t TDF_TRQ_DERATING_THRS_Y_SCHEDUL[11] = 
{
   2048, 1843, 1638, 1433, 1228, 1024, 819, 614, 512, 512, 512, 
/* @2.0@, @1.8@, @1.6@, @1.4@, @1.2@, @1.0@, @0.8@, @0.6@, @0.5@, @0.5@, @0.5@ */
};
unsigned_int16_t TDF_TRQ_FILTER_COEFF[1] = {8192}; /* @0.5@ *//* M.Kuboyama 180126 Adjust for 10ms cyclic */
unsigned_int16_t TDF_TRQ_SCALING_END[1] = {1024}; /* @1@ */
unsigned_int16_t TDF_TRQ_SCALING_START[1] = {0}; /* @0@ */
unsigned_int16_t TDF_VELOCITY_DERATING_SLOPE[1] = {205}; /* @0.2@ */
unsigned_int16_t TDF_VELOCITY_DERATING_THRESHOLD[1] = {4096}; /* @4@ */
unsigned_int16_t TDF_VEL_DER_FALLING_FILT_COEFF[1] = {327}; /* @0.01@ */
unsigned_int16_t TDF_VEL_DER_RISING_FILT_COEFF[1] = {3276}; /* @0.1@ */
unsigned_int16_t TDF_VEL_DERATING_FILT_COEFF[1] = {649}; /* @0.0396@ *//* M.Kuboyama 180126 Adjust for 10ms cyclic */
unsigned_int16_t TGE_STATE_FILTER_TIME_CONSTANT[1] = {102}; /* @0.1@ */
unsigned_int16_t TRJ_GENERATION_MODE[1] = {0}; /* @0@ */
unsigned_int16_t TRJ_MAX_ACCEL[1] = {3072}; /* @3@ */
signed_int16_t TRJ_MAX_HEADING_ANGLE[1] = {2880}; /* @45@ */
signed_int16_t TRJ_STEP_COMMAND[1] = {1024}; /* @1@ */
signed_int16_t VEH_ONE_BY_COLUMN_STIFFNESS[1] = {0}; /* @0@ */
unsigned_char_t VEH_STEER_ANGLE_RATE_SOURCE[1] = {1}; /* @1@ */
unsigned_char_t VEH_STEER_ANGLE_SOURCE[1] = {1}; /* @1@ */
signed_int16_t VEH_STEER_GEAR_RATIO_X_TAB[6] = 
{
   0, 2743, 5486, 8228, 10971, 13714, 
/* @0@, @120@, @240@, @360@, @480@, @600@ */
};
signed_int16_t VEH_STEER_GEAR_RATIO_Y_TAB[6] = 
{
   15482, 15196, 14961, 14561, 14336, 14336, 
/* @15.5@, @15.37@, @15.19@, @15.02@, @14.7@, @13.85@ */
};
