"""
stk/db/mdl/adas_db_def
--------

documentation of test

This file contains database definitions

:org:           Continental AG
:author:        Guenther Raedler

:version:       $Revision: 1.1 $
:contact:       $Author: Wang, David (Wangd3) $ (last change)
:date:          $Date: 2021/12/13 17:56:31CET $
"""

from stk.db.cat.cat import COL_NAME_DRIVERS_DRIVERID, COL_NAME_DRIVERS_NAME, \
    TABLE_NAME_DRIVERS, COL_NAME_FILESTATES_FILESTATEID, COL_NAME_FILESTATES_NAME, \
    TABLE_NAME_FILESTATES, COL_NAME_VEHICLES_VEHICLEID, COL_NAME_VEHICLES_NAME, \
    COL_NAME_VEHICLES_MODEL, COL_NAME_VEHICLES_LICNUMBER, COL_NAME_VEHICLES_VEHCOMMENT, \
    TABLE_NAME_VEHICLES, COL_NAME_VEHICLECFGSTATES_VEHICLECFGSTATEID, COL_NAME_VEHICLECFGSTATES_NAME, \
    TABLE_NAME_VEHICLECFGSTATES, COL_NAME_VEHICLECFGS_VEHCFGID, COL_NAME_VEHICLECFGS_VEHICLEID, \
    COL_NAME_VEHICLECFGS_VEHICLECFGSTATEID, COL_NAME_VEHICLECFGS_NAME, COL_NAME_VEHICLECFGS_SETUPDATE, \
    COL_NAME_VEHICLECFGS_SETUPBY, COL_NAME_VEHICLECFGS_CFGCOMMENT, TABLE_NAME_VEHICLECFGS, \
    COL_NAME_PARTCFGS_PARTCFGID, COL_NAME_PARTCFGS_VEHCFGID, COL_NAME_PARTCFGS_PARTTYPEID, \
    COL_NAME_PARTCFGS_NAME, COL_NAME_PARTCFGS_HWVERSION, COL_NAME_PARTCFGS_SWVERSION, \
    COL_NAME_PARTCFGS_PARTCOMMENT, TABLE_NAME_PARTTYPES, COL_NAME_PARTTYPES_PARTTYPEID, \
    COL_NAME_PARTTYPES_NAME, COL_NAME_FILES_MEASID, COL_NAME_FILES_RECFILEID, COL_NAME_FILES_BEGINTIMESTAMP, \
    COL_NAME_FILES_ENDTIMESTAMP, COL_NAME_FILES_FILEPATH, COL_NAME_FILES_RECTIME, COL_NAME_FILES_IMPORTDATE, \
    COL_NAME_FILES_IMPORTBY, COL_NAME_FILES_FILESTATEID, COL_NAME_FILES_VEHICLECFGID, COL_NAME_FILES_DRIVERID, \
    COL_NAME_FILES_CONTENTHASH, COL_NAME_FILES_RECDRIVENDIST, TABLE_NAME_FILES, COL_NAME_FILES_RECODOSTARTDIST, \
    COL_NAME_COUNTRIES_COUNTRYID, COL_NAME_COUNTRIES_NAME, TABLE_NAME_COUNTRIES, COL_NAME_LOCATION_LOCID, \
    COL_NAME_LOCATION_NAME, TABLE_NAME_LOCATIONS, COL_NAME_LOCINFO_LOCINFOID, COL_NAME_LOCINFO_MEASID, \
    COL_NAME_LOCINFO_COUNTRYID, COL_NAME_LOCINFO_LOCID, COL_NAME_LOCINFO_LOCTIMESTAMP, COL_NAME_LOCINFO_GPSLATDEG, \
    COL_NAME_LOCINFO_GPSLNGDEG, COL_NAME_LOCINFO_GPSALTDEG, TABLE_NAME_LOCINFO, COL_NAME_KW_KWID, \
    COL_NAME_KW_PARENTID, COL_NAME_KW_NAME, COL_NAME_KW_KWCOMMENT, TABLE_NAME_KW, COL_NAME_KWMAP_KWMAPID, \
    COL_NAME_KWMAP_KWID, COL_NAME_KWMAP_MEASID, COL_NAME_KWMAP_BEGINTIMESTAMP, COL_NAME_KWMAP_ENDTIMESTAMP, \
    COL_NAME_KWMAP_ASGNBY, COL_NAME_KWMAP_ASGNDATE, TABLE_NAME_KWMAP, COL_NAME_COLL_COLLID, \
    COL_NAME_COLL_PARENTID, COL_NAME_COLL_NAME, COL_NAME_COLL_COLLCOMMENT, TABLE_NAME_COLL, \
    COL_NAME_COLLMAP_COLLMAPID, COL_NAME_COLLMAP_COLLID, COL_NAME_COLLMAP_MEASID, \
    COL_NAME_COLLMAP_BEGINTIMESTAMP, COL_NAME_COLLMAP_ENDTIMESTAMP, COL_NAME_COLLMAP_ASGNBY, \
    COL_NAME_COLLMAP_ASGNDATE, TABLE_NAME_COLLMAP, COL_NAME_DATAINTTESTS_TESTID, COL_NAME_DATAINTTESTS_NAME, \
    COL_NAME_DATAINTTESTS_DITCOMMENT, TABLE_NAME_DATAINTTESTS, TABLE_NAME_PARTCFGS, \
    COL_NAME_FILES_DATAINTTESTRESULT, COL_NAME_FILES_DATAINTTESTSTATUS

from stk.db.gbl.gbl import TABLE_NAME_USERS, TABLE_NAME_TR_TYPE, TABLE_NAME_UNITS, COL_NAME_WORKFLOW_WFID, \
    COL_NAME_WORKFLOW_NAME, COL_NAME_WORKFLOW_DESC, TABLE_NAME_WORKFLOW, COL_NAME_USER_ID, COL_NAME_USER_NAME, \
    COL_NAME_USER_LOGIN, COL_NAME_UNIT_ID, COL_NAME_UNIT_NAME, COL_NAME_UNIT_TYPE, COL_NAME_UNIT_LABEL, \
    COL_NAME_VO_TYPE_ID, COL_NAME_VO_TYPE_NAME, COL_NAME_VO_TYPE_DESC, COL_NAME_VALTYPE_ID, \
    COL_NAME_VALTYPE_NAME, COL_NAME_VALTYPE_DESC, TABLE_NAME_VALTYPES, COL_NAME_ASSESSMENT_STATE_ASSID, \
    COL_NAME_ASSESSMENT_STATE_NAME, TABLE_NAME_PROJECT, COL_NAME_ASSESSMENT_STATE_DESCRIPTION, \
    COL_NAME_ASSESSMENT_STATE_VALOBS_TYPEID, TABLE_NAME_ASSESSMENT_STATE, COL_NAME_PROJECT_DESC, \
    COL_NAME_PROJECT_PID, COL_NAME_PROJECT_NAME


from stk.db.val.val import TABLE_NAME_RESULT_DESC, COL_NAME_TR_ID, COL_NAME_TR_NAME, COL_NAME_TR_DESC, \
    COL_NAME_TR_START, COL_NAME_TR_END, COL_NAME_TR_CHECKPOINT, COL_NAME_TR_USERID, COL_NAME_TR_TYPE_ID, \
    COL_NAME_TR_PARENT, COL_NAME_TR_COLL_NAME, TABLE_NAME_TESTRUN, COL_NAME_EVENTTYPE_ID, \
    COL_NAME_EVENTTYPE_NAME, COL_NAME_EVENTTYPE_DESC, COL_NAME_EVENTTYPE_CLASSNAME, TABLE_NAME_EVENTTYPE, \
    COL_NAME_VRKEY_ID, COL_NAME_VRKEY_NAME, COL_NAME_VRKEY_DESCRIPTION, TABLE_NAME_VRKEY, \
    COL_NAME_VRKEY_MAP_ID, COL_NAME_VRKEY_MAP_RDID, TABLE_NAME_VRKEY_MAP, COL_NAME_RESDESC_ID, \
    COL_NAME_RESDESC_NAME, COL_NAME_RESDESC_COLLID, COL_NAME_RESDESC_RESTYPE_ID, COL_NAME_RESDESC_UNIT_ID, \
    COL_NAME_RESDESC_PARENT, COL_NAME_RESDESC_REFTAG, TABLE_NAME_RESULTTYPE, COL_NAME_RES_ID, \
    COL_NAME_RES_TESTRUN_ID, COL_NAME_RES_RESDESC_ID, COL_NAME_RES_VALUE, COL_NAME_RES_MEASID, \
    COL_NAME_RES_RESASSID, TABLE_NAME_ASSESSMENT, TABLE_NAME_RESULT, COL_NAME_RESIMG_ID, \
    COL_NAME_RESIMG_IMAGE, COL_NAME_RESIMG_TITLE, COL_NAME_RESIMG_FORMAT, TABLE_NAME_RESULT_IMAGE, \
    COL_NAME_RESVAL_SUBID, COL_NAME_RESVAL_ID, COL_NAME_RESVAL_VALUE, COL_NAME_RESMESS_SUBID, \
    COL_NAME_RESMESS_ID, COL_NAME_RESMESS_MESS, TABLE_NAME_RESULT_MESSAGES, COL_NAME_ASS_ID, \
    COL_NAME_ASS_USER_ID, COL_NAME_ASS_COMMENT, COL_NAME_ASS_WFID, COL_NAME_ASS_DATE, COL_NAME_RESLB_RESID, \
    COL_NAME_RESLB_LBID, TABLE_NAME_RESULT_LABEL_MAP, TABLE_NAME_RESULT_VALUES, COL_NAME_RESULTTYPE_CLASS, \
    TABLE_NAME_EVENTS, COL_NAME_EVENTS_SEID, COL_NAME_EVENTS_BEGINABSTS, COL_NAME_EVENTS_ENDABSTS, \
    COL_NAME_EVENTS_START_IDX, COL_NAME_EVENTS_STOP_IDX, COL_NAME_EVENTS_MEASID, COL_NAME_EVENTS_TRID, \
    COL_NAME_EVENTS_EVENTTYPEID, COL_NAME_EVENTS_RESASSID, COL_NAME_EVENTS_RDID, TABLE_NAME_EVENT_DETAILS, \
    COL_NAME_EVENT_DET_EDID, COL_NAME_EVENT_DET_ABSTS, COL_NAME_EVENT_DET_SEID, TABLE_NAME_EVENT_ATTR, \
    COL_NAME_EVENT_ATTR_ATTRID, COL_NAME_EVENT_ATTR_ATTRTYPEID, COL_NAME_EVENT_ATTR_VALUE, \
    COL_NAME_EVENT_ATTR_EDID, TABLE_NAME_EVENT_ATTR_TYPES, COL_NAME_EVENT_ATTR_TYPES_ATTRTYPEID, \
    COL_NAME_EVENT_ATTR_TYPES_NAME, COL_NAME_EVENT_ATTR_TYPES_DESC, COL_NAME_EVENT_ATTR_TYPES_UNITID, \
    COL_NAME_EVENT_ATTR_TYPES_PARENT, TABLE_NAME_EVENT_IMAGE, COL_NAME_EVENT_IMG_ATTRID, \
    COL_NAME_EVENT_IMG_IMAGE, COL_NAME_EVENT_IMG_TITLE, COL_NAME_EVENT_IMG_FORMAT, COL_NAME_TR_DELETED, \
    COL_NAME_TR_TRUNLOCK, COL_NAME_RESULTTYPE_ID, COL_NAME_RESULTTYPE_NAME, COL_NAME_RESULTTYPE_DESC, \
    COL_NAME_ASS_ASSSTID, COL_NAME_TR_PID, COL_NAME_RESDESC_DOORS_URL, COL_NAME_RESDESC_EXPECTRES, \
    COL_NAME_RESDESC_DESCRIPTION

from stk.db.par.par import TABLE_NAME_DESCRIPTION, COL_NAME_DESC_ID, COL_NAME_DESC_NAME, COL_NAME_DESC_TYPE, \
    COL_NAME_DESC_UNIT, TABLE_NAME_CONFIGS, COL_NAME_CFG_ID, COL_NAME_CFG_NAME, COL_NAME_PARCFG_MAP_ID, \
    COL_NAME_PARCFG_MAP_PDID, COL_NAME_PARCFG_MAP_PCID, TABLE_NAME_CFGMAP, COL_NAME_PAR_VAL_ID, \
    COL_NAME_PAR_VAL_MEASID, COL_NAME_PAR_VAL_PMID, COL_NAME_PAR_VAL_USERID, COL_NAME_PAR_VAL_WFID, \
    COL_NAME_PAR_VAL_TIMESTAMP, COL_NAME_PAR_VAL_VALUE, TABLE_NAME_VALUE

from stk.db.obj.objdata import COL_NAME_EGO_ADMA_MEASID, COL_NAME_EGO_ADMA_KINABSTS, \
    COL_NAME_EGO_ADMA_VELOCITY_X, COL_NAME_EGO_ADMA_VELOCITY_Y, COL_NAME_EGO_ADMA_VELOCITY_Z, \
    COL_NAME_EGO_ADMA_ACCELERATION, COL_NAME_EGO_ADMA_YAWRATE, COL_NAME_EGO_ADMA_PITCH, \
    COL_NAME_EGO_ADMA_ROLL, COL_NAME_EGO_ADMA_SUMDIST, COL_NAME_EGO_ADMA_SUMYAW, \
    TABLE_NAME_EGO_KINEMATICS_ADMA, COL_NAME_PROBSCAM_ABSTS, COL_NAME_PROBSCAM_RECTOBJID, \
    COL_NAME_PROBSCAM_OCCLUDED, COL_NAME_PROBSCAM_ABSTS, COL_NAME_PROBSCAM_RECTOBJID, \
    TABLE_NAME_RECTANGULAR_OBJECT, COL_NAME_RECT_OBJ_RECTOBJID, COL_NAME_RECT_OBJ_MEASID, \
    COL_NAME_RECT_OBJ_ASSOCTYPEID, COL_NAME_RECT_OBJ_RECTOBJ_IS_DELETED, COL_NAME_RECT_OBJ_OBJCLASSID, \
    COL_NAME_RECT_OBJ_CLSLBLSTATEID, COL_NAME_RECT_OBJ_CLSLBLTIME, COL_NAME_RECT_OBJ_CLSLBLBY, \
    COL_NAME_RECT_OBJ_OBJWIDTH, COL_NAME_RECT_OBJ_OBJLENGTH, COL_NAME_RECT_OBJ_OBJHEIGHT, \
    COL_NAME_RECT_OBJ_DIMLBLSTATEID, COL_NAME_RECT_OBJ_DIMLBLTIME, COL_NAME_RECT_OBJ_DIMLBLBY, \
    COL_NAME_RECT_OBJ_ZLAYER, COL_NAME_RECT_OBJ_ZOVERGROUND, COL_NAME_RECT_OBJ_ZOLBLSTATEID, \
    COL_NAME_RECT_OBJ_ZOLBLBY, COL_NAME_RECT_OBJ_ZOLBLTIME, COL_NAME_RECT_OBJ_KINLBLSTATEID, \
    COL_NAME_RECT_OBJ_KINLBLMODTIME, COL_NAME_RECT_OBJ_LBLBY, TABLE_NAME_PROBS_CAM, TABLE_NAME_ASSOC_TYPE, \
    COL_NAME_ASSOC_TYPE_ASSOCTYPEID, COL_NAME_ASSOC_TYPE_NAME, COL_NAME_ASSOC_TYPE_DESC, \
    COL_NAME_ASSOC_TYPE_NAME, COL_NAME_OBJECT_CLASS_CLS_ID, COL_NAME_OBJECT_CLASS_CLASS_NAME, \
    COL_NAME_OBJECT_CLASS_DESCRIPTION, TABLE_NAME_OBJECT_CLASS, COL_NAME_KINEMATICS_KINABSTS, \
    COL_NAME_KINEMATICS_RECTOBJID, COL_NAME_KINEMATICS_RELDISTX, COL_NAME_KINEMATICS_RELDISTY, \
    COL_NAME_KINEMATICS_RELVELX, COL_NAME_KINEMATICS_HEADINGOVERGND, TABLE_NAME_KINEMATICS, \
    COL_NAME_ADMA_KINEMATICS_RECTOBJID, COL_NAME_ADMA_KINEMATICS_KINABSTS, COL_NAME_ADMA_KINEMATICS_RELDISTX, \
    COL_NAME_ADMA_KINEMATICS_RELDISTY, COL_NAME_ADMA_KINEMATICS_RELVELX, COL_NAME_ADMA_KINEMATICS_RELVELY, \
    COL_NAME_ADMA_KINEMATICS_ARELX, COL_NAME_ADMA_KINEMATICS_ARELY, COL_NAME_ADMA_KINEMATICS_HEADINGOG, \
    COL_NAME_ADMA_KINEMATICS_ADMAOK, TABLE_NAME_ADMA_KINEMATICS, COL_NAME_EGO_KINEMATICS_MEASID, \
    COL_NAME_EGO_KINEMATICS_KINABSTS, COL_NAME_EGO_KINEMATICS_VELOCITY, COL_NAME_EGO_KINEMATICS_ACCELERATION, \
    COL_NAME_EGO_KINEMATICS_YAWRATE, TABLE_NAME_EGO_KINEMATICS, COL_NAME_LBL_STATE_LBL_STATE_ID, \
    COL_NAME_LBL_STATE_NAME, COL_NAME_LBL_STATE_DESCRIPTION, TABLE_NAME_OBJ_LBL_STATE, \
    COL_NAME_ACC_LANE_REL_ACCLANERELID, COL_NAME_ACC_LANE_REL_RECTOBJID, COL_NAME_ACC_LANE_REL_BEGINABSTS, \
    COL_NAME_ACC_LANE_REL_ENDABSTS, COL_NAME_ACC_LANE_REL_LANEID, COL_NAME_ACC_LANE_REL_LANEASSOCWEIGHT, \
    COL_NAME_ACC_LANE_REL_LBLSTATEID, COL_NAME_ACC_LANE_REL_LBLMODTIME, COL_NAME_ACC_LANE_REL_LBLBY, \
    TABLE_NAME_ACC_LANE_REL, COL_NAME_LANE_TYPES_LANE_ID, COL_NAME_LANE_TYPES_LANE_NAME, \
    COL_NAME_LANE_TYPES_DESCRIPTION, TABLE_NAME_ACC_LANE_TYPES, COL_NAME_TEST_CASE_TYPE_ID, \
    COL_NAME_TEST_CASE_TYPE_NAME, COL_NAME_TEST_CASE_TYPE_DESCRIPTION, TABLE_NAME_TEST_CASE_TYPE, \
    COL_NAME_TEST_CASES_TESTCASEID, COL_NAME_TEST_CASES_TYPEID, COL_NAME_TEST_CASES_RECTOBJID, \
    COL_NAME_TEST_CASES_BEGINABSTS, COL_NAME_TEST_CASES_ENDABSTS, TABLE_NAME_TEST_CASES, \
    COL_NAME_TEST_CASES_LBLSTATEID, COL_NAME_TEST_CASES_LBLMODTIME, COL_NAME_TEST_CASES_LBLBY

from stk.db.lbl.genlabel import COL_NAME_LABELS_LBID, COL_NAME_LABELS_ABSTS, COL_NAME_LABELS_TYPEID, \
    COL_NAME_LABELS_WFID, COL_NAME_LABELS_STATEID, COL_NAME_LABELS_MEASID, COL_NAME_LABELS_USERID, \
    COL_NAME_LABELS_MODDATE, TABLE_NAME_LABELS, COL_NAME_ATTR_NAMES_LBATTNAMEID, COL_NAME_ATTR_NAMES_NAME, \
    TABLE_NAME_ATTRIBUTE_NAMES, COL_NAME_ATTRIBUTES_LBATTRID, COL_NAME_ATTRIBUTES_LBID, \
    COL_NAME_ATTRIBUTES_LBATTNAMEID, COL_NAME_ATTRIBUTES_UNITID, COL_NAME_ATTRIBUTES_VTID, \
    COL_NAME_ATTRIBUTES_VALUE, TABLE_NAME_ATTRIBUTES, COL_NAME_STATES_STATEID, COL_NAME_STATES_NAME, \
    COL_NAME_STATES_DESC, COL_NAME_STATES_VALUE, COL_NAME_STATES_TYPEID, TABLE_NAME_STATES, \
    COL_NAME_TYPES_TYPEID, COL_NAME_TYPES_NAME, COL_NAME_TYPES_DESC, COL_NAME_TYPES_PARENT, TABLE_NAME_TYPES, \
    COL_NAME_RECTOBJIDMAP_RECTOBJID, COL_NAME_RECTOBJIDMAP_LBID, TABLE_NAME_RECTOBJIDMAP, TABLE_NAME_ADDINFO, \
    COL_NAME_INFO_ID, COL_NAME_INFO_DESC

from stk.db.fct.fct import TABLE_NAME_CRITICALITY, TABLE_NAME_EGOBEHAVIOUR, TABLE_NAME_SCENARIO, \
    TABLE_NAME_ENVIRONMENT, COL_NAME_CRITICALITY_CID, COL_NAME_CRITICALITY_NAME, COL_NAME_CRITICALITY_DESC, \
    COL_NAME_EGOBEHAVIOUR_EBID, COL_NAME_EGOBEHAVIOUR_NAME, COL_NAME_EGOBEHAVIOUR_DESC, \
    COL_NAME_SCENARIO_SCENARIOID, COL_NAME_SCENARIO_MEASID, COL_NAME_SCENARIO_STARTABSTS, \
    COL_NAME_SCENARIO_ENDABSTS, COL_NAME_SCENARIO_LBLCOMMENT, COL_NAME_SCENARIO_ENV_INFRASTRUCTURE, \
    COL_NAME_SCENARIO_ENV_LIGHT_CONDITION, COL_NAME_SCENARIO_ENV_WEATHER_CONDITION, \
    COL_NAME_SCENARIO_ENV_DATAINTEGRITY, COL_NAME_SCENARIO_LABELER_CRITICALITY, \
    COL_NAME_SCENARIO_VEHICLE_CRITICALITY, COL_NAME_SCENARIO_DRIVER_CRITICALITY, COL_NAME_SCENARIO_LBLSTATEID, \
    COL_NAME_SCENARIO_LBLBY, COL_NAME_SCENARIO_LBLTIME, COL_NAME_SCENARIO_PID, COL_NAME_SCENARIO_RECTOBJID, \
    COL_NAME_SCENARIO_EGO_BEHAVIOR, COL_NAME_SCENARIO_REL_EGO_BEHAVIOR, COL_NAME_SCENARIO_OBJ_DYNAMIC, \
    COL_NAME_SCENARIO_OBJ_TYPE, COL_NAME_SCENARIO_OBJ_BEHAVIOR, COL_NAME_ENVIRONMENT_ENVID, \
    COL_NAME_ENVIRONMENT_NAME, COL_NAME_ENVIRONMENT_ENVTYPEID, COL_NAME_ENVIRONMENT_DESC

FOREIGN_KEY = "FOREIGN KEY"
REFERENCES = "REFERENCES"
NAME = "NAME"
PK = "PK"
FK = "FK"
REL = "REL"
COL_LIST = "COL_LIST"
COL_TYPES = "COL_TYPES"
DATA = "DATA"
NUMBER = "NUMBER"
INTEGER = "INTEGER"
BLOB = "BLOB"
FLOAT = "FLOAT"
DATE = "DATE"
TIMESTAMP = "TIMESTAMP"
NVARCHAR = "VARCHAR"
VARCHAR = "NVARCHAR"
NVARCHAR2 = "NVARCHAR2"
TEXT = "TEXT"
PATH = "PATH"

LEN_4 = "_4"
LEN_10 = "_10"
LEN_15 = "_15"
LEN_30 = "_30"
LEN_40 = "_40"
LEN_32 = "_32"
LEN_50 = "_50"
LEN_60 = "_60"
LEN_100 = "_100"
LEN_150 = "_150"
LEN_200 = "_200"
LEN_250 = "_250"
LEN_256 = "_256"
LEN_260 = "_260"
LEN_300 = "_300"
LEN_1000 = "_1000"
LEN_2000 = "_2000"

GBL = "GBL"
CAT = "CAT"
LBL = "LBL"
PAR = "PAR"
OBJ = "OBJ"
VAL = "VAL"
FCT = "FCT"
#############################################  ===== GBL ====  #######################################
# TABLE_NAME_WORKFLOW                 = "GBL_Workflow"
TABLE_NAME_WORKFLOW_COL_LIST = [COL_NAME_WORKFLOW_WFID, COL_NAME_WORKFLOW_NAME,
                                COL_NAME_WORKFLOW_DESC]
TABLE_NAME_WORKFLOW_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_200]
TABLE_NAME_WORKFLOW_PK = [COL_NAME_WORKFLOW_WFID]
TABLE_NAME_WORKFLOW_FK = []
TABLE_NAME_WORKFLOW_REL = []
TABLE_NAME_WORKFLOW_INFO = {NAME: TABLE_NAME_WORKFLOW, COL_LIST: TABLE_NAME_WORKFLOW_COL_LIST,
                            PK: TABLE_NAME_WORKFLOW_PK, REL: TABLE_NAME_WORKFLOW_REL,
                            FK: TABLE_NAME_WORKFLOW_FK, COL_TYPES: TABLE_NAME_WORKFLOW_COL_TYPES}

# TABLE_NAME_USERS                    = "GBL_Users"
TABLE_NAME_USERS_COL_LIST = [COL_NAME_USER_ID, COL_NAME_USER_NAME, COL_NAME_USER_LOGIN]
TABLE_NAME_USERS_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_40, NVARCHAR2 + LEN_30]
TABLE_NAME_USERS_PK = [COL_NAME_USER_ID]
TABLE_NAME_USERS_FK = []
TABLE_NAME_USERS_REL = []
TABLE_NAME_USERS_INFO = {NAME: TABLE_NAME_USERS, COL_LIST: TABLE_NAME_USERS_COL_LIST,
                         PK: TABLE_NAME_USERS_PK, REL: TABLE_NAME_USERS_REL,
                         FK: TABLE_NAME_USERS_FK, COL_TYPES: TABLE_NAME_USERS_COL_TYPES}

# TABLE_NAME_UNITS                    = "GBL_Units"
TABLE_NAME_UNITS_COL_LIST = [COL_NAME_UNIT_ID, COL_NAME_UNIT_NAME, COL_NAME_UNIT_TYPE,
                             COL_NAME_UNIT_LABEL]
TABLE_NAME_UNITS_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_30, NVARCHAR2 + LEN_30, NVARCHAR2 + LEN_10]
TABLE_NAME_UNITS_PK = [COL_NAME_UNIT_ID]
TABLE_NAME_UNITS_FK = []
TABLE_NAME_UNITS_REL = []
TABLE_NAME_UNITS_INFO = {NAME: TABLE_NAME_UNITS, COL_LIST: TABLE_NAME_UNITS_COL_LIST,
                         PK: TABLE_NAME_UNITS_PK, REL: TABLE_NAME_UNITS_REL,
                         FK: TABLE_NAME_UNITS_FK, COL_TYPES: TABLE_NAME_UNITS_COL_TYPES}

# TABLE_NAME_TR_TYPE                  = "GBL_ValObserver"
TABLE_NAME_TR_TYPE_COL_LIST = [COL_NAME_VO_TYPE_ID, COL_NAME_VO_TYPE_NAME, COL_NAME_VO_TYPE_DESC]
TABLE_NAME_TR_TYPE_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_30, NVARCHAR2 + LEN_30, NVARCHAR2 + LEN_10]
TABLE_NAME_TR_TYPE_PK = [COL_NAME_VO_TYPE_ID]
TABLE_NAME_TR_TYPE_FK = []
TABLE_NAME_TR_TYPE_REL = []
TABLE_NAME_TR_TYPE_INFO = {NAME: TABLE_NAME_TR_TYPE, COL_LIST: TABLE_NAME_TR_TYPE_COL_LIST,
                           PK: TABLE_NAME_TR_TYPE_PK, REL: TABLE_NAME_TR_TYPE_REL,
                           FK: TABLE_NAME_TR_TYPE_FK, COL_TYPES: TABLE_NAME_TR_TYPE_COL_TYPES}

# TABLE_NAME_VALTYPES                 = "GBL_ValTypes"
TABLE_NAME_VALTYPES_COL_LIST = [COL_NAME_VALTYPE_ID, COL_NAME_VALTYPE_NAME, COL_NAME_VALTYPE_DESC]
TABLE_NAME_VALTYPES_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_200]
TABLE_NAME_VALTYPES_PK = [COL_NAME_VALTYPE_ID]
TABLE_NAME_VALTYPES_FK = []
TABLE_NAME_VALTYPES_REL = []
TABLE_NAME_VALTYPES_INFO = {NAME: TABLE_NAME_VALTYPES, COL_LIST: TABLE_NAME_VALTYPES_COL_LIST,
                            PK: TABLE_NAME_VALTYPES_PK, REL: TABLE_NAME_VALTYPES_REL,
                            FK: TABLE_NAME_VALTYPES_FK, COL_TYPES: TABLE_NAME_VALTYPES_COL_TYPES}

# TABLE_NAME_ASSESSMENT_STATE        = "GBL_Assessment_State"
TABLE_NAME_ASSESSMENT_STATE_COL_LIST = [COL_NAME_ASSESSMENT_STATE_ASSID,
                                        COL_NAME_ASSESSMENT_STATE_NAME,
                                        COL_NAME_ASSESSMENT_STATE_DESCRIPTION,
                                        COL_NAME_ASSESSMENT_STATE_VALOBS_TYPEID]
TABLE_NAME_ASSESSMENT_STATE_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_200, NUMBER]
TABLE_NAME_ASSESSMENT_STATE_PK = [COL_NAME_ASSESSMENT_STATE_ASSID]
TABLE_NAME_ASSESSMENT_STATE_FK = [COL_NAME_ASSESSMENT_STATE_VALOBS_TYPEID]
TABLE_NAME_ASSESSMENT_STATE_REL = [{TABLE_NAME_TR_TYPE:COL_NAME_VO_TYPE_ID}]
TABLE_NAME_ASSESSMENT_STATE_INFO = {NAME: TABLE_NAME_ASSESSMENT_STATE,
                                    COL_LIST: TABLE_NAME_ASSESSMENT_STATE_COL_LIST,
                                    PK: TABLE_NAME_ASSESSMENT_STATE_PK,
                                    REL: TABLE_NAME_ASSESSMENT_STATE_REL,
                                    FK: TABLE_NAME_ASSESSMENT_STATE_FK,
                                    COL_TYPES: TABLE_NAME_ASSESSMENT_STATE_COL_TYPES}

# TABLE_NAME_PROJECT = "GBL_PROJECT"
TABLE_NAME_PROJECT_COL_LIST = [COL_NAME_PROJECT_PID, COL_NAME_PROJECT_NAME,
                               COL_NAME_PROJECT_DESC]
TABLE_NAME_PROJECT_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_10, NVARCHAR2 + LEN_1000]
TABLE_NAME_PROJECT_PK = [COL_NAME_PROJECT_PID]
TABLE_NAME_PROJECT_FK = []
TABLE_NAME_PROJECT_REL = []
TABLE_NAME_PROJECT_INFO = {NAME: TABLE_NAME_PROJECT, COL_LIST: TABLE_NAME_PROJECT_COL_LIST,
                           PK: TABLE_NAME_PROJECT_PK, REL: TABLE_NAME_PROJECT_REL,
                           FK: TABLE_NAME_PROJECT_FK, COL_TYPES: TABLE_NAME_PROJECT_COL_TYPES}

DB_GBL_TABLE_INFO_LIST = [TABLE_NAME_PROJECT_INFO, TABLE_NAME_WORKFLOW_INFO, TABLE_NAME_USERS_INFO,
                          TABLE_NAME_UNITS_INFO, TABLE_NAME_TR_TYPE_INFO, TABLE_NAME_VALTYPES_INFO,
                          TABLE_NAME_ASSESSMENT_STATE_INFO]
#############################################  ===== CAT ====  ########################################
# TABLE_NAME_DATAINTTESTS             = "CAT_DataIntTests"
TABLE_NAME_DATAINTTESTS_COL_LIST = [COL_NAME_DATAINTTESTS_TESTID, COL_NAME_DATAINTTESTS_NAME,
                                    COL_NAME_DATAINTTESTS_DITCOMMENT]
TABLE_NAME_DATAINTTESTS_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_2000]
TABLE_NAME_DATAINTTESTS_PK = [COL_NAME_DATAINTTESTS_TESTID]
TABLE_NAME_DATAINTTESTS_FK = []
TABLE_NAME_DATAINTTESTS_REL = []
TABLE_NAME_DATAINTTESTS_INFO = {NAME: TABLE_NAME_DATAINTTESTS, COL_LIST: TABLE_NAME_DATAINTTESTS_COL_LIST,
                                PK: TABLE_NAME_DATAINTTESTS_PK, REL: TABLE_NAME_DATAINTTESTS_REL,
                                FK: TABLE_NAME_DATAINTTESTS_FK, COL_TYPES: TABLE_NAME_DATAINTTESTS_COL_TYPES}

# TABLE_NAME_VEHICLECFGSTATES         = "CAT_VehicleCfgStates"
TABLE_NAME_VEHICLECFGSTATES_COL_LIST = [COL_NAME_VEHICLECFGSTATES_VEHICLECFGSTATEID,
                                        COL_NAME_VEHICLECFGSTATES_NAME]
TABLE_NAME_VEHICLECFGSTATES_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50]
TABLE_NAME_VEHICLECFGSTATES_PK = [COL_NAME_VEHICLECFGSTATES_VEHICLECFGSTATEID]
TABLE_NAME_VEHICLECFGSTATES_FK = []
TABLE_NAME_VEHICLECFGSTATES_REL = []
TABLE_NAME_VEHICLECFGSTATES_INFO = {NAME: TABLE_NAME_VEHICLECFGSTATES,
                                    COL_LIST: TABLE_NAME_VEHICLECFGSTATES_COL_LIST,
                                    PK: TABLE_NAME_VEHICLECFGSTATES_PK, FK: TABLE_NAME_VEHICLECFGSTATES_FK,
                                    REL: TABLE_NAME_VEHICLECFGSTATES_REL,
                                    COL_TYPES: TABLE_NAME_VEHICLECFGSTATES_COL_TYPES}

# TABLE_NAME_VEHICLES                 = "CAT_Vehicles"
TABLE_NAME_VEHICLES_COL_LIST = [COL_NAME_VEHICLES_VEHICLEID, COL_NAME_VEHICLES_NAME,
                                COL_NAME_VEHICLES_MODEL, COL_NAME_VEHICLES_LICNUMBER,
                                COL_NAME_VEHICLES_VEHCOMMENT]
TABLE_NAME_VEHICLES_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_50,
                                 NVARCHAR2 + LEN_15, NVARCHAR2 + LEN_2000]
TABLE_NAME_VEHICLES_PK = [COL_NAME_VEHICLES_VEHICLEID]
TABLE_NAME_VEHICLES_FK = []
TABLE_NAME_VEHICLES_REL = []
TABLE_NAME_VEHICLES_INFO = {NAME: TABLE_NAME_VEHICLES, COL_LIST: TABLE_NAME_VEHICLES_COL_LIST,
                            PK: TABLE_NAME_VEHICLES_PK, FK: TABLE_NAME_VEHICLES_FK,
                            REL: TABLE_NAME_VEHICLES_REL, COL_TYPES: TABLE_NAME_VEHICLES_COL_TYPES}

# TABLE_NAME_DRIVERS                  = "CAT_Drivers"
TABLE_NAME_DRIVERS_COL_LIST = [COL_NAME_DRIVERS_DRIVERID, COL_NAME_DRIVERS_NAME]
TABLE_NAME_DRIVERS_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_250]
TABLE_NAME_DRIVERS_PK = [COL_NAME_DRIVERS_DRIVERID]
TABLE_NAME_DRIVERS_FK = []
TABLE_NAME_DRIVERS_REL = []
TABLE_NAME_DRIVERS_INFO = {NAME: TABLE_NAME_DRIVERS, COL_LIST: TABLE_NAME_DRIVERS_COL_LIST,
                           PK: TABLE_NAME_DRIVERS_PK, FK: TABLE_NAME_DRIVERS_FK,
                           REL: TABLE_NAME_DRIVERS_REL, COL_TYPES: TABLE_NAME_DRIVERS_COL_TYPES}

# TABLE_NAME_FILESTATES               = "CAT_FileStates"
TABLE_NAME_FILESTATES_COL_LIST = [COL_NAME_FILESTATES_FILESTATEID, COL_NAME_FILESTATES_NAME]
TABLE_NAME_FILESTATES_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50]
TABLE_NAME_DRIVERS_PK = [COL_NAME_FILESTATES_FILESTATEID]
TABLE_NAME_DRIVERS_FK = []
TABLE_NAME_FILESTATES_REL = []
TABLE_NAME_FILESTATES_INFO = {NAME: TABLE_NAME_FILESTATES, COL_LIST: TABLE_NAME_FILESTATES_COL_LIST,
                              PK: TABLE_NAME_DRIVERS_PK, FK: TABLE_NAME_DRIVERS_FK,
                              REL: TABLE_NAME_FILESTATES_REL, COL_TYPES: TABLE_NAME_FILESTATES_COL_TYPES}

# TABLE_NAME_VEHICLECFGS              = "CAT_VehicleCfgs"
TABLE_NAME_VEHICLECFGS_COL_LIST = [COL_NAME_VEHICLECFGS_VEHCFGID, COL_NAME_VEHICLECFGS_VEHICLEID,
                                   COL_NAME_VEHICLECFGS_VEHICLECFGSTATEID, COL_NAME_VEHICLECFGS_NAME,
                                   COL_NAME_VEHICLECFGS_SETUPDATE, COL_NAME_VEHICLECFGS_SETUPBY,
                                   COL_NAME_VEHICLECFGS_CFGCOMMENT]
TABLE_NAME_VEHICLECFGS_COL_TYPES = [NUMBER, NUMBER, NUMBER, NVARCHAR2 + LEN_300,
                                    DATE, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_2000]

TABLE_NAME_VEHICLECFGS_PK = [COL_NAME_VEHICLECFGS_VEHCFGID]
TABLE_NAME_VEHICLECFGS_FK = [COL_NAME_VEHICLECFGS_VEHICLECFGSTATEID, COL_NAME_VEHICLECFGS_VEHICLEID]
TABLE_NAME_VEHICLECFGS_REL = [TABLE_NAME_VEHICLECFGSTATES, TABLE_NAME_VEHICLES]
TABLE_NAME_VEHICLECFGS_INFO = {NAME: TABLE_NAME_VEHICLECFGS, COL_LIST: TABLE_NAME_VEHICLECFGS_COL_LIST,
                               PK: TABLE_NAME_VEHICLECFGS_PK, FK: TABLE_NAME_VEHICLECFGS_FK,
                               REL: TABLE_NAME_VEHICLECFGS_REL, COL_TYPES: TABLE_NAME_VEHICLECFGS_COL_TYPES}

# TABLE_NAME_PARTTYPES                = "CAT_PartTypes"
TABLE_NAME_PARTTYPES_COL_LIST = [COL_NAME_PARTTYPES_PARTTYPEID, COL_NAME_PARTTYPES_NAME]
TABLE_NAME_PARTTYPES_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50]
TABLE_NAME_PARTTYPES_PK = [COL_NAME_PARTTYPES_PARTTYPEID]
TABLE_NAME_PARTTYPES_FK = []
TABLE_NAME_PARTTYPES_REL = []
TABLE_NAME_PARTTYPES_INFO = {NAME: TABLE_NAME_PARTTYPES, COL_LIST: TABLE_NAME_PARTTYPES_COL_LIST,
                             PK: TABLE_NAME_PARTTYPES_PK, FK: TABLE_NAME_PARTTYPES_FK,
                             REL: TABLE_NAME_PARTTYPES_REL, COL_TYPES:  TABLE_NAME_PARTTYPES_COL_TYPES}
# TABLE_NAME_LOCATIONS                = "CAT_Locations"
TABLE_NAME_LOCATIONS_COL_LIST = [COL_NAME_LOCATION_LOCID, COL_NAME_LOCATION_NAME]
TABLE_NAME_LOCATIONS_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_100]

TABLE_NAME_LOCATIONS_PK = [COL_NAME_LOCATION_LOCID]
TABLE_NAME_LOCATIONS_FK = []
TABLE_NAME_LOCATIONS_REL = []
TABLE_NAME_LOCATIONS_INFO = {NAME: TABLE_NAME_LOCATIONS, COL_LIST: TABLE_NAME_LOCATIONS_COL_LIST,
                             PK: TABLE_NAME_LOCATIONS_PK, FK: TABLE_NAME_LOCATIONS_FK,
                             REL: TABLE_NAME_LOCATIONS_REL, COL_TYPES: TABLE_NAME_LOCATIONS_COL_TYPES}

# TABLE_NAME_COUNTRIES                = "CAT_Countries"
TABLE_NAME_COUNTRIES_COL_LIST = [COL_NAME_COUNTRIES_COUNTRYID, COL_NAME_COUNTRIES_NAME]
TABLE_NAME_COUNTRIES_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_100]
TABLE_NAME_COUNTRIES_PK = [COL_NAME_COUNTRIES_COUNTRYID]
TABLE_NAME_COUNTRIES_FK = []
TABLE_NAME_COUNTRIES_REL = []
TABLE_NAME_COUNTRIES_INFO = {NAME: TABLE_NAME_COUNTRIES, COL_LIST: TABLE_NAME_COUNTRIES_COL_LIST,
                             PK: TABLE_NAME_COUNTRIES_PK, FK: TABLE_NAME_COUNTRIES_FK,
                             REL: TABLE_NAME_COUNTRIES, COL_TYPES: TABLE_NAME_COUNTRIES_COL_TYPES}

# TABLE_NAME_LOCINFO                  = "CAT_LocInfo"
TABLE_NAME_LOCINFO_COL_LIST = [COL_NAME_LOCINFO_LOCINFOID, COL_NAME_LOCINFO_MEASID,
                               COL_NAME_LOCINFO_COUNTRYID, COL_NAME_LOCINFO_LOCID,
                               COL_NAME_LOCINFO_LOCTIMESTAMP, COL_NAME_LOCINFO_GPSLATDEG,
                               COL_NAME_LOCINFO_GPSLNGDEG, COL_NAME_LOCINFO_GPSALTDEG]
TABLE_NAME_LOCINFO_COL_TYPES = [NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, FLOAT, FLOAT, FLOAT]
TABLE_NAME_LOCINFO_PK = [COL_NAME_LOCINFO_LOCINFOID]
TABLE_NAME_LOCINFO_FK = [COL_NAME_LOCINFO_MEASID, COL_NAME_LOCINFO_COUNTRYID, COL_NAME_LOCINFO_LOCID]
TABLE_NAME_LOCINFO_REL = [TABLE_NAME_FILES, TABLE_NAME_COUNTRIES, TABLE_NAME_LOCATIONS]
TABLE_NAME_LOCINFO_INFO = {NAME: TABLE_NAME_LOCINFO, COL_LIST: TABLE_NAME_LOCINFO_COL_LIST,
                           PK: TABLE_NAME_LOCINFO_PK, FK: TABLE_NAME_LOCINFO_FK,
                           REL: TABLE_NAME_LOCINFO_REL, COL_TYPES:  TABLE_NAME_LOCINFO_COL_TYPES}

# TABLE_NAME_FILES                    = "CAT_Files"
TABLE_NAME_FILES_COL_LIST = [COL_NAME_FILES_MEASID, COL_NAME_FILES_RECFILEID,
                             COL_NAME_FILES_BEGINTIMESTAMP, COL_NAME_FILES_ENDTIMESTAMP,
                             COL_NAME_FILES_FILEPATH, COL_NAME_FILES_RECTIME,
                             COL_NAME_FILES_IMPORTDATE, COL_NAME_FILES_IMPORTBY,
                             COL_NAME_FILES_FILESTATEID, COL_NAME_FILES_VEHICLECFGID,
                             COL_NAME_FILES_DRIVERID, COL_NAME_FILES_DATAINTTESTRESULT,
                             COL_NAME_FILES_DATAINTTESTSTATUS, COL_NAME_FILES_CONTENTHASH,
                             COL_NAME_FILES_RECDRIVENDIST, COL_NAME_FILES_RECODOSTARTDIST]
TABLE_NAME_FILES_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_100, NUMBER, NUMBER,
                              PATH, DATE, DATE, NVARCHAR2 + LEN_50,
                              NUMBER, NUMBER, NUMBER, NUMBER, NUMBER,
                              NVARCHAR2 + LEN_256, NUMBER, NUMBER]
TABLE_NAME_FILES_PK = [COL_NAME_FILES_MEASID]
TABLE_NAME_FILES_FK = [COL_NAME_FILES_FILESTATEID, COL_NAME_FILES_VEHICLECFGID,
                       COL_NAME_FILES_DRIVERID]
TABLE_NAME_FILES_REL = [TABLE_NAME_FILESTATES, TABLE_NAME_VEHICLECFGS, TABLE_NAME_DRIVERS]
TABLE_NAME_FILES_INFO = {NAME: TABLE_NAME_FILES, COL_LIST: TABLE_NAME_FILES_COL_LIST,
                         PK: TABLE_NAME_FILES_PK, FK: TABLE_NAME_FILES_FK,
                         REL: TABLE_NAME_FILES_REL, COL_TYPES:  TABLE_NAME_FILES_COL_TYPES}

# TABLE_NAME_KW                       = "CAT_Keywords"
TABLE_NAME_KW_COL_LIST = [COL_NAME_KW_KWID, COL_NAME_KW_PARENTID,
                          COL_NAME_KW_NAME, COL_NAME_KW_KWCOMMENT]
TABLE_NAME_KW_COL_TYPES = [NUMBER, NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_2000]
TABLE_NAME_KW_PK = [COL_NAME_KW_KWID]
TABLE_NAME_KW_FK = [COL_NAME_KW_PARENTID]
TABLE_NAME_KW_REL = [TABLE_NAME_KW]
TABLE_NAME_KW_INFO = {NAME: TABLE_NAME_KW, COL_LIST: TABLE_NAME_KW_COL_LIST,
                      PK: TABLE_NAME_KW_PK, REL: TABLE_NAME_KW_REL, FK: TABLE_NAME_KW_FK,
                      COL_TYPES: TABLE_NAME_KW_COL_TYPES}

# TABLE_NAME_PARTCFGS                 = "CAT_PartCfgs"
TABLE_NAME_PARTCFGS_COL_LIST = [COL_NAME_PARTCFGS_PARTCFGID, COL_NAME_PARTCFGS_VEHCFGID,
                                COL_NAME_PARTCFGS_PARTTYPEID, COL_NAME_PARTCFGS_NAME,
                                COL_NAME_PARTCFGS_HWVERSION, COL_NAME_PARTCFGS_SWVERSION,
                                COL_NAME_PARTCFGS_PARTCOMMENT]
TABLE_NAME_PARTCFGS_COL_TYPES = [NUMBER, NUMBER, NUMBER, NVARCHAR2 + LEN_300,
                                 NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_2000]
TABLE_NAME_PARTCFGS_PK = [COL_NAME_PARTCFGS_PARTCFGID]
TABLE_NAME_PARTCFGS_FK = [COL_NAME_PARTCFGS_VEHCFGID, COL_NAME_PARTCFGS_PARTTYPEID]
TABLE_NAME_PARTCFG_REL = [TABLE_NAME_VEHICLECFGS, TABLE_NAME_PARTTYPES]
TABLE_NAME_PARTCFGS_INFO = {NAME: TABLE_NAME_PARTCFGS, COL_LIST: TABLE_NAME_PARTCFGS_COL_LIST,
                            PK: TABLE_NAME_PARTCFGS_PK, FK: TABLE_NAME_PARTCFGS_FK,
                            REL: TABLE_NAME_PARTCFG_REL, COL_TYPES: TABLE_NAME_PARTCFGS_COL_TYPES}

# TABLE_NAME_KWMAP                    = "CAT_KeywordMap"
TABLE_NAME_KWMAP_COL_LIST = [COL_NAME_KWMAP_KWMAPID, COL_NAME_KWMAP_KWID, COL_NAME_KWMAP_MEASID,
                             COL_NAME_KWMAP_BEGINTIMESTAMP, COL_NAME_KWMAP_ENDTIMESTAMP,
                             COL_NAME_KWMAP_ASGNBY, COL_NAME_KWMAP_ASGNDATE]
TABLE_NAME_KWMAP_COL_TYPES = [NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, NVARCHAR2 + LEN_50, DATE]
TABLE_NAME_KWMAP_PK = [COL_NAME_KWMAP_KWMAPID]
TABLE_NAME_KWMAP_FK = [COL_NAME_KWMAP_KWID, COL_NAME_KWMAP_MEASID]
TABLE_NAME_KWMAP_REL = [TABLE_NAME_KW, TABLE_NAME_FILES]
TABLE_NAME_KWMAP_INFO = {NAME: TABLE_NAME_KWMAP, COL_LIST: TABLE_NAME_KWMAP_COL_LIST,
                         PK: TABLE_NAME_KWMAP_PK, REL: TABLE_NAME_KWMAP_REL,
                         FK: TABLE_NAME_KWMAP_FK, COL_TYPES:  TABLE_NAME_KWMAP_COL_TYPES}

# TABLE_NAME_COLL                     = "CAT_Collections"
TABLE_NAME_COLL_COL_LIST = [COL_NAME_COLL_COLLID, COL_NAME_COLL_PARENTID,
                            COL_NAME_COLL_NAME, COL_NAME_COLL_COLLCOMMENT]
TABLE_NAME_COLL_COL_TYPES = [NUMBER, NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_2000]
TABLE_NAME_COLL_PK = [COL_NAME_COLL_COLLID]
TABLE_NAME_COLL_FK = [COL_NAME_COLL_PARENTID]
TABLE_NAME_COLL_REL = [TABLE_NAME_COLL]

TABLE_NAME_COLL_INFO = {NAME: TABLE_NAME_COLL, COL_LIST: TABLE_NAME_COLL_COL_LIST,
                        PK: TABLE_NAME_COLL_PK, REL: TABLE_NAME_COLL_REL, FK: TABLE_NAME_COLL_FK,
                        COL_TYPES:  TABLE_NAME_COLL_COL_TYPES}

# TABLE_NAME_COLLMAP                  = "CAT_CollectionMap"
TABLE_NAME_COLLMAP_COL_LIST = [COL_NAME_COLLMAP_COLLMAPID, COL_NAME_COLLMAP_COLLID,
                               COL_NAME_COLLMAP_MEASID, COL_NAME_COLLMAP_BEGINTIMESTAMP,
                               COL_NAME_COLLMAP_ENDTIMESTAMP, COL_NAME_COLLMAP_ASGNBY,
                               COL_NAME_COLLMAP_ASGNDATE]
TABLE_NAME_COLLMAP_COL_TYPES = [NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, NVARCHAR2 + LEN_50, DATE]
TABLE_NAME_COLLMAP_PK = [COL_NAME_COLLMAP_COLLMAPID]
TABLE_NAME_COLLMAP_FK = [COL_NAME_COLLMAP_COLLID, COL_NAME_COLLMAP_MEASID]
TABLE_NAME_COLLMAP_REL = [TABLE_NAME_COLL, TABLE_NAME_FILES]
TABLE_NAME_COLLMAP_INFO = {NAME: TABLE_NAME_COLLMAP, COL_LIST: TABLE_NAME_COLLMAP_COL_LIST,
                           PK: TABLE_NAME_COLLMAP_PK, REL: TABLE_NAME_COLLMAP_REL,
                           FK: TABLE_NAME_COLLMAP_FK, COL_TYPES:  TABLE_NAME_COLLMAP_COL_TYPES}


DB_CAT_TABLE_INFO_LIST = [TABLE_NAME_COLL_INFO,
                          #TABLE_NAME_DATAINTTESTS_INFO,
                          TABLE_NAME_PARTTYPES_INFO,
                          TABLE_NAME_DRIVERS_INFO, TABLE_NAME_FILESTATES_INFO, TABLE_NAME_KW_INFO,
                          TABLE_NAME_VEHICLES_INFO, TABLE_NAME_VEHICLECFGSTATES_INFO,
                          TABLE_NAME_VEHICLECFGS_INFO,
                          TABLE_NAME_PARTCFGS_INFO, TABLE_NAME_FILES_INFO, TABLE_NAME_COLLMAP_INFO,
                          TABLE_NAME_KWMAP_INFO, TABLE_NAME_COUNTRIES_INFO, TABLE_NAME_LOCATIONS_INFO,
                          TABLE_NAME_LOCINFO_INFO]
##############################################  ===== PAR ====  #####################################
# #TABLE_NAME_VALUEARCHIVE             = "PAR_ValueArchive"

#TABLE_NAME_CONFIGS = "PAR_Configs"
TABLE_NAME_CONFIGS_COL_LIST = [COL_NAME_CFG_ID, COL_NAME_CFG_NAME]
TABLE_NAME_CONFIGS_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50]
TABLE_NAME_CONFIGS_PK = [COL_NAME_CFG_ID]
TABLE_NAME_CONFIGS_FK = []
TABLE_NAME_CONFIGS_REL = []
TABLE_NAME_CONFIGS_INFO = {NAME: TABLE_NAME_CONFIGS, COL_LIST: TABLE_NAME_CONFIGS_COL_LIST,
                           PK: TABLE_NAME_CONFIGS_PK, REL: TABLE_NAME_CONFIGS_REL,
                           FK: TABLE_NAME_CONFIGS_FK, COL_TYPES:  TABLE_NAME_CONFIGS_COL_TYPES}

#TABLE_NAME_DESCRIPTION              = "PAR_Description"
TABLE_NAME_DESCRIPTION_COL_LIST = [COL_NAME_DESC_ID, COL_NAME_DESC_NAME,
                                   COL_NAME_DESC_TYPE, COL_NAME_DESC_UNIT]
TABLE_NAME_DESCRIPTION_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NUMBER, NUMBER]
TABLE_NAME_DESCRIPTION_PK = [COL_NAME_DESC_ID]
TABLE_NAME_DESCRIPTION_FK = [COL_NAME_DESC_TYPE, COL_NAME_DESC_UNIT]
TABLE_NAME_DESCRIPTION_REL = [TABLE_NAME_VALTYPES, TABLE_NAME_UNITS]
TABLE_NAME_DESCRIPTION_INFO = {NAME: TABLE_NAME_DESCRIPTION, COL_LIST: TABLE_NAME_DESCRIPTION_COL_LIST,
                               PK: TABLE_NAME_DESCRIPTION_PK, REL: TABLE_NAME_DESCRIPTION_REL,
                               FK: TABLE_NAME_DESCRIPTION_FK, COL_TYPES:  TABLE_NAME_DESCRIPTION_COL_TYPES}

#TABLE_NAME_CFGMAP                   = "PAR_CfgMap"
TABLE_NAME_CFGMAP_COL_LIST = [COL_NAME_PARCFG_MAP_ID, COL_NAME_PARCFG_MAP_PDID, COL_NAME_PARCFG_MAP_PCID]
TABLE_NAME_CONFIGS_COL_TYPES = [NUMBER, NUMBER, NUMBER]
TABLE_NAME_CFGMAP_PK = [COL_NAME_PARCFG_MAP_ID]
TABLE_NAME_CFGMAP_FK = [COL_NAME_PARCFG_MAP_PDID, COL_NAME_PARCFG_MAP_PCID]
TABLE_NAME_CONFIGS_REL = [TABLE_NAME_DESCRIPTION, TABLE_NAME_CONFIGS]
TABLE_NAME_CFGMAP_INFO = {NAME: TABLE_NAME_CFGMAP, COL_LIST: TABLE_NAME_CFGMAP_COL_LIST,
                          PK: TABLE_NAME_CFGMAP_PK, REL: TABLE_NAME_CONFIGS_REL,
                          FK: TABLE_NAME_CFGMAP_FK, COL_TYPES:  TABLE_NAME_CONFIGS_COL_TYPES}
#
#TABLE_NAME_VALUE                    = "PAR_Value"
TABLE_NAME_VALUE_COL_LIST = [COL_NAME_PAR_VAL_ID, COL_NAME_PAR_VAL_MEASID, COL_NAME_PAR_VAL_PMID,
                             COL_NAME_PAR_VAL_USERID, COL_NAME_PAR_VAL_WFID, COL_NAME_PAR_VAL_TIMESTAMP,
                             COL_NAME_PAR_VAL_VALUE]
TABLE_NAME_VALUE_COL_TYPES = [NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, TIMESTAMP, FLOAT]
TABLE_NAME_VALUE_PK = [COL_NAME_PAR_VAL_ID]
TABLE_NAME_VALUE_FK = [COL_NAME_PAR_VAL_MEASID, COL_NAME_PAR_VAL_PMID,
                       COL_NAME_PAR_VAL_USERID, COL_NAME_PAR_VAL_WFID]
TABLE_NAME_VALUE_REL = [TABLE_NAME_FILES, TABLE_NAME_CFGMAP, TABLE_NAME_USERS, TABLE_NAME_WORKFLOW]
TABLE_NAME_VALUE_INFO = {NAME: TABLE_NAME_VALUE, COL_LIST: TABLE_NAME_VALUE_COL_LIST,
                         PK: TABLE_NAME_VALUE_PK, REL: TABLE_NAME_VALUE_REL,
                         FK: TABLE_NAME_VALUE_FK, COL_TYPES:  TABLE_NAME_VALUE_COL_TYPES}
#
DB_PAR_TABLE_INFO_LIST = [TABLE_NAME_CONFIGS_INFO, TABLE_NAME_DESCRIPTION_INFO,
                          TABLE_NAME_CFGMAP_INFO, TABLE_NAME_VALUE_INFO]
#############################################  ===== OBJ ====  #####################################
# TABLE_NAME_ASSOC_TYPE =             "OBJ_ASSOCIATIONTYPES"
TABLE_NAME_ASSOC_TYPE_COL_LIST = [COL_NAME_ASSOC_TYPE_ASSOCTYPEID, COL_NAME_ASSOC_TYPE_NAME,
                                  COL_NAME_ASSOC_TYPE_DESC]
TABLE_NAME_ASSOC_TYPE_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_32, NVARCHAR2 + LEN_2000]
TABLE_NAME_ASSOC_TYPE_PK = [COL_NAME_ASSOC_TYPE_ASSOCTYPEID]
TABLE_NAME_ASSOC_TYPE_FK = []
TABLE_NAME_ASSOC_TYPE_REL = []
TABLE_NAME_ASSOC_TYPE_INFO = {NAME: TABLE_NAME_ASSOC_TYPE, COL_LIST: TABLE_NAME_ASSOC_TYPE_COL_LIST,
                              PK: TABLE_NAME_ASSOC_TYPE_PK, REL: TABLE_NAME_ASSOC_TYPE_REL,
                              FK: TABLE_NAME_ASSOC_TYPE_FK, COL_TYPES: TABLE_NAME_ASSOC_TYPE_COL_TYPES}

#TABLE_NAME_OBJECT_CLASS =           "OBJ_CLASSTYPES"
TABLE_NAME_OBJECT_CLASS_COL_LIST = [COL_NAME_OBJECT_CLASS_CLS_ID, COL_NAME_OBJECT_CLASS_CLASS_NAME,
                                    COL_NAME_OBJECT_CLASS_DESCRIPTION]
TABLE_NAME_OBJECT_CLASS_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_32, NVARCHAR2 + LEN_2000]
TABLE_NAME_OBJECT_CLASS_PK = [COL_NAME_OBJECT_CLASS_CLS_ID]
TABLE_NAME_OBJECT_CLASS_FK = []
TABLE_NAME_OBJECT_CLASS_REL = []
TABLE_NAME_OBJECT_CLASS_INFO = {NAME: TABLE_NAME_OBJECT_CLASS, COL_LIST: TABLE_NAME_OBJECT_CLASS_COL_LIST,
                                PK: TABLE_NAME_OBJECT_CLASS_PK, REL: TABLE_NAME_OBJECT_CLASS_REL,
                                FK: TABLE_NAME_OBJECT_CLASS_FK, COL_TYPES: TABLE_NAME_OBJECT_CLASS_COL_TYPES}

#TABLE_NAME_OBJ_LBL_STATE =          "OBJ_LBLSTATE"
TABLE_NAME_OBJ_LBL_STATE_COL_LIST = [COL_NAME_LBL_STATE_LBL_STATE_ID, COL_NAME_LBL_STATE_NAME,
                                     COL_NAME_LBL_STATE_DESCRIPTION]
TABLE_NAME_OBJ_LBL_STATE_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_32, NVARCHAR2 + LEN_2000]
TABLE_NAME_OBJ_LBL_STATE_PK = [COL_NAME_LBL_STATE_LBL_STATE_ID]
TABLE_NAME_OBJ_LBL_STATE_FK = []
TABLE_NAME_OBJ_LBL_STATE_REL = []
TABLE_NAME_OBJ_LBL_STATE_INFO = {NAME: TABLE_NAME_OBJ_LBL_STATE, COL_LIST: TABLE_NAME_OBJ_LBL_STATE_COL_LIST,
                                 PK: TABLE_NAME_OBJ_LBL_STATE_PK, REL: TABLE_NAME_OBJ_LBL_STATE_REL,
                                 FK: TABLE_NAME_OBJ_LBL_STATE_FK, COL_TYPES: TABLE_NAME_OBJ_LBL_STATE_COL_TYPES}

# # TABLE_NAME_RECTANGULAR_OBJECT =     "OBJ_RectangularObject"
TABLE_NAME_RECTANGULAR_OBJECT_COL_LIST = [COL_NAME_RECT_OBJ_RECTOBJID, COL_NAME_RECT_OBJ_MEASID,
                                          COL_NAME_RECT_OBJ_ASSOCTYPEID, COL_NAME_RECT_OBJ_RECTOBJ_IS_DELETED,
                                          COL_NAME_RECT_OBJ_OBJCLASSID, COL_NAME_RECT_OBJ_CLSLBLSTATEID,
                                          COL_NAME_RECT_OBJ_CLSLBLTIME, COL_NAME_RECT_OBJ_CLSLBLBY,
                                          COL_NAME_RECT_OBJ_OBJWIDTH, COL_NAME_RECT_OBJ_OBJLENGTH,
                                          COL_NAME_RECT_OBJ_OBJHEIGHT, COL_NAME_RECT_OBJ_DIMLBLSTATEID,
                                          COL_NAME_RECT_OBJ_DIMLBLTIME, COL_NAME_RECT_OBJ_DIMLBLBY,
                                          COL_NAME_RECT_OBJ_ZLAYER, COL_NAME_RECT_OBJ_ZOVERGROUND,
                                          COL_NAME_RECT_OBJ_ZOLBLSTATEID, COL_NAME_RECT_OBJ_ZOLBLBY,
                                          COL_NAME_RECT_OBJ_ZOLBLTIME, COL_NAME_RECT_OBJ_KINLBLSTATEID,
                                          COL_NAME_RECT_OBJ_KINLBLMODTIME, COL_NAME_RECT_OBJ_LBLBY]
TABLE_NAME_RECTANGULAR_OBJECT_COL_TYPES = [NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, DATE, NUMBER,
                                           FLOAT, FLOAT, FLOAT, NUMBER, DATE, NUMBER, NUMBER, FLOAT,
                                           NUMBER, NUMBER, DATE, NUMBER, DATE, NUMBER]
TABLE_NAME_RECTANGULAR_OBJECT_PK = [COL_NAME_RECT_OBJ_RECTOBJID]
TABLE_NAME_RECTANGULAR_OBJECT_FK = [COL_NAME_RECT_OBJ_MEASID, COL_NAME_RECT_OBJ_ASSOCTYPEID,
                                    COL_NAME_RECT_OBJ_OBJCLASSID, COL_NAME_RECT_OBJ_CLSLBLSTATEID,
                                    COL_NAME_RECT_OBJ_CLSLBLBY, COL_NAME_RECT_OBJ_DIMLBLSTATEID,
                                    COL_NAME_RECT_OBJ_DIMLBLBY, COL_NAME_RECT_OBJ_ZOLBLSTATEID,
                                    COL_NAME_RECT_OBJ_ZOLBLBY, COL_NAME_RECT_OBJ_KINLBLSTATEID,
                                    COL_NAME_RECT_OBJ_LBLBY]
TABLE_NAME_RECTANGULAR_REL = [TABLE_NAME_FILES, TABLE_NAME_ASSOC_TYPE,
                              TABLE_NAME_OBJECT_CLASS,
                              {TABLE_NAME_OBJ_LBL_STATE:COL_NAME_LBL_STATE_LBL_STATE_ID},
                              {TABLE_NAME_USERS:COL_NAME_USER_ID},
                              {TABLE_NAME_OBJ_LBL_STATE:COL_NAME_LBL_STATE_LBL_STATE_ID},
                              {TABLE_NAME_USERS:COL_NAME_USER_ID},
                              {TABLE_NAME_OBJ_LBL_STATE:COL_NAME_LBL_STATE_LBL_STATE_ID},
                              {TABLE_NAME_USERS:COL_NAME_USER_ID},
                              {TABLE_NAME_OBJ_LBL_STATE:COL_NAME_LBL_STATE_LBL_STATE_ID},
                              {TABLE_NAME_USERS:COL_NAME_USER_ID}]
TABLE_NAME_RECTANGULAR_OBJECT_INFO = {NAME: TABLE_NAME_RECTANGULAR_OBJECT,
                                      COL_LIST: TABLE_NAME_RECTANGULAR_OBJECT_COL_LIST,
                                      COL_TYPES:  TABLE_NAME_RECTANGULAR_OBJECT_COL_TYPES,
                                      PK:  TABLE_NAME_RECTANGULAR_OBJECT_PK,
                                      FK: TABLE_NAME_RECTANGULAR_OBJECT_FK,
                                      REL: TABLE_NAME_RECTANGULAR_REL}

# TABLE_NAME_PROBS_CAM = "OBJ_PROBS_CAM"
TABLE_NAME_PROBS_CAM_COL_LIST = [COL_NAME_PROBSCAM_ABSTS, COL_NAME_PROBSCAM_RECTOBJID,
                                 COL_NAME_PROBSCAM_OCCLUDED]

TABLE_NAME_PROBS_CAM_COL_TYPES = [NUMBER, NUMBER, NUMBER]

TABLE_NAME_PROBS_CAM_PK = [COL_NAME_PROBSCAM_ABSTS, COL_NAME_PROBSCAM_RECTOBJID]

TABLE_NAME_PROBS_CAM_FK = [COL_NAME_PROBSCAM_RECTOBJID]

TABLE_NAME_PROBS_CAM_REL = [{TABLE_NAME_RECTANGULAR_OBJECT: COL_NAME_RECT_OBJ_RECTOBJID}]

TABLE_NAME_PROBS_CAM_INFO = {NAME: TABLE_NAME_PROBS_CAM, COL_LIST: TABLE_NAME_PROBS_CAM_COL_LIST,
                             COL_TYPES:  TABLE_NAME_PROBS_CAM_COL_TYPES,
                             PK:  TABLE_NAME_PROBS_CAM_PK, FK: TABLE_NAME_PROBS_CAM_FK,
                             REL: TABLE_NAME_PROBS_CAM_REL}

# TABLE_NAME_EGO_KINEMATICS_ADMA = "OBJ_EGOKINEMATICS_ADMA"
TABLE_NAME_EGO_KINEMATICS_ADMA_COL_LIST = [COL_NAME_EGO_ADMA_MEASID, COL_NAME_EGO_ADMA_KINABSTS,
                                           COL_NAME_EGO_ADMA_VELOCITY_X, COL_NAME_EGO_ADMA_VELOCITY_Y,
                                           COL_NAME_EGO_ADMA_VELOCITY_Z, COL_NAME_EGO_ADMA_ACCELERATION,
                                           COL_NAME_EGO_ADMA_YAWRATE, COL_NAME_EGO_ADMA_PITCH,
                                           COL_NAME_EGO_ADMA_ROLL,
                                           COL_NAME_EGO_ADMA_SUMDIST, COL_NAME_EGO_ADMA_SUMYAW]
TABLE_NAME_EGO_KINEMATICS_ADMA_COL_TYPES = [NUMBER, NUMBER, FLOAT, FLOAT, FLOAT, FLOAT,
                                            FLOAT, FLOAT, FLOAT, FLOAT, FLOAT]
TABLE_NAME_EGO_KINEMATICS_ADMA_PK = [COL_NAME_EGO_ADMA_MEASID, COL_NAME_EGO_ADMA_KINABSTS]
TABLE_NAME_EGO_KINEMATICS_ADMA_FK = [COL_NAME_EGO_ADMA_MEASID]
TABLE_NAME_EGO_KINEMATICS_ADMA_REL = [{TABLE_NAME_FILES: COL_NAME_FILES_MEASID}]
TABLE_NAME_EGO_KINEMATICS_ADMA_INFO = {NAME: TABLE_NAME_EGO_KINEMATICS_ADMA,
                                       COL_LIST: TABLE_NAME_EGO_KINEMATICS_ADMA_COL_LIST,
                                       COL_TYPES:  TABLE_NAME_EGO_KINEMATICS_ADMA_COL_TYPES,
                                       PK:  TABLE_NAME_EGO_KINEMATICS_ADMA_PK,
                                       FK: TABLE_NAME_EGO_KINEMATICS_ADMA_FK,
                                       REL: TABLE_NAME_EGO_KINEMATICS_ADMA_REL}

# TABLE_NAME_KINEMATICS =             "OBJ_KINEMATICS"
TABLE_NAME_KINEMATICS_COL_LIST = [COL_NAME_KINEMATICS_KINABSTS, COL_NAME_KINEMATICS_RECTOBJID,
                                  COL_NAME_KINEMATICS_RELDISTX, COL_NAME_KINEMATICS_RELDISTY,
                                  COL_NAME_KINEMATICS_RELVELX, COL_NAME_KINEMATICS_HEADINGOVERGND]
TABLE_NAME_KINEMATICS_COL_TYPES = [NUMBER, NUMBER, FLOAT, FLOAT, FLOAT, FLOAT]
TABLE_NAME_KINEMATICS_PK = [COL_NAME_KINEMATICS_KINABSTS, COL_NAME_KINEMATICS_RECTOBJID]
TABLE_NAME_KINEMATICS_FK = [COL_NAME_KINEMATICS_RECTOBJID]
TABLE_NAME_KINEMATICS_REL = [TABLE_NAME_RECTANGULAR_OBJECT]
TABLE_NAME_KINEMATICS_INFO = {NAME: TABLE_NAME_KINEMATICS, COL_LIST: TABLE_NAME_KINEMATICS_COL_LIST,
                              PK: TABLE_NAME_KINEMATICS_PK, REL: TABLE_NAME_KINEMATICS_REL,
                              FK: TABLE_NAME_KINEMATICS_FK, COL_TYPES: TABLE_NAME_KINEMATICS_COL_TYPES}

# TABLE_NAME_ADMA_KINEMATICS =        "OBJ_KINEMATICSADMA"
TABLE_NAME_ADMA_KINEMATICS_COL_LIST = [COL_NAME_ADMA_KINEMATICS_RECTOBJID, COL_NAME_ADMA_KINEMATICS_KINABSTS,
                                       COL_NAME_ADMA_KINEMATICS_RELDISTX, COL_NAME_ADMA_KINEMATICS_RELDISTY,
                                       COL_NAME_ADMA_KINEMATICS_RELVELX, COL_NAME_ADMA_KINEMATICS_RELVELY,
                                       COL_NAME_ADMA_KINEMATICS_ARELX, COL_NAME_ADMA_KINEMATICS_ARELY,
                                       COL_NAME_ADMA_KINEMATICS_HEADINGOG, COL_NAME_ADMA_KINEMATICS_ADMAOK]
TABLE_NAME_ADMA_KINEMATICS_COL_TYPES = [NUMBER, NUMBER, FLOAT, FLOAT, FLOAT,
                                        FLOAT, FLOAT, FLOAT, FLOAT, NUMBER]
TABLE_NAME_ADMA_KINEMATICS_PK = [COL_NAME_ADMA_KINEMATICS_RECTOBJID,
                                 COL_NAME_ADMA_KINEMATICS_KINABSTS]
TABLE_NAME_ADMA_KINEMATICS_FK = [COL_NAME_ADMA_KINEMATICS_RECTOBJID]
TABLE_NAME_ADMA_KINEMATICS_REL = [TABLE_NAME_RECTANGULAR_OBJECT]
TABLE_NAME_ADMA_KINEMATICS_INFO = {NAME: TABLE_NAME_ADMA_KINEMATICS,
                                   COL_LIST: TABLE_NAME_ADMA_KINEMATICS_COL_LIST,
                                   PK: TABLE_NAME_ADMA_KINEMATICS_PK,
                                   REL: TABLE_NAME_ADMA_KINEMATICS_REL,
                                   FK: TABLE_NAME_ADMA_KINEMATICS_FK,
                                   COL_TYPES: TABLE_NAME_ADMA_KINEMATICS_COL_TYPES}

#TABLE_NAME_ACC_LANE_TYPES =         "OBJ_ACCLANETYPES"
TABLE_NAME_ACC_LANE_TYPES_COL_LIST = [COL_NAME_LANE_TYPES_LANE_ID, COL_NAME_LANE_TYPES_LANE_NAME,
                                      COL_NAME_LANE_TYPES_DESCRIPTION]
TABLE_NAME_ACC_LANE_TYPES_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_32, NVARCHAR2 + LEN_2000]
TABLE_NAME_ACC_LANE_TYPES_PK = [COL_NAME_LANE_TYPES_LANE_ID]
TABLE_NAME_ACC_LANE_TYPES_FK = []
TABLE_NAME_ACC_LANE_TYPES_REL = []
TABLE_NAME_ACC_LANE_TYPES_INFO = {NAME: TABLE_NAME_ACC_LANE_TYPES,
                                  COL_LIST: TABLE_NAME_ACC_LANE_TYPES_COL_LIST,
                                  PK: TABLE_NAME_ACC_LANE_TYPES_PK,
                                  REL: TABLE_NAME_ACC_LANE_TYPES_REL,
                                  FK: TABLE_NAME_ACC_LANE_TYPES_FK,
                                  COL_TYPES: TABLE_NAME_ACC_LANE_TYPES_COL_TYPES}

#TABLE_NAME_ACC_LANE_REL =           "OBJ_ACCLANERELATION"
TABLE_NAME_ACC_LANE_REL_COL_LIST = [COL_NAME_ACC_LANE_REL_ACCLANERELID, COL_NAME_ACC_LANE_REL_RECTOBJID,
                                    COL_NAME_ACC_LANE_REL_BEGINABSTS, COL_NAME_ACC_LANE_REL_ENDABSTS,
                                    COL_NAME_ACC_LANE_REL_LANEID, COL_NAME_ACC_LANE_REL_LANEASSOCWEIGHT,
                                    COL_NAME_ACC_LANE_REL_LBLSTATEID, COL_NAME_ACC_LANE_REL_LBLMODTIME,
                                    COL_NAME_ACC_LANE_REL_LBLBY]
TABLE_NAME_ACC_LANE_REL_COL_TYPES = [NUMBER, NUMBER, NUMBER, NUMBER, NUMBER,
                                     FLOAT, NUMBER, TIMESTAMP, NUMBER]
TABLE_NAME_ACC_LANE_REL_PK = [COL_NAME_ACC_LANE_REL_ACCLANERELID]
TABLE_NAME_ACC_LANE_REL_FK = [COL_NAME_ACC_LANE_REL_RECTOBJID, COL_NAME_ACC_LANE_REL_LANEID,
                              COL_NAME_ACC_LANE_REL_LBLSTATEID, COL_NAME_ACC_LANE_REL_LBLBY]
TABLE_NAME_ACC_LANE_REL_REL = [TABLE_NAME_RECTANGULAR_OBJECT, TABLE_NAME_ACC_LANE_TYPES,
                               TABLE_NAME_OBJ_LBL_STATE, {TABLE_NAME_USERS:COL_NAME_USER_ID}]
TABLE_NAME_ACC_LANE_REL_INFO = {NAME: TABLE_NAME_ACC_LANE_REL,
                                COL_LIST: TABLE_NAME_ACC_LANE_REL_COL_LIST,
                                PK: TABLE_NAME_ACC_LANE_REL_PK,
                                REL: TABLE_NAME_ACC_LANE_REL_REL,
                                FK: TABLE_NAME_ACC_LANE_REL_FK,
                                COL_TYPES: TABLE_NAME_ACC_LANE_REL_COL_TYPES}

#TABLE_NAME_TEST_CASE_TYPE =         "OBJ_TESTCASETYPE"
TABLE_NAME_TEST_CASE_TYPE_COL_LIST = [COL_NAME_TEST_CASE_TYPE_ID, COL_NAME_TEST_CASE_TYPE_NAME,
                                      COL_NAME_TEST_CASE_TYPE_DESCRIPTION]
TABLE_NAME_TEST_CASE_TYPE_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_32, NVARCHAR2 + LEN_2000]
TABLE_NAME_TEST_CASE_TYPE_PK = [COL_NAME_TEST_CASE_TYPE_ID]
TABLE_NAME_TEST_CASE_TYPE_FK = []
TABLE_NAME_TEST_CASE_TYPE_REL = []
TABLE_NAME_TEST_CASE_TYPE_INFO = {NAME: TABLE_NAME_TEST_CASE_TYPE,
                                  COL_LIST: TABLE_NAME_TEST_CASE_TYPE_COL_LIST,
                                  PK: TABLE_NAME_TEST_CASE_TYPE_PK,
                                  REL: TABLE_NAME_TEST_CASE_TYPE_REL,
                                  FK: TABLE_NAME_TEST_CASE_TYPE_FK,
                                  COL_TYPES: TABLE_NAME_TEST_CASE_TYPE_COL_TYPES}

#TABLE_NAME_TEST_CASES =             "OBJ_TESTCASES"
TABLE_NAME_TEST_CASES_COL_LIST = [COL_NAME_TEST_CASES_TESTCASEID, COL_NAME_TEST_CASES_TYPEID,
                                  COL_NAME_TEST_CASES_RECTOBJID, COL_NAME_TEST_CASES_BEGINABSTS,
                                  COL_NAME_TEST_CASES_ENDABSTS, COL_NAME_TEST_CASES_LBLSTATEID,
                                  COL_NAME_TEST_CASES_LBLMODTIME, COL_NAME_TEST_CASES_LBLBY]
TABLE_NAME_TEST_CASES_COL_TYPES = [NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, TIMESTAMP]
TABLE_NAME_TEST_CASES_PK = [COL_NAME_TEST_CASES_TESTCASEID]
TABLE_NAME_TEST_CASES_FK = [COL_NAME_TEST_CASES_TYPEID, COL_NAME_TEST_CASES_RECTOBJID,
                            COL_NAME_TEST_CASES_LBLSTATEID, COL_NAME_TEST_CASES_LBLBY]
TABLE_NAME_TEST_CASES_REL = [TABLE_NAME_TEST_CASE_TYPE, TABLE_NAME_RECTANGULAR_OBJECT,
                             TABLE_NAME_OBJ_LBL_STATE, {TABLE_NAME_USERS:COL_NAME_USER_ID}]
TABLE_NAME_TEST_CASES_INFO = {NAME: TABLE_NAME_TEST_CASES, COL_LIST: TABLE_NAME_TEST_CASES_COL_LIST,
                              PK: TABLE_NAME_TEST_CASES_PK, REL: TABLE_NAME_TEST_CASES_REL,
                              FK: TABLE_NAME_TEST_CASES_FK, COL_TYPES: TABLE_NAME_TEST_CASES_COL_TYPES}

# TABLE_NAME_EGO_KINEMATICS =     "Obj_EgoKinematics"
TABLE_NAME_EGO_KINEMATICS_COL_LIST = [COL_NAME_EGO_KINEMATICS_MEASID, COL_NAME_EGO_KINEMATICS_KINABSTS,
                                      COL_NAME_EGO_KINEMATICS_VELOCITY, COL_NAME_EGO_KINEMATICS_ACCELERATION,
                                      COL_NAME_EGO_KINEMATICS_YAWRATE]
TABLE_NAME_EGO_KINEMATICS_COL_TYPES = [NUMBER, NUMBER, FLOAT, FLOAT, FLOAT]
TABLE_NAME_EGO_KINEMATICS_PK = [COL_NAME_EGO_KINEMATICS_MEASID, COL_NAME_EGO_KINEMATICS_KINABSTS]
TABLE_NAME_EGO_KINEMATICS_FK = [COL_NAME_EGO_KINEMATICS_MEASID]
TABLE_NAME_EGO_KINEMATICS_REL = [TABLE_NAME_FILES]
TABLE_NAME_EGO_KINEMATICS_INFO = {NAME: TABLE_NAME_EGO_KINEMATICS,
                                  COL_LIST: TABLE_NAME_EGO_KINEMATICS_COL_LIST,
                                  PK: TABLE_NAME_EGO_KINEMATICS_PK,
                                  REL: TABLE_NAME_EGO_KINEMATICS_REL,
                                  FK: TABLE_NAME_EGO_KINEMATICS_FK,
                                  COL_TYPES: TABLE_NAME_EGO_KINEMATICS_COL_TYPES}

DB_OBJ_TABLE_INFO_LIST = [TABLE_NAME_ASSOC_TYPE_INFO, TABLE_NAME_OBJECT_CLASS_INFO,
                          TABLE_NAME_OBJ_LBL_STATE_INFO,
                          TABLE_NAME_RECTANGULAR_OBJECT_INFO,
                          #TABLE_NAME_PROBS_CAM_INFO,
                          #TABLE_NAME_EGO_KINEMATICS_ADMA_INFO,
                          TABLE_NAME_KINEMATICS_INFO,
                          TABLE_NAME_ADMA_KINEMATICS_INFO, TABLE_NAME_ACC_LANE_TYPES_INFO,
                          TABLE_NAME_ACC_LANE_REL_INFO, TABLE_NAME_TEST_CASE_TYPE_INFO,
                          TABLE_NAME_TEST_CASES_INFO, TABLE_NAME_EGO_KINEMATICS_INFO]
##############################################  ===== LBL ====   #######################################
#TABLE_NAME_TYPES = "LB_Types"
TABLE_NAME_TYPES_COL_LIST = [COL_NAME_TYPES_TYPEID, COL_NAME_TYPES_NAME,
                             COL_NAME_TYPES_DESC, COL_NAME_TYPES_PARENT]
TABLE_NAME_TYPES_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_200, NUMBER]
TABLE_NAME_TYPES_PK = [COL_NAME_TYPES_TYPEID]
TABLE_NAME_TYPES_FK = []
TABLE_NAME_TYPES_REL = []
TABLE_NAME_TYPES_INFO = {NAME: TABLE_NAME_TYPES, COL_LIST: TABLE_NAME_TYPES_COL_LIST,
                         PK: TABLE_NAME_TYPES_PK, REL: TABLE_NAME_TYPES_REL,
                         FK: TABLE_NAME_TYPES_FK, COL_TYPES:  TABLE_NAME_TYPES_COL_TYPES}

#TABLE_NAME_STATES = "LB_States"
TABLE_NAME_STATES_COL_LIST = [COL_NAME_STATES_STATEID, COL_NAME_STATES_NAME, COL_NAME_STATES_DESC,
                              COL_NAME_STATES_VALUE, COL_NAME_STATES_TYPEID]
TABLE_NAME_STATES_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_200, FLOAT, NUMBER]
TABLE_NAME_STATES_PK = [COL_NAME_STATES_STATEID]
TABLE_NAME_STATES_FK = [COL_NAME_STATES_TYPEID]
TABLE_NAME_STATES_REL = [TABLE_NAME_TYPES]
TABLE_NAME_STATES_INFO = {NAME: TABLE_NAME_STATES, COL_LIST: TABLE_NAME_STATES_COL_LIST,
                          PK: TABLE_NAME_STATES_PK, REL: TABLE_NAME_STATES_REL,
                          FK: TABLE_NAME_STATES_FK, COL_TYPES:  TABLE_NAME_STATES_COL_TYPES}

#TABLE_NAME_ATTRIBUTE_NAMES = "LB_AttributeNames"
TABLE_NAME_ATTRIBUTE_NAMES_COL_LIST = [COL_NAME_ATTR_NAMES_LBATTNAMEID,
                                       COL_NAME_ATTR_NAMES_NAME]
TABLE_NAME_ATTRIBUTE_NAMES_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50]
TABLE_NAME_ATTRIBUTE_NAMES_PK = [COL_NAME_ATTR_NAMES_LBATTNAMEID]
TABLE_NAME_ATTRIBUTE_NAMES_FK = []
TABLE_NAME_ATTRIBUTE_NAMES_REL = []
TABLE_NAME_ATTRIBUTE_NAMES_INFO = {NAME: TABLE_NAME_ATTRIBUTE_NAMES,
                                   COL_LIST: TABLE_NAME_ATTRIBUTE_NAMES_COL_LIST,
                                   PK: TABLE_NAME_ATTRIBUTE_NAMES_PK,
                                   REL: TABLE_NAME_ATTRIBUTE_NAMES_REL,
                                   FK: TABLE_NAME_ATTRIBUTE_NAMES_FK,
                                   COL_TYPES:  TABLE_NAME_ATTRIBUTE_NAMES_COL_TYPES}

#TABLE_NAME_LABELS = "LB_Labels"
TABLE_NAME_LABELS_COL_LIST = [COL_NAME_LABELS_LBID, COL_NAME_LABELS_ABSTS, COL_NAME_LABELS_TYPEID,
                              COL_NAME_LABELS_WFID, COL_NAME_LABELS_STATEID, COL_NAME_LABELS_MEASID,
                              COL_NAME_LABELS_USERID, COL_NAME_LABELS_MODDATE]
TABLE_NAME_LABELS_COL_TYPES = [NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, TIMESTAMP]
TABLE_NAME_LABELS_PK = [COL_NAME_LABELS_LBID]
TABLE_NAME_LABELS_FK = [COL_NAME_LABELS_TYPEID, COL_NAME_LABELS_WFID, COL_NAME_LABELS_STATEID,
                        COL_NAME_LABELS_USERID,
                        # COL_NAME_LABELS_MEASID
                        ]
TABLE_NAME_LABELS_REL = [TABLE_NAME_TYPES, TABLE_NAME_WORKFLOW, TABLE_NAME_WORKFLOW, TABLE_NAME_USERS]
TABLE_NAME_LABELS_INFO = {NAME: TABLE_NAME_LABELS, COL_LIST: TABLE_NAME_LABELS_COL_LIST,
                          PK: TABLE_NAME_LABELS_PK, REL: TABLE_NAME_LABELS_REL,
                          FK: TABLE_NAME_LABELS_FK, COL_TYPES:  TABLE_NAME_LABELS_COL_TYPES}

#TABLE_NAME_ATTRIBUTES = "LB_Attributes"
TABLE_NAME_ATTRIBUTES_COL_LIST = [COL_NAME_ATTRIBUTES_LBATTRID, COL_NAME_ATTRIBUTES_LBID,
                                  COL_NAME_ATTRIBUTES_LBATTNAMEID, COL_NAME_ATTRIBUTES_UNITID,
                                  COL_NAME_ATTRIBUTES_VTID, COL_NAME_ATTRIBUTES_VALUE]
TABLE_NAME_ATTRIBUTES_COL_TYPES = [NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, FLOAT]
TABLE_NAME_ATTRIBUTES_PK = [COL_NAME_ATTRIBUTES_LBATTRID]
TABLE_NAME_ATTRIBUTES_FK = [COL_NAME_ATTRIBUTES_LBID, COL_NAME_ATTRIBUTES_LBATTNAMEID,
                            COL_NAME_ATTRIBUTES_UNITID, COL_NAME_ATTRIBUTES_VTID]
TABLE_NAME_ATTRIBUTES_REL = [TABLE_NAME_LABELS, TABLE_NAME_ATTRIBUTE_NAMES,
                             TABLE_NAME_UNITS, TABLE_NAME_VALTYPES]
TABLE_NAME_ATTRIBUTES_INFO = {NAME: TABLE_NAME_ATTRIBUTES, COL_LIST: TABLE_NAME_ATTRIBUTES_COL_LIST,
                              PK: TABLE_NAME_ATTRIBUTES_PK, REL: TABLE_NAME_ATTRIBUTES_REL,
                              FK: TABLE_NAME_ATTRIBUTES_FK, COL_TYPES:  TABLE_NAME_ATTRIBUTES_COL_TYPES}

#TABLE_NAME_RECTOBJIDMAP = "LB_RectObjIDMap"
TABLE_NAME_RECTOBJIDMAP_COL_LIST = [COL_NAME_RECTOBJIDMAP_RECTOBJID,
                                    COL_NAME_RECTOBJIDMAP_LBID
                                    #, COL_NAME_RECTOBJIDMAP_RECTOBJIDMAPID
                                    ]
TABLE_NAME_RECTOBJIDMAP_COL_TYPES = [NUMBER, NUMBER
                                     # ,NUMBER
                                     ]
TABLE_NAME_RECTOBJIDMAP_PK = []
TABLE_NAME_RECTOBJIDMAP_FK = [COL_NAME_RECTOBJIDMAP_RECTOBJID, COL_NAME_RECTOBJIDMAP_LBID]
TABLE_NAME_RECTOBJIDMAP_REL = [TABLE_NAME_RECTANGULAR_OBJECT, TABLE_NAME_LABELS]
TABLE_NAME_RECTOBJIDMAP_INFO = {NAME: TABLE_NAME_RECTOBJIDMAP, COL_LIST: TABLE_NAME_RECTOBJIDMAP_COL_LIST,
                                PK: TABLE_NAME_RECTOBJIDMAP_PK, REL: TABLE_NAME_RECTOBJIDMAP_REL,
                                FK: TABLE_NAME_RECTOBJIDMAP_FK, COL_TYPES:  TABLE_NAME_RECTOBJIDMAP_COL_TYPES}

#TABLE_NAME_ADDINFO = "LB_AdditionalInfo"
TABLE_NAME_ADDINFO_COL_LIST = [COL_NAME_INFO_ID, COL_NAME_INFO_DESC]
TABLE_NAME_ADDINFO_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_250]
TABLE_NAME_ADDINFO_PK = []
TABLE_NAME_ADDINFO_FK = [COL_NAME_INFO_ID]
TABLE_NAME_ADDINFO_REL = [TABLE_NAME_LABELS]
TABLE_NAME_ADDINFO_INFO = {NAME: TABLE_NAME_ADDINFO, COL_LIST: TABLE_NAME_ADDINFO_COL_LIST,
                           PK: TABLE_NAME_ADDINFO_PK, REL: TABLE_NAME_ADDINFO_REL,
                           FK: TABLE_NAME_ADDINFO_FK, COL_TYPES:  TABLE_NAME_ADDINFO_COL_TYPES}

DB_LBL_TABLE_INFO_LIST = [TABLE_NAME_TYPES_INFO, TABLE_NAME_STATES_INFO,
                          TABLE_NAME_ATTRIBUTE_NAMES_INFO, TABLE_NAME_LABELS_INFO,
                          TABLE_NAME_ATTRIBUTES_INFO, TABLE_NAME_RECTOBJIDMAP_INFO,
                          TABLE_NAME_ADDINFO_INFO]
##############################################  ===== VAL ====  #####################################
# TABLE_NAME_TESTRUN                  = "VAL_Testrun"
TABLE_NAME_TESTRUN_COL_LIST = [COL_NAME_TR_ID, COL_NAME_TR_NAME, COL_NAME_TR_DESC,
                               COL_NAME_TR_START, COL_NAME_TR_END, COL_NAME_TR_CHECKPOINT,
                               COL_NAME_TR_USERID, COL_NAME_TR_TYPE_ID, COL_NAME_TR_PARENT,
                               COL_NAME_TR_COLL_NAME, COL_NAME_TR_DELETED, COL_NAME_TR_TRUNLOCK,
                               COL_NAME_TR_PID]
TABLE_NAME_TESTRUN_CLASS_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_200,
                                      DATE, DATE, NVARCHAR2 + LEN_50, NUMBER, NUMBER,
                                      NUMBER, NVARCHAR2 + LEN_30, NUMBER, NUMBER, NUMBER]
TABLE_NAME_TESTRUN_PK = [COL_NAME_TR_ID]
TABLE_NAME_TESTRUN_FK = [COL_NAME_TR_USERID, COL_NAME_TR_TYPE_ID, COL_NAME_TR_PARENT, COL_NAME_TR_PID]
TABLE_NAME_TESTRUN_REL = [TABLE_NAME_USERS, TABLE_NAME_TR_TYPE, TABLE_NAME_TESTRUN, TABLE_NAME_PROJECT]
TABLE_NAME_TESTRUN_INFO = {NAME: TABLE_NAME_TESTRUN,
                           COL_LIST: TABLE_NAME_TESTRUN_COL_LIST,
                           PK: TABLE_NAME_TESTRUN_PK,
                           REL: TABLE_NAME_TESTRUN_REL,
                           FK: TABLE_NAME_TESTRUN_FK,
                           COL_TYPES: TABLE_NAME_TESTRUN_CLASS_COL_TYPES}

# TABLE_NAME_RESULT_TYPES             = "VAL_ResultTypes"
TABLE_NAME_RESULTTYPE_COL_LIST = [COL_NAME_RESULTTYPE_ID, COL_NAME_RESULTTYPE_NAME,
                                  COL_NAME_RESULTTYPE_DESC, COL_NAME_RESULTTYPE_CLASS]
TABLE_NAME_RESULTTYPE_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_200, NVARCHAR2 + LEN_50, ]
TABLE_NAME_RESULTTYPE_PK = [COL_NAME_RESULTTYPE_ID]
TABLE_NAME_RESULTTYPE_FK = []
TABLE_NAME_RESULTTYPE_REL = []

TABLE_NAME_RESULT_TYPES_INFO = {NAME: TABLE_NAME_RESULTTYPE, COL_LIST: TABLE_NAME_RESULTTYPE_COL_LIST,
                                PK: TABLE_NAME_RESULTTYPE_PK, REL: TABLE_NAME_RESULTTYPE_REL,
                                FK: TABLE_NAME_RESULTTYPE_FK, COL_TYPES: TABLE_NAME_RESULTTYPE_COL_TYPES}

# TABLE_NAME_RESULT_DESC              = "VAL_ResultDescriptor"
TABLE_NAME_RESULT_DESC_COL_LIST = [COL_NAME_RESDESC_ID, COL_NAME_RESDESC_NAME, COL_NAME_RESDESC_COLLID,
                                   COL_NAME_RESDESC_RESTYPE_ID, COL_NAME_RESDESC_UNIT_ID,
                                   COL_NAME_RESDESC_PARENT, COL_NAME_RESDESC_REFTAG,
                                   COL_NAME_RESDESC_DOORS_URL, COL_NAME_RESDESC_EXPECTRES,
                                   COL_NAME_RESDESC_DESCRIPTION]
TABLE_NAME_RESULT_DESC_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NUMBER, NUMBER,
                                    NUMBER, NUMBER, NVARCHAR2 + LEN_100,
                                    NVARCHAR2 + LEN_200, NVARCHAR2 + LEN_200, NVARCHAR2 + LEN_2000]
TABLE_NAME_RESULT_DESC_PK = [COL_NAME_RESDESC_ID]
TABLE_NAME_RESULT_DESC_FK = [COL_NAME_RESDESC_COLLID, COL_NAME_RESDESC_RESTYPE_ID,
                             COL_NAME_RESDESC_UNIT_ID]
TABLE_NAME_RESULT_DESC_REL = [TABLE_NAME_COLL, TABLE_NAME_RESULTTYPE, TABLE_NAME_UNITS]

TABLE_NAME_RESULT_DESC_INFO = {NAME: TABLE_NAME_RESULT_DESC, COL_LIST: TABLE_NAME_RESULT_DESC_COL_LIST,
                               PK: TABLE_NAME_RESULT_DESC_PK, REL: TABLE_NAME_RESULT_DESC_REL,
                               FK: TABLE_NAME_RESULT_DESC_FK, COL_TYPES: TABLE_NAME_RESULT_DESC_COL_TYPES}

# TABLE_NAME_EVENTTYPE                = "VAL_EventTypes"
TABLE_NAME_EVENTTYPE_COL_LIST = [COL_NAME_EVENTTYPE_ID, COL_NAME_EVENTTYPE_NAME, COL_NAME_EVENTTYPE_DESC,
                                 COL_NAME_EVENTTYPE_CLASSNAME]
TABLE_NAME_EVENTTYPE_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_200, NVARCHAR2 + LEN_50]
TABLE_NAME_EVENTTYPE_PK = [COL_NAME_EVENTTYPE_ID]
TABLE_NAME_EVENTTYPE_FK = []
TABLE_NAME_EVENTTYPE_REL = []
TABLE_NAME_EVENTTYPE_INFO = {NAME: TABLE_NAME_EVENTTYPE, COL_LIST: TABLE_NAME_EVENTTYPE_COL_LIST,
                             PK: TABLE_NAME_EVENTTYPE_PK, REL: TABLE_NAME_EVENTTYPE_REL,
                             FK: TABLE_NAME_EVENTTYPE_FK, COL_TYPES: TABLE_NAME_EVENTTYPE_COL_TYPES}

#TABLE_NAME_EVENT_ATTR_TYPES = "VAL_EventAttrTypes"
TABLE_NAME_EVENT_ATTR_TYPES_COL_LIST = [COL_NAME_EVENT_ATTR_TYPES_ATTRTYPEID, COL_NAME_EVENT_ATTR_TYPES_NAME,
                                        COL_NAME_EVENT_ATTR_TYPES_DESC, COL_NAME_EVENT_ATTR_TYPES_UNITID,
                                        COL_NAME_EVENT_ATTR_TYPES_PARENT]
TABLE_NAME_EVENT_ATTR_TYPES_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_200, NUMBER, NUMBER]
TABLE_NAME_EVENT_ATTR_TYPES_PK = [COL_NAME_EVENT_ATTR_TYPES_ATTRTYPEID]
TABLE_NAME_EVENT_ATTR_TYPES_FK = [COL_NAME_EVENT_ATTR_TYPES_UNITID, COL_NAME_EVENT_ATTR_TYPES_PARENT]
TABLE_NAME_EVENT_ATTR_TYPES_REL = [TABLE_NAME_UNITS, TABLE_NAME_EVENT_ATTR_TYPES]
TABLE_NAME_EVENT_ATTR_TYPES_INFO = {NAME: TABLE_NAME_EVENT_ATTR_TYPES,
                                    COL_LIST: TABLE_NAME_EVENT_ATTR_TYPES_COL_LIST,
                                    PK: TABLE_NAME_EVENT_ATTR_TYPES_PK,
                                    REL: TABLE_NAME_EVENT_ATTR_TYPES_REL,
                                    FK: TABLE_NAME_EVENT_ATTR_TYPES_FK,
                                    COL_TYPES: TABLE_NAME_EVENT_ATTR_TYPES_COL_TYPES}

# TABLE_NAME_RESULT_ASSESSMENT        = "VAL_Assessment"
TABLE_NAME_ASSESSMENT_COL_LIST = [COL_NAME_ASS_ID, COL_NAME_ASS_USER_ID, COL_NAME_ASS_COMMENT,
                                  COL_NAME_ASS_WFID, COL_NAME_ASS_DATE, COL_NAME_ASS_ASSSTID]
TABLE_NAME_ASSESSMENT_COL_TYPES = [NUMBER, NUMBER, NVARCHAR2 + LEN_50, NUMBER, DATE, NUMBER]
TABLE_NAME_ASSESSMENT_PK = [COL_NAME_ASS_ID]
TABLE_NAME_ASSESSMENT_FK = [COL_NAME_ASS_WFID, COL_NAME_ASS_ASSSTID]  # COL_NAME_ASS_USER_ID,
TABLE_NAME_ASSESSMENT_REL = [TABLE_NAME_WORKFLOW, TABLE_NAME_ASSESSMENT_STATE]
TABLE_NAME_ASSESSMENT_INFO = {NAME: TABLE_NAME_ASSESSMENT, COL_LIST: TABLE_NAME_ASSESSMENT_COL_LIST,
                              PK: TABLE_NAME_ASSESSMENT_PK, REL: TABLE_NAME_ASSESSMENT_REL,
                              FK: TABLE_NAME_ASSESSMENT_FK, COL_TYPES: TABLE_NAME_ASSESSMENT_COL_TYPES}

#TABLE_NAME_EVENTS = "VAL_Events"
TABLE_NAME_EVENTS_COL_LIST = [COL_NAME_EVENTS_SEID, COL_NAME_EVENTS_BEGINABSTS,
                              COL_NAME_EVENTS_ENDABSTS, COL_NAME_EVENTS_START_IDX,
                              COL_NAME_EVENTS_STOP_IDX, COL_NAME_EVENTS_MEASID,
                              COL_NAME_EVENTS_TRID, COL_NAME_EVENTS_EVENTTYPEID,
                              COL_NAME_EVENTS_RESASSID, COL_NAME_EVENTS_RDID]

TABLE_NAME_EVENTS_COL_TYPES = [NUMBER, NUMBER, NUMBER, NUMBER, NUMBER,
                               NUMBER, NUMBER, NUMBER, NUMBER, NUMBER]
TABLE_NAME_EVENTS_PK = [COL_NAME_EVENTS_SEID]
TABLE_NAME_EVENTS_FK = [COL_NAME_EVENTS_EVENTTYPEID, COL_NAME_EVENTS_RESASSID,
                        COL_NAME_EVENTS_TRID]   # COL_NAME_EVENTS_RDID
TABLE_NAME_EVENTS_REL = [TABLE_NAME_EVENTTYPE, TABLE_NAME_ASSESSMENT,
                         TABLE_NAME_TESTRUN]   # TABLE_NAME_RESULT_DESC

TABLE_NAME_EVENTS_INFO = {NAME: TABLE_NAME_EVENTS, COL_LIST: TABLE_NAME_EVENTS_COL_LIST,
                          PK: TABLE_NAME_EVENTS_PK, REL: TABLE_NAME_EVENTS_REL,
                          FK: TABLE_NAME_EVENTS_FK, COL_TYPES: TABLE_NAME_EVENTS_COL_TYPES}

#TABLE_NAME_EVENT_DETAILS = "VAL_EventDetails"
TABLE_NAME_EVENT_DETAILS_COL_LIST = [COL_NAME_EVENT_DET_EDID, COL_NAME_EVENT_DET_ABSTS,
                                     COL_NAME_EVENT_DET_SEID]
TABLE_NAME_EVENT_DETAILS_COL_TYPES = [NUMBER, NUMBER, NUMBER]
TABLE_NAME_EVENT_DETAILS_PK = [COL_NAME_EVENT_DET_EDID]
TABLE_NAME_EVENT_DETAILS_FK = [COL_NAME_EVENT_DET_SEID]
TABLE_NAME_EVENT_DETAILS_REL = [TABLE_NAME_EVENTS]
TABLE_NAME_EVENT_DETAILS_INFO = {NAME: TABLE_NAME_EVENT_DETAILS,
                                 COL_LIST: TABLE_NAME_EVENT_DETAILS_COL_LIST,
                                 PK: TABLE_NAME_EVENT_DETAILS_PK,
                                 REL: TABLE_NAME_EVENT_DETAILS_REL,
                                 FK: TABLE_NAME_EVENT_DETAILS_FK,
                                 COL_TYPES: TABLE_NAME_EVENT_DETAILS_COL_TYPES}

#TABLE_NAME_EVENT_ATTR = "VAL_EventAttr"
TABLE_NAME_EVENT_ATTR_COL_LIST = [COL_NAME_EVENT_ATTR_ATTRID, COL_NAME_EVENT_ATTR_ATTRTYPEID,
                                  COL_NAME_EVENT_ATTR_VALUE, COL_NAME_EVENT_ATTR_EDID]
TABLE_NAME_EVENT_ATTR_COL_TYPES = [NUMBER, NUMBER, FLOAT, NUMBER]
TABLE_NAME_EVENT_ATTR_PK = [COL_NAME_EVENT_ATTR_ATTRID]
TABLE_NAME_EVENT_ATTR_FK = [COL_NAME_EVENT_ATTR_ATTRTYPEID, COL_NAME_EVENT_ATTR_EDID]
TABLE_NAME_EVENT_ATTR_REL = [TABLE_NAME_EVENT_ATTR_TYPES, TABLE_NAME_EVENT_DETAILS]
TABLE_NAME_EVENT_ATTR_INFO = {NAME: TABLE_NAME_EVENT_ATTR, COL_LIST: TABLE_NAME_EVENT_ATTR_COL_LIST,
                              PK: TABLE_NAME_EVENT_ATTR_PK, REL: TABLE_NAME_EVENT_ATTR_REL,
                              FK: TABLE_NAME_EVENT_ATTR_FK, COL_TYPES: TABLE_NAME_EVENT_ATTR_COL_TYPES}

#TABLE_NAME_EVENT_IMAGE = "VAL_EventImage"

TABLE_NAME_EVENT_IMAGE_COL_LIST = [COL_NAME_EVENT_IMG_ATTRID, COL_NAME_EVENT_IMG_IMAGE,
                                   COL_NAME_EVENT_IMG_TITLE, COL_NAME_EVENT_IMG_FORMAT]
TABLE_NAME_EVENT_IMAGE_COL_TYPES = [NUMBER, BLOB, NVARCHAR2 + LEN_60, NVARCHAR2 + LEN_4]
TABLE_NAME_EVENT_IMAGE_PK = []
TABLE_NAME_EVENT_IMAGE_FK = [COL_NAME_EVENT_IMG_ATTRID]
TABLE_NAME_EVENT_IMAGE_REL = [TABLE_NAME_EVENT_ATTR]
TABLE_NAME_EVENT_IMAGE_INFO = {NAME: TABLE_NAME_EVENT_IMAGE, COL_LIST: TABLE_NAME_EVENT_IMAGE_COL_LIST,
                               PK: TABLE_NAME_EVENT_IMAGE_PK, REL: TABLE_NAME_EVENT_IMAGE_REL,
                               FK: TABLE_NAME_EVENT_IMAGE_FK, COL_TYPES: TABLE_NAME_EVENT_IMAGE_COL_TYPES}

# TABLE_NAME_VRKEY                    = "VAL_Keys"
TABLE_NAME_VRKEY_COL_LIST = [COL_NAME_VRKEY_ID, COL_NAME_VRKEY_NAME, COL_NAME_VRKEY_DESCRIPTION]
TABLE_NAME_VRKEY_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_200]
TABLE_NAME_VRKEY_PK = [COL_NAME_VRKEY_ID]
TABLE_NAME_VRKEY_FK = []
TABLE_NAME_VRKEY_REL = []
TABLE_NAME_VRKEY_INFO = {NAME: TABLE_NAME_VRKEY, COL_LIST: TABLE_NAME_VRKEY_COL_LIST,
                         PK: TABLE_NAME_VRKEY_PK, REL: TABLE_NAME_VRKEY_REL,
                         FK: TABLE_NAME_VRKEY_FK, COL_TYPES: TABLE_NAME_VRKEY_COL_TYPES}

# TABLE_NAME_VRKEY_MAP                = "VAL_ConstraintsMap"
TABLE_NAME_VRKEY_MAP_COL_LIST = [COL_NAME_VRKEY_MAP_ID, COL_NAME_VRKEY_MAP_RDID]
TABLE_NAME_VRKEY_MAP_COL_TYPES = [NUMBER, NUMBER]
TABLE_NAME_VRKEY_MAP_PK = []
TABLE_NAME_VRKEY_MAP_FK = [COL_NAME_VRKEY_MAP_ID, COL_NAME_VRKEY_MAP_RDID]
TABLE_NAME_VRKEY_MAP_REL = [TABLE_NAME_VRKEY, TABLE_NAME_RESULT_DESC]
TABLE_NAME_VRKEY_MAP_INFO = {NAME: TABLE_NAME_VRKEY_MAP, COL_LIST: TABLE_NAME_VRKEY_MAP_COL_LIST,
                             PK: TABLE_NAME_VRKEY_MAP_PK, REL: TABLE_NAME_VRKEY_MAP_REL,
                             FK: TABLE_NAME_VRKEY_MAP_FK, COL_TYPES: TABLE_NAME_VRKEY_MAP_COL_TYPES}

# TABLE_NAME_RESULT                   = "VAL_Result"
TABLE_NAME_RESULT_COL_LIST = [COL_NAME_RES_ID, COL_NAME_RES_TESTRUN_ID, COL_NAME_RES_RESDESC_ID,
                              COL_NAME_RES_VALUE, COL_NAME_RES_MEASID, COL_NAME_RES_RESASSID]
TABLE_NAME_RESULT_COL_TYPES = [NUMBER, NUMBER, NUMBER, FLOAT, NUMBER, NUMBER]
TABLE_NAME_RESULT_PK = [COL_NAME_RES_ID]
TABLE_NAME_RESULT_FK = [COL_NAME_RES_TESTRUN_ID, COL_NAME_RES_RESDESC_ID,
                        COL_NAME_RES_MEASID, COL_NAME_RES_RESASSID]
TABLE_NAME_RESULT_REL = [TABLE_NAME_TESTRUN, TABLE_NAME_RESULT_DESC,
                         TABLE_NAME_FILES, TABLE_NAME_ASSESSMENT]
TABLE_NAME_RESULT_INFO = {NAME: TABLE_NAME_RESULT, COL_LIST: TABLE_NAME_RESULT_COL_LIST,
                          PK: TABLE_NAME_RESULT_PK, REL: TABLE_NAME_RESULT_REL,
                          FK: TABLE_NAME_RESULT_FK, COL_TYPES: TABLE_NAME_RESULT_COL_TYPES}

# TABLE_NAME_RESULT_VALUES            = "VAL_ResultValues"
TABLE_NAME_RESULT_VALUES_COL_LIST = [COL_NAME_RESVAL_SUBID, COL_NAME_RESVAL_ID, COL_NAME_RESVAL_VALUE]
TABLE_NAME_RESULT_VALUES_COL_TYPES = [NUMBER, NUMBER, FLOAT]
TABLE_NAME_RESULT_VALUES_PK = [COL_NAME_RESVAL_SUBID]
TABLE_NAME_RESULT_VALUES_FK = [COL_NAME_RESVAL_ID]
TABLE_NAME_RESULT_VALUES_REL = [TABLE_NAME_RESULT]
TABLE_NAME_RESULT_VALUES_INFO = {NAME: TABLE_NAME_RESULT_VALUES,
                                 COL_LIST: TABLE_NAME_RESULT_VALUES_COL_LIST,
                                 PK: TABLE_NAME_RESULT_VALUES_PK,
                                 REL: TABLE_NAME_RESULT_VALUES_REL,
                                 FK: TABLE_NAME_RESULT_VALUES_FK,
                                 COL_TYPES: TABLE_NAME_RESULT_VALUES_COL_TYPES}

# TABLE_NAME_RESULT_IMAGE             = "VAL_ResultImage"
TABLE_NAME_RESULT_IMAGE_COL_LIST = [COL_NAME_RESIMG_ID, COL_NAME_RESIMG_IMAGE, COL_NAME_RESIMG_TITLE,
                                    COL_NAME_RESIMG_FORMAT]
TABLE_NAME_RESULT_IMAGE_COL_TYPES = [NUMBER, BLOB, NVARCHAR2 + LEN_60, NVARCHAR2 + LEN_4]
TABLE_NAME_RESULT_IMAGE_PK = []
TABLE_NAME_RESULT_IMAGE_FK = [COL_NAME_RESIMG_ID]
TABLE_NAME_RESULT_IMAGE_REL = [TABLE_NAME_RESULT]
TABLE_NAME_RESULT_IMAGE_INFO = {NAME: TABLE_NAME_RESULT_IMAGE,
                                COL_LIST: TABLE_NAME_RESULT_IMAGE_COL_LIST,
                                PK: TABLE_NAME_RESULT_IMAGE_PK,
                                REL: TABLE_NAME_RESULT_IMAGE_REL,
                                FK: TABLE_NAME_RESULT_IMAGE_FK,
                                COL_TYPES: TABLE_NAME_RESULT_IMAGE_COL_TYPES}

# TABLE_NAME_RESULT_MESSAGES          = "VAL_ResultMessages"
TABLE_NAME_RESULT_MESSAGES_COL_LIST = [COL_NAME_RESMESS_SUBID, COL_NAME_RESMESS_ID,
                                       COL_NAME_RESMESS_MESS]
TABLE_NAME_RESULT_MESSAGES_COL_TYPES = [NUMBER, NUMBER, NVARCHAR2 + LEN_50]
TABLE_NAME_RESULT_MESSAGES_PK = []  # COL_NAME_RESMESS_SUBID, COL_NAME_RESMESS_ID]
TABLE_NAME_RESULT_MESSAGES_FK = [COL_NAME_RESMESS_ID]
TABLE_NAME_RESULT_MESSAGES_REL = [TABLE_NAME_RESULT]
TABLE_NAME_RESULT_MESSAGES_INFO = {NAME: TABLE_NAME_RESULT_MESSAGES,
                                   COL_LIST: TABLE_NAME_RESULT_MESSAGES_COL_LIST,
                                   PK: TABLE_NAME_RESULT_MESSAGES_PK,
                                   REL: TABLE_NAME_RESULT_MESSAGES_REL,
                                   FK: TABLE_NAME_RESULT_MESSAGES_FK,
                                   COL_TYPES: TABLE_NAME_RESULT_MESSAGES_COL_TYPES}

# TABLE_NAME_RESULT_LABEL_MAP         = "VAL_ResultLabelMap"
TABLE_NAME_RESULT_LABEL_MAP_COL_LIST = [COL_NAME_RESLB_RESID, COL_NAME_RESLB_LBID]
TABLE_NAME_RESULT_LABEL_MAP_COL_TYPES = [NUMBER, NUMBER]
TABLE_NAME_RESULT_LABEL_MAP_PK = []
TABLE_NAME_RESULT_LABEL_MAP_FK = [COL_NAME_RESLB_RESID]
TABLE_NAME_RESULT_LABEL_MAP_REL = [TABLE_NAME_RESULT]
TABLE_NAME_RESULT_LABEL_MAP_INFO = {NAME: TABLE_NAME_RESULT_LABEL_MAP,
                                    COL_LIST: TABLE_NAME_RESULT_LABEL_MAP_COL_LIST,
                                    PK: TABLE_NAME_RESULT_LABEL_MAP_PK,
                                    REL: TABLE_NAME_RESULT_LABEL_MAP_REL,
                                    FK: TABLE_NAME_RESULT_LABEL_MAP_FK,
                                    COL_TYPES: TABLE_NAME_RESULT_LABEL_MAP_COL_TYPES}

DB_VAL_TABLE_INFO_LIST = [TABLE_NAME_TESTRUN_INFO, TABLE_NAME_RESULT_TYPES_INFO,
                          TABLE_NAME_RESULT_DESC_INFO, TABLE_NAME_EVENTTYPE_INFO,
                          TABLE_NAME_EVENT_ATTR_TYPES_INFO, TABLE_NAME_ASSESSMENT_INFO,
                          TABLE_NAME_EVENTS_INFO, TABLE_NAME_EVENT_DETAILS_INFO,
                          TABLE_NAME_EVENT_ATTR_INFO, TABLE_NAME_EVENT_IMAGE_INFO,
                          TABLE_NAME_VRKEY_INFO, TABLE_NAME_VRKEY_MAP_INFO,
                          TABLE_NAME_RESULT_INFO, TABLE_NAME_RESULT_VALUES_INFO,
                          TABLE_NAME_RESULT_IMAGE_INFO, TABLE_NAME_RESULT_MESSAGES_INFO,
                          TABLE_NAME_RESULT_LABEL_MAP_INFO]

#############################################  ===== FCT ====  #######################################################
TABLE_NAME_CRITICALITY_COL_LIST = [COL_NAME_CRITICALITY_CID, COL_NAME_CRITICALITY_NAME, COL_NAME_CRITICALITY_DESC]
TABLE_NAME_CRITICALITY_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_1000]
TABLE_NAME_CRITICALITY_PK = [COL_NAME_CRITICALITY_CID]
TABLE_NAME_CRITICALITY_FK = []
TABLE_NAME_CRITICALITY_REL = []
TABLE_NAME_CRITICALITY_INFO = {NAME: TABLE_NAME_CRITICALITY, COL_LIST: TABLE_NAME_CRITICALITY_COL_LIST,
                               PK: TABLE_NAME_CRITICALITY_PK, REL: TABLE_NAME_CRITICALITY_REL,
                               FK: TABLE_NAME_CRITICALITY_FK,
                               COL_TYPES: TABLE_NAME_CRITICALITY_COL_TYPES}

TABLE_NAME_EGOBEHAVIOUR_COL_LIST = [COL_NAME_EGOBEHAVIOUR_EBID, COL_NAME_EGOBEHAVIOUR_NAME, COL_NAME_EGOBEHAVIOUR_DESC]
TABLE_NAME_EGOBEHAVIOUR_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NVARCHAR2 + LEN_2000]
TABLE_NAME_EGOBEHAVIOUR_PK = [COL_NAME_EGOBEHAVIOUR_EBID]
TABLE_NAME_EGOBEHAVIOUR_FK = []
TABLE_NAME_EGOBEHAVIOUR_REL = []
TABLE_NAME_EGOBEHAVIOUR_INFO = {NAME: TABLE_NAME_EGOBEHAVIOUR, COL_LIST: TABLE_NAME_EGOBEHAVIOUR_COL_LIST,
                                PK: TABLE_NAME_EGOBEHAVIOUR_PK, REL: TABLE_NAME_EGOBEHAVIOUR_REL,
                                FK: TABLE_NAME_EGOBEHAVIOUR_FK,
                                COL_TYPES: TABLE_NAME_EGOBEHAVIOUR_COL_TYPES}

TABLE_NAME_ENVIRONMENT_COL_LIST = [COL_NAME_ENVIRONMENT_ENVID, COL_NAME_ENVIRONMENT_NAME,
                                   COL_NAME_ENVIRONMENT_ENVTYPEID, COL_NAME_ENVIRONMENT_DESC]
TABLE_NAME_ENVIRONMENT_COL_TYPES = [NUMBER, NVARCHAR2 + LEN_50, NUMBER, NVARCHAR2 + LEN_1000]
TABLE_NAME_ENVIRONMENT_PK = [COL_NAME_ENVIRONMENT_ENVID]
TABLE_NAME_ENVIRONMENT_FK = []
TABLE_NAME_ENVIRONMENT_REL = []
TABLE_NAME_ENVIRONMENT_INFO = {NAME: TABLE_NAME_ENVIRONMENT, COL_LIST: TABLE_NAME_ENVIRONMENT_COL_LIST,
                               PK: TABLE_NAME_ENVIRONMENT_PK, REL: TABLE_NAME_ENVIRONMENT_REL,
                               FK: TABLE_NAME_ENVIRONMENT_FK,
                               COL_TYPES: TABLE_NAME_ENVIRONMENT_COL_TYPES}

TABLE_NAME_SCENARIO_COL_LIST = [COL_NAME_SCENARIO_SCENARIOID, COL_NAME_SCENARIO_MEASID,
                                COL_NAME_SCENARIO_STARTABSTS, COL_NAME_SCENARIO_ENDABSTS,
                                COL_NAME_SCENARIO_LBLCOMMENT, COL_NAME_SCENARIO_ENV_INFRASTRUCTURE,
                                COL_NAME_SCENARIO_ENV_LIGHT_CONDITION, COL_NAME_SCENARIO_ENV_WEATHER_CONDITION,
                                COL_NAME_SCENARIO_ENV_DATAINTEGRITY, COL_NAME_SCENARIO_LABELER_CRITICALITY,
                                COL_NAME_SCENARIO_VEHICLE_CRITICALITY, COL_NAME_SCENARIO_DRIVER_CRITICALITY,
                                COL_NAME_SCENARIO_LBLSTATEID, COL_NAME_SCENARIO_LBLBY, COL_NAME_SCENARIO_LBLTIME,
                                COL_NAME_SCENARIO_PID, COL_NAME_SCENARIO_RECTOBJID, COL_NAME_SCENARIO_EGO_BEHAVIOR,
                                COL_NAME_SCENARIO_REL_EGO_BEHAVIOR, COL_NAME_SCENARIO_OBJ_DYNAMIC,
                                COL_NAME_SCENARIO_OBJ_TYPE, COL_NAME_SCENARIO_OBJ_BEHAVIOR]
TABLE_NAME_SCENARIO_COL_TYPES = [NUMBER, NUMBER, NUMBER, NUMBER, NVARCHAR2 + LEN_2000, NUMBER, NUMBER, NUMBER, NUMBER,
                                 NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, TIMESTAMP, NUMBER, NUMBER, NUMBER,
                                 NUMBER, NUMBER, NUMBER, NUMBER]
TABLE_NAME_SCENARIO_PK = [COL_NAME_SCENARIO_SCENARIOID]
TABLE_NAME_SCENARIO_FK = [COL_NAME_SCENARIO_MEASID, COL_NAME_SCENARIO_LABELER_CRITICALITY,
                          COL_NAME_SCENARIO_VEHICLE_CRITICALITY, COL_NAME_SCENARIO_DRIVER_CRITICALITY,
                          COL_NAME_SCENARIO_LBLSTATEID, COL_NAME_SCENARIO_LBLBY, COL_NAME_SCENARIO_PID,
                          COL_NAME_SCENARIO_RECTOBJID, COL_NAME_SCENARIO_EGO_BEHAVIOR,
                          COL_NAME_SCENARIO_ENV_INFRASTRUCTURE, COL_NAME_SCENARIO_ENV_LIGHT_CONDITION,
                          COL_NAME_SCENARIO_ENV_WEATHER_CONDITION, COL_NAME_SCENARIO_ENV_DATAINTEGRITY,
                          COL_NAME_SCENARIO_REL_EGO_BEHAVIOR, COL_NAME_SCENARIO_OBJ_DYNAMIC,
                          COL_NAME_SCENARIO_OBJ_TYPE, COL_NAME_SCENARIO_OBJ_BEHAVIOR]
TABLE_NAME_SCENARIO_REL = [{TABLE_NAME_FILES: COL_NAME_FILES_MEASID},
                           {TABLE_NAME_CRITICALITY: COL_NAME_CRITICALITY_CID},
                           {TABLE_NAME_CRITICALITY: COL_NAME_CRITICALITY_CID},
                           {TABLE_NAME_CRITICALITY: COL_NAME_CRITICALITY_CID},
                           {TABLE_NAME_WORKFLOW: COL_NAME_WORKFLOW_WFID}, {TABLE_NAME_USERS: COL_NAME_USER_ID},
                           {TABLE_NAME_PROJECT: COL_NAME_PROJECT_PID},
                           {TABLE_NAME_RECTANGULAR_OBJECT: COL_NAME_RECT_OBJ_RECTOBJID},
                           {TABLE_NAME_PROJECT: COL_NAME_PROJECT_PID},
                           {TABLE_NAME_EGOBEHAVIOUR: COL_NAME_EGOBEHAVIOUR_EBID},
                           {TABLE_NAME_ENVIRONMENT: COL_NAME_ENVIRONMENT_ENVID},
                           {TABLE_NAME_ENVIRONMENT: COL_NAME_ENVIRONMENT_ENVID},
                           {TABLE_NAME_ENVIRONMENT: COL_NAME_ENVIRONMENT_ENVID},
                           {TABLE_NAME_ENVIRONMENT: COL_NAME_ENVIRONMENT_ENVID},
                           {TABLE_NAME_ENVIRONMENT: COL_NAME_ENVIRONMENT_ENVID},
                           {TABLE_NAME_ENVIRONMENT: COL_NAME_ENVIRONMENT_ENVID},
                           {TABLE_NAME_ENVIRONMENT: COL_NAME_ENVIRONMENT_ENVID},
                           {TABLE_NAME_ENVIRONMENT: COL_NAME_ENVIRONMENT_ENVID}]
TABLE_NAME_SCENARIO_INFO = {NAME: TABLE_NAME_SCENARIO, COL_LIST: TABLE_NAME_SCENARIO_COL_LIST,
                            PK: TABLE_NAME_SCENARIO_PK, REL: TABLE_NAME_SCENARIO_REL,
                            FK: TABLE_NAME_SCENARIO_FK,
                            COL_TYPES: TABLE_NAME_SCENARIO_COL_TYPES}
DB_FCT_TABLE_INFO_LIST = [TABLE_NAME_CRITICALITY_INFO, TABLE_NAME_EGOBEHAVIOUR_INFO, TABLE_NAME_ENVIRONMENT_INFO,
                          TABLE_NAME_SCENARIO_INFO]

#############################################

ADAS_DB_TABLE_INFO_LIST = DB_GBL_TABLE_INFO_LIST + DB_CAT_TABLE_INFO_LIST + \
    DB_PAR_TABLE_INFO_LIST + DB_OBJ_TABLE_INFO_LIST + \
    DB_LBL_TABLE_INFO_LIST + DB_VAL_TABLE_INFO_LIST + DB_FCT_TABLE_INFO_LIST

NOT_IN_DB = {"DEV_ARS4XX_ADMIN": [TABLE_NAME_EGO_KINEMATICS_ADMA]}

ADAS_DATABASE_MODULE_NAMES = [GBL, CAT, PAR, OBJ, LBL, VAL]
MODULE_TABLEINFOMAP = {GBL: DB_GBL_TABLE_INFO_LIST, CAT: DB_CAT_TABLE_INFO_LIST,
                       PAR: DB_PAR_TABLE_INFO_LIST, OBJ: DB_OBJ_TABLE_INFO_LIST,
                       LBL: DB_LBL_TABLE_INFO_LIST, VAL: DB_VAL_TABLE_INFO_LIST}

ADAS_DB_INFO = DB_GBL_TABLE_INFO_LIST + DB_CAT_TABLE_INFO_LIST + DB_PAR_TABLE_INFO_LIST + \
    DB_OBJ_TABLE_INFO_LIST + DB_LBL_TABLE_INFO_LIST + DB_VAL_TABLE_INFO_LIST + DB_FCT_TABLE_INFO_LIST

#MODULE_TABLEINFOMAP = {GBL:DB_GBL_TABLE_INFO_LIST, CAT:None,
#                       PAR:None, OBJ:None,
#                       LBL:None, VAL:None}


TABLES_WITH_NO_PK_TRIGGER = [TABLE_NAME_RESULT_VALUES, TABLE_NAME_RESULT_MESSAGES]
# TABLES_WITH_NO_PK_TRIGGER = [TABLE_NAME_EGO_KINEMATICS, TABLE_NAME_KINEMATICS, TABLE_NAME_ADMA_KINEMATICS]
EXCLUDE = {}

TRUN_DATA_SETTING = [{COL_NAME_TR_ID:[TABLE_NAME_TESTRUN_INFO]},
                     {COL_NAME_ASS_ID:[TABLE_NAME_ASSESSMENT_INFO]},
                     {COL_NAME_TR_ID:[TABLE_NAME_RESULT_INFO, TABLE_NAME_EVENTS_INFO]},
                     {COL_NAME_EVENT_DET_SEID:[TABLE_NAME_EVENT_DETAILS_INFO]},
                     {COL_NAME_EVENT_DET_EDID:[TABLE_NAME_EVENT_ATTR_INFO]},
                     {COL_NAME_EVENT_IMG_ATTRID:[TABLE_NAME_EVENT_IMAGE_INFO]},
                     {COL_NAME_RES_ID:[TABLE_NAME_RESULT_VALUES_INFO, TABLE_NAME_RESULT_IMAGE_INFO,
                                       TABLE_NAME_RESULT_MESSAGES_INFO, TABLE_NAME_RESULT_LABEL_MAP_INFO]},
                     ]

"""
CHANGE LOG:
-----------
$Log: adas_db_def.py  $
Revision 1.1 2021/12/13 17:56:31CET Wang, David (Wangd3) 
Initial revision
Member added to project /ADAS/Projects/MFC5xx/MFC5J3/06_Algorithm/DPU/04_Engineering/02_Development_Tools/algo_build_cmd/stk/db/mdl/project.pj
Revision 1.12 2013/12/13 13:36:05CET Zafar, Sohaib (uidu6396) 
New columns in FCT_SCENARIO
- Added comments -  uidu6396 [Dec 13, 2013 1:36:05 PM CET]
Change Package : 208164:1 http://mks-psad:7002/im/viewissue?selection=208164
Revision 1.11 2013/12/05 15:58:07CET Ahmed-EXT, Zaheer (uidu7634)
Add Testrun Data Dependency setting used for trun delete utilty and import export utility
--- Added comments ---  uidu7634 [Dec 5, 2013 3:58:07 PM CET]
Change Package : 210017:1 http://mks-psad:7002/im/viewissue?selection=210017
Revision 1.10 2013/11/28 12:13:34CET Zafar-EXT, Sohaib (uidu6396)
Removing pep8 errors
--- Added comments ---  uidu6396 [Nov 28, 2013 12:13:34 PM CET]
Change Package : 208164:1 http://mks-psad:7002/im/viewissue?selection=208164
Revision 1.9 2013/11/28 11:23:34CET Zafar-EXT, Sohaib (uidu6396)
DB.FCT imported
--- Added comments ---  uidu6396 [Nov 28, 2013 11:23:34 AM CET]
Change Package : 208164:1 http://mks-psad:7002/im/viewissue?selection=208164
Revision 1.8 2013/11/18 09:32:12CET Ahmed-EXT, Zaheer (uidu7634)
Fixed pep8 and pylint errors
--- Added comments ---  uidu7634 [Nov 18, 2013 9:32:13 AM CET]
Change Package : 203293:2 http://mks-psad:7002/im/viewissue?selection=203293
Revision 1.7 2013/11/04 09:07:42CET Ahmed-EXT, Zaheer (uidu7634)
Complete Defination of Db Schema
--- Added comments ---  uidu7634 [Nov 4, 2013 9:07:42 AM CET]
Change Package : 203293:1 http://mks-psad:7002/im/viewissue?selection=203293
Revision 1.6 2013/04/25 14:48:09CEST Mertens, Sven (uidv7805)
adding defines for additional objData Tables
--- Added comments ---  uidv7805 [Apr 25, 2013 2:48:10 PM CEST]
Change Package : 179495:2 http://mks-psad:7002/im/viewissue?selection=179495
Revision 1.5 2013/04/22 12:54:18CEST Raedler, Guenther (uidt9430)
- added class name column into val_restype table description
--- Added comments ---  uidt9430 [Apr 22, 2013 12:54:19 PM CEST]
Change Package : 180569:1 http://mks-psad:7002/im/viewissue?selection=180569
Revision 1.4 2013/03/27 09:04:36CET Mertens, Sven (uidv7805)
pylint: reorg of imports, rename of some variables
--- Added comments ---  uidv7805 [Mar 27, 2013 9:04:36 AM CET]
Change Package : 178224:1 http://mks-psad:7002/im/viewissue?selection=178224
Revision 1.3 2013/02/26 15:53:07CET Raedler, Guenther (uidt9430)
- added tests for gbl and val
--- Added comments ---  uidt9430 [Feb 26, 2013 3:53:07 PM CET]
Change Package : 174385:1 http://mks-psad:7002/im/viewissue?selection=174385
Revision 1.2 2013/02/20 09:41:56CET Raedler, Guenther (uidt9430)
- added gbl testes
--- Added comments ---  uidt9430 [Feb 20, 2013 9:41:57 AM CET]
Change Package : 174385:1 http://mks-psad:7002/im/viewissue?selection=174385
Revision 1.1 2013/02/19 14:19:28CET Raedler, Guenther (uidt9430)
Initial revision
Member added to project /nfs/projekte1/REPOSITORY/Base_Development/05_Algorithm
/STK_ScriptingToolKit/05_Testing/05_Test_Environment/moduletest/test_db/project.pj
"""
