// Copyright (C) Continental AG
// All Rights Reserved
// COMPONENT: OS
/// @file
/// @brief This file contains all taskIDs used for RTA
///        It is generated by the RtaTaskIdLutGenerator. 

#ifndef OS_RTA_TASK_IDS_H
#define OS_RTA_TASK_IDS_H


//Generated file - no manual changes please!****************************************************************************

//___GENERATOR_TAG___RTA_TASK_ENUM___START___
typedef enum
{
  OS_RTA_TASKID_Interrupts            =   0, 
  OS_RTA_TASKID_Bsw5ms                =   1, 
  OS_RTA_TASKID_Bsw10ms               =   2, 
  OS_RTA_TASKID_Bsw20ms               =   3, 
  OS_RTA_TASKID_Appl5ms               =   4, 
  OS_RTA_TASKID_Appl10ms              =   5, 
  OS_RTA_TASKID_Appl20ms              =   6, 
  OS_RTA_TASKID_Appl50ms              =   7, 
  OS_RTA_TASKID_OperationInovkedProxy =   8, 
  OS_RTA_TASKID_Default               =   9, 
  OS_RTA_TASKID_InitAppl              =  10, 
  OS_RTA_TASKID_Appl60ms              =  11 
}OS_t_RtaTaskIDs;
//___GENERATOR_TAG___RTA_TASK_ENUM___END___

//Generated file - no manual changes please!****************************************************************************


#endif //OS_RTA_TASK_IDS_H