IF "%TARGET%"=="" SET TARGET=TRICORE
IF "%DERIVATE%"=="" SET DERIVATE=TC38XQ
IF "%TOOLCHAIN%"=="" SET TOOLCHAIN=tasking
IF [%TOOLPATH_COMPILER%]==[] SET TOOLPATH_COMPILER=

IF [%TRESOS_BASE%]==[] SET TRESOS_BASE=C:/EB/tresos
IF [%PLUGINS_BASE%]==[] SET PLUGINS_BASE=%TRESOS_BASE%/plugins
