/************************************************************
  Autogenerated C-Header File (c) Continental 2017
  PROJECT       : LCF100
  COMPONENT     : LCF
  TASK          : Vehicle (Veh)
  SUB-COMPONENT : LATDMC
  MODULES       : 
  FILE NAME     : LATDMCVEH_data.h
  AUTHOR        : SubComponent_AuxCodeGen
  VERSION       : 3.0

  Version Management Information
  $Workfile: $
  $Revision: 1.2 $
  $Author: Asong, Wedndah Asaha (uidj2187) $
  $Date: 2019/03/15 16:51:28CET $
 ***********************************************************/

#ifndef _LATDMC_DATA_H_
#define _LATDMC_DATA_H_

/*---------------------------------------------------------*
   I N C L U D E S
**---------------------------------------------------------*/

#include "latdmc_wrp.h"

#endif /* _LATDMC_DATA_H_ */
