/************************************************************
  Autogenerated C-Header File (c) Continental 2017
  PROJECT       : LCF100
  COMPONENT     : LCF
  TASK          : Vehicle (Veh)
  SUB-COMPONENT : LATDMC
  MODULES       : 
  FILE NAME     : LATDMC_type.h
  AUTHOR        : SubComponent_AuxCodeGen
  VERSION       : 3.0

  Version Management Information
  $Workfile: $
  $Revision: 1.1 $
  $Author: Feick, Stefan (uidw0691) $
  $Date: 2018/02/07 09:45:53CET $
 ***********************************************************/

#ifndef _LATDMC_TYPE_H_
#define _LATDMC_TYPE_H_

/*---------------------------------------------------------*
   D U M M Y   F I L E
 *---------------------------------------------------------*/

#endif /* _LATDMC_TYPE_H_ */
