/**********************************************************************************************************************
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *          File:  CP_AP_ModeManager.c
 *     Workspace:  D:/Sandboxes/MFC300/MFC300_Base/05_Software/MCU/03_Design/05_DaVinci/mfc310_SMPC.dev
 *   ECU-Project:  MPC
 *     SW-C Type:  CP_AP_ModeManager
 *  Generated at:  Thu Jul  7 11:16:20 2011
 *
 *     Generator:  MICROSAR RTE Generator Version 2.17.3
 *       License:  License CBD1000091 valid for CBD1000091 A.D.C. GmbH Continental  Package: Daimler Car SLP10  Micro: MPC567xK / MPC5675K  Compiler: Metrowerks V4.0.0
 *
 *   Description:  C-Code implementation template for SW-C <CP_AP_ModeManager>
 *********************************************************************************************************************/


/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << Start of version logging area >>                DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/

/*! \file **********************************************************************

  COMPANY:                Continental Automotive , 

  PROJECT:                MFC310

  CPU:                    MPC567x

  PACKAGE:                DIAG

  MODULNAME:              CP_AP_ModeManager.c

  DESCRIPTION:            Implementation of Mode Management tasks and creation of NMuser Data;
                          File sceleton generated by RTE generator; 

  AUTHOR:                 Andreas Gilch (b-plus GmbH)

  CREATION DATE:          28.05.2010

  VERSION:                $Revision: 1.1 $


  ---*/ /*---
      CHANGES:              $Log: CP_AP_ModeManager.c  $
      CHANGES:              Revision 1.1 2021/12/13 17:24:49CET Wang, David (Wangd3) 
      CHANGES:              Initial revision
      CHANGES:              Member added to project /ADAS/Projects/MFC5xx/MFC5J3/06_Algorithm/DPU/04_Engineering/01_Source_Code/GIA_sim/sim_swc_wrapper/Include/mfc310_common/Rte/project.pj
      CHANGES:              Revision 1.0 2017/03/03 10:35:46CET Sorge, Sven (uidg3181) 
      CHANGES:              Initial revision
      CHANGES:              Member added to project /ADAS/SW/Integration/06_Simulation_Components/GIA_GenericInterfaceAdapter/04_Engineering/03_Workspace/Component_Workspace/GIA_sim/sim_swc_wrapper/Include/mfc310_common/Rte/project.pj
      CHANGES:              Revision 1.1 2014/03/13 15:11:18CET Sorge, Sven (uidg3181) 
      CHANGES:              Initial revision
      CHANGES:              Member added to project /nfs/projekte1/REPOSITORY/Base_Development/05_Algorithm/ETK_EngineeringToolKit/04_Engineering/GIA_GenericInterfaceAdapter/04_Engineering/03_Workspace/algo/gia_sim/wrapper/Include/mfc310_common/Rte/project.pj
      CHANGES:              Revision 1.29 2012/10/05 09:03:43CEST Fuehrmann-EXT, Johann (x-fuehrmannj) 
      CHANGES:              fixed Star1 include of norm_s1_errorhandler.h
      CHANGES:              --- Added comments ---  x-fuehrmannj [Oct 5, 2012 9:03:44 AM CEST]
      CHANGES:              Change Package : 161625:1 http://mks-psad:7002/im/viewissue?selection=161625
      CHANGES:              Revision 1.28 2012/06/28 11:53:45CEST Fuehrmann-EXT, Johann (x-fuehrmannj) 
      CHANGES:              slight change of setting FR_COMM_CONNECTION_LOST to passed, this is now done cyclically to avoid readiness problems
      CHANGES:              --- Added comments ---  x-fuehrmannj [Jun 28, 2012 11:53:45 AM CEST]
      CHANGES:              Change Package : 131608:1 http://mks-psad:7002/im/viewissue?selection=131608
      CHANGES:              Revision 1.27 2012/06/28 09:42:36CEST Buligan, Silviu (uidt5555) 
      CHANGES:              Added compiler switch for stereo specific changes.
      CHANGES:              --- Added comments ---  uidt5555 [Jun 28, 2012 9:42:38 AM CEST]
      CHANGES:              Change Package : 129475:1 http://mks-psad:7002/im/viewissue?selection=129475
      CHANGES:              Revision 1.26 2012/06/15 20:10:35CEST Gilch-EXT, Andreas (uidt0904) 
      CHANGES:              Add implementation for FR communication connection lost - DTC.
      CHANGES:              --- Added comments ---  uidt0904 [Jun 15, 2012 8:10:36 PM CEST]
      CHANGES:              Change Package : 124153:1 http://mks-psad:7002/im/viewissue?selection=124153
      CHANGES:              Revision 1.25 2012/06/13 10:17:21CEST Gilch-EXT, Andreas (uidt0904) 
      CHANGES:              Fix to keep ECU awake even when no FR is connected in case NM is deactivated by diagnostic.
      CHANGES:              --- Added comments ---  uidt0904 [Jun 13, 2012 10:17:23 AM CEST]
      CHANGES:              Change Package : 124270:1 http://mks-psad:7002/im/viewissue?selection=124270
      CHANGES:              Revision 1.24 2012/05/31 20:51:38CEST Gilch-EXT, Andreas (uidt0904) 
      CHANGES:              Add monitoring for lost communication. In this case (after 10sec), we no more request FULL_COMMUNICATION, hence we can go to sleep in this case.
      CHANGES:              --- Added comments ---  uidt0904 [May 31, 2012 8:51:40 PM CEST]
      CHANGES:              Change Package : 103618:1 http://mks-psad:7002/im/viewissue?selection=103618
      CHANGES:              Revision 1.23 2012/03/12 18:54:18CET Gilch-EXT, Andreas (uidt0904) 
      CHANGES:              Change of plattform config switches.
      CHANGES:              --- Added comments ---  uidt0904 [Mar 12, 2012 6:54:19 PM CET]
      CHANGES:              Change Package : 98915:1 http://mks-psad:7002/im/viewissue?selection=98915
      CHANGES:              Revision 1.22 2012/02/24 17:49:42CET Gilch-EXT, Andreas (uidt0904) 
      CHANGES:              Avoid requesting the Network (FULL_COMMUNICATION) in case the ignition switch signal is not available.
      CHANGES:              --- Added comments ---  uidt0904 [Feb 24, 2012 5:49:43 PM CET]
      CHANGES:              Change Package : 91050:1 http://mks-psad:7002/im/viewissue?selection=91050
      CHANGES:              Revision 1.21 2011/09/06 16:23:19CEST Limbrunner-EXT, Matthias (x-limbrunnem) 
      CHANGES:              Star 1 integration
      CHANGES:              --- Added comments ---  x-limbrunnem [Sep 6, 2011 4:23:20 PM CEST]
      CHANGES:              Change Package : 71604:16 http://mks-psad:7002/im/viewissue?selection=71604
      CHANGES:              Revision 1.20 2011/08/18 13:53:10CEST Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              Removed compiler warning: add missing NvM header include.
      CHANGES:              --- Added comments ---  uidt0904 [Aug 18, 2011 1:53:10 PM CEST]
      CHANGES:              Change Package : 75820:1 http://mks-psad:7002/im/viewissue?selection=75820
      CHANGES:              Revision 1.19 2011/07/07 15:33:43CEST Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              Generated from ECU_C file revision 1.20:
      CHANGES:              Generated with "mfc310_SMPC_dev.zip" 1.15:
      CHANGES:              Undo activation of "ComM_ModeLimitation"; Caused Reset while OnGoToSleep.
      CHANGES:              Unification between MFC310 and MFC312;
      CHANGES:              --- Added comments ---  uidt0904 [Jul 7, 2011 3:33:43 PM CEST]
      CHANGES:              Change Package : 71893:1 http://mks-psad:7002/im/viewissue?selection=71893
      CHANGES:              Revision 1.18 2011/06/10 11:56:07CEST Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              Generated from ECU_C file revision 1.19:  
      CHANGES:              Generated with "mfc310_SMPC_dev.zip" 1.14:
      CHANGES:               Use of SMPC222.cdd rev 1.17; internal cdd version: 02.08.00 -> variant 0x008008:
      CHANGES:               SAC & SCN;
      CHANGES:              --- Added comments ---  uidt0904 [Jun 10, 2011 11:56:07 AM CEST]
      CHANGES:              Change Package : 69724:1 http://mks-psad:7002/im/viewissue?selection=69724
      CHANGES:              Revision 1.17 2011/05/31 09:58:40CEST Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              In case NM should be deactivated by Compiler-switch (pre-compile-time), "Rte_Call_modeLimitation_LimitECUToNoComMode(FALSE);" is used, 
      CHANGES:              after ComM_ModeLimitation was activated. ( ComM_ModeLimitation is requested by Daimler.)
      CHANGES:              In the previous file version, this fix was only for the case: deactivation by NvM parameter (runtime).
      CHANGES:              --- Added comments ---  uidt0904 [May 31, 2011 9:58:41 AM CEST]
      CHANGES:              Change Package : 66715:1 http://mks-psad:7002/im/viewissue?selection=66715
      CHANGES:              Revision 1.16 2011/05/26 21:15:53CEST Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              In case NM should be deactivated, "Rte_Call_modeLimitation_LimitECUToNoComMode(FALSE);" is used, 
      CHANGES:              after ComM_ModeLimitation was activated. ( ComM_ModeLimitation is requested by Daimler.)
      CHANGES:              --- Added comments ---  uidt0904 [May 26, 2011 9:15:54 PM CEST]
      CHANGES:              Change Package : 66715:1 http://mks-psad:7002/im/viewissue?selection=66715
      CHANGES:              Revision 1.15 2011/05/25 16:54:14CEST Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              Generated from ECU_C file revision 1.18: 
      CHANGES:              Generated with "mfc310_SMPC_dev.zip" 1.13: 
      CHANGES:              Update to KM11/16a;
      CHANGES:              --- Added comments ---  uidt0904 [May 25, 2011 4:54:14 PM CEST]
      CHANGES:              Change Package : 66715:1 http://mks-psad:7002/im/viewissue?selection=66715
      CHANGES:              Revision 1.14 2011/05/23 18:03:58CEST Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              Generated from ECU_C file revision 1.17: 
      CHANGES:              Generated with "mfc310_SMPC_dev.zip" 1.12:
      CHANGES:               + Start configuring monitoring of bus signals;
      CHANGES:               * Changes due to ECU_Configuration_Difference_Report from Daimler;
      CHANGES:              --- Added comments ---  uidt0904 [May 23, 2011 6:03:58 PM CEST]
      CHANGES:              Change Package : 68128:1 http://mks-psad:7002/im/viewissue?selection=68128
      CHANGES:              Revision 1.13 2011/05/16 14:02:52CEST Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              Add DEM-SC and RoElite from Daimler / Vector to project.
      CHANGES:              --- Added comments ---  uidt0904 [May 16, 2011 2:02:52 PM CEST]
      CHANGES:              Change Package : 66728:1 http://mks-psad:7002/im/viewissue?selection=66728
      CHANGES:              Revision 1.12 2011/05/05 16:18:53CEST Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              Generated from ECU_C file revision 1.12: 
      CHANGES:               Generated with "mfc310_SMPC_dev.zip" 1.15: 
      CHANGES:                Usage of cdd-File-rev 02.05.07 (MKS-rev 1.15) (see change list there;):
      CHANGES:                -> new variante 0x008006; Add SAC-routine;
      CHANGES:              --- Added comments ---  uidt0904 [May 5, 2011 4:18:54 PM CEST]
      CHANGES:              Change Package : 66440:1 http://mks-psad:7002/im/viewissue?selection=66440
      CHANGES:              Revision 1.11 2011/03/28 11:11:19CEST Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              Update diagnostic implementation for 92.04.150;
      CHANGES:              --- Added comments ---  uidt0904 [Mar 28, 2011 11:11:20 AM CEST]
      CHANGES:              Change Package : 60741:1 http://mks-psad:7002/im/viewissue?selection=60741
      CHANGES:              --- Added comments ---  uidt0904 [Mar 28, 2011 11:25:12 AM CEST]
      CHANGES:              Generated from ECU_C file revision 1.13:
      CHANGES:              Generated with "mfc310_SMPC_dev.zip" 1.8:
      CHANGES:              Update diagnostic implementation for 92.04.150;
      CHANGES:               - Usage of cdd-File-rev 02.05.04 (MKS-rev 1.11) (see change list there;)
      CHANGES:              Revision 1.10 2011/03/17 23:06:36CET Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              Generated from ECU_C file revision 1.12:
      CHANGES:              Generated with "mfc310_SMPC_dev.zip" 1.7:
      CHANGES:              Update to KM11/05a and SLP10.10 and DaVinciDeveloper 3.0.69.3 (SP3);
      CHANGES:              ==> Signal group degradation!!
      CHANGES:              Usage of cdd-File-rev 02.05.04 (MKS-rev 1.10) (see change list there;)
      CHANGES:              --- Added comments ---  uidt0904 [Mar 17, 2011 11:06:36 PM CET]
      CHANGES:              Change Package : 60741:1 http://mks-psad:7002/im/viewissue?selection=60741
      CHANGES:              Revision 1.9 2011/02/28 13:56:45CET Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              Add RTE ADAS_OnRx runnables for all remaining ADAS signal groups; Need for time related calls to function MAP_xxxx;
      CHANGES:              --- Added comments ---  uidt0904 [Feb 28, 2011 1:56:45 PM CET]
      CHANGES:              Change Package : 60453:1 http://mks-psad:7002/im/viewissue?selection=60453
      CHANGES:              Revision 1.8 2010/12/07 17:16:03CET Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              Generated from ECU_C file revision 1.9:
      CHANGES:              - Usage of cdd-File-rev 02.04.01 (MKS-rev 1.7) (see change list there;)
      CHANGES:              - Split up runnable "Norm_v_ABCpreVw_fin" into "Norm_v_PV_Header_Fin" and "Norm_v_PV_ProfData_fin";
      CHANGES:              --- Added comments ---  uidt0904 [Dec 7, 2010 5:16:03 PM CET]
      CHANGES:              Change Package : 56224:1 http://mks-psad:7002/im/viewissue?selection=56224
      CHANGES:              Revision 1.7 2010/12/01 18:03:21CET Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              Update to "SMPC_STAR_2_V1_2013_Ecu_Extract_2010_41a_3.1.4";
      CHANGES:              --- Added comments ---  uidt0904 [Dec 1, 2010 6:03:22 PM CET]
      CHANGES:              Change Package : 55839:1 http://mks-psad:7002/im/viewissue?selection=55839
      CHANGES:              Revision 1.6 2010/11/26 17:20:20CET Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              "Avoid-goto-sleep" is now handled in this file (was former SchM.c);
      CHANGES:              Fixed wrong output of awake reasons in NM messages;
      CHANGES:              --- Added comments ---  uidt0904 [Nov 26, 2010 5:20:20 PM CET]
      CHANGES:              Change Package : 55751:1 http://mks-psad:7002/im/viewissue?selection=55751
      CHANGES:              Revision 1.5 2010/10/23 02:32:08CEST Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              Add missing revision information;
      CHANGES:              --- Added comments ---  uidt0904 [Oct 23, 2010 2:32:09 AM CEST]
      CHANGES:              Change Package : 53183:1 http://mks-psad:7002/im/viewissue?selection=53183
      CHANGES:              Revision 1.4 2010/10/22 22:38:08CEST Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              Update diag services in cdd:
      CHANGES:              1)Service 270 geändert
      CHANGES:              2) Gesp. Daten: Kalibrierumgebungsdaten  hinzugefügt
      CHANGES:              3) Aktuelle Daten: 'Temperaturen' hinzugefügt
      CHANGES:              4) Aktuelle Daten: 'Spannungen' hinzugefügt
      CHANGES:              --- Added comments ---  uidt0904 [Oct 22, 2010 10:38:08 PM CEST]
      CHANGES:              Revision 1.3 2010/10/22 17:51:08CEST Gilch Andreas (uidt0904) (uidt0904) 
      CHANGES:              Changes by new cdd variante 8003 and changes from Marc Münch / RTE CESSAR;
      CHANGES:              --- Added comments ---  uidt0904 [Oct 22, 2010 5:51:08 PM CEST]
      CHANGES:              Change Package : 53183:1 http://mks-psad:7002/im/viewissue?selection=53183
      CHANGES:              Revision 1.2 2010/10/06 19:29:14CEST Gazvoda Andrej (uidt1085) (uidt1085) 
      CHANGES:              Changes caused by update to SLP10 Version 9 and Ecu-Extract 2010_29a
      CHANGES:              --- Added comments ---  uidt1085 [Oct 6, 2010 7:29:15 PM CEST]
      CHANGES:              Change Package : 52311:1 http://mks-psad:7002/im/viewissue?selection=52311
      CHANGES:              Revision 1.11 2010/09/01 16:38:29CEST Gazvoda Andrej (uidt1085) (uidt1085) 
      CHANGES:              Added diagnostic service 0x0256. See change history of cdd-file for further information.
      CHANGES:              --- Added comments ---  uidt1085 [Sep 1, 2010 4:38:30 PM CEST]
      CHANGES:              Change Package : 50770:1 http://mks-psad:7002/im/viewissue?selection=50770
      CHANGES:              Revision 1.10 2010/08/10 16:58:29CEST Gazvoda Andrej (uidt1085) (uidt1085) 
      CHANGES:              Added diag service 0x0255;
      CHANGES:              Moved data objects CorrectionFactor, DCGGainFactor and TestGenerator from service 0x0250 to service 0x0255
      CHANGES:              --- Added comments ---  uidt1085 [Aug 10, 2010 4:58:29 PM CEST]
      CHANGES:              Change Package : 49135:1 http://mks-psad:7002/im/viewissue?selection=49135
      CHANGES:              Revision 1.9 2010/08/05 17:34:37CEST Gazvoda Andrej (uidt1085) (uidt1085) 
      CHANGES:              Update diagnostic services: Add new: DIDs 0x0216, 0x0217, 0x0272, 0x0380; Changed: DIDs 0x0250 & 0x0270;
      CHANGES:              --- Added comments ---  uidt1085 [Aug 5, 2010 5:34:37 PM CEST]
      CHANGES:              Change Package : 49135:1 http://mks-psad:7002/im/viewissue?selection=49135
      CHANGES:              Revision 1.8 2010/07/07 13:26:56CEST agilch 
      CHANGES:              Generated with DaVinci_DEV and ECU_C file revision 1.29;
      CHANGES:               (
      CHANGES:                  Changes due to feedback from Daimler for ECU_Cconfig report:
      CHANGES:                   - Removed not used EcuM service ports;
      CHANGES:                   - FrNmStateChangeIndication no more needed;
      CHANGES:               )
      CHANGES:              --- Added comments ---  agilch [2010/07/07 11:26:56Z]
      CHANGES:              Change Package : 46978:1 http://LISS014:6001/im/viewissue?selection=46978
      CHANGES:              Revision 1.7 2010/06/23 19:10:46CEST Andreas Gilch (agilch) 
      CHANGES:              Generated with DaVinci_DEV and ECU_C file revision 1.28;
      CHANGES:              --- Added comments ---  agilch [2010/06/23 17:10:46Z]
      CHANGES:              Change Package : 45800:1 http://LISS014:6001/im/viewissue?selection=45800
      CHANGES:              Revision 1.6 2010/06/17 16:50:53CEST Andreas Gilch (agilch) 
      CHANGES:              Changed used Service function: Use "GetRequestedComMode" instead of "GetCurrentComMode"; 
      CHANGES:              should fix the "freezed Awake_IgnOn" within the NMuserdata and the late goto sleep after Ogn_OFF;
      CHANGES:              --- Added comments ---  agilch [2010/06/17 14:50:54Z]
      CHANGES:              Change Package : 45800:1 http://LISS014:6001/im/viewissue?selection=45800
      CHANGES:              Revision 1.5 2010/06/17 11:05:26CEST Andreas Gilch (agilch) 
      CHANGES:              Use of Nm_GetState() instaed of Nm_StateChangeNotification(); But does not fix NmUserData problem (On_Awake_Ignition_On freezes);
      CHANGES:              --- Added comments ---  agilch [2010/06/17 09:05:27Z]
      CHANGES:              Change Package : 45800:1 http://LISS014:6001/im/viewissue?selection=45800
      CHANGES:              Revision 1.4 2010/06/15 12:01:02CEST Andreas Gilch (agilch) 
      CHANGES:              Generated source-file from ECU_C-file revision 1.27 and cdd-file revision 1.5;
      CHANGES:              ECU_C: Moved call of (data) runnable "NORM_v_BApQ_finished" from TASK_VehicleAlgo (RTE-controlled) to TASK_SchMSynch2 (SCHM-controlled);
      CHANGES:                     This runnable is now called synchron to the FR-cycle with 5ms;
      CHANGES:              cdd: Add DIDs for Stereo algo parameters (0x260, 0x0261, 0x0262, 0x0263, 0x0265, 0x0266, 0x0270;)
      CHANGES:              --- Added comments ---  agilch [2010/06/15 10:01:02Z]
      CHANGES:              Change Package : 45219:1 http://LISS014:6001/im/viewissue?selection=45219
      CHANGES:              Revision 1.3 2010/06/14 14:46:48CEST Andreas Gilch (agilch) 
      CHANGES:              Removed compiler warning (use of enum constant for var.init.;
      CHANGES:              --- Added comments ---  agilch [2010/06/14 12:46:48Z]
      CHANGES:              Change Package : 44460:1 http://LISS014:6001/im/viewissue?selection=44460
      CHANGES:              Revision 1.2 2010/06/09 23:01:48CEST Andreas Gilch (agilch) 
      CHANGES:              Generated with DaVinci_DEV and ECU_C file revision 1.26;
      CHANGES:              (
      CHANGES:              Undo Rev. 1.25 change ("Seperate PDU callout "ALDW_Disp_Warn_Rq" for SQC done over RTE;")
      CHANGES:               because it does not fix SQC problem;
      CHANGES:              Update to new cdd variant (008001) within Dcm;
      CHANGES:              Enable EcuPassivMode in FrSM & Vmm;
      CHANGES:              Vmm/VmmGeneral/VmmChannel/VmmTxPduGroup is ActiveEcuC/Com/ComConfig/PduGrp_TxRedu_MPC_CHASSIS;
      CHANGES:              
      CHANGES:              Changes within MPC222.cdd variant 008001:
      CHANGES:              Added "FlexRay - ISO10681" as supportes ECU-Interface;
      CHANGES:              
      CHANGES:              Basis-Variante:
      CHANGES:              ------------------
      CHANGES:              - DID and Datatypes for R/W ImageControl (0x0250) added;
      CHANGES:              - Removed doubled DIDs 0x0214, 0x0216 & 0x0217 (was doubled to have seperate ones for read and write),
      CHANGES:                as CANdela now is able to handle seperate Target Groups for read and write within one DID (see "[ZE(P)(S)(D)]".
      CHANGES:              - Edit state transitions "Sessions" und "Security";
      CHANGES:              - HW_Supplier corrected: 0x3C ("Conti Temic) -> 0x46 (ADC);
      CHANGES:              
      CHANGES:              Generated new variante: "MPC222_008001" (referenced from Basis);
      CHANGES:              ---------------------------------------------------
      CHANGES:               ECU_PassiveMode activated;
      CHANGES:               StandBy-Session activated;
      CHANGES:               Unsupported DIDs / RIDs from the Basis-variante not used;
      CHANGES:               Activated following DIDs:
      CHANGES:               - 0x0210 (Status Scheibenheizung);
      CHANGES:               - 0x0242 (Kalibrierungsstatus);
      CHANGES:               - 0x0214 (Kalibrierungsdaten);
      CHANGES:               - 0xF1A5 (DoFR-Spec);
      CHANGES:              
      CHANGES:               IO-Control "Scheibenheizung Steuerung" activated; (0xD000);
      CHANGES:              )
      CHANGES:              --- Added comments ---  agilch [2010/06/09 21:01:48Z]
      CHANGES:              Change Package : 44460:1 http://LISS014:6001/im/viewissue?selection=44460
      CHANGES:              

**************************************************************************** */


/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << End of version logging area >>                  DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *
 * AUTOSAR Modelling Object Descriptions
 *
 **********************************************************************************************************************

 Data Types:
 ===========
  REC_Ign_Stat_b0ko81o0x5jgvwtduf99gvzi0
    (degraded)


 Port Prototypes:
 ================
  P_Awake_Diag_Actv
    Wachhalten für Diagnose aktiv

  P_Awake_Ignition_On
    Wachhalten für Zündung eingeschaltet

  P_WakeupRsn_MPC
    Weckgrund

  R_Ign_Stat
    Zündungsstatus (degraded)


 Data Element Prototypes:
 ========================
  Awake_Diag_Actv of Port Interface IF_Awake_Diag_Actv
    Wachhalten für Diagnose aktiv

  Awake_Ignition_On of Port Interface IF_Awake_Ignition_On
    Wachhalten für Zündung eingeschaltet

  WakeupRsn_MPC of Port Interface IF_WakeupRsn_MPC
    Weckgrund

  Ign_Stat of Port Interface IG_Ign_Stat_9bhu63hx0g75nr9rmuo7dc0ed
    Zündungsstatus (degraded)

 *********************************************************************************************************************/
#include "osek.h"
#include "Com.h"
#include "ComM.h"
#include "Dcm.h"

/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << Start of include and declaration area >>        DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/

#include "glob_cfg.h"
#include "NvM_Data.h"
#if (defined FR_BUS_ARCHT_STAR_1)
#include "Norm_S1_ErrorHandler.h"
#else
#include "Norm_ErrorHandler.h"
#endif
#if(CFG_MFC_STEREO == 1)
#include "FrIf.h"
#include "Fr_GeneralTypes.h"
#endif
#include "Dem.h"

#define COM_CONST_I_C03_ISW_STAT_IGN_LOCK (0u)
#define COM_CONST_I_C03_ISW_STAT_IGN_OFF (1u)
#define COM_CONST_I_C03_ISW_STAT_IGN_ACC (2u)
#define COM_CONST_I_C03_ISW_STAT_IGN_ON (4u)
#define COM_CONST_I_C03_ISW_STAT_IGN_START (5u)
#define COM_CONST_I_C03_ISW_STAT_SNA (7u)

#define COM_CONST_I_C08_WAKEUPRSN_MPC_NETWORK (0u)
#define COM_CONST_I_C08_WAKEUPRSN_MPC_SNA (255u)

#ifdef CAN_BUS_ARCHT_STAR_1
# define MM_NM_NETWORK_ID_CHASSIS2 (50u)
#endif

/* Timeout time until we release our networking request. 
 * Actuall time is following value multiplied with function call cycle time 20ms. */
#define MM_TIMEOUT_LOST_COM_CONNECTION (500uL)

/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << End of include and declaration area >>          DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/


/**********************************************************************************************************************
 *
 * Used AUTOSAR Data Types
 *
 **********************************************************************************************************************
 *
 * Primitive Types:
 * ================
 * DC_BOOL: Boolean
 *
 * Enumeration Types:
 * ==================
 * ComM_ModeType: Enumeration of integer in interval [0...2] with enumerators
 *   COMM_NO_COMMUNICATION (0u)
 *   COMM_SILENT_COMMUNICATION (1u)
 *   COMM_FULL_COMMUNICATION (2u)
 * Dcm_SecLevelType: Enumeration of integer in interval [0...255] with enumerators
 *   DCM_SEC_LEV_LOCKED (0u)
 *   DCM_SEC_LEV_L1 (1u)
 *   DCM_SEC_LEV_ALL (255u)
 * Dcm_SesCtrlType: Enumeration of integer in interval [1...255] with enumerators
 *   DCM_DEFAULT_SESSION (1u)
 *   DCM_PROGRAMMING_SESSION (2u)
 *   DCM_EXTENDED_DIAGNOSTIC_SESSION (3u)
 *   DCM_SAFETY_SYSTEM_DIAGNOSTIC_SESSION (4u)
 *   STAND_BY (73u)
 *   DCM_ALL_SESSION_LEVEL (255u)
 * c03_ISw_Stat: Enumeration of integer in interval [0...7] with enumerators
 *   I_C03_ISW_STAT_IGN_LOCK (0u)
 *   I_C03_ISW_STAT_IGN_OFF (1u)
 *   I_C03_ISW_STAT_IGN_ACC (2u)
 *   I_C03_ISW_STAT_IGN_ON (4u)
 *   I_C03_ISW_STAT_IGN_START (5u)
 *   I_C03_ISW_STAT_SNA (7u)
 * c08_WakeupRsn_MPC: Enumeration of integer in interval [0...255] with enumerators
 *   I_C08_WAKEUPRSN_MPC_NETWORK (0u)
 *   I_C08_WAKEUPRSN_MPC_SNA (255u)
 *
 * Record Types:
 * =============
 * REC_Ign_Stat_b0ko81o0x5jgvwtduf99gvzi0: Record with elements
 *   ISw_Stat of type c03_ISw_Stat
 *
 *********************************************************************************************************************/


#define RTE_START_SEC_CP_AP_MODEMANAGER_APPL_CODE
#include "MemMap.h"

/**********************************************************************************************************************
 *
 * Runnable Entity Name: RE_CT_ModeManager_MainFct
 *
 *---------------------------------------------------------------------------------------------------------------------
 *
 * Executed if at least one of the following trigger conditions occurred:
 *   - triggered on TimingEvent every 20ms
 *
 **********************************************************************************************************************
 *
 * Input Interfaces:
 * =================
 *   Explicit S/R API:
 *   -----------------
 *   Std_ReturnType Rte_Read_R_Ign_Stat_Ign_Stat(REC_Ign_Stat_b0ko81o0x5jgvwtduf99gvzi0 *data)
 *
 * Output Interfaces:
 * ==================
 *   Explicit S/R API:
 *   -----------------
 *   Std_ReturnType Rte_Write_P_Awake_Diag_Actv_Awake_Diag_Actv(DC_BOOL data)
 *   Std_ReturnType Rte_Write_P_Awake_Ignition_On_Awake_Ignition_On(DC_BOOL data)
 *   Std_ReturnType Rte_Write_P_WakeupRsn_MPC_WakeupRsn_MPC(c08_WakeupRsn_MPC data)
 *
 * Service Calls:
 * ==============
 *   Service Invocation:
 *   -------------------
 *   Std_ReturnType Rte_Call_DCMServices_GetSesCtrlType(Dcm_SesCtrlType *SessionCtrlType)
 *     Synchronous Service Invocation. Timeout: None
 *     Returned Application Errors: RTE_E_DCMServices_E_NOT_OK
 *   Std_ReturnType Rte_Call_UR_ComMUser_CHASSIS_GetRequestedComMode(ComM_ModeType *ComMode)
 *     Synchronous Service Invocation. Timeout: None
 *     Returned Application Errors: RTE_E_ComM_UserRequest_E_NOT_OK
 *   Std_ReturnType Rte_Call_UR_ComMUser_CHASSIS_RequestComMode(ComM_ModeType ComMode)
 *     Synchronous Service Invocation. Timeout: None
 *     Returned Application Errors: RTE_E_ComM_UserRequest_COMM_E_MODE_LIMITATION, RTE_E_ComM_UserRequest_E_NOT_OK
 *
 *********************************************************************************************************************/

FUNC(void, RTE_CP_AP_MODEMANAGER_APPL_CODE) RE_CT_ModeManager_MainFct(void)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << Start of runnable implementation >>             DO NOT CHANGE THIS COMMENT!
 * Symbol: RE_CT_ModeManager_MainFct
 *********************************************************************************************************************/

  ComM_ModeType       ui8_RequestedComM_Mode;
  ComM_ModeType       ui8_CurrentComM_Mode;
  static uint32 ui32ComMDebounce = 0u;
  Dcm_SesCtrlType     ui8_SesCtrlType;
  uint8 ui8_ISw_Stat;
  uint8 ui8_NmContent;
#if ((defined MODM_AVOID_GOTO_SLEEP_IS_RUNTIME_CONF) && (MODM_AVOID_GOTO_SLEEP_IS_RUNTIME_CONF == SWITCH_ON))
  uint8 lNmDeactivation;
#endif

  //FrTrcv_TrcvWUReasonType ui8_MmWuReason;
  //Std_ReturnType ret;


#if(CFG_MFC_STEREO == 1)
  (void)ComM_GetRequestedComMode(ComMUser_CHASSIS, &ui8_RequestedComM_Mode);
  (void)ComM_GetCurrentComMode(ComMUser_CHASSIS, &ui8_CurrentComM_Mode);
#else
# ifdef CAN_BUS_ARCHT_STAR_2
  (void)ComM_GetRequestedComMode(ComMUser_PERIPHERY, &ui8_RequestedComM_Mode);
# else
#  ifdef CAN_BUS_ARCHT_STAR_1
  (void)ComM_GetRequestedComMode(ComMUser_CHASSIS2, &ui8_RequestedComM_Mode);
#  else
#  error "Specify a valid bus architecture!"
#   endif
# endif
#endif
  (void)Dcm_GetSesCtrlType(&ui8_SesCtrlType);
  
#if (defined CAN_BUS_ARCHT_STAR_1 || defined FR_BUS_ARCHT_STAR_1)
  (void)Com_ReceiveSignalGroup(Com_Grp_EIS_Stat_75zlv4f9cn7ja5rpmb4see39r);
#else
  (void)Com_ReceiveSignalGroup(Com_Grp_Ign_Stat_9q60tj4xuav66mp4vjkxlr6ka);
#endif
  (void)Com_ReceiveShadowSignal(Com_ISw_Stat, &ui8_ISw_Stat);


  /* As we don't use the DaVinci-RTE, we need to get the signal status from the NORM. */
#if (defined FR_BUS_ARCHT_STAR_1)
  if(NORM_STATE_OK != NORM_ui8_GetSigGrpState(NORM_GRP_EIS_STAT))
#else
  if(NORM_STATE_OK != NORM_ui8_GetSigGrpState(NORM_GRP_IGN_STAT))
#endif
  {
    /* In case the signal group 'Ign_Stat', containing the 'ISw_Stat' signal, is timeout
     * or the CRC is not OK, or ...., we asume the IGN is not ON. This is to prevent, that
     * we keep the network awake. */
    ui8_ISw_Stat = COM_CONST_I_C03_ISW_STAT_SNA;
  }

#if ((defined MODM_AVOID_GOTO_SLEEP_IS_RUNTIME_CONF) && (MODM_AVOID_GOTO_SLEEP_IS_RUNTIME_CONF == SWITCH_ON))
  /* read NvM at all circumstances, if default is returned, the worst case would be that
     the ECU falls asleep */
  NvM_v_ReadRamNmDeactivation(&lNmDeactivation);

  if(lNmDeactivation == TRUE)
  {
    /* Overwrite actuall IgnSwitchState read from COM; */
    ui8_ISw_Stat = COM_CONST_I_C03_ISW_STAT_IGN_ON;
  }
#else
# if ((defined MODM_AVOID_GO_TO_SLEEP) && (MODM_AVOID_GO_TO_SLEEP == SWITCH_ON))
  /* Overwrite actuall IgnSwitchState read from COM; */
  ui8_ISw_Stat = COM_CONST_I_C03_ISW_STAT_IGN_ON;

  // REMARK Andreas Gilch: Necessary?
  // EcuM_RequestRUN(EcuMUserConfig_FirstUser);
# endif
#endif

  /* Avoid lost connection monitoring in case NvM switch is set. */
  if(lNmDeactivation == FALSE)
  {
    /* Monitor for lost communication connection. */
    if( (COMM_NO_COMMUNICATION != ui8_RequestedComM_Mode) &&
        (COMM_NO_COMMUNICATION == ui8_CurrentComM_Mode)     )
    {
      if(ui32ComMDebounce < MM_TIMEOUT_LOST_COM_CONNECTION)
      {
        ui32ComMDebounce++;
      }
      else
      {
        /* We assume, that we have lost the FlexRay / CAN conncetion:
         * Force GoToSleep. */
        ui8_ISw_Stat = COM_CONST_I_C03_ISW_STAT_SNA;
        /* Overwrite also the NORM signal state, as the comBuffer still contains the last received ISw_Stat.
         * Otherwise in the next cycle FULL_COMM would be requested again.*/
#if (defined FR_BUS_ARCHT_STAR_1)
        NORM_ui8_SetSigGrpState(NORM_GRP_EIS_STAT, NORM_STATE_TIMEOUT);
#else
        NORM_ui8_SetSigGrpState(NORM_GRP_IGN_STAT, NORM_STATE_TIMEOUT);
#endif

#if(CFG_MFC_STEREO == 1)
        /* Store DTC "Die Kommunikation mit dem Fahrwerk-FlexRay hat Funktionsstörung.". */
        (void)Dem_SetEventStatus(FR_COMM_CONNECTION_LOST, DEM_EVENT_STATUS_FAILED);
#endif
      }
    }
    else
    {
      ui32ComMDebounce = 0;
    }
    /* END OF IF/ELSE lost connection. */
  }
  /* END OF IF NvM switch NmDeactivation. */


  if( (COM_CONST_I_C03_ISW_STAT_IGN_ON    == ui8_ISw_Stat) ||
      (COM_CONST_I_C03_ISW_STAT_IGN_START == ui8_ISw_Stat)   )
  {
    if(COMM_FULL_COMMUNICATION != ui8_RequestedComM_Mode)
    {
#if(CFG_MFC_STEREO == 1)
      (void)ComM_RequestComMode(ComMUser_CHASSIS, COMM_FULL_COMMUNICATION);
    }
    else if(COMM_FULL_COMMUNICATION == ui8_RequestedComM_Mode)
    {
      /* Store DTC "Die Kommunikation mit dem Fahrwerk-FlexRay hat Funktionsstörung.". */
      (void)Dem_SetEventStatus(FR_COMM_CONNECTION_LOST, DEM_EVENT_STATUS_PASSED);
#else
# ifdef CAN_BUS_ARCHT_STAR_2
      (void)ComM_RequestComMode(ComMUser_PERIPHERY, COMM_FULL_COMMUNICATION);
# else
#  ifdef CAN_BUS_ARCHT_STAR_1
      (void)ComM_RequestComMode(ComMUser_CHASSIS2, COMM_FULL_COMMUNICATION);
#  else
#  error "Specify a valid bus architecture!"
#   endif
# endif
#endif
    }
  }
  else
  {
    if(COMM_NO_COMMUNICATION != ui8_RequestedComM_Mode)
    {
      /* requested mode is silent or full */
#if(CFG_MFC_STEREO == 1)
      (void)ComM_RequestComMode(ComMUser_CHASSIS, COMM_NO_COMMUNICATION);
#else
# ifdef CAN_BUS_ARCHT_STAR_2
      (void)ComM_RequestComMode(ComMUser_PERIPHERY, COMM_NO_COMMUNICATION);
# else
#  ifdef CAN_BUS_ARCHT_STAR_1
      (void)ComM_RequestComMode(ComMUser_CHASSIS2, COMM_NO_COMMUNICATION);
#  else
#  error "Specify a valid bus architecture!"
#   endif
# endif
#endif
    }
  }

#ifdef CAN_BUS_ARCHT_STAR_1
  (void)Com_SendSignal(Com_Nw_Id1, MM_NM_NETWORK_ID_CHASSIS2);
  (void)Com_SendSignal(Com_Nw_Id2, MM_NM_NETWORK_ID_CHASSIS2);
#endif

  /* ******* evaluate awake/wakeup reasons ******** */

  /* ***** set wakeup reason ***** */
  //ret = FrIf_GetTransceiverWUReason(0, 0, &ui8_MmWuReason);
  //if( (ui8_MmWuReason == FRTRCV_WU_BY_BUS)&& (ret == E_OK) )
  {
    ui8_NmContent = COM_CONST_I_C08_WAKEUPRSN_MPC_NETWORK;
  }
  //else
  //{
  //  ui8_NmContent = COM_CONST_I_C08_WAKEUPRSN_MPC_SNA;
  //}

#ifdef CAN_BUS_ARCHT_STAR_1
  (void)Com_SendSignal(Com_WakeupRsn_MPC2, (&ui8_NmContent));
#else
  (void)Com_SendSignal(Com_WakeupRsn_MPC,  (&ui8_NmContent));
#endif


  /* ***** set awake reason: ignition ***** */
  if( (COM_CONST_I_C03_ISW_STAT_IGN_ON    == ui8_ISw_Stat) ||
      (COM_CONST_I_C03_ISW_STAT_IGN_START == ui8_ISw_Stat)   )
  {
    ui8_NmContent = TRUE;
  }
  else
  {
    ui8_NmContent = FALSE;
  }
#ifdef CAN_BUS_ARCHT_STAR_1
  Com_UpdateShadowSignal(Com_Awake_Ignition_On1, (&ui8_NmContent));
#else
  (void)Com_SendSignal(Com_Awake_Ignition_On, (&ui8_NmContent));
#endif

  /* ***** set awake reason: diagnostic ***** */
  if(DCM_EXTENDED_DIAGNOSTIC_SESSION == ui8_SesCtrlType)
  {
    ui8_NmContent = TRUE;
  }
  else
  {
    ui8_NmContent = FALSE;
  }
#ifdef CAN_BUS_ARCHT_STAR_1
  Com_UpdateShadowSignal(Com_Awake_Diag_Actv1, (&ui8_NmContent));
#else
  (void)Com_SendSignal(Com_Awake_Diag_Actv, (&ui8_NmContent));
#endif


#ifdef CAN_BUS_ARCHT_STAR_1
  /* ***** Stay awake for network startup? ***** */
  /* Muss noch erarbeitet werden: Wachhalten für Netzwerkstartphase
  if(STAY_AWAKE_FOR_NETWORK_STARTUP_TRUE    == ComM_EcuM_Get_yxz)
  {
    ui8_NmContent = TRUE;
  }
  else */
  {
    ui8_NmContent = FALSE;
  }
  Com_UpdateShadowSignal(Com_Awake_NwSt1, (&ui8_NmContent));
  (void)Com_SendSignalGroup(Com_Grp_SG_Awake_MPC_71ygbgoq62s3sewwgwkdfy5nl);
#endif

/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << End of runnable implementation >>               DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
}


#define RTE_STOP_SEC_CP_AP_MODEMANAGER_APPL_CODE
#include "MemMap.h"


/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << Start of function definition area >>            DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/


/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << End of function definition area >>              DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/


/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << Start of removed code area >>                   DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/


/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << End of removed code area >>                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
