/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \version 6.4.3
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2020 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains an Rte component template / example code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.4.3
 * on Thu Feb 24 11:41:56 CST 2022. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#include"Fcu_Rte_Process.h"

/*==================[internal function definitions]=========================*/


/*==================[external function definitions]=========================*/

/**
 * \functions Fcu_Aeb_Data_Process
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */
FUNC(void, RTE_CODE) Fcu_Aeb_Data_Process (s_Fcu_Aeb_SignalData_t *ptr_Aeb_Data)
{

	Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBActive(ptr_Aeb_Data->u8_FC_AEBActive);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBCtrlType(ptr_Aeb_Data->u8_FC_AEBCtrlType);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBEnable(ptr_Aeb_Data->u8_FC_AEBEnable);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBVehilceHoldReq(ptr_Aeb_Data->u8_FC_AEBVehilceHoldReq);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_PrefillActive(ptr_Aeb_Data->u8_FC_PrefillActive);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AWBlevel(ptr_Aeb_Data->u8_FC_AWBlevell);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AWBActive(ptr_Aeb_Data->u8_FC_AWBActive);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_FCWActive(ptr_Aeb_Data->u8_FC_FCWActive);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_ABAlevel(ptr_Aeb_Data->u8_FC_ABAlevel);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_ABAActive(ptr_Aeb_Data->u8_FC_ABAActive);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_FCWPreWarning(ptr_Aeb_Data->u8_FC_FCWPreWarning);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBTargetDeceleration(ptr_Aeb_Data->f32_FC_AEBTargetDeceleration);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_OBJ_AEB_ID(ptr_Aeb_Data->u8_FC_OBJ_AEB_ID);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBTargetType(ptr_Aeb_Data->u8_FC_AEBTargetType);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBTargetDetection(ptr_Aeb_Data->u8_FC_AEBTargetDetection);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBTargetLngRange(ptr_Aeb_Data->f32_FC_AEBTargetLngRange);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBTargetmode(ptr_Aeb_Data->u8_FC_AEBTargetmode);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBTextInfo(ptr_Aeb_Data->u8_FC_AEBTextInfo);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBTargetLatRange(ptr_Aeb_Data->f32_FC_AEBTargetLatRange);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBStatus(ptr_Aeb_Data->u8_FC_AEBStatus);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_FCWLatentWarning(ptr_Aeb_Data->u8_FC_FCWLatentWarning);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_FCWSettingStatus(ptr_Aeb_Data->u8_FC_FCWSettingStatus);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_FCWStatus(ptr_Aeb_Data->u8_FC_FCWStatus);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBTargetAy(ptr_Aeb_Data->f32_FC_AEBTargetAy);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBTargetAx(ptr_Aeb_Data->f32_FC_AEBTargetAx);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBTargetProb(ptr_Aeb_Data->u8_FC_AEBTargetProb);

    Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBTargetLatRelSpeed(ptr_Aeb_Data->f32_FC_AEBTargetLatRelSpeed);

	Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_AEBTargetRelSpeed(ptr_Aeb_Data->f32_FC_AEBTargetRelSpeed);

	// Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_LLaneDistanceFus(ptr_Aeb_Data->);
    // Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_RLaneDistanceFus(ptr_Aeb_Data->);
    // Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_LLaneMarkerType(ptr_Aeb_Data->);
    // Rte_Write_PP_Fcu_Cps_TxSignal_Aeb_Cps_SignalPhyData_FC_RLaneMarkerType(ptr_Aeb_Data->);

}


/**
 * \functions Fcu_Lcf_Data_Process
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */
FUNC(void, RTE_CODE) Fcu_Lcf_Data_Process (s_Fcu_Lcf_SignalData_t *ptr_Lcf_Data)
{	
    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_HostLaneLeftStatus(ptr_Lcf_Data->u8_FC_HostLaneLeftStatus);

    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_HostLaneRightStatus(ptr_Lcf_Data->u8_FC_HostLaneRightStatus);

    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_LDWStatus(ptr_Lcf_Data->u8_FC_LDWStatus);

    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_LDWVibrationWarningReq(ptr_Lcf_Data->u8_FC_LDWVibrationWarningReq);

    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_LKAStatus(ptr_Lcf_Data->u8_FC_LKAStatus);

    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_LKATakeoverReq(ptr_Lcf_Data->u8_FC_LKATakeoverReq);

    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_LASModeSelectionStatus(ptr_Lcf_Data->u8_FC_LASModeSelectionStatus);

    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_LASWarningModeSelectionSts(ptr_Lcf_Data->u8_FC_LASWarningModeSelectionSts);

    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_LDWShakeLevStatus(ptr_Lcf_Data->u8_FC_LDWShakeLevStatus);

    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_ELKMode(ptr_Lcf_Data->u8_FC_ELKMode);

    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_ELKInterventionMode(ptr_Lcf_Data->u8_FC_ELKInterventionMode);

    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_ELKEnableStatus(ptr_Lcf_Data->u8_FC_ELKEnableStatus);

    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_LatAngReqActive(ptr_Lcf_Data->u8_FC_LatAngReqActive);
    
    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_LatAngReq(ptr_Lcf_Data->f32_FC_LatAngReq);

    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_MotorTorqueMaxLimitRequest(ptr_Lcf_Data->f32_FC_MotorTorqueMaxLimitRequest);

    Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_MotorTorqueMinLimitRequest(ptr_Lcf_Data->f32_FC_MotorTorqueMinLimitRequest);

    // 

}


/**
 * \functions Fcu_Acc_Data_Process
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */
FUNC(void, RTE_CODE) Fcu_Acc_Data_Process (s_Fcu_Acc_SignalData_t *ptr_Acc_Data)
{

}

/**
 * \functions Fcu_Hla_Data_Process
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */
FUNC(void, RTE_CODE) Fcu_Hla_Data_Process (s_Fcu_Hla_SignalData_t *ptr_Hla_Data)
{
    Rte_Write_PP_Fcu_Cps_TxSignal_Hla_Cps_SignalPhyData_FC_HMALightDistribution(ptr_Hla_Data->u8_FC_HMALightDistribution);

    Rte_Write_PP_Fcu_Cps_TxSignal_Hla_Cps_SignalPhyData_FC_HMAEnableStatus(ptr_Hla_Data->u8_FC_HMAEnableStatus);

    Rte_Write_PP_Fcu_Cps_TxSignal_Hla_Cps_SignalPhyData_FC_HMAStatus(ptr_Hla_Data->u8_FC_HMAStatus);
}

/**
 * \functions Fcu_Interaction_Process
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */
FUNC(void, RTE_CODE) Fcu_Interaction_Process (s_Fcu_Rte_Output_SignalData_t * const ptr_Fcu_Rte_Output_Signal)
{

	//AEB higher priority than LCF
	if((1 == ptr_Fcu_Rte_Output_Signal->Aeb_Data.u8_FC_Voiceinfo_Aeb)||(2 == ptr_Fcu_Rte_Output_Signal->Aeb_Data.u8_FC_Voiceinfo_Aeb))
	{
		Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_Voiceinfo(ptr_Fcu_Rte_Output_Signal->Aeb_Data.u8_FC_Voiceinfo_Aeb);
	}
	else if((6 == ptr_Fcu_Rte_Output_Signal->Lcf_Data.u8_FC_Voiceinfo_Lcf)||(7 == ptr_Fcu_Rte_Output_Signal->Lcf_Data.u8_FC_Voiceinfo_Lcf))
	{
		Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_Voiceinfo(ptr_Fcu_Rte_Output_Signal->Lcf_Data.u8_FC_Voiceinfo_Lcf);
	}
	else
	{
		Rte_Write_PP_Fcu_Cps_TxSignal_Lcf_Cps_SignalPhyData_FC_Voiceinfo(0);
	}
	

}


/**
 * \functions Fcu_Adas_Data_Process
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */
FUNC(void, RTE_CODE) Fcu_Adas_Data_Process (s_Fcu_AdasDomain_SignalData_t *ptr_AdasDomainData)
{
	Com_SignalSts_t  u8_Rte_SignalSts = 0;

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_Location_Status(&u8_Rte_SignalSts);
	
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_Location(&ptr_AdasDomainData->u8_Rte_Radar_Location[0]);
	}
	else
	{
		ptr_AdasDomainData->u8_Rte_Radar_Location[0] = 0u;  //Default Value
	}
	
	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_Location_Status(&u8_Rte_SignalSts);
	
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_Location(&ptr_AdasDomainData->u8_Rte_Radar_Location[1]);
	}
	else
	{
		ptr_AdasDomainData->u8_Rte_Radar_Location[1] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_Location_Status(&u8_Rte_SignalSts);
	
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_Location(&ptr_AdasDomainData->u8_Rte_Radar_Location[2]);
	}
	else
	{
		ptr_AdasDomainData->u8_Rte_Radar_Location[2] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_Location_Status(&u8_Rte_SignalSts);
	
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_Location(&ptr_AdasDomainData->u8_Rte_Radar_Location[3]);
	}
	else
	{
		ptr_AdasDomainData->u8_Rte_Radar_Location[3] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_ExistProb_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_ExistProb(&ptr_AdasDomainData->u8_Rte_Radar_ExistProb[0]);
	}
	else
	{
		ptr_AdasDomainData->u8_Rte_Radar_ExistProb[0] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_ExistProb_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_ExistProb(&ptr_AdasDomainData->u8_Rte_Radar_ExistProb[1]);
	}
	else
	{
		ptr_AdasDomainData->u8_Rte_Radar_ExistProb[1] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_ExistProb_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_ExistProb(&ptr_AdasDomainData->u8_Rte_Radar_ExistProb[2]);
	}
	else
	{
		ptr_AdasDomainData->u8_Rte_Radar_ExistProb[2] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_ExistProb_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_ExistProb(&ptr_AdasDomainData->u8_Rte_Radar_ExistProb[3]);
	}
	else
	{
		ptr_AdasDomainData->u8_Rte_Radar_ExistProb[3] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_Measured_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_Measured(&ptr_AdasDomainData->u8_Rte_Radar_Measured[0]);
	}
	else
	{
		ptr_AdasDomainData->u8_Rte_Radar_Measured[0] = 0u;  //Default Value
	}	

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_Measured_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_Measured(&ptr_AdasDomainData->u8_Rte_Radar_Measured[1]);
	}
	else
	{
		ptr_AdasDomainData->u8_Rte_Radar_Measured[1] = 0u;  //Default Value
	}	

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_Measured_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_Measured(&ptr_AdasDomainData->u8_Rte_Radar_Measured[2]);
	}
	else
	{
		ptr_AdasDomainData->u8_Rte_Radar_Measured[2] = 0u;  //Default Value
	}	

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_Measured_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_Measured(&ptr_AdasDomainData->u8_Rte_Radar_Measured[3]);
	}
	else
	{
		ptr_AdasDomainData->u8_Rte_Radar_Measured[3] = 0u;  //Default Value
	}	

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_Dx_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_Dx(&ptr_AdasDomainData->f32_Rte_Radar_Dx[0]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Dx[0] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_Dx_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_Dx(&ptr_AdasDomainData->f32_Rte_Radar_Dx[1]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Dx[1] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_Dx_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_Dx(&ptr_AdasDomainData->f32_Rte_Radar_Dx[2]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Dx[2] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_Dx_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_Dx(&ptr_AdasDomainData->f32_Rte_Radar_Dx[3]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Dx[3] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_Dy_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_Dy(&ptr_AdasDomainData->f32_Rte_Radar_Dy[0]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Dy[0] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_Dy_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_Dy(&ptr_AdasDomainData->f32_Rte_Radar_Dy[1]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Dy[1] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_Dy_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_Dy(&ptr_AdasDomainData->f32_Rte_Radar_Dy[2]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Dy[2] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_Dy_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_Dy(&ptr_AdasDomainData->f32_Rte_Radar_Dy[3]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Dy[3] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_RelVx_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_RelVx(&ptr_AdasDomainData->f32_Rte_Radar_RelVx[0]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_RelVx[0] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_RelVx_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_RelVx(&ptr_AdasDomainData->f32_Rte_Radar_RelVx[1]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_RelVx[1] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_RelVx_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_RelVx(&ptr_AdasDomainData->f32_Rte_Radar_RelVx[2]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_RelVx[2] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_RelVx_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_RelVx(&ptr_AdasDomainData->f32_Rte_Radar_RelVx[3]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_RelVx[3] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_RelAx_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_RelAx(&ptr_AdasDomainData->f32_Rte_Radar_RelAx[0]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_RelAx[0] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_RelAx_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_RelAx(&ptr_AdasDomainData->f32_Rte_Radar_RelAx[1]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_RelAx[1] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_RelAx_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_RelAx(&ptr_AdasDomainData->f32_Rte_Radar_RelAx[2]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_RelAx[2] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_RelAx_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_RelAx(&ptr_AdasDomainData->f32_Rte_Radar_RelAx[3]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_RelAx[3] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_RelVy_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_RelVy(&ptr_AdasDomainData->f32_Rte_Radar_RelVy[0]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_RelVy[0] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_RelVy_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_RelVy(&ptr_AdasDomainData->f32_Rte_Radar_RelVy[1]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_RelVy[1] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_RelVy_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_RelVy(&ptr_AdasDomainData->f32_Rte_Radar_RelVy[2]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_RelVy[2] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_RelVy_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_RelVy(&ptr_AdasDomainData->f32_Rte_Radar_RelVy[3]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_RelVx[3] = 0u;  //Default Value
	}


	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_RelVx_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_RelVx(&ptr_AdasDomainData->f32_Rte_Radar_RelVx[0]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_RelVx[0] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_Length_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_Length(&ptr_AdasDomainData->f32_Rte_Radar_Length[0]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Length[0] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_Length_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_Length(&ptr_AdasDomainData->f32_Rte_Radar_Length[1]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Length[1] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_Length_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_Length(&ptr_AdasDomainData->f32_Rte_Radar_Length[2]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Length[2] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_Length_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_Length(&ptr_AdasDomainData->f32_Rte_Radar_Length[3]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Length[3] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_Dy_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_Dy(&ptr_AdasDomainData->f32_Rte_Radar_Dy[0]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Length[0] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_Dy_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		Rte_Read_RP_Fcu_Adas_Data_RadarObj2_Dy(&ptr_AdasDomainData->f32_Rte_Radar_Dy[1]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Length[1] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_Dy_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_Dy(&ptr_AdasDomainData->f32_Rte_Radar_Dy[2]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Length[2] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_Dy_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_Dy(&ptr_AdasDomainData->f32_Rte_Radar_Dy[3]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Length[3] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_Width_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj1_Width(&ptr_AdasDomainData->f32_Rte_Radar_Width[0]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Width[0] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_Width_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj2_Width(&ptr_AdasDomainData->f32_Rte_Radar_Width[1]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Width[1] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_Width_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj3_Width(&ptr_AdasDomainData->f32_Rte_Radar_Width[2]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Width[2] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_Width_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_RadarObj4_Width(&ptr_AdasDomainData->f32_Rte_Radar_Width[3]);
	}
	else
	{
		ptr_AdasDomainData->f32_Rte_Radar_Width[3] = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Body_Data_AccIaccHWAMode_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Body_Data_AccIaccHWAMode(&ptr_AdasDomainData->u8_Rte_AccIaccHWAMode);
	}
	else
	{
		ptr_AdasDomainData->u8_Rte_AccIaccHWAMode = 0u;  //Default Value
	}

	(void)Rte_Read_RP_Fcu_Adas_Data_ACCMode_Status(&u8_Rte_SignalSts);
	if(E_SIG_STATUS_VALID == (uint8)u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Adas_Data_ACCMode(&ptr_AdasDomainData->u8_Rte_ACC_ACCMode);
	}
	else
	{
		ptr_AdasDomainData->u8_Rte_ACC_ACCMode = 0u;  //Default Value
	}	

	return;	
}

/**
 * \functions Fcu_Chassis_Data_Process
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */
FUNC(void, RTE_CODE) Fcu_Chassis_Data_Process (s_Fcu_ChassisDomain_SignalData_t *ptr_ChassisDomainData)
{

	(void)Rte_Read_RP_Fcu_Chassis_Data_EpsSasSteerAg(&ptr_ChassisDomainData->f32_Rte_EpsSasSteerAg);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EpsSasSteerAgVld(&ptr_ChassisDomainData->u8_Rte_EpsSasSteerAgVld);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EpsSteerAgRate(&ptr_ChassisDomainData->f32_Rte_EpsSteerAgRate);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EpsPinionang(&ptr_ChassisDomainData->f32_Rte_EpsPinionang);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EPS_Pinionang_Valid(&ptr_ChassisDomainData->u8_Rte_EPS_Pinionang_Valid);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspEbdFailr(&ptr_ChassisDomainData->u8_Rte_EspEbdFailr);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspAbsFailr(&ptr_ChassisDomainData->u8_Rte_EspAbsFailr);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspAbsActv(&ptr_ChassisDomainData->u8_Rte_EspAbsActv);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspActvSts(&ptr_ChassisDomainData->u8_Rte_EspActvSts);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspVdcActvSts(&ptr_ChassisDomainData->u8_Rte_EspVdcActvSts);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspTcsActvSts(&ptr_ChassisDomainData->u8_Rte_EspTcsActvSts);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspTcsFailr(&ptr_ChassisDomainData->u8_Rte_EspTcsFailr);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspAEBdecActive(&ptr_ChassisDomainData->u8_Rte_EspAEBdecActive);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspAEBdecActive(&ptr_ChassisDomainData->u8_Rte_EspAEBdecActive);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EpsLatCtrlActive(&ptr_ChassisDomainData->u8_Rte_EpsLatCtrlActive);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EpsLatCtrlAvailabilityStatus(&ptr_ChassisDomainData->u8_Rte_EpsLatCtrlAvailabilityStatus);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EpsIACCabortreason(&ptr_ChassisDomainData->u8_Rte_EpsIACCabortreason);

	(void)Rte_Read_RP_Fcu_Chassis_Data_BrakePressureSimulator(&ptr_ChassisDomainData->f32_Rte_BrakePressureSimulator);

	(void)Rte_Read_RP_Fcu_Chassis_Data_IBCU_PFSBrakePressureValid(&ptr_ChassisDomainData->u8_Rte_IBCU_PFSBrakePressureValid);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspLatAccel(&ptr_ChassisDomainData->f32_Rte_EspLatAccel);

	(void)Rte_Read_RP_Fcu_Chassis_Data_ESP_LatAccelValid(&ptr_ChassisDomainData->u8_Rte_ESP_LatAccelValid);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspLongAccel(&ptr_ChassisDomainData->f32_Rte_EspLongAccel);

	(void)Rte_Read_RP_Fcu_Chassis_Data_ESP_LongAccelValid(&ptr_ChassisDomainData->u8_Rte_ESP_LongAccelValid);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspVehSpd(&ptr_ChassisDomainData->f32_Rte_EspVehSpd);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspVehSpdVld(&ptr_ChassisDomainData->u8_Rte_EspVehSpdVld);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspYawRate(&ptr_ChassisDomainData->f32_Rte_EspYawRate);

	(void)Rte_Read_RP_Fcu_Chassis_Data_ESP_YawRateValid(&ptr_ChassisDomainData->u8_Rte_ESP_YawRateValid);

	(void)Rte_Read_RP_Fcu_Chassis_Data_VcuGearPosn(&ptr_ChassisDomainData->u8_Rte_VcuGearPosn);

	(void)Rte_Read_RP_Fcu_Chassis_Data_AdsUDLCStatus(&ptr_ChassisDomainData->u8_Rte_ADS_UDLCStatus);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspPrefillAvailable(&ptr_ChassisDomainData->u8_Rte_EsprefillAvailable);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspAEBAvailable(&ptr_ChassisDomainData->u8_Rte_EspAEBAvailable);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspAWBavailable(&ptr_ChassisDomainData->u8_Rte_EspAWBavailable);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EspABAavailable(&ptr_ChassisDomainData->u8_Rte_EspABAavailable);

	(void)Rte_Read_RP_Fcu_Chassis_Data_VcuAccrPedlPosn(&ptr_ChassisDomainData->f32_Rte_VcuAccrPedlPosn);

	(void)Rte_Read_RP_Fcu_Chassis_Data_VcuAccrPedlPosnVld(&ptr_ChassisDomainData->u8_Rte_VcuAccrPedlPosnVld);

	(void)Rte_Read_RP_Fcu_Chassis_Data_IbBrkPedlStsGb(&ptr_ChassisDomainData->u8_Rte_IbBrkPedlStsGb);

	(void)Rte_Read_RP_Fcu_Chassis_Data_IbBrkPedlStsGbVld(&ptr_ChassisDomainData->u8_Rte_IbBrkPedlStsGbVld);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EpsMeasuredTorsionBarTorque(&ptr_ChassisDomainData->f32_Rte_EpsMeasuredTorsionBarTorque);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EPS_MeasuredTorsionBarTorqValid(&ptr_ChassisDomainData->u8_Rte_EPS_MeasuredTorsionBarTorqValid);

	(void)Rte_Read_RP_Fcu_Chassis_Data_EpsConcussAvailabilityStatus(&ptr_ChassisDomainData->u8_Rte_EpsConcussAvailabilityStatus);

	(void)Rte_Read_RP_Fcu_Chassis_Data_VcuVehGearPosnVld(&ptr_ChassisDomainData->u8_Rte_VcuVehGearPosnVld);

	(void)Rte_Read_RP_Fcu_Chassis_Data_IbBrkPedlTrvlDrvr(&ptr_ChassisDomainData->f32_Rte_IbBrkPedlTrvlDrvr);

	(void)Rte_Read_RP_Fcu_Chassis_Data_IbBrkPedlTrvlDrvrVld(&ptr_ChassisDomainData->u8_Rte_IbBrkPedlTrvlDrvrVld);

	return;
}

/**
 * \functions Fcu_Body_Data_Process
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */
FUNC(void, RTE_CODE) Fcu_Body_Data_Process (s_Fcu_BodyDomain_SignalData_t *ptr_BodyDomainData)
{
	Com_SignalSts_t  u8_Rte_SignalSts = 0;

	Rte_Read_RP_Fcu_Body_Data_BcmDrvrDoorSts_Status(&u8_Rte_SignalSts);
	u8_Rte_SignalSts = 1;
	if(E_SIG_STATUS_VALID == u8_Rte_SignalSts)
	{
		Rte_Read_RP_Fcu_Body_Data_BcmDrvrDoorSts(&ptr_BodyDomainData->u8_Rte_BcmDrvrDoorSts);
	}
	else
	{
		ptr_BodyDomainData->u8_Rte_BcmDrvrDoorSts = 0;//Default Value
	}

	Rte_Read_RP_Fcu_Body_Data_BcmLeReDoorSts_Status(&u8_Rte_SignalSts);
	u8_Rte_SignalSts = 1;
	if(E_SIG_STATUS_VALID == u8_Rte_SignalSts)
	{
		Rte_Read_RP_Fcu_Body_Data_BcmLeReDoorSts(&ptr_BodyDomainData->u8_Rte_BcmLeReDoorSts);
	}
	else
	{
		ptr_BodyDomainData->u8_Rte_BcmLeReDoorSts = 0;//Default Value
	}

	Rte_Read_RP_Fcu_Body_Data_BcmPassDoorSts_Status(&u8_Rte_SignalSts);
	u8_Rte_SignalSts = 1;
	if(E_SIG_STATUS_VALID == u8_Rte_SignalSts)
	{
		Rte_Read_RP_Fcu_Body_Data_BcmPassDoorSts(&ptr_BodyDomainData->u8_Rte_BcmPassDoorSts);
	}
	else
	{
		ptr_BodyDomainData->u8_Rte_BcmPassDoorSts = 0;//Default Value
	}

	Rte_Read_RP_Fcu_Body_Data_BcmRiReDoorSts_Status(&u8_Rte_SignalSts);
	u8_Rte_SignalSts = 1;
	if(E_SIG_STATUS_VALID == u8_Rte_SignalSts)
	{
		Rte_Read_RP_Fcu_Body_Data_BcmRiReDoorSts(&ptr_BodyDomainData->u8_Rte_BcmRiReDoorSts);
	}
	else
	{
		ptr_BodyDomainData->u8_Rte_BcmRiReDoorSts = 0;//Default Value
	}

	Rte_Read_RP_Fcu_Body_Data_SrsDrvrBucSwtSts_Status(&u8_Rte_SignalSts);
	u8_Rte_SignalSts = 1;
	if(E_SIG_STATUS_VALID == u8_Rte_SignalSts)
	{
		Rte_Read_RP_Fcu_Body_Data_SrsDrvrBucSwtSts(&ptr_BodyDomainData->u8_Rte_SrsDrvrBucSwtSts);
	}
	else
	{
		ptr_BodyDomainData->u8_Rte_SrsDrvrBucSwtSts = 0;//Default Value
	}

	Rte_Read_RP_Fcu_Body_Data_BcmTurnIndcrRi_Status(&u8_Rte_SignalSts);
	u8_Rte_SignalSts = 1;
	if(E_SIG_STATUS_VALID == u8_Rte_SignalSts)
	{
		Rte_Read_RP_Fcu_Body_Data_BcmTurnIndcrRi(&ptr_BodyDomainData->u8_Rte_BcmTurnIndcrRi);
	}
	else
	{
		ptr_BodyDomainData->u8_Rte_BcmTurnIndcrRi = 0;//Default Value
	}

	Rte_Read_RP_Fcu_Body_Data_BcmTurnIndcrLe_Status(&u8_Rte_SignalSts);
	u8_Rte_SignalSts = 1;
	if(E_SIG_STATUS_VALID == u8_Rte_SignalSts)
	{
		Rte_Read_RP_Fcu_Body_Data_BcmTurnIndcrLe(&ptr_BodyDomainData->u8_Rte_BcmTurnIndcrLe);
	}
	else
	{
		ptr_BodyDomainData->u8_Rte_BcmTurnIndcrLe = 0;//Default Value
	}

	Rte_Read_RP_Fcu_Body_Data_BcmEmgyLiSts_Status(&u8_Rte_SignalSts);
	u8_Rte_SignalSts = 1;
	if(E_SIG_STATUS_VALID == u8_Rte_SignalSts)
	{
		Rte_Read_RP_Fcu_Body_Data_BcmEmgyLiSts(&ptr_BodyDomainData->u8_Rte_BcmEmgyLiSts);
	}
	else
	{
		ptr_BodyDomainData->u8_Rte_BcmEmgyLiSts = 0;//Default Value
	}

	Rte_Read_RP_Fcu_Body_Data_BcmAutHeadLiSts_Status(&u8_Rte_SignalSts);
	u8_Rte_SignalSts = 1;
	if(E_SIG_STATUS_VALID == u8_Rte_SignalSts)
	{
		Rte_Read_RP_Fcu_Body_Data_BcmAutHeadLiSts(&ptr_BodyDomainData->u8_Rte_BcmAutHeadLiSts);
	}
	else
	{
		ptr_BodyDomainData->u8_Rte_BcmAutHeadLiSts = 0;//Default Value
	}

	Rte_Read_RP_Fcu_Body_Data_BcmFrntFogLmpSts_Status(&u8_Rte_SignalSts);
	u8_Rte_SignalSts = 1;
	if(E_SIG_STATUS_VALID == u8_Rte_SignalSts)
	{
		Rte_Read_RP_Fcu_Body_Data_BcmFrntFogLmpSts(&ptr_BodyDomainData->u8_Rte_BcmFrntFogLmpSts);
	}
	else
	{
		ptr_BodyDomainData->u8_Rte_BcmFrntFogLmpSts = 0;//Default Value
	}

	Rte_Read_RP_Fcu_Body_Data_BcmReFoglmpSts_Status(&u8_Rte_SignalSts);
	u8_Rte_SignalSts = 1;
	if(E_SIG_STATUS_VALID == u8_Rte_SignalSts)
	{
		Rte_Read_RP_Fcu_Body_Data_BcmReFoglmpSts(&ptr_BodyDomainData->u8_Rte_BcmReFoglmpSts);
	}
	else
	{
		ptr_BodyDomainData->u8_Rte_BcmReFoglmpSts = 0;//Default Value
	}

	Rte_Read_RP_Fcu_Body_Data_BcmHiBeamSts_Status(&u8_Rte_SignalSts);
	u8_Rte_SignalSts = 1;
	if(E_SIG_STATUS_VALID == u8_Rte_SignalSts)
	{
		Rte_Read_RP_Fcu_Body_Data_BcmHiBeamSts(&ptr_BodyDomainData->u8_Rte_BcmHiBeamSts);
	}
	else
	{
		ptr_BodyDomainData->u8_Rte_BcmHiBeamSts = 0;//Default Value
	}

	Rte_Read_RP_Fcu_Body_Data_BCM_TurnLightSwitchSts_Status(&u8_Rte_SignalSts);
	u8_Rte_SignalSts = 1;
	if(E_SIG_STATUS_VALID == u8_Rte_SignalSts)
	{
		Rte_Read_RP_Fcu_Body_Data_BCM_TurnLightSwitchSts(&ptr_BodyDomainData->u8_Rte_BcmTurnLightSwitchStst);
	}
	else
	{
		ptr_BodyDomainData->u8_Rte_BcmTurnLightSwitchStst = 0;//Default Value
	}

	(void)Rte_Read_RP_Fcu_Body_Data_BcmFrntWiperSts_Status(&u8_Rte_SignalSts);
	u8_Rte_SignalSts = 1;
	if(E_SIG_STATUS_VALID == u8_Rte_SignalSts)
	{
		(void)Rte_Read_RP_Fcu_Body_Data_BcmFrntWiperSts(&ptr_BodyDomainData->u8_Rte_BcmFrntWiperSts);
	}
	else
	{
		ptr_BodyDomainData->u8_Rte_BcmFrntWiperSts = 0;//Default Value
	}

	return;
}

/**
 * \functions Fcu_Powertrain_Data_Process
 *
 * \brief
 *
 * \parameters-in none
 *
 * \parameters-out none
 *
 * \return 	none
 *
 * \comments
 *
 */
FUNC(void, RTE_CODE) Fcu_Powertrain_Data_Process (s_Fcu_PowertrainDomain_SignalData_t *ptr_PowertrainData)
{

	(void)Rte_Read_RP_Fcu_Powertrain_Data_WhlSpdLeFrntDir(&ptr_PowertrainData->u8_Rte_WhlSpdLeFrntDir);

	(void)Rte_Read_RP_Fcu_Powertrain_Data_WhlSpdLeReDir(&ptr_PowertrainData->u8_Rte_WhlSpdLeReDir);

	(void)Rte_Read_RP_Fcu_Powertrain_Data_WhlSpdRiFrntDir(&ptr_PowertrainData->u8_Rte_WhlSpdRiFrntDir);

	(void)Rte_Read_RP_Fcu_Powertrain_Data_WhlSpdRiReDir(&ptr_PowertrainData->u8_Rte_WhlSpdRiReDir);

	(void)Rte_Read_RP_Fcu_Powertrain_Data_WhlSpdLeFrntData(&ptr_PowertrainData->f32_Rte_WhlSpdLeFrntData);

	(void)Rte_Read_RP_Fcu_Powertrain_Data_WhlSpdLeFrntDataVld(&ptr_PowertrainData->u8_Rte_WhlSpdLeFrntDataVld);
	
	(void)Rte_Read_RP_Fcu_Powertrain_Data_WhlSpdLeReData(&ptr_PowertrainData->f32_Rte_WhlSpdLeReData);

	(void)Rte_Read_RP_Fcu_Powertrain_Data_WhlSpdLeReDataVld(&ptr_PowertrainData->u8_Rte_WhlSpdLeReDataVld);

	(void)Rte_Read_RP_Fcu_Powertrain_Data_WhlSpdRiFrntData(&ptr_PowertrainData->f32_Rte_WhlSpdRiFrntData);

	(void)Rte_Read_RP_Fcu_Powertrain_Data_WhlSpdRiFrntDataVld(&ptr_PowertrainData->u8_Rte_WhlSpdRiFrntDataVld);

	(void)Rte_Read_RP_Fcu_Powertrain_Data_WhlSpdRiReData(&ptr_PowertrainData->f32_Rte_WhlSpdRiReData);

	(void)Rte_Read_RP_Fcu_Powertrain_Data_WhlSpdRiReDataVld(&ptr_PowertrainData->u8_Rte_WhlSpdRiReDataVld);

	return;
}



