#ifndef sim_perspectives_ver_h__
#define sim_perspectives_ver_h__

#include "cct_ver.h"

// version numbering
#define VIS_PERSPECTIVESALL_SW_MAIN_VER_NO  (1)
#define VIS_PERSPECTIVESALL_SW_SUB_VER_NO   (0)
#define VIS_PERSPECTIVESALL_SW_BUG_FIX_LEV  (0)
#define VIS_PERSPECTIVESALL_SW_BUG_FIX_LEV2 (0)

#define VIS_PERSPECTIVESALL_SW_VERSION_NUMBER ((VIS_PERSPECTIVESALL_SW_MAIN_VER_NO<<24) | (VIS_PERSPECTIVESALL_SW_SUB_VER_NO<<16) | (VIS_PERSPECTIVESALL_SW_BUG_FIX_LEV<<8) | (VIS_PERSPECTIVESALL_SW_BUG_FIX_LEV2))

#ifndef NDEBUG
#define VIS_PERSPECTIVESALL_BUILD CCT_CHECKPOINT "DEBUG"
#else
#define VIS_PERSPECTIVESALL_BUILD CCT_CHECKPOINT "RELEASE"
#endif

#endif // sim_perspectives_ver_h__
