
/**
 * \file
 *
 * \brief AUTOSAR MemMap
 *
 * This file contains the implementation of the AUTOSAR
 * module MemMap.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2018 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*==================[inclusions]=============================================*/


/* Memory section macros for Rte */

#if (defined RTE_START_SEC_CODE)
    #undef RTE_START_SEC_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_CODE)
    #undef RTE_STOP_SEC_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_32)
    #undef RTE_START_SEC_VAR_32
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_32)
    #undef RTE_STOP_SEC_VAR_32
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_UNSPECIFIED)
    #undef RTE_START_SEC_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_UNSPECIFIED)
    #undef RTE_STOP_SEC_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_8)
    #undef RTE_START_SEC_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_8)
    #undef RTE_STOP_SEC_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_16)
    #undef RTE_START_SEC_VAR_16
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_16)
    #undef RTE_STOP_SEC_VAR_16
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C1_CONST_UNSPECIFIED)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C1_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C1_CONST_UNSPECIFIED)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C1_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C1_VAR_32)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C1_VAR_32
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C1_VAR_32)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C1_VAR_32
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C1_VAR_8)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C1_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C1_VAR_8)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C1_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C1_VAR_UNSPECIFIED)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C1_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C1_VAR_UNSPECIFIED)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C1_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C1_VAR_16)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C1_VAR_16
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C1_VAR_16)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C1_VAR_16
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C1_CODE)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C1_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C1_CODE)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C1_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C1_APPL_CODE)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C1_APPL_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C1_APPL_CODE)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C1_APPL_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C0_CONST_UNSPECIFIED)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C0_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C0_CONST_UNSPECIFIED)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C0_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C0_VAR_8)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C0_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C0_VAR_8)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C0_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C0_VAR_UNSPECIFIED)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C0_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C0_VAR_UNSPECIFIED)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C0_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C0_VAR_32)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C0_VAR_32
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C0_VAR_32)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C0_VAR_32
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C0_VAR_16)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C0_VAR_16
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C0_VAR_16)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C0_VAR_16
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C0_CONST_8)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C0_CONST_8
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C0_CONST_8)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C0_CONST_8
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C0_CODE)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C0_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C0_CODE)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C0_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C0_APPL_CODE)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C0_APPL_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C0_APPL_CODE)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C0_APPL_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C1_CONST_UNSPECIFIED)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C1_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C1_CONST_UNSPECIFIED)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C1_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C1_VAR_32)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C1_VAR_32
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C1_VAR_32)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C1_VAR_32
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C1_VAR_8)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C1_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C1_VAR_8)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C1_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C1_VAR_UNSPECIFIED)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C1_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C1_VAR_UNSPECIFIED)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C1_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C1_VAR_16)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C1_VAR_16
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C1_VAR_16)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C1_VAR_16
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C1_CODE)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C1_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C1_CODE)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C1_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C1_APPL_CODE)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C1_APPL_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C1_APPL_CODE)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C1_APPL_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C2_CONST_UNSPECIFIED)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C2_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C2_CONST_UNSPECIFIED)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C2_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C2_VAR_32)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C2_VAR_32
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C2_VAR_32)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C2_VAR_32
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C2_VAR_8)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C2_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C2_VAR_8)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C2_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C2_VAR_UNSPECIFIED)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C2_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C2_VAR_UNSPECIFIED)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C2_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C2_VAR_16)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C2_VAR_16
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C2_VAR_16)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C2_VAR_16
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C2_CODE)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C2_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C2_CODE)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C2_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C2_APPL_CODE)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C2_APPL_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C2_APPL_CODE)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C2_APPL_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C2_CONST_UNSPECIFIED)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C2_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C2_CONST_UNSPECIFIED)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C2_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C2_VAR_8)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C2_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C2_VAR_8)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C2_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C2_CONST_8)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C2_CONST_8
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C2_CONST_8)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C2_CONST_8
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C2_VAR_32)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C2_VAR_32
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C2_VAR_32)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C2_VAR_32
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C2_CONST_32)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C2_CONST_32
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C2_CONST_32)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C2_CONST_32
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C2_VAR_UNSPECIFIED)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C2_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C2_VAR_UNSPECIFIED)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C2_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C2_VAR_16)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C2_VAR_16
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C2_VAR_16)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C2_VAR_16
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C2_CODE)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C2_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C2_CODE)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C2_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C2_APPL_CODE)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C2_APPL_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C2_APPL_CODE)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C2_APPL_CODE
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C1_OSAPP_BSW_QM_C0_VAR_UNSPECIFIED)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C1_OSAPP_BSW_QM_C0_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C1_OSAPP_BSW_QM_C0_VAR_UNSPECIFIED)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C1_OSAPP_BSW_QM_C0_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C1_OSAPP_BSW_QM_C0_VAR_8)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C1_OSAPP_BSW_QM_C0_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C1_OSAPP_BSW_QM_C0_VAR_8)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C1_OSAPP_BSW_QM_C0_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_SWC_QM_C1_OSAPP_BSW_QM_C1_VAR_8)
    #undef RTE_START_SEC_OSAPP_SWC_QM_C1_OSAPP_BSW_QM_C1_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_SWC_QM_C1_OSAPP_BSW_QM_C1_VAR_8)
    #undef RTE_STOP_SEC_OSAPP_SWC_QM_C1_OSAPP_BSW_QM_C1_VAR_8
    #undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_OSAPP_BSW_QM_C0_VAR_1)
    #undef RTE_START_SEC_OSAPP_BSW_QM_C0_VAR_1
    #undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_OSAPP_BSW_QM_C0_VAR_1)
    #undef RTE_STOP_SEC_OSAPP_BSW_QM_C0_VAR_1
    #undef MEMMAP_ERROR
#endif

#include <Common_MemMap.h>

