#include "Sdc_Perception_Type.h"
#include "Com.h"
#include <Com_SymbolicNames_PBcfg.h>//because of the components shall use the Signal Id


#define SDC_START_SEC_CONST_UNSPECIFIED
#include "Sdc_MemMap.h"

/*Tx FC_Object*/


const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Brakelight_Info[SDC_TX_FC_OBJECT_NUMBER] =
{
#if 1
	ComConf_ComGroupSignal_FC_obj1_Brakelight_Info_352T,
	ComConf_ComGroupSignal_FC_obj2_Brakelight_Info_353T,
	ComConf_ComGroupSignal_FC_obj3_Brakelight_Info_354T,
	ComConf_ComGroupSignal_FC_obj4_Brakelight_Info_355T,
	ComConf_ComGroupSignal_FC_obj5_Brakelight_Info_356T,
	ComConf_ComGroupSignal_FC_obj6_Brakelight_Info_357T,
	ComConf_ComGroupSignal_FC_obj7_Brakelight_Info_358T,
	ComConf_ComGroupSignal_FC_obj8_Brakelight_Info_359T,
	ComConf_ComGroupSignal_FC_obj9_Brakelight_Info_360T,
	ComConf_ComGroupSignal_FC_obj10_Brakelight_Info_361T,
	ComConf_ComGroupSignal_FC_obj11_Brakelight_Info_368T,
	ComConf_ComGroupSignal_FC_obj12_Brakelight_Info_369T,
	ComConf_ComGroupSignal_FC_obj13_Brakelight_Info_370T,
	ComConf_ComGroupSignal_FC_obj14_Brakelight_Info_371T,
	ComConf_ComGroupSignal_FC_obj15_Brakelight_Info_372T,
	ComConf_ComGroupSignal_FC_obj16_Brakelight_Info_373T,
	ComConf_ComGroupSignal_FC_obj17_Brakelight_Info_374T,
	ComConf_ComGroupSignal_FC_obj18_Brakelight_Info_375T,
	ComConf_ComGroupSignal_FC_obj19_Brakelight_Info_376T,
	ComConf_ComGroupSignal_FC_obj20_Brakelight_Info_377T
#else
	0x00
#endif
};
const uint16 Sdc_ConsigIdList_Tx_FC_Objx_CenterAngle[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_CenterAngle_352T,
	ComConf_ComGroupSignal_FC_Obj2_CenterAngle_353T,
	ComConf_ComGroupSignal_FC_Obj3_CenterAngle_354T,
	ComConf_ComGroupSignal_FC_Obj4_CenterAngle_355T,
	ComConf_ComGroupSignal_FC_Obj5_CenterAngle_356T,
	ComConf_ComGroupSignal_FC_Obj6_CenterAngle_357T,
	ComConf_ComGroupSignal_FC_Obj7_CenterAngle_358T,
	ComConf_ComGroupSignal_FC_Obj8_CenterAngle_359T,
	ComConf_ComGroupSignal_FC_Obj9_CenterAngle_360T,
	ComConf_ComGroupSignal_FC_Obj10_CenterAngle_361T,
	ComConf_ComGroupSignal_FC_Obj11_CenterAngle_368T,
	ComConf_ComGroupSignal_FC_Obj12_CenterAngle_369T,
	ComConf_ComGroupSignal_FC_Obj13_CenterAngle_370T,
	ComConf_ComGroupSignal_FC_Obj14_CenterAngle_371T,
	ComConf_ComGroupSignal_FC_Obj15_CenterAngle_372T,
	ComConf_ComGroupSignal_FC_Obj16_CenterAngle_373T,
	ComConf_ComGroupSignal_FC_Obj17_CenterAngle_374T,
	ComConf_ComGroupSignal_FC_Obj18_CenterAngle_375T,
	ComConf_ComGroupSignal_FC_Obj19_CenterAngle_376T,
	ComConf_ComGroupSignal_FC_Obj20_CenterAngle_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_CornerPoint_x[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_CornerPoint_x_352T,
	ComConf_ComGroupSignal_FC_Obj2_CornerPoint_x_353T,
	ComConf_ComGroupSignal_FC_Obj3_CornerPoint_x_354T,
	ComConf_ComGroupSignal_FC_Obj4_CornerPoint_x_355T,
	ComConf_ComGroupSignal_FC_Obj5_CornerPoint_x_356T,
	ComConf_ComGroupSignal_FC_Obj6_CornerPoint_x_357T,
	ComConf_ComGroupSignal_FC_Obj7_CornerPoint_x_358T,
	ComConf_ComGroupSignal_FC_Obj8_CornerPoint_x_359T,
	ComConf_ComGroupSignal_FC_Obj9_CornerPoint_x_360T,
	ComConf_ComGroupSignal_FC_Obj10_CornerPoint_x_361T,
	ComConf_ComGroupSignal_FC_Obj11_CornerPoint_x_368T,
	ComConf_ComGroupSignal_FC_Obj12_CornerPoint_x_369T,
	ComConf_ComGroupSignal_FC_Obj13_CornerPoint_x_370T,
	ComConf_ComGroupSignal_FC_Obj14_CornerPoint_x_371T,
	ComConf_ComGroupSignal_FC_Obj15_CornerPoint_x_372T,
	ComConf_ComGroupSignal_FC_Obj16_CornerPoint_x_373T,
	ComConf_ComGroupSignal_FC_Obj17_CornerPoint_x_374T,
	ComConf_ComGroupSignal_FC_Obj18_CornerPoint_x_375T,
	ComConf_ComGroupSignal_FC_Obj19_CornerPoint_x_376T,
	ComConf_ComGroupSignal_FC_Obj20_CornerPoint_x_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_CornerPoint_y[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_CornerPoint_y_352T,
	ComConf_ComGroupSignal_FC_Obj2_CornerPoint_y_353T,
	ComConf_ComGroupSignal_FC_Obj3_CornerPoint_y_354T,
	ComConf_ComGroupSignal_FC_Obj4_CornerPoint_y_355T,
	ComConf_ComGroupSignal_FC_Obj5_CornerPoint_y_356T,
	ComConf_ComGroupSignal_FC_Obj6_CornerPoint_y_357T,
	ComConf_ComGroupSignal_FC_Obj7_CornerPoint_y_358T,
	ComConf_ComGroupSignal_FC_Obj8_CornerPoint_y_359T,
	ComConf_ComGroupSignal_FC_Obj9_CornerPoint_y_360T,
	ComConf_ComGroupSignal_FC_Obj10_CornerPoint_y_361T,
	ComConf_ComGroupSignal_FC_Obj11_CornerPoint_y_368T,
	ComConf_ComGroupSignal_FC_Obj12_CornerPoint_y_369T,
	ComConf_ComGroupSignal_FC_Obj13_CornerPoint_y_370T,
	ComConf_ComGroupSignal_FC_Obj14_CornerPoint_y_371T,
	ComConf_ComGroupSignal_FC_Obj15_CornerPoint_y_372T,
	ComConf_ComGroupSignal_FC_Obj16_CornerPoint_y_373T,
	ComConf_ComGroupSignal_FC_Obj17_CornerPoint_y_374T,
	ComConf_ComGroupSignal_FC_Obj18_CornerPoint_y_375T,
	ComConf_ComGroupSignal_FC_Obj19_CornerPoint_y_376T,
	ComConf_ComGroupSignal_FC_Obj20_CornerPoint_y_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_CutInType[SDC_TX_FC_OBJECT_NUMBER] =
{
#if 0
	ComConf_ComSignal_SGFC_Obj1_CutInType_352T,
	ComConf_ComSignal_SGFC_Obj2_CutInType_353T,
	ComConf_ComSignal_SGFC_Obj3_CutInType_354T,
	ComConf_ComSignal_SGFC_Obj4_CutInType_355T,
	ComConf_ComSignal_SGFC_Obj5_CutInType_356T,
	ComConf_ComSignal_SGFC_Obj6_CutInType_357T,
	ComConf_ComSignal_SGFC_Obj7_CutInType_358T,
	ComConf_ComSignal_SGFC_Obj8_CutInType_359T,
	ComConf_ComSignal_SGFC_Obj9_CutInType_360T,
	ComConf_ComSignal_SGFC_Obj10_CutInType_361T,
	ComConf_ComSignal_SGFC_Obj11_CutInType_368T,
	ComConf_ComSignal_SGFC_Obj12_CutInType_369T,
	ComConf_ComSignal_SGFC_Obj13_CutInType_370T,
	ComConf_ComSignal_SGFC_Obj14_CutInType_371T,
	ComConf_ComSignal_SGFC_Obj15_CutInType_372T,
	ComConf_ComSignal_SGFC_Obj16_CutInType_373T,
	ComConf_ComSignal_SGFC_Obj17_CutInType_374T,
	ComConf_ComSignal_SGFC_Obj18_CutInType_375T,
	ComConf_ComSignal_SGFC_Obj19_CutInType_376T,
	ComConf_ComSignal_SGFC_Obj20_CutInType_377T
#else
	0x00
#endif
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_DistInLane[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_DistInLane_352T,
	ComConf_ComGroupSignal_FC_Obj2_DistInLane_353T,
	ComConf_ComGroupSignal_FC_Obj3_DistInLane_354T,
	ComConf_ComGroupSignal_FC_Obj4_DistInLane_355T,
	ComConf_ComGroupSignal_FC_Obj5_DistInLane_356T,
	ComConf_ComGroupSignal_FC_Obj6_DistInLane_357T,
	ComConf_ComGroupSignal_FC_Obj7_DistInLane_358T,
	ComConf_ComGroupSignal_FC_Obj8_DistInLane_359T,
	ComConf_ComGroupSignal_FC_Obj9_DistInLane_360T,
	ComConf_ComGroupSignal_FC_Obj10_DistInLane_361T,
	ComConf_ComGroupSignal_FC_Obj11_DistInLane_368T,
	ComConf_ComGroupSignal_FC_Obj12_DistInLane_369T,
	ComConf_ComGroupSignal_FC_Obj13_DistInLane_370T,
	ComConf_ComGroupSignal_FC_Obj14_DistInLane_371T,
	ComConf_ComGroupSignal_FC_Obj15_DistInLane_372T,
	ComConf_ComGroupSignal_FC_Obj16_DistInLane_373T,
	ComConf_ComGroupSignal_FC_Obj17_DistInLane_374T,
	ComConf_ComGroupSignal_FC_Obj18_DistInLane_375T,
	ComConf_ComGroupSignal_FC_Obj19_DistInLane_376T,
	ComConf_ComGroupSignal_FC_Obj20_DistInLane_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Dx[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_Dx_352T,
	ComConf_ComGroupSignal_FC_Obj2_Dx_353T,
	ComConf_ComGroupSignal_FC_Obj3_Dx_354T,
	ComConf_ComGroupSignal_FC_Obj4_Dx_355T,
	ComConf_ComGroupSignal_FC_Obj5_Dx_356T,
	ComConf_ComGroupSignal_FC_Obj6_Dx_357T,
	ComConf_ComGroupSignal_FC_Obj7_Dx_358T,
	ComConf_ComGroupSignal_FC_Obj8_Dx_359T,
	ComConf_ComGroupSignal_FC_Obj9_Dx_360T,
	ComConf_ComGroupSignal_FC_Obj10_Dx_361T,
	ComConf_ComGroupSignal_FC_Obj11_Dx_368T,
	ComConf_ComGroupSignal_FC_Obj12_Dx_369T,
	ComConf_ComGroupSignal_FC_Obj13_Dx_370T,
	ComConf_ComGroupSignal_FC_Obj14_Dx_371T,
	ComConf_ComGroupSignal_FC_Obj15_Dx_372T,
	ComConf_ComGroupSignal_FC_Obj16_Dx_373T,
	ComConf_ComGroupSignal_FC_Obj17_Dx_374T,
	ComConf_ComGroupSignal_FC_Obj18_Dx_375T,
	ComConf_ComGroupSignal_FC_Obj19_Dx_376T,
	ComConf_ComGroupSignal_FC_Obj20_Dx_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Dx_Vnce[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_Dx_Vnce_352T,
	ComConf_ComGroupSignal_FC_Obj2_Dx_Vnce_353T,
	ComConf_ComGroupSignal_FC_Obj3_Dx_Vnce_354T,
	ComConf_ComGroupSignal_FC_Obj4_Dx_Vnce_355T,
	ComConf_ComGroupSignal_FC_Obj5_Dx_Vnce_356T,
	ComConf_ComGroupSignal_FC_Obj6_Dx_Vnce_357T,
	ComConf_ComGroupSignal_FC_Obj7_Dx_Vnce_358T,
	ComConf_ComGroupSignal_FC_Obj8_Dx_Vnce_359T,
	ComConf_ComGroupSignal_FC_Obj9_Dx_Vnce_360T,
	ComConf_ComGroupSignal_FC_Obj10_Dx_Vnce_361T,
	ComConf_ComGroupSignal_FC_Obj11_Dx_Vnce_368T,
	ComConf_ComGroupSignal_FC_Obj12_Dx_Vnce_369T,
	ComConf_ComGroupSignal_FC_Obj13_Dx_Vnce_370T,
	ComConf_ComGroupSignal_FC_Obj14_Dx_Vnce_371T,
	ComConf_ComGroupSignal_FC_Obj15_Dx_Vnce_372T,
	ComConf_ComGroupSignal_FC_Obj16_Dx_Vnce_373T,
	ComConf_ComGroupSignal_FC_Obj17_Dx_Vnce_374T,
	ComConf_ComGroupSignal_FC_Obj18_Dx_Vnce_375T,
	ComConf_ComGroupSignal_FC_Obj19_Dx_Vnce_376T,
	ComConf_ComGroupSignal_FC_Obj20_Dx_Vnce_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Dy[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_Dy_352T,
	ComConf_ComGroupSignal_FC_Obj2_Dy_353T,
	ComConf_ComGroupSignal_FC_Obj3_Dy_354T,
	ComConf_ComGroupSignal_FC_Obj4_Dy_355T,
	ComConf_ComGroupSignal_FC_Obj5_Dy_356T,
	ComConf_ComGroupSignal_FC_Obj6_Dy_357T,
	ComConf_ComGroupSignal_FC_Obj7_Dy_358T,
	ComConf_ComGroupSignal_FC_Obj8_Dy_359T,
	ComConf_ComGroupSignal_FC_Obj9_Dy_360T,
	ComConf_ComGroupSignal_FC_Obj10_Dy_361T,
	ComConf_ComGroupSignal_FC_Obj11_Dy_368T,
	ComConf_ComGroupSignal_FC_Obj12_Dy_369T,
	ComConf_ComGroupSignal_FC_Obj13_Dy_370T,
	ComConf_ComGroupSignal_FC_Obj14_Dy_371T,
	ComConf_ComGroupSignal_FC_Obj15_Dy_372T,
	ComConf_ComGroupSignal_FC_Obj16_Dy_373T,
	ComConf_ComGroupSignal_FC_Obj17_Dy_374T,
	ComConf_ComGroupSignal_FC_Obj18_Dy_375T,
	ComConf_ComGroupSignal_FC_Obj19_Dy_376T,
	ComConf_ComGroupSignal_FC_Obj20_Dy_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Dy_Vnce[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_Dy_Vnce_352T,
	ComConf_ComGroupSignal_FC_Obj2_Dy_Vnce_353T,
	ComConf_ComGroupSignal_FC_Obj3_Dy_Vnce_354T,
	ComConf_ComGroupSignal_FC_Obj4_Dy_Vnce_355T,
	ComConf_ComGroupSignal_FC_Obj5_Dy_Vnce_356T,
	ComConf_ComGroupSignal_FC_Obj6_Dy_Vnce_357T,
	ComConf_ComGroupSignal_FC_Obj7_Dy_Vnce_358T,
	ComConf_ComGroupSignal_FC_Obj8_Dy_Vnce_359T,
	ComConf_ComGroupSignal_FC_Obj9_Dy_Vnce_360T,
	ComConf_ComGroupSignal_FC_Obj10_Dy_Vnce_361T,
	ComConf_ComGroupSignal_FC_Obj11_Dy_Vnce_368T,
	ComConf_ComGroupSignal_FC_Obj12_Dy_Vnce_369T,
	ComConf_ComGroupSignal_FC_Obj13_Dy_Vnce_370T,
	ComConf_ComGroupSignal_FC_Obj14_Dy_Vnce_371T,
	ComConf_ComGroupSignal_FC_Obj15_Dy_Vnce_372T,
	ComConf_ComGroupSignal_FC_Obj16_Dy_Vnce_373T,
	ComConf_ComGroupSignal_FC_Obj17_Dy_Vnce_374T,
	ComConf_ComGroupSignal_FC_Obj18_Dy_Vnce_375T,
	ComConf_ComGroupSignal_FC_Obj19_Dy_Vnce_376T,
	ComConf_ComGroupSignal_FC_Obj20_Dy_Vnce_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_ExistProb[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_ExistProb_352T,
	ComConf_ComGroupSignal_FC_Obj2_ExistProb_353T,
	ComConf_ComGroupSignal_FC_Obj3_ExistProb_354T,
	ComConf_ComGroupSignal_FC_Obj4_ExistProb_355T,
	ComConf_ComGroupSignal_FC_Obj5_ExistProb_356T,
	ComConf_ComGroupSignal_FC_Obj6_ExistProb_357T,
	ComConf_ComGroupSignal_FC_Obj7_ExistProb_358T,
	ComConf_ComGroupSignal_FC_Obj8_ExistProb_359T,
	ComConf_ComGroupSignal_FC_Obj9_ExistProb_360T,
	ComConf_ComGroupSignal_FC_Obj10_ExistProb_361T,
	ComConf_ComGroupSignal_FC_Obj11_ExistProb_368T,
	ComConf_ComGroupSignal_FC_Obj12_ExistProb_369T,
	ComConf_ComGroupSignal_FC_Obj13_ExistProb_370T,
	ComConf_ComGroupSignal_FC_Obj14_ExistProb_371T,
	ComConf_ComGroupSignal_FC_Obj15_ExistProb_372T,
	ComConf_ComGroupSignal_FC_Obj16_ExistProb_373T,
	ComConf_ComGroupSignal_FC_Obj17_ExistProb_374T,
	ComConf_ComGroupSignal_FC_Obj18_ExistProb_375T,
	ComConf_ComGroupSignal_FC_Obj19_ExistProb_376T,
	ComConf_ComGroupSignal_FC_Obj20_ExistProb_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_VehicleDir[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_VehicleDir_352T,
	ComConf_ComGroupSignal_FC_Obj2_VehicleDir_353T,
	ComConf_ComGroupSignal_FC_Obj3_VehicleDir_354T,
	ComConf_ComGroupSignal_FC_Obj4_VehicleDir_355T,
	ComConf_ComGroupSignal_FC_Obj5_VehicleDir_356T,
	ComConf_ComGroupSignal_FC_Obj6_VehicleDir_357T,
	ComConf_ComGroupSignal_FC_Obj7_VehicleDir_358T,
	ComConf_ComGroupSignal_FC_Obj8_VehicleDir_359T,
	ComConf_ComGroupSignal_FC_Obj9_VehicleDir_360T,
	ComConf_ComGroupSignal_FC_Obj10_VehicleDir_361T,
	ComConf_ComGroupSignal_FC_Obj11_VehicleDir_368T,
	ComConf_ComGroupSignal_FC_Obj12_VehicleDir_369T,
	ComConf_ComGroupSignal_FC_Obj13_VehicleDir_370T,
	ComConf_ComGroupSignal_FC_Obj14_VehicleDir_371T,
	ComConf_ComGroupSignal_FC_Obj15_VehicleDir_372T,
	ComConf_ComGroupSignal_FC_Obj16_VehicleDir_373T,
	ComConf_ComGroupSignal_FC_Obj17_VehicleDir_374T,
	ComConf_ComGroupSignal_FC_Obj18_VehicleDir_375T,
	ComConf_ComGroupSignal_FC_Obj19_VehicleDir_376T,
	ComConf_ComGroupSignal_FC_Obj20_VehicleDir_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_HeadingAngle[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_HeadingAngle_352T,
	ComConf_ComGroupSignal_FC_Obj2_HeadingAngle_353T,
	ComConf_ComGroupSignal_FC_Obj3_HeadingAngle_354T,
	ComConf_ComGroupSignal_FC_Obj4_HeadingAngle_355T,
	ComConf_ComGroupSignal_FC_Obj5_HeadingAngle_356T,
	ComConf_ComGroupSignal_FC_Obj6_HeadingAngle_357T,
	ComConf_ComGroupSignal_FC_Obj7_HeadingAngle_358T,
	ComConf_ComGroupSignal_FC_Obj8_HeadingAngle_359T,
	ComConf_ComGroupSignal_FC_Obj9_HeadingAngle_360T,
	ComConf_ComGroupSignal_FC_Obj10_HeadingAngle_361T,
	ComConf_ComGroupSignal_FC_Obj11_HeadingAngle_368T,
	ComConf_ComGroupSignal_FC_Obj12_HeadingAngle_369T,
	ComConf_ComGroupSignal_FC_Obj13_HeadingAngle_370T,
	ComConf_ComGroupSignal_FC_Obj14_HeadingAngle_371T,
	ComConf_ComGroupSignal_FC_Obj15_HeadingAngle_372T,
	ComConf_ComGroupSignal_FC_Obj16_HeadingAngle_373T,
	ComConf_ComGroupSignal_FC_Obj17_HeadingAngle_374T,
	ComConf_ComGroupSignal_FC_Obj18_HeadingAngle_375T,
	ComConf_ComGroupSignal_FC_Obj19_HeadingAngle_376T,
	ComConf_ComGroupSignal_FC_Obj20_HeadingAngle_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_HeadOrientation[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_HeadOrientation_352T,
	ComConf_ComGroupSignal_FC_Obj2_HeadOrientation_353T,
	ComConf_ComGroupSignal_FC_Obj3_HeadOrientation_354T,
	ComConf_ComGroupSignal_FC_Obj4_HeadOrientation_355T,
	ComConf_ComGroupSignal_FC_Obj5_HeadOrientation_356T,
	ComConf_ComGroupSignal_FC_Obj6_HeadOrientation_357T,
	ComConf_ComGroupSignal_FC_Obj7_HeadOrientation_358T,
	ComConf_ComGroupSignal_FC_Obj8_HeadOrientation_359T,
	ComConf_ComGroupSignal_FC_Obj9_HeadOrientation_360T,
	ComConf_ComGroupSignal_FC_Obj10_HeadOrientation_361T,
	ComConf_ComGroupSignal_FC_Obj11_HeadOrientation_368T,
	ComConf_ComGroupSignal_FC_Obj12_HeadOrientation_369T,
	ComConf_ComGroupSignal_FC_Obj13_HeadOrientation_370T,
	ComConf_ComGroupSignal_FC_Obj14_HeadOrientation_371T,
	ComConf_ComGroupSignal_FC_Obj15_HeadOrientation_372T,
	ComConf_ComGroupSignal_FC_Obj16_HeadOrientation_373T,
	ComConf_ComGroupSignal_FC_Obj17_HeadOrientation_374T,
	ComConf_ComGroupSignal_FC_Obj18_HeadOrientation_375T,
	ComConf_ComGroupSignal_FC_Obj19_HeadOrientation_376T,
	ComConf_ComGroupSignal_FC_Obj20_HeadOrientation_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Height[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_Height_352T,
	ComConf_ComGroupSignal_FC_Obj2_Height_353T,
	ComConf_ComGroupSignal_FC_Obj3_Height_354T,
	ComConf_ComGroupSignal_FC_Obj4_Height_355T,
	ComConf_ComGroupSignal_FC_Obj5_Height_356T,
	ComConf_ComGroupSignal_FC_Obj6_Height_357T,
	ComConf_ComGroupSignal_FC_Obj7_Height_358T,
	ComConf_ComGroupSignal_FC_Obj8_Height_359T,
	ComConf_ComGroupSignal_FC_Obj9_Height_360T,
	ComConf_ComGroupSignal_FC_Obj10_Height_361T,
	ComConf_ComGroupSignal_FC_Obj11_Height_368T,
	ComConf_ComGroupSignal_FC_Obj12_Height_369T,
	ComConf_ComGroupSignal_FC_Obj13_Height_370T,
	ComConf_ComGroupSignal_FC_Obj14_Height_371T,
	ComConf_ComGroupSignal_FC_Obj15_Height_372T,
	ComConf_ComGroupSignal_FC_Obj16_Height_373T,
	ComConf_ComGroupSignal_FC_Obj17_Height_374T,
	ComConf_ComGroupSignal_FC_Obj18_Height_375T,
	ComConf_ComGroupSignal_FC_Obj19_Height_376T,
	ComConf_ComGroupSignal_FC_Obj20_Height_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Img2dBox_LeftTop_U[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_Img2dBox_LeftTop_U_352T,
	ComConf_ComGroupSignal_FC_Obj2_Img2dBox_LeftTop_U_353T,
	ComConf_ComGroupSignal_FC_Obj3_Img2dBox_LeftTop_U_354T,
	ComConf_ComGroupSignal_FC_Obj4_Img2dBox_LeftTop_U_355T,
	ComConf_ComGroupSignal_FC_Obj5_Img2dBox_LeftTop_U_356T,
	ComConf_ComGroupSignal_FC_Obj6_Img2dBox_LeftTop_U_357T,
	ComConf_ComGroupSignal_FC_Obj7_Img2dBox_LeftTop_U_358T,
	ComConf_ComGroupSignal_FC_Obj8_Img2dBox_LeftTop_U_359T,
	ComConf_ComGroupSignal_FC_Obj9_Img2dBox_LeftTop_U_360T,
	ComConf_ComGroupSignal_FC_Obj10_Img2dBox_LeftTop_U_361T,
	ComConf_ComGroupSignal_FC_Obj11_Img2dBox_LeftTop_U_368T,
	ComConf_ComGroupSignal_FC_Obj12_Img2dBox_LeftTop_U_369T,
	ComConf_ComGroupSignal_FC_Obj13_Img2dBox_LeftTop_U_370T,
	ComConf_ComGroupSignal_FC_Obj14_Img2dBox_LeftTop_U_371T,
	ComConf_ComGroupSignal_FC_Obj15_Img2dBox_LeftTop_U_372T,
	ComConf_ComGroupSignal_FC_Obj16_Img2dBox_LeftTop_U_373T,
	ComConf_ComGroupSignal_FC_Obj17_Img2dBox_LeftTop_U_374T,
	ComConf_ComGroupSignal_FC_Obj18_Img2dBox_LeftTop_U_375T,
	ComConf_ComGroupSignal_FC_Obj19_Img2dBox_LeftTop_U_376T,
	ComConf_ComGroupSignal_FC_Obj20_Img2dBox_LeftTop_U_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Img2dBox_LeftTop_V[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_Img2dBox_LeftTop_V_352T,
	ComConf_ComGroupSignal_FC_Obj2_Img2dBox_LeftTop_V_353T,
	ComConf_ComGroupSignal_FC_Obj3_Img2dBox_LeftTop_V_354T,
	ComConf_ComGroupSignal_FC_Obj4_Img2dBox_LeftTop_V_355T,
	ComConf_ComGroupSignal_FC_Obj5_Img2dBox_LeftTop_V_356T,
	ComConf_ComGroupSignal_FC_Obj6_Img2dBox_LeftTop_V_357T,
	ComConf_ComGroupSignal_FC_Obj7_Img2dBox_LeftTop_V_358T,
	ComConf_ComGroupSignal_FC_Obj8_Img2dBox_LeftTop_V_359T,
	ComConf_ComGroupSignal_FC_Obj9_Img2dBox_LeftTop_V_360T,
	ComConf_ComGroupSignal_FC_Obj10_Img2dBox_LeftTop_V_361T,
	ComConf_ComGroupSignal_FC_Obj11_Img2dBox_LeftTop_V_368T,
	ComConf_ComGroupSignal_FC_Obj12_Img2dBox_LeftTop_V_369T,
	ComConf_ComGroupSignal_FC_Obj13_Img2dBox_LeftTop_V_370T,
	ComConf_ComGroupSignal_FC_Obj14_Img2dBox_LeftTop_V_371T,
	ComConf_ComGroupSignal_FC_Obj15_Img2dBox_LeftTop_V_372T,
	ComConf_ComGroupSignal_FC_Obj16_Img2dBox_LeftTop_V_373T,
	ComConf_ComGroupSignal_FC_Obj17_Img2dBox_LeftTop_V_374T,
	ComConf_ComGroupSignal_FC_Obj18_Img2dBox_LeftTop_V_375T,
	ComConf_ComGroupSignal_FC_Obj19_Img2dBox_LeftTop_V_376T,
	ComConf_ComGroupSignal_FC_Obj20_Img2dBox_LeftTop_V_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Img2dBox_RightDown_U[] =
{
	ComConf_ComGroupSignal_FC_Obj1_Img2dBox_RightDown_U_352T,
	ComConf_ComGroupSignal_FC_Obj2_Img2dBox_RightDown_U_353T,
	ComConf_ComGroupSignal_FC_Obj3_Img2dBox_RightDown_U_354T,
	ComConf_ComGroupSignal_FC_Obj4_Img2dBox_RightDown_U_355T,
	ComConf_ComGroupSignal_FC_Obj5_Img2dBox_RightDown_U_356T,
	ComConf_ComGroupSignal_FC_Obj6_Img2dBox_RightDown_U_357T,
	ComConf_ComGroupSignal_FC_Obj7_Img2dBox_RightDown_U_358T,
	ComConf_ComGroupSignal_FC_Obj8_Img2dBox_RightDown_U_359T,
	ComConf_ComGroupSignal_FC_Obj9_Img2dBox_RightDown_U_360T,
	ComConf_ComGroupSignal_FC_Obj10_Img2dBox_RightDown_U_361T,
	ComConf_ComGroupSignal_FC_Obj11_Img2dBox_RightDown_U_368T,
	ComConf_ComGroupSignal_FC_Obj12_Img2dBox_RightDown_U_369T,
	ComConf_ComGroupSignal_FC_Obj13_Img2dBox_RightDown_U_370T,
	ComConf_ComGroupSignal_FC_Obj14_Img2dBox_RightDown_U_371T,
	ComConf_ComGroupSignal_FC_Obj15_Img2dBox_RightDown_U_372T,
	ComConf_ComGroupSignal_FC_Obj16_Img2dBox_RightDown_U_373T,
	ComConf_ComGroupSignal_FC_Obj17_Img2dBox_RightDown_U_374T,
	ComConf_ComGroupSignal_FC_Obj18_Img2dBox_RightDown_U_375T,
	ComConf_ComGroupSignal_FC_Obj19_Img2dBox_RightDown_U_376T,
	ComConf_ComGroupSignal_FC_Obj20_Img2dBox_RightDown_U_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Img2dBox_RightDown_V[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_Img2dBox_RightDown_V_352T,
	ComConf_ComGroupSignal_FC_Obj2_Img2dBox_RightDown_V_353T,
	ComConf_ComGroupSignal_FC_Obj3_Img2dBox_RightDown_V_354T,
	ComConf_ComGroupSignal_FC_Obj4_Img2dBox_RightDown_V_355T,
	ComConf_ComGroupSignal_FC_Obj5_Img2dBox_RightDown_V_356T,
	ComConf_ComGroupSignal_FC_Obj6_Img2dBox_RightDown_V_357T,
	ComConf_ComGroupSignal_FC_Obj7_Img2dBox_RightDown_V_358T,
	ComConf_ComGroupSignal_FC_Obj8_Img2dBox_RightDown_V_359T,
	ComConf_ComGroupSignal_FC_Obj9_Img2dBox_RightDown_V_360T,
	ComConf_ComGroupSignal_FC_Obj10_Img2dBox_RightDown_V_361T,
	ComConf_ComGroupSignal_FC_Obj11_Img2dBox_RightDown_V_368T,
	ComConf_ComGroupSignal_FC_Obj12_Img2dBox_RightDown_V_369T,
	ComConf_ComGroupSignal_FC_Obj13_Img2dBox_RightDown_V_370T,
	ComConf_ComGroupSignal_FC_Obj14_Img2dBox_RightDown_V_371T,
	ComConf_ComGroupSignal_FC_Obj15_Img2dBox_RightDown_V_372T,
	ComConf_ComGroupSignal_FC_Obj16_Img2dBox_RightDown_V_373T,
	ComConf_ComGroupSignal_FC_Obj17_Img2dBox_RightDown_V_374T,
	ComConf_ComGroupSignal_FC_Obj18_Img2dBox_RightDown_V_375T,
	ComConf_ComGroupSignal_FC_Obj19_Img2dBox_RightDown_V_376T,
	ComConf_ComGroupSignal_FC_Obj20_Img2dBox_RightDown_V_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_LaneAssignment[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_LaneAssignment_352T,
	ComConf_ComGroupSignal_FC_Obj2_LaneAssignment_353T,
	ComConf_ComGroupSignal_FC_Obj3_LaneAssignment_354T,
	ComConf_ComGroupSignal_FC_Obj4_LaneAssignment_355T,
	ComConf_ComGroupSignal_FC_Obj5_LaneAssignment_356T,
	ComConf_ComGroupSignal_FC_Obj6_LaneAssignment_357T,
	ComConf_ComGroupSignal_FC_Obj7_LaneAssignment_358T,
	ComConf_ComGroupSignal_FC_Obj8_LaneAssignment_359T,
	ComConf_ComGroupSignal_FC_Obj9_LaneAssignment_360T,
	ComConf_ComGroupSignal_FC_Obj10_LaneAssignment_361T,
	ComConf_ComGroupSignal_FC_Obj11_LaneAssignment_368T,
	ComConf_ComGroupSignal_FC_Obj12_LaneAssignment_369T,
	ComConf_ComGroupSignal_FC_Obj13_LaneAssignment_370T,
	ComConf_ComGroupSignal_FC_Obj14_LaneAssignment_371T,
	ComConf_ComGroupSignal_FC_Obj15_LaneAssignment_372T,
	ComConf_ComGroupSignal_FC_Obj16_LaneAssignment_373T,
	ComConf_ComGroupSignal_FC_Obj17_LaneAssignment_374T,
	ComConf_ComGroupSignal_FC_Obj18_LaneAssignment_375T,
	ComConf_ComGroupSignal_FC_Obj19_LaneAssignment_376T,
	ComConf_ComGroupSignal_FC_Obj20_LaneAssignment_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Length[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_Length_352T,
	ComConf_ComGroupSignal_FC_Obj2_Length_353T,
	ComConf_ComGroupSignal_FC_Obj3_Length_354T,
	ComConf_ComGroupSignal_FC_Obj4_Length_355T,
	ComConf_ComGroupSignal_FC_Obj5_Length_356T,
	ComConf_ComGroupSignal_FC_Obj6_Length_357T,
	ComConf_ComGroupSignal_FC_Obj7_Length_358T,
	ComConf_ComGroupSignal_FC_Obj8_Length_359T,
	ComConf_ComGroupSignal_FC_Obj9_Length_360T,
	ComConf_ComGroupSignal_FC_Obj10_Length_361T,
	ComConf_ComGroupSignal_FC_Obj11_Length_368T,
	ComConf_ComGroupSignal_FC_Obj12_Length_369T,
	ComConf_ComGroupSignal_FC_Obj13_Length_370T,
	ComConf_ComGroupSignal_FC_Obj14_Length_371T,
	ComConf_ComGroupSignal_FC_Obj15_Length_372T,
	ComConf_ComGroupSignal_FC_Obj16_Length_373T,
	ComConf_ComGroupSignal_FC_Obj17_Length_374T,
	ComConf_ComGroupSignal_FC_Obj18_Length_375T,
	ComConf_ComGroupSignal_FC_Obj19_Length_376T,
	ComConf_ComGroupSignal_FC_Obj20_Length_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_MotionType[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_MotionType_352T,
	ComConf_ComGroupSignal_FC_Obj2_MotionType_353T,
	ComConf_ComGroupSignal_FC_Obj3_MotionType_354T,
	ComConf_ComGroupSignal_FC_Obj4_MotionType_355T,
	ComConf_ComGroupSignal_FC_Obj5_MotionType_356T,
	ComConf_ComGroupSignal_FC_Obj6_MotionType_357T,
	ComConf_ComGroupSignal_FC_Obj7_MotionType_358T,
	ComConf_ComGroupSignal_FC_Obj8_MotionType_359T,
	ComConf_ComGroupSignal_FC_Obj9_MotionType_360T,
	ComConf_ComGroupSignal_FC_Obj10_MotionType_361T,
	ComConf_ComGroupSignal_FC_Obj11_MotionType_368T,
	ComConf_ComGroupSignal_FC_Obj12_MotionType_369T,
	ComConf_ComGroupSignal_FC_Obj13_MotionType_370T,
	ComConf_ComGroupSignal_FC_Obj14_MotionType_371T,
	ComConf_ComGroupSignal_FC_Obj15_MotionType_372T,
	ComConf_ComGroupSignal_FC_Obj16_MotionType_373T,
	ComConf_ComGroupSignal_FC_Obj17_MotionType_374T,
	ComConf_ComGroupSignal_FC_Obj18_MotionType_375T,
	ComConf_ComGroupSignal_FC_Obj19_MotionType_376T,
	ComConf_ComGroupSignal_FC_Obj20_MotionType_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_objCutInFlag[] =
{
	ComConf_ComGroupSignal_FC_Obj1_objCutInFlag_352T,
	ComConf_ComGroupSignal_FC_Obj2_objCutInFlag_353T,
	ComConf_ComGroupSignal_FC_Obj3_objCutInFlag_354T,
	ComConf_ComGroupSignal_FC_Obj4_objCutInFlag_355T,
	ComConf_ComGroupSignal_FC_Obj5_objCutInFlag_356T,
	ComConf_ComGroupSignal_FC_Obj6_objCutInFlag_357T,
	ComConf_ComGroupSignal_FC_Obj7_objCutInFlag_358T,
	ComConf_ComGroupSignal_FC_Obj8_objCutInFlag_359T,
	ComConf_ComGroupSignal_FC_Obj9_objCutInFlag_360T,
	ComConf_ComGroupSignal_FC_Obj10_objCutInFlag_361T,
	ComConf_ComGroupSignal_FC_Obj11_objCutInFlag_368T,
	ComConf_ComGroupSignal_FC_Obj12_objCutInFlag_369T,
	ComConf_ComGroupSignal_FC_Obj13_objCutInFlag_370T,
	ComConf_ComGroupSignal_FC_Obj14_objCutInFlag_371T,
	ComConf_ComGroupSignal_FC_Obj15_objCutInFlag_372T,
	ComConf_ComGroupSignal_FC_Obj16_objCutInFlag_373T,
	ComConf_ComGroupSignal_FC_Obj17_objCutInFlag_374T,
	ComConf_ComGroupSignal_FC_Obj18_objCutInFlag_375T,
	ComConf_ComGroupSignal_FC_Obj19_objCutInFlag_376T,
	ComConf_ComGroupSignal_FC_Obj20_objCutInFlag_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_objCutInLane[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_objCutInLane_352T,
	ComConf_ComGroupSignal_FC_Obj2_objCutInLane_353T,
	ComConf_ComGroupSignal_FC_Obj3_objCutInLane_354T,
	ComConf_ComGroupSignal_FC_Obj4_objCutInLane_355T,
	ComConf_ComGroupSignal_FC_Obj5_objCutInLane_356T,
	ComConf_ComGroupSignal_FC_Obj6_objCutInLane_357T,
	ComConf_ComGroupSignal_FC_Obj7_objCutInLane_358T,
	ComConf_ComGroupSignal_FC_Obj8_objCutInLane_359T,
	ComConf_ComGroupSignal_FC_Obj9_objCutInLane_360T,
	ComConf_ComGroupSignal_FC_Obj10_objCutInLane_361T,
	ComConf_ComGroupSignal_FC_Obj11_objCutInLane_368T,
	ComConf_ComGroupSignal_FC_Obj12_objCutInLane_369T,
	ComConf_ComGroupSignal_FC_Obj13_objCutInLane_370T,
	ComConf_ComGroupSignal_FC_Obj14_objCutInLane_371T,
	ComConf_ComGroupSignal_FC_Obj15_objCutInLane_372T,
	ComConf_ComGroupSignal_FC_Obj16_objCutInLane_373T,
	ComConf_ComGroupSignal_FC_Obj17_objCutInLane_374T,
	ComConf_ComGroupSignal_FC_Obj18_objCutInLane_375T,
	ComConf_ComGroupSignal_FC_Obj19_objCutInLane_376T,
	ComConf_ComGroupSignal_FC_Obj20_objCutInLane_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_ObjxLeDoorSts[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1LeDoorSts_352T,
	ComConf_ComGroupSignal_FC_Obj2LeDoorSts_353T,
	ComConf_ComGroupSignal_FC_Obj3LeDoorSts_354T,
	ComConf_ComGroupSignal_FC_Obj4LeDoorSts_355T,
	ComConf_ComGroupSignal_FC_Obj5LeDoorSts_356T,
	ComConf_ComGroupSignal_FC_Obj6LeDoorSts_357T,
	ComConf_ComGroupSignal_FC_Obj7LeDoorSts_358T,
	ComConf_ComGroupSignal_FC_Obj8LeDoorSts_359T,
	ComConf_ComGroupSignal_FC_Obj9LeDoorSts_360T,
	ComConf_ComGroupSignal_FC_Obj10LeDoorSts_361T,
	ComConf_ComGroupSignal_FC_Obj11LeDoorSts_368T,
	ComConf_ComGroupSignal_FC_Obj12LeDoorSts_369T,
	ComConf_ComGroupSignal_FC_Obj13LeDoorSts_370T,
	ComConf_ComGroupSignal_FC_Obj14LeDoorSts_371T,
	ComConf_ComGroupSignal_FC_Obj15LeDoorSts_372T,
	ComConf_ComGroupSignal_FC_Obj16LeDoorSts_373T,
	ComConf_ComGroupSignal_FC_Obj17LeDoorSts_374T,
	ComConf_ComGroupSignal_FC_Obj18LeDoorSts_375T,
	ComConf_ComGroupSignal_FC_Obj19LeDoorSts_376T,
	ComConf_ComGroupSignal_FC_Obj20LeDoorSts_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_ObjxRiDoorSts[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1RiDoorSts_352T,
	ComConf_ComGroupSignal_FC_Obj2RiDoorSts_353T,
	ComConf_ComGroupSignal_FC_Obj3RiDoorSts_354T,
	ComConf_ComGroupSignal_FC_Obj4RiDoorSts_355T,
	ComConf_ComGroupSignal_FC_Obj5RiDoorSts_356T,
	ComConf_ComGroupSignal_FC_Obj6RiDoorSts_357T,
	ComConf_ComGroupSignal_FC_Obj7RiDoorSts_358T,
	ComConf_ComGroupSignal_FC_Obj8RiDoorSts_359T,
	ComConf_ComGroupSignal_FC_Obj9RiDoorSts_360T,
	ComConf_ComGroupSignal_FC_Obj10RiDoorSts_361T,
	ComConf_ComGroupSignal_FC_Obj11RiDoorSts_368T,
	ComConf_ComGroupSignal_FC_Obj12RiDoorSts_369T,
	ComConf_ComGroupSignal_FC_Obj13RiDoorSts_370T,
	ComConf_ComGroupSignal_FC_Obj14RiDoorSts_371T,
	ComConf_ComGroupSignal_FC_Obj15RiDoorSts_372T,
	ComConf_ComGroupSignal_FC_Obj16RiDoorSts_373T,
	ComConf_ComGroupSignal_FC_Obj17RiDoorSts_374T,
	ComConf_ComGroupSignal_FC_Obj18RiDoorSts_375T,
	ComConf_ComGroupSignal_FC_Obj19RiDoorSts_376T,
	ComConf_ComGroupSignal_FC_Obj20RiDoorSts_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_ObjxReDoorSts[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1ReDoorSts_352T,
	ComConf_ComGroupSignal_FC_Obj2ReDoorSts_353T,
	ComConf_ComGroupSignal_FC_Obj3ReDoorSts_354T,
	ComConf_ComGroupSignal_FC_Obj4ReDoorSts_355T,
	ComConf_ComGroupSignal_FC_Obj5ReDoorSts_356T,
	ComConf_ComGroupSignal_FC_Obj6ReDoorSts_357T,
	ComConf_ComGroupSignal_FC_Obj7ReDoorSts_358T,
	ComConf_ComGroupSignal_FC_Obj8ReDoorSts_359T,
	ComConf_ComGroupSignal_FC_Obj9ReDoorSts_360T,
	ComConf_ComGroupSignal_FC_Obj10ReDoorSts_361T,
	ComConf_ComGroupSignal_FC_Obj11ReDoorSts_368T,
	ComConf_ComGroupSignal_FC_Obj12ReDoorSts_369T,
	ComConf_ComGroupSignal_FC_Obj13ReDoorSts_370T,
	ComConf_ComGroupSignal_FC_Obj14ReDoorSts_371T,
	ComConf_ComGroupSignal_FC_Obj15ReDoorSts_372T,
	ComConf_ComGroupSignal_FC_Obj16ReDoorSts_373T,
	ComConf_ComGroupSignal_FC_Obj17ReDoorSts_374T,
	ComConf_ComGroupSignal_FC_Obj18ReDoorSts_375T,
	ComConf_ComGroupSignal_FC_Obj19ReDoorSts_376T,
	ComConf_ComGroupSignal_FC_Obj20ReDoorSts_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_RelAx[SDC_TX_FC_OBJECT_NUMBER] =
{
#if 1
	ComConf_ComGroupSignal_FC_Obj1_RelAx_352T,
	ComConf_ComGroupSignal_FC_Obj2_RelAx_353T,
	ComConf_ComGroupSignal_FC_Obj3_RelAx_354T,
	ComConf_ComGroupSignal_FC_Obj4_RelAx_355T,
	ComConf_ComGroupSignal_FC_Obj5_RelAx_356T,
	ComConf_ComGroupSignal_FC_Obj6_RelAx_357T,
	ComConf_ComGroupSignal_FC_Obj7_RelAx_358T,
	ComConf_ComGroupSignal_FC_Obj8_RelAx_359T,
	ComConf_ComGroupSignal_FC_Obj9_RelAx_360T,
	ComConf_ComGroupSignal_FC_Obj10_RelAx_361T,
	ComConf_ComGroupSignal_FC_Obj11_RelAx_368T,
	ComConf_ComGroupSignal_FC_Obj12_RelAx_369T,
	ComConf_ComGroupSignal_FC_Obj13_RelAx_370T,
	ComConf_ComGroupSignal_FC_Obj14_RelAx_371T,
	ComConf_ComGroupSignal_FC_Obj15_RelAx_372T,
	ComConf_ComGroupSignal_FC_Obj16_RelAx_373T,
	ComConf_ComGroupSignal_FC_Obj17_RelAx_374T,
	ComConf_ComGroupSignal_FC_Obj18_RelAx_375T,
	ComConf_ComGroupSignal_FC_Obj19_RelAx_376T,
	ComConf_ComGroupSignal_FC_Obj20_RelAx_377T
#else
	0x00
#endif
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_RelAy[SDC_TX_FC_OBJECT_NUMBER] =
{
#if 1
	ComConf_ComGroupSignal_FC_Obj1_RelAy_352T,
	ComConf_ComGroupSignal_FC_Obj2_RelAy_353T,
	ComConf_ComGroupSignal_FC_Obj3_RelAy_354T,
	ComConf_ComGroupSignal_FC_Obj4_RelAy_355T,
	ComConf_ComGroupSignal_FC_Obj5_RelAy_356T,
	ComConf_ComGroupSignal_FC_Obj6_RelAy_357T,
	ComConf_ComGroupSignal_FC_Obj7_RelAy_358T,
	ComConf_ComGroupSignal_FC_Obj8_RelAy_359T,
	ComConf_ComGroupSignal_FC_Obj9_RelAy_360T,
	ComConf_ComGroupSignal_FC_Obj10_RelAy_361T,
	ComConf_ComGroupSignal_FC_Obj11_RelAy_368T,
	ComConf_ComGroupSignal_FC_Obj12_RelAy_369T,
	ComConf_ComGroupSignal_FC_Obj13_RelAy_370T,
	ComConf_ComGroupSignal_FC_Obj14_RelAy_371T,
	ComConf_ComGroupSignal_FC_Obj15_RelAy_372T,
	ComConf_ComGroupSignal_FC_Obj16_RelAy_373T,
	ComConf_ComGroupSignal_FC_Obj17_RelAy_374T,
	ComConf_ComGroupSignal_FC_Obj18_RelAy_375T,
	ComConf_ComGroupSignal_FC_Obj19_RelAy_376T,
	ComConf_ComGroupSignal_FC_Obj20_RelAy_377T
#else
	0x00
#endif
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_RelVx[SDC_TX_FC_OBJECT_NUMBER] =
{
#if 1
	ComConf_ComGroupSignal_FC_Obj1_RelVx_352T,
	ComConf_ComGroupSignal_FC_Obj2_RelVx_353T,
	ComConf_ComGroupSignal_FC_Obj3_RelVx_354T,
	ComConf_ComGroupSignal_FC_Obj4_RelVx_355T,
	ComConf_ComGroupSignal_FC_Obj5_RelVx_356T,
	ComConf_ComGroupSignal_FC_Obj6_RelVx_357T,
	ComConf_ComGroupSignal_FC_Obj7_RelVx_358T,
	ComConf_ComGroupSignal_FC_Obj8_RelVx_359T,
	ComConf_ComGroupSignal_FC_Obj9_RelVx_360T,
	ComConf_ComGroupSignal_FC_Obj10_RelVx_361T,
	ComConf_ComGroupSignal_FC_Obj11_RelVx_368T,
	ComConf_ComGroupSignal_FC_Obj12_RelVx_369T,
	ComConf_ComGroupSignal_FC_Obj13_RelVx_370T,
	ComConf_ComGroupSignal_FC_Obj14_RelVx_371T,
	ComConf_ComGroupSignal_FC_Obj15_RelVx_372T,
	ComConf_ComGroupSignal_FC_Obj16_RelVx_373T,
	ComConf_ComGroupSignal_FC_Obj17_RelVx_374T,
	ComConf_ComGroupSignal_FC_Obj18_RelVx_375T,
	ComConf_ComGroupSignal_FC_Obj19_RelVx_376T,
	ComConf_ComGroupSignal_FC_Obj20_RelVx_377T
#else
	0x00
#endif
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_RelVy[SDC_TX_FC_OBJECT_NUMBER] =
{
#if 1
	ComConf_ComGroupSignal_FC_Obj1_RelVy_352T,
	ComConf_ComGroupSignal_FC_Obj2_RelVy_353T,
	ComConf_ComGroupSignal_FC_Obj3_RelVy_354T,
	ComConf_ComGroupSignal_FC_Obj4_RelVy_355T,
	ComConf_ComGroupSignal_FC_Obj5_RelVy_356T,
	ComConf_ComGroupSignal_FC_Obj6_RelVy_357T,
	ComConf_ComGroupSignal_FC_Obj7_RelVy_358T,
	ComConf_ComGroupSignal_FC_Obj8_RelVy_359T,
	ComConf_ComGroupSignal_FC_Obj9_RelVy_360T,
	ComConf_ComGroupSignal_FC_Obj10_RelVy_361T,
	ComConf_ComGroupSignal_FC_Obj11_RelVy_368T,
	ComConf_ComGroupSignal_FC_Obj12_RelVy_369T,
	ComConf_ComGroupSignal_FC_Obj13_RelVy_370T,
	ComConf_ComGroupSignal_FC_Obj14_RelVy_371T,
	ComConf_ComGroupSignal_FC_Obj15_RelVy_372T,
	ComConf_ComGroupSignal_FC_Obj16_RelVy_373T,
	ComConf_ComGroupSignal_FC_Obj17_RelVy_374T,
	ComConf_ComGroupSignal_FC_Obj18_RelVy_375T,
	ComConf_ComGroupSignal_FC_Obj19_RelVy_376T,
	ComConf_ComGroupSignal_FC_Obj20_RelVy_377T
#else
	0x00
#endif
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Taillight_Info[SDC_TX_FC_OBJECT_NUMBER] =
{
#if 0
	ComConf_ComSignal_SGFC_obj1_Taillight_Info_352T,
	ComConf_ComSignal_SGFC_obj2_Taillight_Info_353T,
	ComConf_ComSignal_SGFC_obj3_Taillight_Info_354T,
	ComConf_ComSignal_SGFC_obj4_Taillight_Info_355T,
	ComConf_ComSignal_SGFC_obj5_Taillight_Info_356T,
	ComConf_ComSignal_SGFC_obj6_Taillight_Info_357T,
	ComConf_ComSignal_SGFC_obj7_Taillight_Info_358T,
	ComConf_ComSignal_SGFC_obj8_Taillight_Info_359T,
	ComConf_ComSignal_SGFC_obj9_Taillight_Info_360T,
	ComConf_ComSignal_SGFC_obj10_Taillight_Info_361T,
	ComConf_ComSignal_SGFC_obj11_Taillight_Info_368T,
	ComConf_ComSignal_SGFC_obj12_Taillight_Info_369T,
	ComConf_ComSignal_SGFC_obj13_Taillight_Info_370T,
	ComConf_ComSignal_SGFC_obj14_Taillight_Info_371T,
	ComConf_ComSignal_SGFC_obj15_Taillight_Info_372T,
	ComConf_ComSignal_SGFC_obj16_Taillight_Info_373T,
	ComConf_ComSignal_SGFC_obj17_Taillight_Info_374T,
	ComConf_ComSignal_SGFC_obj18_Taillight_Info_375T,
	ComConf_ComSignal_SGFC_obj19_Taillight_Info_376T,
	ComConf_ComSignal_SGFC_obj20_Taillight_Info_377T
#else
	0x00
#endif
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Track_Age[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_Track_Age_352T,
	ComConf_ComGroupSignal_FC_Obj2_Track_Age_353T,
	ComConf_ComGroupSignal_FC_Obj3_Track_Age_354T,
	ComConf_ComGroupSignal_FC_Obj4_Track_Age_355T,
	ComConf_ComGroupSignal_FC_Obj5_Track_Age_356T,
	ComConf_ComGroupSignal_FC_Obj6_Track_Age_357T,
	ComConf_ComGroupSignal_FC_Obj7_Track_Age_358T,
	ComConf_ComGroupSignal_FC_Obj8_Track_Age_359T,
	ComConf_ComGroupSignal_FC_Obj9_Track_Age_360T,
	ComConf_ComGroupSignal_FC_Obj10_Track_Age_361T,
	ComConf_ComGroupSignal_FC_Obj11_Track_Age_368T,
	ComConf_ComGroupSignal_FC_Obj12_Track_Age_369T,
	ComConf_ComGroupSignal_FC_Obj13_Track_Age_370T,
	ComConf_ComGroupSignal_FC_Obj14_Track_Age_371T,
	ComConf_ComGroupSignal_FC_Obj15_Track_Age_372T,
	ComConf_ComGroupSignal_FC_Obj16_Track_Age_373T,
	ComConf_ComGroupSignal_FC_Obj17_Track_Age_374T,
	ComConf_ComGroupSignal_FC_Obj18_Track_Age_375T,
	ComConf_ComGroupSignal_FC_Obj19_Track_Age_376T,
	ComConf_ComGroupSignal_FC_Obj20_Track_Age_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Track_ID[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_Track_ID_352T,
	ComConf_ComGroupSignal_FC_Obj2_Track_ID_353T,
	ComConf_ComGroupSignal_FC_Obj3_Track_ID_354T,
	ComConf_ComGroupSignal_FC_Obj4_Track_ID_355T,
	ComConf_ComGroupSignal_FC_Obj5_Track_ID_356T,
	ComConf_ComGroupSignal_FC_Obj6_Track_ID_357T,
	ComConf_ComGroupSignal_FC_Obj7_Track_ID_358T,
	ComConf_ComGroupSignal_FC_Obj8_Track_ID_359T,
	ComConf_ComGroupSignal_FC_Obj9_Track_ID_360T,
	ComConf_ComGroupSignal_FC_Obj10_Track_ID_361T,
	ComConf_ComGroupSignal_FC_Obj11_Track_ID_368T,
	ComConf_ComGroupSignal_FC_Obj12_Track_ID_369T,
	ComConf_ComGroupSignal_FC_Obj13_Track_ID_370T,
	ComConf_ComGroupSignal_FC_Obj14_Track_ID_371T,
	ComConf_ComGroupSignal_FC_Obj15_Track_ID_372T,
	ComConf_ComGroupSignal_FC_Obj16_Track_ID_373T,
	ComConf_ComGroupSignal_FC_Obj17_Track_ID_374T,
	ComConf_ComGroupSignal_FC_Obj18_Track_ID_375T,
	ComConf_ComGroupSignal_FC_Obj19_Track_ID_376T,
	ComConf_ComGroupSignal_FC_Obj20_Track_ID_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TurnLight[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_TurnLight_352T,
	ComConf_ComGroupSignal_FC_Obj2_TurnLight_353T,
	ComConf_ComGroupSignal_FC_Obj3_TurnLight_354T,
	ComConf_ComGroupSignal_FC_Obj4_TurnLight_355T,
	ComConf_ComGroupSignal_FC_Obj5_TurnLight_356T,
	ComConf_ComGroupSignal_FC_Obj6_TurnLight_357T,
	ComConf_ComGroupSignal_FC_Obj7_TurnLight_358T,
	ComConf_ComGroupSignal_FC_Obj8_TurnLight_359T,
	ComConf_ComGroupSignal_FC_Obj9_TurnLight_360T,
	ComConf_ComGroupSignal_FC_Obj10_TurnLight_361T,
	ComConf_ComGroupSignal_FC_Obj11_TurnLight_368T,
	ComConf_ComGroupSignal_FC_Obj12_TurnLight_369T,
	ComConf_ComGroupSignal_FC_Obj13_TurnLight_370T,
	ComConf_ComGroupSignal_FC_Obj14_TurnLight_371T,
	ComConf_ComGroupSignal_FC_Obj15_TurnLight_372T,
	ComConf_ComGroupSignal_FC_Obj16_TurnLight_373T,
	ComConf_ComGroupSignal_FC_Obj17_TurnLight_374T,
	ComConf_ComGroupSignal_FC_Obj18_TurnLight_375T,
	ComConf_ComGroupSignal_FC_Obj19_TurnLight_376T,
	ComConf_ComGroupSignal_FC_Obj20_TurnLight_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Type[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_Type_352T,
	ComConf_ComGroupSignal_FC_Obj2_Type_353T,
	ComConf_ComGroupSignal_FC_Obj3_Type_354T,
	ComConf_ComGroupSignal_FC_Obj4_Type_355T,
	ComConf_ComGroupSignal_FC_Obj5_Type_356T,
	ComConf_ComGroupSignal_FC_Obj6_Type_357T,
	ComConf_ComGroupSignal_FC_Obj7_Type_358T,
	ComConf_ComGroupSignal_FC_Obj8_Type_359T,
	ComConf_ComGroupSignal_FC_Obj9_Type_360T,
	ComConf_ComGroupSignal_FC_Obj10_Type_361T,
	ComConf_ComGroupSignal_FC_Obj11_Type_368T,
	ComConf_ComGroupSignal_FC_Obj12_Type_369T,
	ComConf_ComGroupSignal_FC_Obj13_Type_370T,
	ComConf_ComGroupSignal_FC_Obj14_Type_371T,
	ComConf_ComGroupSignal_FC_Obj15_Type_372T,
	ComConf_ComGroupSignal_FC_Obj16_Type_373T,
	ComConf_ComGroupSignal_FC_Obj17_Type_374T,
	ComConf_ComGroupSignal_FC_Obj18_Type_375T,
	ComConf_ComGroupSignal_FC_Obj19_Type_376T,
	ComConf_ComGroupSignal_FC_Obj20_Type_377T

};



const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TypeProb[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_TypeProb_352T,
	ComConf_ComGroupSignal_FC_Obj2_TypeProb_353T,
	ComConf_ComGroupSignal_FC_Obj3_TypeProb_354T,
	ComConf_ComGroupSignal_FC_Obj4_TypeProb_355T,
	ComConf_ComGroupSignal_FC_Obj5_TypeProb_356T,
	ComConf_ComGroupSignal_FC_Obj6_TypeProb_357T,
	ComConf_ComGroupSignal_FC_Obj7_TypeProb_358T,
	ComConf_ComGroupSignal_FC_Obj8_TypeProb_359T,
	ComConf_ComGroupSignal_FC_Obj9_TypeProb_360T,
	ComConf_ComGroupSignal_FC_Obj10_TypeProb_361T,
	ComConf_ComGroupSignal_FC_Obj11_TypeProb_368T,
	ComConf_ComGroupSignal_FC_Obj12_TypeProb_369T,
	ComConf_ComGroupSignal_FC_Obj13_TypeProb_370T,
	ComConf_ComGroupSignal_FC_Obj14_TypeProb_371T,
	ComConf_ComGroupSignal_FC_Obj15_TypeProb_372T,
	ComConf_ComGroupSignal_FC_Obj16_TypeProb_373T,
	ComConf_ComGroupSignal_FC_Obj17_TypeProb_374T,
	ComConf_ComGroupSignal_FC_Obj18_TypeProb_375T,
	ComConf_ComGroupSignal_FC_Obj19_TypeProb_376T,
	ComConf_ComGroupSignal_FC_Obj20_TypeProb_377T

};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_valid[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_valid_352T,
	ComConf_ComGroupSignal_FC_Obj2_valid_353T,
	ComConf_ComGroupSignal_FC_Obj3_valid_354T,
	ComConf_ComGroupSignal_FC_Obj4_valid_355T,
	ComConf_ComGroupSignal_FC_Obj5_valid_356T,
	ComConf_ComGroupSignal_FC_Obj6_valid_357T,
	ComConf_ComGroupSignal_FC_Obj7_valid_358T,
	ComConf_ComGroupSignal_FC_Obj8_valid_359T,
	ComConf_ComGroupSignal_FC_Obj9_valid_360T,
	ComConf_ComGroupSignal_FC_Obj10_valid_361T,
	ComConf_ComGroupSignal_FC_Obj11_valid_368T,
	ComConf_ComGroupSignal_FC_Obj12_valid_369T,
	ComConf_ComGroupSignal_FC_Obj13_valid_370T,
	ComConf_ComGroupSignal_FC_Obj14_valid_371T,
	ComConf_ComGroupSignal_FC_Obj15_valid_372T,
	ComConf_ComGroupSignal_FC_Obj16_valid_373T,
	ComConf_ComGroupSignal_FC_Obj17_valid_374T,
	ComConf_ComGroupSignal_FC_Obj18_valid_375T,
	ComConf_ComGroupSignal_FC_Obj19_valid_376T,
	ComConf_ComGroupSignal_FC_Obj20_valid_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Vx_Vnce[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_Vx_Vnce_352T,
	ComConf_ComGroupSignal_FC_Obj2_Vx_Vnce_353T,
	ComConf_ComGroupSignal_FC_Obj3_Vx_Vnce_354T,
	ComConf_ComGroupSignal_FC_Obj4_Vx_Vnce_355T,
	ComConf_ComGroupSignal_FC_Obj5_Vx_Vnce_356T,
	ComConf_ComGroupSignal_FC_Obj6_Vx_Vnce_357T,
	ComConf_ComGroupSignal_FC_Obj7_Vx_Vnce_358T,
	ComConf_ComGroupSignal_FC_Obj8_Vx_Vnce_359T,
	ComConf_ComGroupSignal_FC_Obj9_Vx_Vnce_360T,
	ComConf_ComGroupSignal_FC_Obj10_Vx_Vnce_361T,
	ComConf_ComGroupSignal_FC_Obj11_Vx_Vnce_368T,
	ComConf_ComGroupSignal_FC_Obj12_Vx_Vnce_369T,
	ComConf_ComGroupSignal_FC_Obj13_Vx_Vnce_370T,
	ComConf_ComGroupSignal_FC_Obj14_Vx_Vnce_371T,
	ComConf_ComGroupSignal_FC_Obj15_Vx_Vnce_372T,
	ComConf_ComGroupSignal_FC_Obj16_Vx_Vnce_373T,
	ComConf_ComGroupSignal_FC_Obj17_Vx_Vnce_374T,
	ComConf_ComGroupSignal_FC_Obj18_Vx_Vnce_375T,
	ComConf_ComGroupSignal_FC_Obj19_Vx_Vnce_376T,
	ComConf_ComGroupSignal_FC_Obj20_Vx_Vnce_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Vy_Vnce[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_Vy_Vnce_352T,
	ComConf_ComGroupSignal_FC_Obj2_Vy_Vnce_353T,
	ComConf_ComGroupSignal_FC_Obj3_Vy_Vnce_354T,
	ComConf_ComGroupSignal_FC_Obj4_Vy_Vnce_355T,
	ComConf_ComGroupSignal_FC_Obj5_Vy_Vnce_356T,
	ComConf_ComGroupSignal_FC_Obj6_Vy_Vnce_357T,
	ComConf_ComGroupSignal_FC_Obj7_Vy_Vnce_358T,
	ComConf_ComGroupSignal_FC_Obj8_Vy_Vnce_359T,
	ComConf_ComGroupSignal_FC_Obj9_Vy_Vnce_360T,
	ComConf_ComGroupSignal_FC_Obj10_Vy_Vnce_361T,
	ComConf_ComGroupSignal_FC_Obj11_Vy_Vnce_368T,
	ComConf_ComGroupSignal_FC_Obj12_Vy_Vnce_369T,
	ComConf_ComGroupSignal_FC_Obj13_Vy_Vnce_370T,
	ComConf_ComGroupSignal_FC_Obj14_Vy_Vnce_371T,
	ComConf_ComGroupSignal_FC_Obj15_Vy_Vnce_372T,
	ComConf_ComGroupSignal_FC_Obj16_Vy_Vnce_373T,
	ComConf_ComGroupSignal_FC_Obj17_Vy_Vnce_374T,
	ComConf_ComGroupSignal_FC_Obj18_Vy_Vnce_375T,
	ComConf_ComGroupSignal_FC_Obj19_Vy_Vnce_376T,
	ComConf_ComGroupSignal_FC_Obj20_Vy_Vnce_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_Width[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1_Width_352T,
	ComConf_ComGroupSignal_FC_Obj2_Width_353T,
	ComConf_ComGroupSignal_FC_Obj3_Width_354T,
	ComConf_ComGroupSignal_FC_Obj4_Width_355T,
	ComConf_ComGroupSignal_FC_Obj5_Width_356T,
	ComConf_ComGroupSignal_FC_Obj6_Width_357T,
	ComConf_ComGroupSignal_FC_Obj7_Width_358T,
	ComConf_ComGroupSignal_FC_Obj8_Width_359T,
	ComConf_ComGroupSignal_FC_Obj9_Width_360T,
	ComConf_ComGroupSignal_FC_Obj10_Width_361T,
	ComConf_ComGroupSignal_FC_Obj11_Width_368T,
	ComConf_ComGroupSignal_FC_Obj12_Width_369T,
	ComConf_ComGroupSignal_FC_Obj13_Width_370T,
	ComConf_ComGroupSignal_FC_Obj14_Width_371T,
	ComConf_ComGroupSignal_FC_Obj15_Width_372T,
	ComConf_ComGroupSignal_FC_Obj16_Width_373T,
	ComConf_ComGroupSignal_FC_Obj17_Width_374T,
	ComConf_ComGroupSignal_FC_Obj18_Width_375T,
	ComConf_ComGroupSignal_FC_Obj19_Width_376T,
	ComConf_ComGroupSignal_FC_Obj20_Width_377T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Obj1WSInfoPosType[SDC_TX_FC_OBJECT_NUMBER] =
{
	ComConf_ComGroupSignal_FC_Obj1WSInfoPosType_352T,
	ComConf_ComGroupSignal_FC_Obj2WSInfoPosType_353T,
	ComConf_ComGroupSignal_FC_Obj3WSInfoPosType_354T,
	ComConf_ComGroupSignal_FC_Obj4WSInfoPosType_355T,
	ComConf_ComGroupSignal_FC_Obj5WSInfoPosType_356T,
	ComConf_ComGroupSignal_FC_Obj6WSInfoPosType_357T,
	ComConf_ComGroupSignal_FC_Obj7WSInfoPosType_358T,
	ComConf_ComGroupSignal_FC_Obj8WSInfoPosType_359T,
	ComConf_ComGroupSignal_FC_Obj9WSInfoPosType_360T,
	ComConf_ComGroupSignal_FC_Obj10WSInfoPosType_361T,
	ComConf_ComGroupSignal_FC_Obj11WSInfoPosType_368T,
	ComConf_ComGroupSignal_FC_Obj12WSInfoPosType_369T,
	ComConf_ComGroupSignal_FC_Obj13WSInfoPosType_370T,
	ComConf_ComGroupSignal_FC_Obj14WSInfoPosType_371T,
	ComConf_ComGroupSignal_FC_Obj15WSInfoPosType_372T,
	ComConf_ComGroupSignal_FC_Obj16WSInfoPosType_373T,
	ComConf_ComGroupSignal_FC_Obj17WSInfoPosType_374T,
	ComConf_ComGroupSignal_FC_Obj18WSInfoPosType_375T,
	ComConf_ComGroupSignal_FC_Obj19WSInfoPosType_376T,
	ComConf_ComGroupSignal_FC_Obj20WSInfoPosType_377T
};


const uint16 Sdc_ConsigIdList_Tx_FC_ObstacleData[SDC_TX_FC_OBJECT_NUMBER] = 
{
    ComConf_ComGroupSignal_FC_Obj1_valid_352T,
    ComConf_ComGroupSignal_FC_Obj2_valid_353T,
    ComConf_ComGroupSignal_FC_Obj3_valid_354T,
    ComConf_ComGroupSignal_FC_Obj4_valid_355T,
    ComConf_ComGroupSignal_FC_Obj5_valid_356T,
    ComConf_ComGroupSignal_FC_Obj6_valid_357T,
    ComConf_ComGroupSignal_FC_Obj7_valid_358T,
    ComConf_ComGroupSignal_FC_Obj8_valid_359T,
    ComConf_ComGroupSignal_FC_Obj9_valid_360T,
    ComConf_ComGroupSignal_FC_Obj10_valid_361T,
    ComConf_ComGroupSignal_FC_Obj11_valid_368T,
    ComConf_ComGroupSignal_FC_Obj12_valid_369T,
    ComConf_ComGroupSignal_FC_Obj13_valid_370T,
    ComConf_ComGroupSignal_FC_Obj14_valid_371T,
    ComConf_ComGroupSignal_FC_Obj15_valid_372T,
    ComConf_ComGroupSignal_FC_Obj16_valid_373T,
    ComConf_ComGroupSignal_FC_Obj17_valid_374T,
    ComConf_ComGroupSignal_FC_Obj18_valid_375T,
    ComConf_ComGroupSignal_FC_Obj19_valid_376T,
    ComConf_ComGroupSignal_FC_Obj20_valid_377T
};
#if (SDC_PERCEPTION_TSR_TFL_STRUCT_ENABLE == STD_ON)
const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_ClassificationType[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM]=
{
    ComConf_ComGroupSignal_FC_TLA1_ClassificationType_405T,
    ComConf_ComGroupSignal_FC_TLA2_ClassificationType_405T,
    ComConf_ComGroupSignal_FC_TLA3_ClassificationType_405T,
    ComConf_ComGroupSignal_FC_TLA4_ClassificationType_405T,
    ComConf_ComGroupSignal_FC_TLA5_ClassificationType_406T,
    ComConf_ComGroupSignal_FC_TLA6_ClassificationType_406T,
    ComConf_ComGroupSignal_FC_TLA7_ClassificationType_406T,
    ComConf_ComGroupSignal_FC_TLA8_ClassificationType_406T
};


const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_Color[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComGroupSignal_FC_TLA1_Color_405T,
    ComConf_ComGroupSignal_FC_TLA2_Color_405T,
    ComConf_ComGroupSignal_FC_TLA3_Color_405T,
    ComConf_ComGroupSignal_FC_TLA4_Color_405T,
    ComConf_ComGroupSignal_FC_TLA5_Color_406T,
    ComConf_ComGroupSignal_FC_TLA6_Color_406T,
    ComConf_ComGroupSignal_FC_TLA7_Color_406T,
    ComConf_ComGroupSignal_FC_TLA8_Color_406T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_direction[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComGroupSignal_FC_TLA1_direction_405T,
    ComConf_ComGroupSignal_FC_TLA2_direction_405T,
    ComConf_ComGroupSignal_FC_TLA3_direction_405T,
    ComConf_ComGroupSignal_FC_TLA4_direction_405T,
    ComConf_ComGroupSignal_FC_TLA5_direction_406T,
    ComConf_ComGroupSignal_FC_TLA6_direction_406T,
    ComConf_ComGroupSignal_FC_TLA7_direction_406T,
    ComConf_ComGroupSignal_FC_TLA8_direction_406T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_BlindingStatus[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComGroupSignal_FC_TLA1_BlindingStatus_405T,
    ComConf_ComGroupSignal_FC_TLA2_BlindingStatus_405T,
    ComConf_ComGroupSignal_FC_TLA3_BlindingStatus_405T,
    ComConf_ComGroupSignal_FC_TLA4_BlindingStatus_405T,
    ComConf_ComGroupSignal_FC_TLA5_BlindingStatus_406T,
    ComConf_ComGroupSignal_FC_TLA6_BlindingStatus_406T,
    ComConf_ComGroupSignal_FC_TLA7_BlindingStatus_406T,
    ComConf_ComGroupSignal_FC_TLA8_BlindingStatus_406T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_PosX[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComGroupSignal_FC_TLA1_PosX_405T,
	ComConf_ComGroupSignal_FC_TLA2_PosX_405T,
	ComConf_ComGroupSignal_FC_TLA3_PosX_405T,
	ComConf_ComGroupSignal_FC_TLA4_PosX_405T,
	ComConf_ComGroupSignal_FC_TLA5_PosX_406T,
	ComConf_ComGroupSignal_FC_TLA6_PosX_406T,
	ComConf_ComGroupSignal_FC_TLA7_PosX_406T,
	ComConf_ComGroupSignal_FC_TLA8_PosX_406T
};



const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_PosY[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComGroupSignal_FC_TLA1_PosY_405T,
    ComConf_ComGroupSignal_FC_TLA2_PosY_405T,
    ComConf_ComGroupSignal_FC_TLA3_PosY_405T,
    ComConf_ComGroupSignal_FC_TLA4_PosY_405T,
    ComConf_ComGroupSignal_FC_TLA5_PosY_406T,
    ComConf_ComGroupSignal_FC_TLA6_PosY_406T,
    ComConf_ComGroupSignal_FC_TLA7_PosY_406T,
    ComConf_ComGroupSignal_FC_TLA8_PosY_406T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_PosZ[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComGroupSignal_FC_TLA1_PosZ_405T,
    ComConf_ComGroupSignal_FC_TLA2_PosZ_405T,
    ComConf_ComGroupSignal_FC_TLA3_PosZ_405T,
    ComConf_ComGroupSignal_FC_TLA4_PosZ_405T,
    ComConf_ComGroupSignal_FC_TLA5_PosZ_406T,
    ComConf_ComGroupSignal_FC_TLA6_PosZ_406T,
    ComConf_ComGroupSignal_FC_TLA7_PosZ_406T,
    ComConf_ComGroupSignal_FC_TLA8_PosZ_406T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_Confidence[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComGroupSignal_FC_TLA1_Confidence_405T,
    ComConf_ComGroupSignal_FC_TLA2_Confidence_405T,
    ComConf_ComGroupSignal_FC_TLA3_Confidence_405T,
    ComConf_ComGroupSignal_FC_TLA4_Confidence_405T,
    ComConf_ComGroupSignal_FC_TLA5_Confidence_406T,
    ComConf_ComGroupSignal_FC_TLA6_Confidence_406T,
    ComConf_ComGroupSignal_FC_TLA7_Confidence_406T,
    ComConf_ComGroupSignal_FC_TLA8_Confidence_406T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_ShapeType[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComGroupSignal_FC_TLA1_ShapeType_405T,
    ComConf_ComGroupSignal_FC_TLA2_ShapeType_405T,
    ComConf_ComGroupSignal_FC_TLA3_ShapeType_405T,
    ComConf_ComGroupSignal_FC_TLA4_ShapeType_405T,
    ComConf_ComGroupSignal_FC_TLA5_ShapeType_406T,
    ComConf_ComGroupSignal_FC_TLA6_ShapeType_406T,
    ComConf_ComGroupSignal_FC_TLA7_ShapeType_406T,
    ComConf_ComGroupSignal_FC_TLA8_ShapeType_406T
};


#if 0 	/*dbc v2.3 delete*/
const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_SignBoardType[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComSignal_SGFC_SignBoardType_1_407T,
    ComConf_ComSignal_SGFC_SignBoardType_2_407T,
    ComConf_ComSignal_SGFC_SignBoardType_3_407T,
    ComConf_ComSignal_SGFC_SignBoardType_4_407T,
    0u,
    0u,
    0u,
    0u
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_SpeedLimit[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComSignal_SGFC_SpeedLimit_1_407T,
    ComConf_ComSignal_SGFC_SpeedLimit_2_407T,
    ComConf_ComSignal_SGFC_SpeedLimit_3_407T,
    ComConf_ComSignal_SGFC_SpeedLimit_4_407T,
    0u,
    0u,
    0u,
    0u
};


const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_SpeedLimitType[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComSignal_SGFC_SpeedLimitType_1_407T,
    ComConf_ComSignal_SGFC_SpeedLimitType_2_407T,
    ComConf_ComSignal_SGFC_SpeedLimitType_3_407T,
    ComConf_ComSignal_SGFC_SpeedLimitType_4_407T,
    0u,
    0u,
    0u,
    0u
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_SignBoardCenterLngRange[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComSignal_SGFC_SignBoardCenterLngRange_1_407T,
    ComConf_ComSignal_SGFC_SignBoardCenterLngRange_2_407T,
    ComConf_ComSignal_SGFC_SignBoardCenterLngRange_3_407T,
    ComConf_ComSignal_SGFC_SignBoardCenterLngRange_4_407T,
    0u,
    0u,
    0u,
    0u

};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_SignBoardCenterLatRange[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComSignal_SGFC_SignBoardCenterLatRange_1_407T,
    ComConf_ComSignal_SGFC_SignBoardCenterLatRange_2_407T,
    ComConf_ComSignal_SGFC_SignBoardCenterLatRange_3_407T,
    ComConf_ComSignal_SGFC_SignBoardCenterLatRange_4_407T,
    0u,
    0u,
    0u,
    0u

};


const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_SignBoardHeight[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComSignal_SGFC_SignBoardHeight_1_407T,
    ComConf_ComSignal_SGFC_SignBoardHeight_2_407T,
    ComConf_ComSignal_SGFC_SignBoardHeight_3_407T,
    ComConf_ComSignal_SGFC_SignBoardHeight_4_407T,
    0u,
    0u,
    0u,
    0u

};
#endif

#if 0 //delete dbc v2.3
const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_SignBoardConfidence[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComSignal_SGFC_SignBoardConfidence_1_407T,
    ComConf_ComSignal_SGFC_SignBoardConfidence_2_407T,
    ComConf_ComSignal_SGFC_SignBoardConfidence_3_407T,
    ComConf_ComSignal_SGFC_SignBoardConfidence_4_407T,
    0u,
    0u,
    0u,
    0u

};
#endif

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_LM_RoadSignType[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM] =
{
    ComConf_ComGroupSignal_FC_RoadSignType_1_408T,
    ComConf_ComGroupSignal_FC_RoadSignType_2_408T,
    ComConf_ComGroupSignal_FC_RoadSignType_3_408T,
    0u,/*ComConf_ComSignal_SGFC_RoadSignType_4_408T ---dbc v2.3 delete */
    0u,
    0u,
    0u,
    0u

};



const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_LM_RoadSignConfidence[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM]=
{
    ComConf_ComGroupSignal_FC_RoadSignConfidence_1_408T,
    ComConf_ComGroupSignal_FC_RoadSignConfidence_2_408T,
    ComConf_ComGroupSignal_FC_RoadSignConfidence_3_408T,
    0u,/*ComConf_ComSignal_SGFC_RoadSignConfidence_4_408T,---dbc v2.3 delete */
    0u,
    0u,
    0u,
    0u
};


const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_LM_RoadSignCenterLngRange[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM]=
{
    ComConf_ComGroupSignal_FC_RoadSignCenterLngRange_1_408T,
    ComConf_ComGroupSignal_FC_RoadSignCenterLngRange_2_408T,
    ComConf_ComGroupSignal_FC_RoadSignCenterLngRange_3_408T,
    0u,/*ComConf_ComSignal_SGFC_RoadSignCenterLngRange_4_408T,---dbc v2.3 delete */
    0u,
    0u,
    0u,
    0u
};


const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_LM_RoadSignCenterLatRange[SDC_J3_TSR_TFL_TRAFFICSIGN_NUM]=
{
    ComConf_ComGroupSignal_FC_RoadSignCenterLatRange_1_408T,
    ComConf_ComGroupSignal_FC_RoadSignCenterLatRange_2_408T,
    ComConf_ComGroupSignal_FC_RoadSignCenterLatRange_3_408T,
    0u,/*ComConf_ComSignal_SGFC_RoadSignCenterLatRange_4_408T,---dbc v2.3 delete */
    0u,
    0u,
    0u,
    0u
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_LM_FC_StaticObj_Dx[20u]=
{
    ComConf_ComGroupSignal_FC_StaticObj1_Dx_384T,
    ComConf_ComGroupSignal_FC_StaticObj2_Dx_384T,
    ComConf_ComGroupSignal_FC_StaticObj3_Dx_384T,
    ComConf_ComGroupSignal_FC_StaticObj4_Dx_384T,
    ComConf_ComGroupSignal_FC_StaticObj5_Dx_384T,
    ComConf_ComGroupSignal_FC_StaticObj6_Dx_384T,
    ComConf_ComGroupSignal_FC_StaticObj7_Dx_384T,
    ComConf_ComGroupSignal_FC_StaticObj8_Dx_384T,
    ComConf_ComGroupSignal_FC_StaticObj9_Dx_384T,
    ComConf_ComGroupSignal_FC_StaticObj10_Dx_384T,
    ComConf_ComGroupSignal_FC_StaticObj11_Dx_385T,
    ComConf_ComGroupSignal_FC_StaticObj12_Dx_385T,
    ComConf_ComGroupSignal_FC_StaticObj13_Dx_385T,
    ComConf_ComGroupSignal_FC_StaticObj14_Dx_385T,
    ComConf_ComGroupSignal_FC_StaticObj15_Dx_385T,
    ComConf_ComGroupSignal_FC_StaticObj16_Dx_385T,
    ComConf_ComGroupSignal_FC_StaticObj17_Dx_385T,
    ComConf_ComGroupSignal_FC_StaticObj18_Dx_385T,
    ComConf_ComGroupSignal_FC_StaticObj19_Dx_385T,
    ComConf_ComGroupSignal_FC_StaticObj20_Dx_385T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_LM_FC_StaticObj_Dy[20u]=
{
    ComConf_ComGroupSignal_FC_StaticObj1_Dy_384T,
    ComConf_ComGroupSignal_FC_StaticObj2_Dy_384T,
    ComConf_ComGroupSignal_FC_StaticObj3_Dy_384T,
    ComConf_ComGroupSignal_FC_StaticObj4_Dy_384T,
    ComConf_ComGroupSignal_FC_StaticObj5_Dy_384T,
    ComConf_ComGroupSignal_FC_StaticObj6_Dy_384T,
    ComConf_ComGroupSignal_FC_StaticObj7_Dy_384T,
    ComConf_ComGroupSignal_FC_StaticObj8_Dy_384T,
    ComConf_ComGroupSignal_FC_StaticObj9_Dy_384T,
    ComConf_ComGroupSignal_FC_StaticObj10_Dy_384T,
    ComConf_ComGroupSignal_FC_StaticObj11_Dy_385T,
    ComConf_ComGroupSignal_FC_StaticObj12_Dy_385T,
    ComConf_ComGroupSignal_FC_StaticObj13_Dy_385T,
    ComConf_ComGroupSignal_FC_StaticObj14_Dy_385T,
    ComConf_ComGroupSignal_FC_StaticObj15_Dy_385T,
    ComConf_ComGroupSignal_FC_StaticObj16_Dy_385T,
    ComConf_ComGroupSignal_FC_StaticObj17_Dy_385T,
    ComConf_ComGroupSignal_FC_StaticObj18_Dy_385T,
    ComConf_ComGroupSignal_FC_StaticObj19_Dy_385T,
    ComConf_ComGroupSignal_FC_StaticObj20_Dy_385T
};


const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_LM_FC_StaticObj_Type[20u]=
{
    ComConf_ComGroupSignal_FC_StaticObj1_Type_384T,
    ComConf_ComGroupSignal_FC_StaticObj2_Type_384T,
    ComConf_ComGroupSignal_FC_StaticObj3_Type_384T,
    ComConf_ComGroupSignal_FC_StaticObj4_Type_384T,
    ComConf_ComGroupSignal_FC_StaticObj5_Type_384T,
    ComConf_ComGroupSignal_FC_StaticObj6_Type_384T,
    ComConf_ComGroupSignal_FC_StaticObj7_Type_384T,
    ComConf_ComGroupSignal_FC_StaticObj8_Type_384T,
    ComConf_ComGroupSignal_FC_StaticObj9_Type_384T,
    ComConf_ComGroupSignal_FC_StaticObj10_Type_384T,
    ComConf_ComGroupSignal_FC_StaticObj11_Type_385T,
    ComConf_ComGroupSignal_FC_StaticObj12_Type_385T,
    ComConf_ComGroupSignal_FC_StaticObj13_Type_385T,
    ComConf_ComGroupSignal_FC_StaticObj14_Type_385T,
    ComConf_ComGroupSignal_FC_StaticObj15_Type_385T,
    ComConf_ComGroupSignal_FC_StaticObj16_Type_385T,
    ComConf_ComGroupSignal_FC_StaticObj17_Type_385T,
    ComConf_ComGroupSignal_FC_StaticObj18_Type_385T,
    ComConf_ComGroupSignal_FC_StaticObj19_Type_385T,
    ComConf_ComGroupSignal_FC_StaticObj20_Type_385T
};
//add by yf at 22.10.12
const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_LM_FC_StaticObj_LaneAssi[20u]=
{
    ComConf_ComGroupSignal_FC_StaticObj1_LaneAssi_384T,
    ComConf_ComGroupSignal_FC_StaticObj2_LaneAssi_384T,
    ComConf_ComGroupSignal_FC_StaticObj3_LaneAssi_384T,
    ComConf_ComGroupSignal_FC_StaticObj4_LaneAssi_384T,
    ComConf_ComGroupSignal_FC_StaticObj5_LaneAssi_384T,
    ComConf_ComGroupSignal_FC_StaticObj6_LaneAssi_384T,
    ComConf_ComGroupSignal_FC_StaticObj7_LaneAssi_384T,
    ComConf_ComGroupSignal_FC_StaticObj8_LaneAssi_384T,
    ComConf_ComGroupSignal_FC_StaticObj9_LaneAssi_384T,
    ComConf_ComGroupSignal_FC_StaticObj10_LaneAssi_384T,
    ComConf_ComGroupSignal_FC_StaticObj11_LaneAssi_385T,
    ComConf_ComGroupSignal_FC_StaticObj12_LaneAssi_385T,
    ComConf_ComGroupSignal_FC_StaticObj13_LaneAssi_385T,
    ComConf_ComGroupSignal_FC_StaticObj14_LaneAssi_385T,
    ComConf_ComGroupSignal_FC_StaticObj15_LaneAssi_385T,
    ComConf_ComGroupSignal_FC_StaticObj16_LaneAssi_385T,
    ComConf_ComGroupSignal_FC_StaticObj17_LaneAssi_385T,
    ComConf_ComGroupSignal_FC_StaticObj18_LaneAssi_385T,
    ComConf_ComGroupSignal_FC_StaticObj19_LaneAssi_385T,
    ComConf_ComGroupSignal_FC_StaticObj20_LaneAssi_385T
};

const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_LM_FC_StaticObj_TrackID[20u]=
{
    ComConf_ComGroupSignal_FC_StaticObj1_Track_ID_384T,
    ComConf_ComGroupSignal_FC_StaticObj2_Track_ID_384T,
    ComConf_ComGroupSignal_FC_StaticObj3_Track_ID_384T,
    ComConf_ComGroupSignal_FC_StaticObj4_Track_ID_384T,
    ComConf_ComGroupSignal_FC_StaticObj5_Track_ID_384T,
    ComConf_ComGroupSignal_FC_StaticObj6_Track_ID_384T,
    ComConf_ComGroupSignal_FC_StaticObj7_Track_ID_384T,
    ComConf_ComGroupSignal_FC_StaticObj8_Track_ID_384T,
    ComConf_ComGroupSignal_FC_StaticObj9_Track_ID_384T,
    ComConf_ComGroupSignal_FC_StaticObj10_Track_ID_384T,
    ComConf_ComGroupSignal_FC_StaticObj11_Track_ID_385T,
    ComConf_ComGroupSignal_FC_StaticObj12_Track_ID_385T,
    ComConf_ComGroupSignal_FC_StaticObj13_Track_ID_385T,
    ComConf_ComGroupSignal_FC_StaticObj14_Track_ID_385T,
    ComConf_ComGroupSignal_FC_StaticObj15_Track_ID_385T,
    ComConf_ComGroupSignal_FC_StaticObj16_Track_ID_385T,
    ComConf_ComGroupSignal_FC_StaticObj17_Track_ID_385T,
    ComConf_ComGroupSignal_FC_StaticObj18_Track_ID_385T,
    ComConf_ComGroupSignal_FC_StaticObj19_Track_ID_385T,
    ComConf_ComGroupSignal_FC_StaticObj20_Track_ID_385T
};
//add by yf at 22.10.12
const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_LM_FC_Pole_LiftAng[2u]=
{
    ComConf_ComGroupSignal_FC_Pole1_LiftAng_407T,
    ComConf_ComGroupSignal_FC_Pole2_LiftAng_407T
};
const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_LM_FC_Pole_Dx[2u]=
{
    ComConf_ComGroupSignal_FC_Pole1_Dx_407T,
    ComConf_ComGroupSignal_FC_Pole2_Dx_407T
};
const uint16 Sdc_ConsigIdList_Tx_FC_Objx_TSR_TFL_TLA_LM_FC_Pole_Dy[2u]=
{
    ComConf_ComGroupSignal_FC_Pole1_Dy_407T,
    ComConf_ComGroupSignal_FC_Pole2_Dy_407T
};
#endif	/*SDC_PERCEPTION_TSR_TFL_STRUCT_ENABLE == STD_ON*/

#define SDC_STOP_SEC_CONST_UNSPECIFIED
#include "Sdc_MemMap.h"