IF "%TARGET%"=="" SET TARGET=TRICORE
IF "%DERIVATE%"=="" SET DERIVATE=TC38XQ
IF "%TOOLCHAIN%"=="" SET TOOLCHAIN=tasking
IF [%TOOLPATH_COMPILER%]==[] SET TOOLPATH_COMPILER=%TASKING_TriCore_v6_3r1%
IF [%PROJECT_BASE%]==[] SET PROJECT_BASE=..\..\
IF [%TRESOS_BASE%]==[] SET TRESOS_BASE=..\..\00_AsrStack
IF [%PLUGINS_BASE%]==[] set PLUGINS_BASE=%TRESOS_BASE%\plugins
IF [%TRACE32_PATH%]==[] set TRACE32_PATH=D:\00_software\07_T32_2.4.48
IF [%DEBUG_OPT_FILE%]==[] set DEBUG_OPT_FILE = -s ..\TC38X_TriCore_Debug.cmm ..\output\bin\$(PROJECT).$(ABS_FILE_SUFFIX)
IF [%TOOLPATH_PYTHON_EXE%]==[] SET TOOLPATH_PYTHON_EXE=%Python3_exe%
