/*! \file **********************************************************************

COMPANY:                   COPYRIGHT (C) Continental AG

PROJECT:                   Mainstream

CPU:                       CPU-Independent

COMPONENT:                 MEDIC (Monitoring Evaluation And Decision For Intervention Control)

PACKAGENAME:               medic_project_id.h

DESCRIPTION:               Customer project IDs

AUTHOR:                    $Author: Ramachandra, Rashmi (uids9858) $

CREATION DATE:             $Date: 2020/04/01 15:54:20CEST $

VERSION:                   $Revision: 1.3 $

**************************************************************************** */

#ifndef MEDIC_PROJECT_ID_H
#define MEDIC_PROJECT_ID_H

/*****************************************************************************
  SYMBOLISCHE KONSTANTEN 
*****************************************************************************/

/*****************************************************************************
Table for setting up  Project IDs

Interpretation in HEX:
TCCC PPPP:
T    => Technology
CCC  => Customer
PPPP => Project ID

Example:
000A 0001 
T -> 0 ==> Radar    
C -> A ==> 10 (Honda)
P -> 1 ==> 1

******************************************************************************/
/*! @cond Doxygen_Suppress */
/* Values from 0 7 */
#define MEDIC_SW_PROJID_TECH_OFFSET (268435456)
#define MEDIC_SW_PROJID_RADAR       (0)   /*!< indicates radar project in Function Version Number*/
#define MEDIC_SW_PROJID_CAMERA      (1)
#define MEDIC_SW_PROJID_ADCU        (2)

  
/* Values from 0 4095 */
#define MEDIC_SW_PROJID_CUST_OFFSET (65536)
#define MEDIC_SW_PROJID_BMW         (0)   /*!< indicates BMW project in Function Version Number*/
#define MEDIC_SW_PROJID_MERCEDES    (1)
#define MEDIC_SW_PROJID_TOYOTA      (2)
#define MEDIC_SW_PROJID_VW          (3)
#define MEDIC_SW_PROJID_GM          (4)
#define MEDIC_SW_PROJID_FORD        (5)
#define MEDIC_SW_PROJID_M_LKW       (6)
#define MEDIC_SW_PROJID_HYUNDAI     (7)
#define MEDIC_SW_PROJID_MITSUBISHI  (8)
#define MEDIC_SW_PROJID_MAZDA       (9)
#define MEDIC_SW_PROJID_HONDA       (10)
#define MEDIC_SW_PROJID_FIAT        (11)
#define MEDIC_SW_PROJID_VOLVO       (12)
#define MEDIC_SW_PROJID_RENAULT     (13)
#define MEDIC_SW_PROJID_PSA         (14)
#define MEDIC_SW_PROJID_NISSAN      (15)
#define MEDIC_SW_PROJID_BASE        (16)
#define MEDIC_SW_PROJID_GEELY       (17)
#define MEDIC_SW_PROJID_TESLA       (18)
#define MEDIC_SW_PROJID_WABCO       (19)
#define MEDIC_SW_PROJID_LYNKCO      (20)
#define MEDIC_SW_PROJID_MOBIS       (21)
#define MEDIC_SW_PROJID_SAIC        (22)
#define MEDIC_SW_PROJID_SGMW        (23)
#define MEDIC_SW_PROJID_OTHER       (4095)

/*
List for actual Projects

Radar
=========
ARS4B0        -- 0 000 0000
ARS430BW18    -- 0 000 0001
ARS4D0        -- 0 001 0000
ARS4D1        -- 0 001 0001
ARS4D2        -- 0 001 0002
ARS441DP10    -- 0 001 0003
ARS4T0        -- 0 002 0000
ARS510TA19    -- 0 002 0001
ARS410VW16    -- 0 003 0000
ARS410VW18    -- 0 003 0001
ARS410VW29    -- 0 003 0002
ARS510VW19    -- 0 003 0003
ARS4G0        -- 0 004 0000
ARS4G1        -- 0 004 0001
ARS510GM18    -- 0 004 0001
ARS4L0        -- 0 006 0000
ARS4L1        -- 0 006 0001
ARS410HI17    -- 0 007 0000
ARS410HI28    -- 0 007 0001
ARS430MI18    -- 0 008 0000
ARS510HA10    -- 0 010 0000
ARS4V0        -- 0 012 0000
ARS410RT17    -- 0 013 0000
ARS410RT28    -- 0 013 0001
ARS510RT10    -- 0 013 0002
ARS410NN16    -- 0 015 0000
ARS430NN17    -- 0 015 0001
ARS410NCAP18  -- 0 016 0000
ARS510        -- 0 016 0001
ARS410ACC400  -- 0 016 0002
ARS510ACC400  -- 0 016 0003
ARS410GY18    -- 0 017 0000
ARS410GY69    -- 0 017 0001
ARS410TL17    -- 0 018 0000
ARS430WC19    -- 0 019 0000
ARS410LO19    -- 0 020 0000
ARS410MS19    -- 0 021 0000
ARS410SC19    -- 0 022 0000
ARS410SW29    -- 0 023 0000
*/

#define  MEDIC_SW_PROJID_ARS4B0       ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_BMW       )   + 0)
#define  MEDIC_SW_PROJID_ARS430BW18   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_BMW       )   + 1)
#define  MEDIC_SW_PROJID_ARS4D0       ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_MERCEDES  )   + 0)
#define  MEDIC_SW_PROJID_ARS4D1       ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_MERCEDES  )   + 1)
#define  MEDIC_SW_PROJID_ARS4D2       ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_MERCEDES  )   + 2)
#define  MEDIC_SW_PROJID_ARS441DP10   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_MERCEDES  )   + 3)
#define  MEDIC_SW_PROJID_ARS4T0       ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_TOYOTA    )   + 0)
#define  MEDIC_SW_PROJID_ARS510TA19   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_TOYOTA    )   + 1)
#define  MEDIC_SW_PROJID_ARS410VW16   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_VW        )   + 0)
#define  MEDIC_SW_PROJID_ARS410VW18   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_VW        )   + 1)
#define  MEDIC_SW_PROJID_ARS410VW29   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_VW        )   + 2)
#define  MEDIC_SW_PROJID_ARS510VW19   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_VW        )   + 3)
#define  MEDIC_SW_PROJID_ARS4G0       ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_GM        )   + 0)
#define  MEDIC_SW_PROJID_ARS4G1       ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_GM        )   + 1)
#define  MEDIC_SW_PROJID_ARS510GM18   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_GM        )   + 2)
#define  MEDIC_SW_PROJID_ARS4L0       ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_M_LKW     )   + 0)
#define  MEDIC_SW_PROJID_ARS4L1       ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_M_LKW     )   + 1)
#define  MEDIC_SW_PROJID_ARS410HI17   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_HYUNDAI   )   + 0)
#define  MEDIC_SW_PROJID_ARS410HI28   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_HYUNDAI   )   + 1)
#define  MEDIC_SW_PROJID_ARS430MI18   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_MITSUBISHI)   + 0)
#define  MEDIC_SW_PROJID_ARS510HA10   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_HONDA     )   + 0)
#define  MEDIC_SW_PROJID_ARS4V0       ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_VOLVO     )   + 0)
#define  MEDIC_SW_PROJID_ARS410RT17   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_RENAULT   )   + 0)
#define  MEDIC_SW_PROJID_ARS410RT28   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_RENAULT   )   + 1)
#define  MEDIC_SW_PROJID_ARS510RT10   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_RENAULT   )   + 2)
#define  MEDIC_SW_PROJID_ARS410NN16   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_NISSAN    )   + 0)
#define  MEDIC_SW_PROJID_ARS430NN17   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_NISSAN    )   + 1)
#define  MEDIC_SW_PROJID_ARS430NCAP18 ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_BASE      )   + 0)
#define  MEDIC_SW_PROJID_ARS510       ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_BASE      )   + 1)
#define  MEDIC_SW_PROJID_ARS410ACC400 ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_BASE      )   + 2)
#define  MEDIC_SW_PROJID_ARS410GY18   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_GEELY     )   + 0)
#define  MEDIC_SW_PROJID_ARS410GY69   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_GEELY     )   + 1)
#define  MEDIC_SW_PROJID_ARS410TL17   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_TESLA     )   + 0)
#define  MEDIC_SW_PROJID_ARS430WC19   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_WABCO     )   + 0)
#define  MEDIC_SW_PROJID_ARS410LO19   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_LYNKCO    )   + 0)
#define  MEDIC_SW_PROJID_ARS410MS19   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_MOBIS     )   + 0)
#define  MEDIC_SW_PROJID_ARS410SC19   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_SAIC      )   + 0)
#define  MEDIC_SW_PROJID_ARS410SW29   ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_RADAR) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_SGMW      )   + 0)

/*
Camera
==========
SMFC4B0       -- 1 000 0000
MFS430BW16    -- 1 000 0001
SRLCAM4T0     -- 1 002 0000
MFC4T0        -- 1 002 0001
MFC430H17     -- 1 007 000
MFC440GY18    -- 1 012 0001 (To clarify: GY-Project with Volvo Project ID)
MFC430NCAP18  -- 1 016 0000
MFC431        -- 1 016 0001
MFC510        -- 1 016 0002
*/
#define  MEDIC_SW_PROJID_SMFC4B0       ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_CAMERA) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_BMW   )  + 0)
#define  MEDIC_SW_PROJID_MFS430BW16    ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_CAMERA) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_BMW   )  + 1)
#define  MEDIC_SW_PROJID_SRLCAM4T0     ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_CAMERA) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_TOYOTA)  + 0)
#define  MEDIC_SW_PROJID_MFC4T0        ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_CAMERA) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_TOYOTA)  + 1)
#define  MEDIC_SW_PROJID_MFC430H17     ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_CAMERA) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_HYUNDAI) + 0)
#define  MEDIC_SW_PROJID_MFC440GY18    ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_CAMERA) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_VOLVO)   + 0)
#define  MEDIC_SW_PROJID_MFC430NCAP18  ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_CAMERA) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_BASE  )  + 0)
#define  MEDIC_SW_PROJID_MFC431        ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_CAMERA) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_BASE )   + 1)
#define  MEDIC_SW_PROJID_MFC510        ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_CAMERA) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_BASE )   + 2)

/*
ADCU
==========
ADC420HA10    -- 2 010 0000
*/
#define  MEDIC_SW_PROJID_ADC420HA10    ((MEDIC_SW_PROJID_TECH_OFFSET * MEDIC_SW_PROJID_ADCU) + (MEDIC_SW_PROJID_CUST_OFFSET * MEDIC_SW_PROJID_HONDA)   + 0)

/*! @endcond Doxygen_Suppress */
#endif/* MEDIC_PROJECT_ID_H */

