/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \version 6.4.3
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2020 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains an Rte component template / example code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.4.3
 * on Mon Nov 21 15:55:57 CST 2022. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#include <Rte_RtaAdapter_C1.h>
#include "rta_prj_cfg.h"
uint32 RtaAdapter_C1_MainCnt;
/* ==================[Definition of functions with external linkage]========== */
/* ------------------------[runnable entity skeletons]------------------------ */
FUNC(void, RTE_CODE) RtaAdapter_C1_InitFunction (void)
{
  RtaAdapter_C1_MainCnt = 0;
  RTA_v_Init();
} /* FUNC(void, RTE_CODE) RtaAdapter_C1_InitFunction (void) */

FUNC(void, RTE_CODE) RtaAdapter_C1_MainFunction (void)
{
  RtaAdapter_C1_MainCnt ++;
  (void)MTSI_DriverStartTaskCycle(RTA_MEAS_FUNCTION_ID___IUC_CORE_1);
  RTA_v_MainFunction();
} /* FUNC(void, RTE_CODE) RtaAdapter_C1_MainFunction (void) */

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------
  ------------------------[per instance memory API]--------------------------
 */

/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
