/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      600.0,                                       
            catalogName:    "ti.catalog.arm.cortexa8",
            deviceName:     "TMS320C6A8149",
            customMemoryMap:
           [          
                ["DDR_CA8_CODE", 
                     {
                        name: "DDR_CA8_CODE",
                        base: 0x00000000,                    
                        len: 0x00000004,                    
                        space: "code",
                        access: "RX",
                     }
                ],
                ["DDR_CA8_DATA_ASIL", 
                     {
                        name: "DDR_CA8_DATA_ASIL",
                        base: 0x00000004,                    
                        len: 0x00000004,                    
                        space: "data",
                        access: "RW",
                     }
                ],
           ],

    });
    
instance :
    
    override config string codeMemory  = "DDR_CA8_CODE";   
    override config string dataMemory  = "DDR_CA8_DATA_ASIL";                                
    override config string stackMemory = "DDR_CA8_DATA_ASIL";
    
}
