// Copyright (C) Continental AG
// All Rights Reserved
// COMPONENT: RTE - RealTimeEnvironment
/// @file  Rte_Trace_Hooks.h
/// @brief This file contains defines and localID-enums required for the RTA instrumentation of the RTE. 
///        Note: This file is generated by the RteStandardRtaInstrGenerator. Therefore it must not be altered in the sections between the 
///              startTag and the related endTag eg. ___GENERATOR_TAG___XXX___SECTION_START___, ___GENERATOR_TAG___XXX___SECTION_END___
///              as these parts are overwritten at next generatorRun. But code can be added manually outside of these sections. It is also  
///              possible to extend the localID-enumerations manually but this has to be done AFTER the related generatorTag!
 

#ifndef RTE_TRACE_HOOKS_INCLUDED
#define RTE_TRACE_HOOKS_INCLUDED


/* The following GENERATOR_TAG indicates the start of the section where all defines of the globalIDs used by RTE are implemented.
 * DO NOT DO manually codeChanges within this section. 
 * DO NOT change or remove this comment block as it is needed by codeGenerator adding the rtaInstrumentation (GenerateRteStandardRtaInstrumentation)!!! 
 * ___GENERATOR_TAG___GLOBAL_ID_DEFINES___SECTION_START___ */ 



/* ___GENERATOR_TAG___GLOBAL_ID_DEFINES___SECTION_END___
 * The GENERATOR_TAG above indicates the end of the section where all defines of the globalIDs used by RTE are implemented.
 * All the lines below the GENERATOR_TAG will not be changed by the codeGenerator at all. 
 * DO NOT change or remove this comment block as it is needed by codeGenerator adding the rtaInstrumentation (GenerateRteStandardRtaInstrumentation)!!! 
 */ 




/* The following GENERATOR_TAG indicates the start of the section where all localID-enumerations used by RTE traceHooks are implemented.
 * DO NOT DO manually codeChanges within this section. 
 * DO NOT change or remove this comment block as it is needed by codeGenerator adding the rtaInstrumentation (GenerateRteStandardRtaInstrumentation)!!! 
 * ___GENERATOR_TAG___LOCAL_ID_ENUM___SECTION_START___ */ 



/* ___GENERATOR_TAG___LOCAL_ID_ENUM___SECTION_END___
 * The GENERATOR_TAG above indicates the end of the section where all localID-enumerations used by RTE traceHooks are implemented.
 * All the lines below the GENERATOR_TAG will not be changed by the codeGenerator at all. 
 * DO NOT change or remove this comment block as it is needed by codeGenerator adding the rtaInstrumentation (GenerateRteStandardRtaInstrumentation)!!! 
 */ 




/* The following GENERATOR_TAG indicates the start of the section where all errors/warnings related to the RTE/RTA configuration are implemented.
 * DO NOT DO manually codeChanges within this section. 
 * DO NOT change or remove this comment block as it is needed by codeGenerator adding the rtaInstrumentation (GenerateRteStandardRtaInstrumentation)!!! 
 * ___GENERATOR_TAG___ERROR_WARNING_INFO___SECTION_START___ */ 



/* ___GENERATOR_TAG___ERROR_WARNING_INFO___SECTION_END___
 * The GENERATOR_TAG above indicates the end of the section where errors/warnings related to the RTE/RTA configuration are implemented.
 * All the lines below the GENERATOR_TAG will not be changed by the codeGenerator at all. 
 * DO NOT change or remove this comment block as it is needed by codeGenerator adding the rtaInstrumentation (GenerateRteStandardRtaInstrumentation)!!! 
 */ 



#endif //RTE_TRACE_HOOKS_INCLUDED
