// Copyright (C) Continental AG
// All Rights Reserved
// COMPONENT: RTE - RealTimeEnvironment
/// @file  Rte_StepCounter.h
/// @brief This file contains all function proto types and enumerations required for the stepCounterHandling in the RTE.
///        Note: This file is generated by the RteStandardRtaInstrGenerator. Therefore it must not be altered in the sections between the 
///              startTag and the related endTag eg. ___GENERATOR_TAG___XXX___SECTION_START___, ___GENERATOR_TAG___XXX___SECTION_END___
///              as these parts are overwritten at next generatorRun. But code can be added manually outside of these sections.

#ifndef RTE_STEP_COUNTER_INCLUDED
#define RTE_STEP_COUNTER_INCLUDED

#include <Std_Types.h>
#include <Os.h>


/* The following GENERATOR_TAG indicates the start of the functions used for the stepCounterHandling. 
 * All the lines above the GENERATOR_TAG will not be changed by the codeGenerator at all. 
 * DO NOT change or remove this comment block as it is needed by codeGenerator adding the rtaInstrumentation (GenerateRteStandardRtaInstrumentation)!!! 
 * ___GENERATOR_TAG___STEP_COUNTER_FUNCTIONS___SECTION_START___ */ 


/* ___GENERATOR_TAG___STEP_COUNTER_FUNCTIONS___SECTION_END___
 * The GENERATOR_TAG above indicates the end of the functions used for the stepCounterHandling.
 * All the lines below the GENERATOR_TAG will not be changed by the codeGenerator at all. 
 * DO NOT change or remove this comment block as it is needed by codeGenerator adding the rtaInstrumentation (GenerateRteStandardRtaInstrumentation)!!! 
 */ 
 
/* The following GENERATOR_TAG indicates the start of the section where all enumerations used for the stepCounters are implemented.
 * DO NOT DO manually codeChanges within this section. 
 * DO NOT change or remove this comment block as it is needed by codeGenerator adding the rtaInstrumentation (GenerateRteStandardRtaInstrumentation)!!! 
 * ___GENERATOR_TAG___STEP_COUNTER_ENUMERATIONS___SECTION_START___ */ 



/* ___GENERATOR_TAG___STEP_COUNTER_ENUMERATIONS___SECTION_END___
 * The GENERATOR_TAG above indicates the end of the section where all enumerations used for the stepCounters are implemented.
 * All the lines below the GENERATOR_TAG will not be changed by the codeGenerator at all. 
 * DO NOT change or remove this comment block as it is needed by codeGenerator adding the rtaInstrumentation (GenerateRteStandardRtaInstrumentation)!!! 
 */ 



#endif //RTE_STEP_COUNTER_INCLUDED
